/*
 * 上游核心系统
 * 表名: crmdm.cbs_kdpl_zhminx
 * 来源: TB.ddl
 */

-- crmdm.cbs_kdpl_zhminx 定义

-- Drop table

-- DROP TABLE crmdm.cbs_kdpl_zhminx;

CREATE TABLE crmdm.cbs_kdpl_zhminx (
	farendma varchar(4) NOT NULL,
	zhanghao varchar(40) NOT NULL,
	zhhuzwmc varchar(500) NOT NULL,
	kehuzhlx varchar(1) NULL,
	yezdminc varchar(32) NOT NULL,
	mxixuhao numeric(19) NOT NULL,
	jiedaibz varchar(1) NOT NULL,
	jiaoybiz varchar(3) NOT NULL,
	chaohubz varchar(1) NOT NULL,
	jiaoyije numeric(17, 2) NOT NULL,
	zhanghye numeric(21, 2) NOT NULL,
	kehuzhao varchar(35) NOT NULL,
	zhhaoxuh varchar(8) NULL,
	shifoudy varchar(1) NULL,
	zhondhao varchar(200) NULL,
	butiiibz varchar(1) NULL,
	chapbhao varchar(10) NOT NULL,
	suoshudx varchar(1) NOT NULL,
	zhqixzhi varchar(6) NULL,
	pngzzlei varchar(3) NULL,
	pngzphao varchar(8) NULL,
	pngzxhao varchar(18) NULL,
	zhaiyodm varchar(10) NULL,
	zhaiyoms varchar(80) NULL,
	qdaoleix varchar(7) NULL,
	wbjoyima varchar(10) NOT NULL,
	nbjoyima varchar(10) NOT NULL,
	xianzzbz varchar(1) NOT NULL,
	duifkhzh varchar(35) NULL,
	dfzhhxuh varchar(8) NULL,
	duifxtzh varchar(40) NULL,
	duifminc varchar(500) NULL,
	duifkhlx varchar(2) NULL,
	duifjgmc varchar(60) NULL,
	duifjglx varchar(2) NULL,
	duifjgdm varchar(20) NULL,
	dailxinm varchar(500) NULL,
	dailzjlx varchar(2) NULL,
	dailzjho varchar(80) NULL,
	dailguoj varchar(10) NULL,
	zhcphaoo varchar(10) NULL,
	zhcpzhao varchar(40) NULL,
	yhywbhao varchar(30) NULL,
	xgywbhao varchar(40) NULL,
	guiylius varchar(32) NOT NULL,
	jyyyjigo varchar(10) NOT NULL,
	kaihjigo varchar(10) NOT NULL,
	caozguiy varchar(8) NOT NULL,
	fuheguiy varchar(8) NULL,
	shoqguiy varchar(8) NULL,
	jiaoyirq varchar(8) NOT NULL,
	jiaoyisj numeric(19) NOT NULL,
	zhujriqi varchar(8) NULL,
	chongzbz varchar(1) NOT NULL,
	bchongbz varchar(1) NOT NULL,
	cuozriqi varchar(8) NULL,
	cuozlius varchar(32) NULL,
	beizhuuu varchar(200) NULL,
	jioycffs varchar(1) NULL,
	dayiyesh numeric(19) NULL,
	weihguiy varchar(8) NOT NULL,
	weihjigo varchar(10) NOT NULL,
	weihriqi varchar(8) NOT NULL,
	weihshij varchar(9) NULL,
	shijchuo numeric(19) NOT NULL,
	jiluztai varchar(1) NOT NULL,
	xnjnxmdm varchar(4) NULL,
	dailreyw varchar(500) NULL,
	dlirdhua varchar(40) NULL,
	qianfarq varchar(8) NULL,
	doqiriqi varchar(8) NULL,
	ipdizhii varchar(32) NULL,
	macdizhi varchar(32) NULL,
	zijnlaiy varchar(200) NULL,
	qxyongtu varchar(200) NULL,
	ryzd varchar(1) NULL
);

