/*
 * 上游核心系统
 * 表名: crmdm.cbs_kdpa_zhxinx
 * 来源: TB.ddl
 */

-- crmdm.cbs_kdpa_zhxinx 定义

-- Drop table

-- DROP TABLE crmdm.cbs_kdpa_zhxinx;

CREATE TABLE crmdm.cbs_kdpa_zhxinx (
	farendma varchar(4) NOT NULL,
	zhanghao varchar(40) NOT NULL,
	zhhuzwmc varchar(500) NOT NULL,
	kehuhaoo varchar(16) NOT NULL,
	guobdaim varchar(10) NULL,
	huobdaih varchar(3) NOT NULL,
	chaohubz varchar(1) NOT NULL,
	cunqiiii varchar(6) NOT NULL,
	doqiriqi varchar(8) NULL,
	qixifans varchar(1) NOT NULL,
	csqixirq varchar(8) NOT NULL,
	csdoqirq varchar(8) NULL,
	yewudhao varchar(6) NULL,
	pcljigoh varchar(10) NULL,
	zhujigoh varchar(10) NULL,
	kaihjigo varchar(10) NOT NULL,
	kaihriqi varchar(8) NOT NULL,
	kaihguiy varchar(8) NOT NULL,
	xiohjigo varchar(10) NULL,
	xiohriqi varchar(8) NULL,
	xiohguiy varchar(10) NULL,
	lancreny varchar(500) NULL,
	lancrymc varchar(500) NULL,
	youxriqi varchar(8) NULL,
	weiyxuho numeric(19) NULL,
	zhhuyuee numeric(21, 2) NOT NULL,
	shrizhye numeric(21, 2) NOT NULL,
	yegxriqi varchar(8) NOT NULL,
	sccrriqi varchar(8) NULL,
	scywriqi varchar(8) NULL,
	scsfriqi varchar(8) NULL,
	chapbhao varchar(10) NOT NULL,
	fzcpleix varchar(1) NOT NULL,
	suoshudx varchar(1) NOT NULL,
	zhufldm1 varchar(10) NULL,
	zhufldm2 varchar(10) NULL,
	zhufldm3 varchar(10) NULL,
	huansbiz varchar(3) NOT NULL,
	zuidlcye numeric(21, 2) NULL,
	zuixlcye numeric(21, 2) NULL,
	cunrkzhi varchar(1) NOT NULL,
	cunrkzff varchar(1) NULL,
	cunrclsx varchar(32) NOT NULL,
	zhiqkzfs varchar(1) NOT NULL,
	zhiqkzff varchar(1) NULL,
	zdzqkzfs varchar(4) NULL,
	kehuzhao varchar(35) NOT NULL,
	zhcunfsh varchar(1) NULL,
	beiyjine numeric(21, 2) NULL,
	kaihjine numeric(21, 2) NULL,
	cunkzlei varchar(2) NOT NULL,
	zhhuztai varchar(1) NOT NULL,
	yezztbbz varchar(1) NOT NULL,
	zhcphaoo varchar(10) NULL,
	zhcpxuho varchar(8) NULL,
	zhcpmuzh varchar(35) NULL,
	zhzhleix varchar(1) NULL,
	zhhuxzbz varchar(1) NOT NULL,
	xzhileix varchar(1) NULL,
	xunhdkbz varchar(1) NOT NULL,
	zhbhgxbz varchar(1) NOT NULL,
	zhiqbhsx varchar(32) NOT NULL,
	gltouzbz varchar(1) NOT NULL,
	xtaizybz varchar(1) NOT NULL,
	budhjzch varchar(20) NULL,
	dghushux varchar(1) NULL,
	jinkzhbz varchar(1) NOT NULL,
	yuxutzbz varchar(1) NOT NULL,
	waihjgbz varchar(1) NOT NULL,
	waihhcbz varchar(1) NOT NULL,
	jieszhbz varchar(1) NOT NULL,
	qyuelxbz varchar(1) NOT NULL,
	yxxjzqbz varchar(1) NOT NULL,
	yxzzzqbz varchar(1) NOT NULL,
	yxxjcrbz varchar(1) NOT NULL,
	yxzzcrbz varchar(1) NOT NULL,
	xiedckbz varchar(1) NOT NULL,
	shfojdjx varchar(1) NOT NULL,
	sfdylxjh varchar(1) NOT NULL,
	lxzffans varchar(1) NOT NULL,
	shcifxri varchar(8) NULL,
	xiacfxri varchar(8) NULL,
	fuxipinl varchar(8) NULL,
	shcijxri varchar(8) NULL,
	xiacjxri varchar(8) NULL,
	jixipnlv varchar(8) NULL,
	tzlixibz varchar(1) NULL,
	lilvbhao varchar(20) NULL,
	zhixlilv numeric(12, 7) NULL,
	lilvsffd varchar(1) NOT NULL,
	leijlixi numeric(20, 7) NULL,
	jishuuuu numeric(21, 2) NULL,
	yjyjlixi numeric(20, 7) NULL,
	yjyjjish numeric(21, 2) NULL,
	shfoyouz varchar(1) NOT NULL,
	shishbbz varchar(1) NOT NULL,
	yueegjbz varchar(1) NOT NULL,
	zhjedjbz varchar(1) NOT NULL,
	zhfbdjbz varchar(1) NOT NULL,
	zhzsbfbz varchar(1) NOT NULL,
	zhzfbsbz varchar(1) NOT NULL,
	jiaoyanm varchar(200) NULL,
	beiyzd01 varchar(50) NULL,
	beiyzd02 varchar(50) NULL,
	beiyzd03 varchar(50) NULL,
	beiyye01 numeric(21, 2) NULL,
	beiyrq01 varchar(8) NULL,
	kaihuqud varchar(7) NULL,
	jitiywbm varchar(32) NULL,
	sffydszh varchar(1) NULL,
	zhhuztzd varchar(50) NULL,
	plcffzzh varchar(16) NOT NULL,
	fsfyuerq varchar(8) NULL,
	weihguiy varchar(8) NOT NULL,
	weihjigo varchar(10) NOT NULL,
	weihriqi varchar(8) NOT NULL,
	weihshij varchar(9) NULL,
	shijchuo numeric(19) NOT NULL,
	jiluztai varchar(1) NOT NULL,
	khzjlyzh varchar(40) NULL,
	bjlxzrzh varchar(35) NULL,
	bxzrzhao varchar(40) NULL,
	drjfxjje numeric(21, 2) NULL,
	drjfzzje numeric(21, 2) NULL,
	drdfxjje numeric(21, 2) NULL,
	drdfzzje numeric(21, 2) NULL,
	ryzd varchar(1) NULL
);

