/*
 * 上游核心系统
 * 表名: crmdm.cbs_kdpa_zhbcxx
 * 来源: TB.ddl
 */

-- crmdm.cbs_kdpa_zhbcxx 定义

-- Drop table

-- DROP TABLE crmdm.cbs_kdpa_zhbcxx;

CREATE TABLE crmdm.cbs_kdpa_zhbcxx (
	farendma varchar(4) NOT NULL,
	zhanghao varchar(40) NOT NULL,
	dlirminc varchar(500) NULL,
	dlirzhjn varchar(2) NULL,
	dlirzhjh varchar(80) NULL,
	dlirguoj varchar(10) NULL,
	dlirdhua varchar(40) NULL,
	tuozrenn varchar(500) NULL,
	tuozrbho varchar(8) NULL,
	kaihdjbz varchar(1) NULL,
	dongjbho varchar(32) NULL,
	qiyongrq varchar(8) NULL,
	jibhkhho varchar(12) NULL,
	jibhkhhm varchar(120) NULL,
	jibhzhho varchar(35) NULL,
	jibhhzho varchar(30) NULL,
	xukezhho varchar(30) NULL,
	bqicishu numeric(19) NULL,
	loucunys numeric(19) NULL,
	weiyriqi varchar(8) NULL,
	zhdquxng varchar(1) NULL,
	dxkehuzh varchar(35) NULL,
	dxzhuxho varchar(8) NULL,
	dingxzht varchar(1) NULL,
	quxjiech varchar(1) NULL,
	yerzzkhz varchar(35) NULL,
	yerzzzhx varchar(8) NULL,
	beiyzd01 varchar(50) NULL,
	beiyzd02 varchar(50) NULL,
	beiyzd03 varchar(50) NULL,
	beiyye01 numeric(21, 2) NULL,
	beiyye02 numeric(21, 2) NULL,
	beiyye03 numeric(21, 2) NULL,
	ljplhsbz varchar(1) NULL,
	zhphbzhi varchar(1) NULL,
	ylzhmmbz varchar(1) NULL,
	kehuzhao varchar(35) NULL,
	zhhaoxuh varchar(8) NULL,
	zmwjzlei varchar(2) NULL,
	zmwjbhao varchar(30) NULL,
	kehuzhmc varchar(500) NULL,
	jigouhao varchar(12) NULL,
	kehuhaoo varchar(16) NULL,
	scnjriqi varchar(8) NULL,
	bcnjriqi varchar(8) NULL,
	njanztai varchar(1) NULL,
	sfbztshi varchar(1) NULL,
	beizhuxx varchar(200) NULL,
	kouhhpnz varchar(1) NULL,
	kaihriqi varchar(8) NULL,
	kaihlius varchar(32) NULL,
	xiohriqi varchar(8) NULL,
	xiahlius varchar(32) NULL,
	xiaohuje numeric(17, 2) NULL,
	weihguiy varchar(8) NOT NULL,
	weihjigo varchar(12) NOT NULL,
	weihriqi varchar(8) NOT NULL,
	weihshij varchar(9) NULL,
	shijchuo numeric(19) NOT NULL,
	jiluztai varchar(1) NOT NULL,
	dlirywmc varchar(500) NULL,
	tyzhleix varchar(2) NULL,
	scjioyrq varchar(8) NULL,
	sscijyrq varchar(8) NULL,
	sfxwgshu varchar(1) NULL,
	nmggzhbz varchar(1) NULL,
	smsfhsrq varchar(8) NULL,
	zhhufxdj varchar(1) NULL,
	fxdjpdrq varchar(8) NULL,
	zhahlxzx varchar(5) NULL,
	zjinxinz varchar(5) NULL,
	xiaohuyy varchar(5) NULL,
	yxkzclfs varchar(5) NULL,
	yfqqudao varchar(7) NULL,
	yingxjig varchar(12) NULL,
	ryzd varchar(1) NULL
);

