-- crmdm.fms_td_cust_trans_req_log 定义

-- Drop table

-- DROP TABLE crmdm.fms_td_cust_trans_req_log;

CREATE TABLE crmdm.fms_td_cust_trans_req_log (
	app_serno varchar(32) NOT NULL,
	busi_code varchar(3) NOT NULL,
	trans_code varchar(8) NULL,
	fnc_trans_acct_no varchar(24) NOT NULL,
	tano varchar(16) NOT NULL,
	prod_code varchar(32) NOT NULL,
	share_class bpchar(1) NULL,
	cust_no varchar(32) NOT NULL,
	cust_type varchar(3) NOT NULL,
	ta_acct_no varchar(32) NULL,
	ta_cfm_serno varchar(32) NULL,
	card_no varchar(32) NULL,
	card_type varchar(2) NULL,
	acct_no varchar(32) NOT NULL,
	app_date varchar(8) NOT NULL,
	cfm_date varchar(8) NULL,
	ccy varchar(3) NULL,
	app_amt numeric(32, 2) NULL,
	app_vol numeric(32, 2) NULL,
	cfm_amt numeric(32, 2) NULL,
	cfm_vol numeric(32, 2) NULL,
	charge numeric(32, 2) NULL,
	cmms_disct numeric(8, 5) NULL,
	ta_flag bpchar(1) NULL,
	lrdm_flag bpchar(1) NULL,
	channel varchar(8) NULL,
	channel_serno varchar(32) NULL,
	channel_date varchar(8) NULL,
	channel_time varchar(8) NULL,
	bank_code varchar(16) NULL,
	branch_code varchar(16) NULL,
	trans_orgno varchar(16) NULL,
	inputuser varchar(10) NULL,
	grantuser varchar(8) NULL,
	agent_name varchar(128) NULL,
	agent_id_type varchar(8) NULL,
	agent_id_code varchar(32) NULL,
	nav numeric(16, 8) NULL,
	nav_date varchar(8) NULL,
	tag_trans_acct_no varchar(24) NULL,
	tag_distributorcode varchar(9) NULL,
	tag_ta_acct_no varchar(16) NULL,
	tag_prod_code varchar(32) NULL,
	tag_share_class bpchar(1) NULL,
	frozen_cause bpchar(1) NULL,
	frozen_ddl varchar(8) NULL,
	ori_app_serno varchar(32) NULL,
	def_div_method bpchar(1) NULL,
	trans_status bpchar(1) NULL,
	capital_status varchar(1) NULL,
	capital_type varchar(1) NULL,
	rtn_code varchar(30) NULL,
	rtn_desc varchar(512) NULL,
	mac_date varchar(8) NOT NULL,
	mac_time varchar(8) NOT NULL,
	legal_code varchar(32) NULL,
	host_trans_serno varchar(32) NULL,
	update_date varchar(8) NULL,
	update_time varchar(8) NULL,
	sys_date varchar(8) NULL,
	cust_manager varchar(20) NULL,
	ext_sub_branch_code varchar(16) NULL,
	frozen_no varchar(32) NULL,
	deposit_acct varchar(32) NULL,
	cust_risk_level bpchar(1) NULL,
	prod_risk_level bpchar(1) NULL,
	tag_acct_no varchar(32) NULL,
	tag_card_no varchar(32) NULL,
	tag_card_type varchar(1) NULL,
	tag_agent_name varchar(128) NULL,
	tag_agent_id_type varchar(8) NULL,
	tag_agent_id_code varchar(32) NULL,
	tag_cust_name varchar(128) NULL,
	tag_id_type varchar(8) NULL,
	tag_id_code varchar(32) NULL,
	is_first bpchar(1) NULL,
	ta_batch varchar(16) NULL,
	ta_app_serno varchar(32) NULL,
	ori_ta_cfm_serno varchar(32) NULL,
	src_serno varchar(32) NULL,
	print_count varchar(2) NULL,
	account_date varchar(8) NULL,
	trans_deal_ip varchar(128) NULL,
	channel_ip varchar(128) NULL,
	channel_mac varchar(64) NULL,
	recomm_ppl varchar(32) NULL,
	session_id varchar(32) NULL,
	ryzd varchar(1) NULL
);
