/*
 * 上游理财系统
 * 表名: crmdm.fms_td_prod_info
 * 来源: TB.ddl
 */

-- crmdm.fms_td_prod_info 定义

-- Drop table

-- DROP TABLE crmdm.fms_td_prod_info;

CREATE TABLE crmdm.fms_td_prod_info (
	tano varchar(16) NULL,
	prod_code varchar(32) NULL,
	legal_code varchar(32) NULL,
	prod_name varchar(400) NULL,
	prod_name_short varchar(120) NULL,
	prod_type varchar(2) NULL,
	share_class bpchar(1) NULL,
	prod_status bpchar(1) NULL,
	sale_status bpchar(1) NULL,
	prod_risk_level bpchar(1) NULL,
	prod_manager varchar(32) NULL,
	prod_mandator varchar(32) NULL,
	rasie_type varchar(32) NULL,
	regist_code varchar(32) NULL,
	benchmarks numeric(11, 8) NULL,
	prod_cur varchar(3) NULL,
	collect_feetype bpchar(1) NULL,
	redeemfee_backratio numeric(9, 5) NULL,
	redeem_feerate numeric(9, 5) NULL,
	def_div_method bpchar(1) NULL,
	div_chg_flag bpchar(1) NULL,
	price numeric(16, 8) NULL,
	nav numeric(16, 8) NULL,
	nav_date varchar(8) NULL,
	proxy_fee_flag varchar(1) NULL,
	prod_size numeric(32, 2) NULL,
	quota_ctrl_flag bpchar(1) NULL,
	subs_capital_mode bpchar(1) NULL,
	subs_capital_type bpchar(1) NULL,
	sub_payback_period numeric(38) NULL,
	subs_nextday_cancel bpchar(1) NULL,
	apply_capital_mode bpchar(1) NULL,
	apply_pay_period numeric(38) NULL,
	first_buy_flag varchar(32) NULL,
	convert_status varchar(1) NULL,
	periodic_status varchar(1) NULL,
	transfer_agency_status varchar(1) NULL,
	divident_date varchar(8) NULL,
	registration_date varchar(8) NULL,
	booking_begin_date varchar(8) NULL,
	booking_invalid_date varchar(8) NULL,
	subs_begin_date varchar(8) NULL,
	subs_end_date varchar(8) NULL,
	subs_end_time varchar(6) NULL,
	subs_cancel_end_date varchar(8) NULL,
	establish_date varchar(8) NULL,
	value_date varchar(8) NULL,
	open_begin_date varchar(8) NULL,
	open_end_date varchar(8) NULL,
	winding_date varchar(8) NULL,
	close_time varchar(6) NULL,
	trans_start_time varchar(6) NULL,
	trans_end_time varchar(6) NULL,
	period_type bpchar(1) NULL,
	profit_type varchar(32) NULL,
	prod_lifecycle bpchar(1) NULL,
	redeem_pay_period numeric(38) NULL,
	divide_pay_period numeric(38) NULL,
	end_pay_period numeric(38) NULL,
	apply_cfm_n numeric(38) NULL,
	redeem_cfm_n numeric(38) NULL,
	is_discount varchar(1) NULL,
	can_booking varchar(1) NULL,
	redeem_type bpchar(1) NULL,
	can_realtime_redeem varchar(1) NULL,
	realtime_repay_flag bpchar(1) NULL,
	realtime_repay_method bpchar(1) NULL,
	windup_type bpchar(1) NULL,
	prod_order numeric(38) NULL,
	can_frozen varchar(1) NULL,
	can_conv_flag varchar(1) NULL,
	recom_flg varchar(1) NULL,
	pgmno varchar(32) NULL,
	pre_workday varchar(8) NULL,
	current_workday varchar(8) NULL,
	next_workday varchar(8) NULL,
	min_subs_amt numeric(32, 2) NULL,
	max_subs_amt numeric(32, 2) NULL,
	online_date varchar(8) NULL,
	invest_target bpchar(1) NULL,
	cash_flag bpchar(1) NULL,
	is_hot_sale bpchar(1) NULL,
	operation_period_day numeric NULL,
	max_lock_days numeric(32) NULL,
	benchmarks_text varchar(1536) NULL,
	prod_rate numeric NULL,
	min_hold numeric(38) NULL,
	prod_days numeric(38) NULL,
	channel_show_flag bpchar(1) NULL,
	sort_no numeric(8, 4) NULL,
	apply_begin_date varchar(8) NULL,
	redeem_begin_date varchar(8) NULL,
	prod_template_code varchar(8) NULL,
	cycle_days numeric NULL,
	is_dx_new_cust_prod varchar(1) NULL,
	cust_cycle_redeem_type varchar(1) NULL,
	open_notify_flag varchar(1) NULL,
	achievement_show_type varchar(1) NULL,
	show_short_flag varchar(1) NULL,
	workdaytype varchar(1) NULL,
	benchmarkexpiredate varchar(8) NULL,
	ryzd varchar(1) NULL
);

