/*
 * 上游理财系统
 * 表名: crmdm.fms_t1_cust_info
 * 来源: TB.ddl
 */

-- crmdm.fms_t1_cust_info 定义

-- Drop table

-- DROP TABLE crmdm.fms_t1_cust_info;

CREATE TABLE crmdm.fms_t1_cust_info (
    cust_no varchar(20) NULL,
    host_cust_no varchar(32) NULL,
    id_type varchar(8) NULL,
    id_code varchar(32) NULL,
    host_id_type varchar(8) NULL,
    cust_name varchar(128) NULL,
    cust_type varchar(8) NULL,
    cust_level varchar(8) NULL,
    cust_card_type varchar(8) NULL,
    instrepr_name varchar(128) NULL,
    instrepr_id_type varchar(8) NULL,
    instrepr_id_code varchar(32) NULL,
    agent_name varchar(128) NULL,
    agent_id_type varchar(8) NULL,
    agent_id_code varchar(32) NULL,
    birthday bpchar(8) NULL,
    sex bpchar(1) NULL,
    education bpchar(1) NULL,
    mobile varchar(20) NULL,
    home_tel varchar(20) NULL,
    office_tel varchar(20) NULL,
    fax varchar(20) NULL,
    postcode bpchar(6) NULL,
    addr varchar(128) NULL,
    email varchar(64) NULL,
    cust_manager varchar(20) NULL,
    fnc_manager varchar(20) NULL,
    protocol_serno varchar(32) NULL,
    protocol_status bpchar(1) NULL,
    bank_code varchar(20) NULL,
    branch_code varchar(20) NULL,
    sub_branch_code varchar(20) NULL,
    inputuser varchar(20) NULL,
    crt_date bpchar(8) NULL,
    crt_time bpchar(6) NULL,
    inv_date bpchar(8) NULL,
    inv_time bpchar(6) NULL,
    remark varchar(255) NULL,
    upd_date bpchar(8) NULL,
    upd_time bpchar(6) NULL,
    investor_type bpchar(2) NULL,
    cust_ename varchar(100) NULL,
    cust_cname varchar(100) NULL,
    agent_ename varchar(100) NULL,
    agent_cname varchar(100) NULL,
    is_new_cust bpchar(1) NULL,
    investor_class bpchar(1) NULL,
    investor_invalid_date bpchar(8) NULL,
    legal_code varchar(32) NULL,
    certvaliddate bpchar(8) NULL,
    annualincome numeric(16) NULL,
    nationality varchar(3) NULL,
    vocationcode varchar(5) NULL,
    specialpersonflag bpchar(1) NULL,
    fir_investor_type bpchar(1) NULL,
    family_name varchar(100) NULL,
    first_name varchar(100) NULL,
    living_country varchar(3) NULL,
    living_province varchar(6) NULL,
    living_city varchar(6) NULL,
    living_district varchar(6) NULL,
    living_address varchar(300) NULL,
    corp_name varchar(40) NULL,
    non_resi_flag varchar(1) NULL,
    tax_country varchar(3) NULL,
    tax_id varchar(200) NULL,
    is_dx_new_cust bpchar(1) NULL,
    ryzd varchar(1) NULL
);