/*
 * 上游理财系统
 * 表名: crmdm.fms_t5_cust_trans_log
 * 来源: TB.ddl
 */

-- crmdm.fms_t5_cust_trans_log 定义

-- Drop table

-- DROP TABLE crmdm.fms_t5_cust_trans_log;

CREATE TABLE crmdm.fms_t5_cust_trans_log (
    trans_serno varchar(32) NOT NULL,
    sys_mbt varchar(6) NULL,
    busi_code varchar(6) NOT NULL,
    channel_flag varchar(3) NOT NULL,
    channel_date bpchar(8) NULL,
    channel_time bpchar(6) NULL,
    channel_serno varchar(32) NULL,
    macdate bpchar(8) NOT NULL,
    mactime bpchar(6) NOT NULL,
    bank_code varchar(20) NOT NULL,
    branch_code varchar(20) NOT NULL,
    sub_branch_code varchar(20) NOT NULL,
    inputuser varchar(20) NOT NULL,
    checkuser varchar(20) NULL,
    grantuser varchar(20) NULL,
    distributor_code varchar(14) NULL,
    acct_no varchar(32) NULL,
    sub_acct_no varchar(32) NULL,
    match_acct_no varchar(32) NULL,
    cust_no varchar(20) NULL,
    fnc_trans_acct_no varchar(17) NULL,
    self_fnc_acct_no varchar(12) NULL,
    cust_name varchar(128) NULL,
    id_type varchar(8) NULL,
    id_code varchar(32) NULL,
    host_id_type varchar(8) NULL,
    cust_type varchar(8) NULL,
    cust_level varchar(8) NULL,
    agent_name varchar(128) NULL,
    agent_id_type varchar(8) NULL,
    agent_id_code varchar(32) NULL,
    risk_match_flag varchar(1) NULL,
    cust_risk_level varchar(1) NULL,
    prod_risk_level varchar(1) NULL,
    prod_code varchar(32) NOT NULL,
    prod_child_no numeric(8) NULL,
    nav numeric(12,
    6) NULL,
    cur varchar(8) NULL,
    app_amt numeric(16,
    2) NULL,
    app_vol numeric(16,
    2) NULL,
    ack_amt numeric(16,
    2) NULL,
    ack_vol numeric(16,
    2) NULL,
    discount numeric(7,
    4) NULL,
    feeamt numeric(16,
    2) NULL,
    back_fee numeric(16,
    2) NULL,
    redeem_fee numeric(16,
    2) NULL,
    interest numeric(16,
    2) NULL,
    interest_tax numeric(16,
    2) NULL,
    cust_manager varchar(20) NULL,
    fm_manager varchar(20) NULL,
    ori_trans_serno varchar(32) NULL,
    frozen_cause varchar(1) NULL,
    contract_no varchar(32) NULL,
    elisor_name varchar(128) NULL,
    frozen_enddate bpchar(8) NULL,
    ori_div_method varchar(1) NULL,
    div_method varchar(1) NULL,
    haeres_deposit_acct varchar(32) NULL,
    buyplan_no varchar(16) NULL,
    should_exec_date bpchar(8) NULL,
    ack_date bpchar(8) NULL,
    trans_date bpchar(8) NOT NULL,
    capital_status varchar(1) NOT NULL,
    trans_status varchar(1) NOT NULL,
    rtn_code varchar(12) NULL,
    rtn_desc varchar(255) NULL,
    host_code varchar(12) NULL,
    host_desc varchar(255) NULL,
    host_trans_serno varchar(32) NULL,
    freeze_serno varchar(32) NULL,
    chk_status varchar(1) NOT NULL,
    chk_date bpchar(8) NULL,
    cert_serno bpchar(8) NULL,
    print_no numeric(8) NOT NULL,
    remark varchar(255) NULL,
    upd_date bpchar(8) NOT NULL,
    upd_time bpchar(6) NOT NULL,
    card_type varchar(8) NULL,
    card_no varchar(32) NULL,
    in_card_type varchar(8) NULL,
    in_card_no varchar(32) NULL,
    in_acct_no varchar(32) NULL,
    in_agent_name varchar(128) NULL,
    in_agent_id_type varchar(8) NULL,
    in_agent_id_code varchar(32) NULL,
    in_cust_name varchar(128) NULL,
    in_id_type varchar(8) NULL,
    in_id_code varchar(32) NULL,
    trans_deal_ip varchar(128) NULL,
    channel_ip varchar(128) NULL,
    channel_mac varchar(64) NULL,
    new_cust_flag varchar(1) NULL,
    recomm_ppl varchar(15) NULL,
    special_code varchar(8) NULL,
    fund_mode varchar(1) NULL,
    hugeredeemflag varchar(1) NULL,
    host_date bpchar(8) NULL,
    busi_type varchar(1) NULL,
    backup_date bpchar(8) NULL,
    income numeric(16,
    2) NULL,
    ryzd varchar(1) NULL,
    CONSTRAINT pk_fms_t5_cust_trans_log PRIMARY KEY (trans_serno)
);