/*
 * 上游ECIF系统
 * 表名: crmdm.ecif_t01_p_cust_info
 * 来源: TB.ddl
 */

-- crmdm.ecif_t01_p_cust_info 定义

-- Drop table

-- DROP TABLE crmdm.ecif_t01_p_cust_info;

CREATE TABLE crmdm.ecif_t01_p_cust_info (
	party_id bpchar(20) NULL,
	ecif_cust_no varchar(20) NULL,
	party_name varchar(100) NULL,
	cert_type varchar(30) NULL,
	cert_no varchar(30) NULL,
	cert_org_area varchar(30) NULL,
	cert_org_name varchar(100) NULL,
	cert_issue_date sys."date" NULL,
	cert_due_date sys."date" NULL,
	cust_enname varchar(100) NULL,
	cust_spname varchar(100) NULL,
	cust_call varchar(100) NULL,
	gender varchar(30) NULL,
	people varchar(30) NULL,
	birth_date sys."date" NULL,
	birth_place varchar(60) NULL,
	health_state varchar(30) NULL,
	marital_stat varchar(30) NULL,
	nat_code varchar(30) NULL,
	native varchar(60) NULL,
	rgster varchar(100) NULL,
	"language" varchar(30) NULL,
	hobb_intrst varchar(200) NULL,
	relig_code varchar(30) NULL,
	polit_stat varchar(30) NULL,
	edu_state varchar(30) NULL,
	highest_degree varchar(30) NULL,
	grad_year varchar(30) NULL,
	rsdt_type varchar(30) NULL,
	pmt_rsdt_flag bpchar(1) NULL,
	country_code varchar(30) NULL,
	area_code varchar(30) NULL,
	reside_start_time sys."date" NULL,
	livg_condit varchar(30) NULL,
	resdt_type varchar(30) NULL,
	idvu_scl_insurs_no varchar(30) NULL,
	idvu_tx_no varchar(30) NULL,
	month_income numeric(20, 2) NULL,
	year_salary numeric(20, 2) NULL,
	econ_resur varchar(30) NULL,
	psn_asset_type varchar(30) NULL,
	num_depend varchar(30) NULL,
	fam_month numeric(20, 2) NULL,
	fam_year numeric(20, 2) NULL,
	fam_assets numeric(20, 2) NULL,
	fam_memb_total varchar(30) NULL,
	unit_name varchar(120) NULL,
	unit_type varchar(30) NULL,
	industry_type varchar(30) NULL,
	profession varchar(30) NULL,
	job_level varchar(30) NULL,
	unit_position varchar(30) NULL,
	tech_title varchar(30) NULL,
	work_stat bpchar(1) NULL,
	qualft_stat varchar(30) NULL,
	work_start_date sys."date" NULL,
	unit_start_year varchar(10) NULL,
	bank_rel_code varchar(30) NULL,
	shareholder_flag bpchar(1) NULL,
	cust_fore_exch_attr bpchar(1) NULL,
	credit_level varchar(30) NULL,
	grade_date sys."date" NULL,
	grade_due_date sys."date" NULL,
	bank_svr_grade varchar(30) NULL,
	cust_eval_level varchar(30) NULL,
	best_call_time varchar(30) NULL,
	cust_level varchar(30) NULL,
	cust_manager_no varchar(20) NULL,
	cust_mng_name varchar(100) NULL,
	ide_check_result varchar(30) NULL,
	ide_false_reason varchar(30) NULL,
	own_org varchar(20) NULL,
	open_org varchar(20) NULL,
	open_teller varchar(20) NULL,
	open_date sys."date" NULL,
	real_full_flag bpchar(1) NULL,
	cust_status bpchar(1) NULL,
	last_updated_te varchar(20) NULL,
	last_updated_org varchar(20) NULL,
	created_ts timestamp(6) NULL,
	updated_ts timestamp(6) NULL,
	init_system_id varchar(30) NULL,
	init_created_ts timestamp(6) NULL,
	last_system_id varchar(30) NULL,
	last_updated_ts timestamp(6) NULL,
	ryzd varchar(1) NULL
);

