/*
 * 上游ECIF系统
 * 表名: crmdm.ecif_t01_c_cust_info
 * 来源: TB.ddl
 */

-- crmdm.ecif_t01_c_cust_info 定义

-- Drop table

-- DROP TABLE crmdm.ecif_t01_c_cust_info;

CREATE TABLE crmdm.ecif_t01_c_cust_info (
    party_id bpchar(20) NULL,
    ecif_cust_no varchar(20) NULL,
    cust_type varchar(30) NULL,
    party_name varchar(200) NULL,
    cust_shtname varchar(100) NULL,
    cust_enname varchar(200) NULL,
    cust_spname varchar(200) NULL,
    govn_cert_no varchar(30) NULL,
    govn_efft_date DATE NULL,
    govn_expd_date DATE NULL,
    govn_review_year varchar(10) NULL,
    org_code varchar(20) NULL,
    org_code_issu varchar(60) NULL,
    org_code_iss_date DATE NULL,
    org_code_due_date DATE NULL,
    reg_org varchar(60) NULL,
    reg_country varchar(30) NULL,
    reg_province varchar(30) NULL,
    reg_area_code varchar(30) NULL,
    reg_date DATE NULL,
    reg_cptl numeric(20,
    2) NULL,
    reg_cptl_curr varchar(30) NULL,
    paid_cptl numeric(20,
    2) NULL,
    paid_cptl_curr varchar(30) NULL,
    org_type varchar(30) NULL,
    corp_attr varchar(30) NULL,
    comp_attr varchar(30) NULL,
    pay_no varchar(30) NULL,
    spe_inst_code varchar(20) NULL,
    tax_reg_no varchar(30) NULL,
    reg_expd_date DATE NULL,
    tax_area_no varchar(30) NULL,
    area_expd_date DATE NULL,
    tax_org varchar(60) NULL,
    loan_card_flag bpchar(1) NULL,
    loan_card_no varchar(20) NULL,
    loan_card_due_date DATE NULL,
    loan_card_chk_date DATE NULL,
    unit_credit_code varchar(30) NULL,
    mang_dept varchar(30) NULL,
    corp_subj varchar(30) NULL,
    industry_type varchar(30) NULL,
    econ_kind varchar(30) NULL,
    basic_acc_lic_no varchar(30) NULL,
    basic_acc_permit_no varchar(30) NULL,
    basic_acc_bank_no varchar(30) NULL,
    basic_acc_open_bank varchar(80) NULL,
    basic_acc_no varchar(30) NULL,
    busi_lic_no varchar(30) NULL,
    admn_type varchar(1600) NULL,
    side_type varchar(200) NULL,
    country_mng varchar(30) NULL,
    province_mng varchar(30) NULL,
    mng_situation varchar(30) NULL,
    mng_operate_area numeric(10) NULL,
    mng_operate_ownership varchar(30) NULL,
    comp_size varchar(30) NULL,
    emp_num numeric(10) NULL,
    total_assets numeric(20,
    2) NULL,
    net_assets numeric(20,
    2) NULL,
    sell_sum numeric(20,
    2) NULL,
    annual_income numeric(20,
    2) NULL,
    free_tax_flag bpchar(1) NULL,
    free_tax_limit varchar(10) NULL,
    private_flag bpchar(1) NULL,
    listed_flag bpchar(1) NULL,
    listed_on varchar(30) NULL,
    stock_code varchar(30) NULL,
    holding_type varchar(30) NULL,
    actual_controller varchar(200) NULL,
    new_tech_corpornot bpchar(1) NULL,
    spe_industry_flag bpchar(1) NULL,
    spe_industry_lic varchar(30) NULL,
    imex_mana_ind bpchar(1) NULL,
    fin_cust_type varchar(30) NULL,
    fin_org_type varchar(30) NULL,
    swift_no varchar(20) NULL,
    fin_lic_no varchar(30) NULL,
    fin_org_cd varchar(30) NULL,
    fin_manage_area varchar(200) NULL,
    busi_area_code varchar(30) NULL,
    cust_fore_exch_attr bpchar(1) NULL,
    nra_flag bpchar(1) NULL,
    fore_cust_type varchar(30) NULL,
    fore_exch_lic_no varchar(30) NULL,
    busi_site_code varchar(30) NULL,
    res_country varchar(30) NULL,
    fore_basic_acc_bank varchar(60) NULL,
    fore_basic_acc varchar(30) NULL,
    fore_inv_country varchar(30) NULL,
    spe_econ_inst_flag bpchar(1) NULL,
    spe_econ_inst_type varchar(30) NULL,
    pay_lis_flag bpchar(1) NULL,
    fore_safe_no varchar(30) NULL,
    fore_industry_type varchar(30) NULL,
    fore_econ_type varchar(30) NULL,
    fore_first_name varchar(200) NULL,
    fore_second_name varchar(200) NULL,
    bank_rel_flag varchar(30) NULL,
    shareholder_flag bpchar(1) NULL,
    bank_svr_grade varchar(30) NULL,
    cust_eval_level varchar(30) NULL,
    credit_level varchar(30) NULL,
    evaluate_date DATE NULL,
    other_credit_level varchar(30) NULL,
    other_evaluate_date DATE NULL,
    other_org_name varchar(100) NULL,
    evaluate_level varchar(30) NULL,
    cust_level varchar(30) NULL,
    cust_manager_no varchar(20) NULL,
    cust_mng_name varchar(100) NULL,
    own_org varchar(20) NULL,
    open_org varchar(20) NULL,
    open_teller varchar(20) NULL,
    open_date varchar(50) NULL,
    cust_status bpchar(1) NULL,
    last_updated_te varchar(20) NULL,
    last_updated_org varchar(20) NULL,
    created_ts timestamp(6) NULL,
    updated_ts timestamp(6) NULL,
    init_system_id varchar(30) NULL,
    init_created_ts timestamp(6) NULL,
    last_system_id varchar(30) NULL,
    last_updated_ts timestamp(6) NULL,
    ryzd varchar(1) NULL
);