-- ============================================================
-- Functional validation: detail + statis assertions (batch 20260630)
-- ============================================================
SET PAGESIZE 200
SET LINESIZE 300

PROMPT ============ F1 Detail row count (expected 15; P14 cross-org probe) ============
SELECT COUNT(*) AS DETAIL_ROW_CNT FROM ADS_CUST_POTN_UPGRADE_CUST_DTL;
SELECT CUST_ID, COUNT(*) AS CNT FROM ADS_CUST_POTN_UPGRADE_CUST_DTL
 GROUP BY CUST_ID HAVING COUNT(*) > 1 ORDER BY CUST_ID;
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_POTN_UPGRADE_CUST_DTL WHERE CUST_ID='P14') = 2
            THEN 'PASS' ELSE 'FAIL' END AS F1_P14_NO_CARTESIAN
  FROM dual;

PROMPT ============ F2 LVL_CRIT classification ============
SELECT CUST_ID, LVL_CRIT
  FROM (SELECT CUST_ID, MAX(LVL_CRIT) LVL_CRIT FROM ADS_CUST_POTN_UPGRADE_CUST_DTL GROUP BY CUST_ID)
 WHERE CUST_ID IN ('P01','P02','P04','P05','P06','P07','P08','P12','P13','P15','P16','P17','P18')
 ORDER BY CUST_ID;
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_POTN_UPGRADE_CUST_DTL
                  WHERE (CUST_ID='P01' AND LVL_CRIT='03') OR (CUST_ID='P04' AND LVL_CRIT='04')
                     OR (CUST_ID='P06' AND LVL_CRIT='05') OR (CUST_ID='P07' AND LVL_CRIT='06')
                     OR (CUST_ID='P08' AND LVL_CRIT='07')) = 5
            THEN 'PASS' ELSE 'FAIL' END AS F2_LEVELS
  FROM dual;

PROMPT ============ F3 Exclusion rules (P03/P09/P10/P11 must be absent) ============
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_POTN_UPGRADE_CUST_DTL
                  WHERE CUST_ID IN ('P03','P09','P10','P11')) = 0
            THEN 'PASS' ELSE 'FAIL' END AS F3_EXCLUSIONS
  FROM dual;

PROMPT ============ F4 QUAL_STATE point-in-time threshold ============
SELECT CUST_ID, QUAL_STATE
  FROM (SELECT CUST_ID, MAX(QUAL_STATE) QUAL_STATE FROM ADS_CUST_POTN_UPGRADE_CUST_DTL GROUP BY CUST_ID)
 WHERE CUST_ID IN ('P01','P02','P04','P05','P06','P07','P08','P12','P13','P15','P16','P17','P18')
 ORDER BY CUST_ID;
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_POTN_UPGRADE_CUST_DTL
                  WHERE (CUST_ID='P01' AND QUAL_STATE='1') OR (CUST_ID='P02' AND QUAL_STATE='0')
                     OR (CUST_ID='P04' AND QUAL_STATE='1') OR (CUST_ID='P05' AND QUAL_STATE='0')
                     OR (CUST_ID='P12' AND QUAL_STATE='0') OR (CUST_ID='P13' AND QUAL_STATE='1')
                     OR (CUST_ID='P15' AND QUAL_STATE='0') OR (CUST_ID='P18' AND QUAL_STATE='1')) = 8
            THEN 'PASS' ELSE 'FAIL' END AS F4_QUAL
  FROM dual;

PROMPT ============ F5 CNTCT_STATE contact window ============
SELECT CUST_ID, CNTCT_STATE
  FROM (SELECT CUST_ID, MAX(CNTCT_STATE) CNTCT_STATE FROM ADS_CUST_POTN_UPGRADE_CUST_DTL GROUP BY CUST_ID)
 WHERE CUST_ID IN ('P01','P04','P06','P08','P12','P17','P18')
 ORDER BY CUST_ID;
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_POTN_UPGRADE_CUST_DTL
                  WHERE (CUST_ID='P01' AND CNTCT_STATE='1') OR (CUST_ID='P04' AND CNTCT_STATE='1')
                     OR (CUST_ID='P06' AND CNTCT_STATE='1') OR (CUST_ID='P08' AND CNTCT_STATE='1')
                     OR (CUST_ID='P12' AND CNTCT_STATE='1') OR (CUST_ID='P17' AND CNTCT_STATE='0')
                     OR (CUST_ID='P18' AND CNTCT_STATE='1')) = 7
            THEN 'PASS' ELSE 'FAIL' END AS F5_CNTCT
  FROM dual;

PROMPT ============ F6 Output completeness (cycle/date/manager/org) ============
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_POTN_UPGRADE_CUST_DTL
                  WHERE DATA_DATE='20260630' AND STATIS_CYCLE='M') = 
              (SELECT COUNT(*) FROM ADS_CUST_POTN_UPGRADE_CUST_DTL)
             AND (SELECT COUNT(*) FROM ADS_CUST_POTN_UPGRADE_CUST_DTL WHERE POST_ID IS NULL) = 2
            THEN 'PASS' ELSE 'FAIL' END AS F6_COMPLETENESS
  FROM dual;

PROMPT ============ F7 Statis rollup (unpolluted slices) ============
SELECT STATIS_OBJ, LVL_CRIT, TTL_CUST_CNT, MTH_AVG_QUAL_CNT, MTH_AVG_QUAL_RATE,
       PNT_QUAL_CNT, PNT_QUAL_RATE, CNTCT_CUST_CNT, CNTCT_RATE
  FROM ADS_CUST_POTN_UPGRADE_STATIS
 WHERE (STATIS_OBJ='ORG100' AND LVL_CRIT IN ('04','05','06','07'))
    OR (STATIS_OBJ='ORG102' AND LVL_CRIT='03')
    OR (STATIS_OBJ='ORG101' AND LVL_CRIT='04')
 ORDER BY STATIS_OBJ, LVL_CRIT;
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_POTN_UPGRADE_STATIS
                  WHERE (STATIS_OBJ='ORG100' AND LVL_CRIT='04' AND TTL_CUST_CNT=4
                         AND MTH_AVG_QUAL_CNT=1 AND MTH_AVG_QUAL_RATE=25
                         AND PNT_QUAL_CNT=2 AND PNT_QUAL_RATE=50
                         AND CNTCT_CUST_CNT=1 AND CNTCT_RATE=25)
                     OR (STATIS_OBJ='ORG102' AND LVL_CRIT='03' AND TTL_CUST_CNT=1
                         AND MTH_AVG_QUAL_CNT=1 AND MTH_AVG_QUAL_RATE=100
                         AND PNT_QUAL_CNT=1 AND PNT_QUAL_RATE=100
                         AND CNTCT_CUST_CNT=1 AND CNTCT_RATE=100)
                     OR (STATIS_OBJ='ORG100' AND LVL_CRIT='06' AND TTL_CUST_CNT=1
                         AND MTH_AVG_QUAL_CNT=0 AND MTH_AVG_QUAL_RATE=0
                         AND PNT_QUAL_CNT=1 AND PNT_QUAL_RATE=100)) = 3
            THEN 'PASS' ELSE 'FAIL' END AS F7_ROLLUP
  FROM dual;

PROMPT ============ F8 Manager rollup PM100 (no cross-org pollution) ============
SELECT STATIS_OBJ, LVL_CRIT, TTL_CUST_CNT, MTH_AVG_QUAL_CNT, MTH_AVG_QUAL_RATE,
       PNT_QUAL_CNT, PNT_QUAL_RATE, CNTCT_CUST_CNT, CNTCT_RATE
  FROM ADS_CUST_POTN_UPGRADE_STATIS
 WHERE STATIS_OBJ='PM100' ORDER BY LVL_CRIT;
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_POTN_UPGRADE_STATIS
                  WHERE STATIS_OBJ='PM100'
                    AND ((LVL_CRIT='03' AND TTL_CUST_CNT=2 AND MTH_AVG_QUAL_RATE=50 AND PNT_QUAL_RATE=50 AND CNTCT_RATE=50)
                      OR (LVL_CRIT='04' AND TTL_CUST_CNT=2 AND MTH_AVG_QUAL_RATE=50 AND PNT_QUAL_RATE=50 AND CNTCT_RATE=50)
                      OR (LVL_CRIT='05' AND TTL_CUST_CNT=1 AND MTH_AVG_QUAL_RATE=100 AND PNT_QUAL_RATE=100 AND CNTCT_RATE=100)
                      OR (LVL_CRIT='06' AND TTL_CUST_CNT=1 AND MTH_AVG_QUAL_RATE=0 AND PNT_QUAL_RATE=100 AND CNTCT_RATE=0)
                      OR (LVL_CRIT='07' AND TTL_CUST_CNT=1 AND MTH_AVG_QUAL_RATE=100 AND PNT_QUAL_RATE=100 AND CNTCT_RATE=100))) = 5
            THEN 'PASS' ELSE 'FAIL' END AS F8_PM100
  FROM dual;

EXIT
