/*
 * ADS_CUST_SLEEP_WAKE_DTL
 * 中文名称: 睡眠户明细表
 * 版本: v2.16.0
 * 创建时间: 2026-07-30
 * 更新: v2.0 新增INSUR_AMT，消除"幽灵唤醒"问题
 *       v2.14.0 版本同步至存储过程v2.14.0
 *       v2.16.0 版本同步至存储过程v2.16.0（睡眠户来源切换DWS_CUST_DORMANT_ACCOUNT）
 * 说明: 记录月度睡眠客户清单、产品余额、接触状态和当月唤醒状态；月内清单只增不减，
 *       月初由过程重新计算，不单独保存睡眠开始时间、唤醒时间或存量/新增字段。
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_SLEEP_WAKE_DTL (
    PERSN_LEGAL_BK_CODE VARCHAR(4),
    DATA_DATE VARCHAR(8),
    CUST_ID VARCHAR(20),
    CUST_NAME VARCHAR(100),
    CUST_LVL VARCHAR(2),
    DEPO_CURNT_DEPO_BAL NUMBER(20,2),
    FIXD_DEPO_BAL NUMBER(20,2),
    FIN_AMT NUMBER(20,2),
    INSUR_AMT NUMBER(20,2),
    CNTCT_STATE VARCHAR(1),
    WAKE_STATE VARCHAR(1),
    POST_ID VARCHAR(20),
    ORG_ID VARCHAR(7),
    STATIS_CYCLE VARCHAR(2)
);

COMMENT ON TABLE ADS_CUST_SLEEP_WAKE_DTL IS '睡眠户明细表';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_DTL.PERSN_LEGAL_BK_CODE IS '法人行号：VARCHAR(4)，非空业务键组成部分，取值为法人行编码。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_DTL.DATA_DATE IS '数据日期：VARCHAR(8)，YYYYMMDD，当前跑批日；同一客户同一法人机构同一日期仅保留月度记录。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_DTL.CUST_ID IS '客户编号：VARCHAR(20)，客户唯一标识；与法人行号、归属机构共同确定业务粒度。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_DTL.CUST_NAME IS '客户名称：VARCHAR(100)，客户展示名称，可随源快照更新。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_DTL.CUST_LVL IS '客户等级：VARCHAR(2)，取值由客户等级快照提供，允许空值。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_DTL.DEPO_CURNT_DEPO_BAL IS '活期余额：NUMBER(20,2)，金额元，缺失按0处理，允许负数由资产快照口径决定。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_DTL.FIXD_DEPO_BAL IS '定期余额：NUMBER(20,2)，金额元，缺失按0处理；用于新增定期唤醒判断。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_DTL.FIN_AMT IS '理财余额：NUMBER(20,2)，金额元，缺失按0处理；用于新增理财唤醒判断。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_DTL.INSUR_AMT IS '保险余额：NUMBER(20,2)，金额元，缺失按0处理；用于新增保险唤醒判断。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_DTL.CNTCT_STATE IS '接触状态：VARCHAR(1)，仅允许0/1，0=当月未接触、1=当月至少一次有效接触，月首重置后月内累计。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_DTL.WAKE_STATE IS '唤醒状态：VARCHAR(1)，仅允许0/1，0=当月未唤醒、1=当月新增持有定期/理财/保险，月首重置后月内只增不减。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_DTL.POST_ID IS '管户经理：VARCHAR(20)，理财管户经理编号，允许空值。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_DTL.ORG_ID IS '归属机构：VARCHAR(7)，资产快照归属机构编码，允许空值但参与机构粒度计算。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_DTL.STATIS_CYCLE IS '统计周期：VARCHAR(2)，固定取值M，表示月度统计。';
