/*
 * ADS_CUST_LOST_STATIS
 * 中文名称: 客户挽回统计表
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_LOST_STATIS (
    PERSN_LEGAL_BK_CODE VARCHAR(4),
    DATA_DATE VARCHAR(8),
    STATIS_OBJ VARCHAR(20),
    STATIS_CYCLE VARCHAR(2),
    LVL_CHURN VARCHAR(1),
    CUST_CNT NUMBER(8),
    CNTCT_CUST_CNT NUMBER(8),
    CNTCT_RATE NUMBER(20,
    2),
    RESCUED_CUST_CNT NUMBER(8),
    RESCUE_RATE NUMBER(20,
    2),
    RESCUED_FINA_ASSET NUMBER(20,
    2)
);

COMMENT ON TABLE ADS_CUST_LOST_STATIS IS '客户挽回统计表';
COMMENT ON COLUMN ADS_CUST_LOST_STATIS.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CUST_LOST_STATIS.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_CUST_LOST_STATIS.STATIS_OBJ IS '统计对象(机构/客户经理)';
COMMENT ON COLUMN ADS_CUST_LOST_STATIS.STATIS_CYCLE IS '统计周期(月/季/年)';
COMMENT ON COLUMN ADS_CUST_LOST_STATIS.LVL_CHURN IS '流失等级';
COMMENT ON COLUMN ADS_CUST_LOST_STATIS.CUST_CNT IS '客户数';
COMMENT ON COLUMN ADS_CUST_LOST_STATIS.CNTCT_CUST_CNT IS '已接触客户';
COMMENT ON COLUMN ADS_CUST_LOST_STATIS.CNTCT_RATE IS '接触率';
COMMENT ON COLUMN ADS_CUST_LOST_STATIS.RESCUED_CUST_CNT IS '已挽回客户';
COMMENT ON COLUMN ADS_CUST_LOST_STATIS.RESCUE_RATE IS '挽回率';
COMMENT ON COLUMN ADS_CUST_LOST_STATIS.RESCUED_FINA_ASSET IS '已挽回金融资产';