/*
 * ads_cust_new_cust_statis
 * 中文名称: 新客经营统计表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS ads_cust_new_cust_statis (
    DATA_DATE VARCHAR(8) NOT NULL COMMENT '数据日期',
    STATIS_OBJ VARCHAR(2) NULL COMMENT '统计对象',
    STATIS_CYCLE VARCHAR(2) NULL COMMENT '统计周期',
    NEW_CUST_CYCLE VARCHAR(1) NULL COMMENT '新客周期',
    NEW_CUST_CNT NUMBER(8) NULL COMMENT '新客数',
    CNTCT_CUST_CNT NUMBER(8) NULL COMMENT '已接触客户',
    ASSET_BAL_SEG1_CUST_CNT NUMBER(8) NULL COMMENT '资产余额区间1客户数',
    ASSET_BAL_SEG2_CUST_CNT NUMBER(8) NULL COMMENT '资产余额区间2客户数',
    ASSET_BAL_SEG3_CUST_CNT NUMBER(8) NULL COMMENT '资产余额区间3客户数',
    ASSET_BAL_SEG4_CUST_CNT NUMBER(8) NULL COMMENT '资产余额区间4客户数',
    ASSET_BAL_SEG5_CUST_CNT NUMBER(8) NULL COMMENT '资产余额区间5客户数',
    CNTCT_RATE NUMBER(20,2) NULL COMMENT '接触率',
    KYC_CUST_CNT NUMBER(8) NULL COMMENT 'KYC客户',
    COMP_RATE NUMBER(20,2) NULL COMMENT '完成率'
);

COMMENT ON TABLE ads_cust_new_cust_statis IS '新客经营统计表';
