/*
 * ADS_CUST_POTN_UPGRADE_CUST_DTL
 * 中文名称: 潜力提升客户明细列表
 * 版本: v2.2.0
 * 创建时间: 2026-07-20
 * 变更记录:
 *   v2.2.0 2026-07-28 修复NUMBER格式断裂、补行内注释、年码值N→Y
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_POTN_UPGRADE_CUST_DTL (
    PERSN_LEGAL_BK_CODE  VARCHAR(4),     -- 法人行号
    DATA_DATE            VARCHAR(8),     -- 数据日期
    CUST_ID              VARCHAR(20),    -- 客户编号
    CUST_NAME            VARCHAR(100),   -- 客户名称
    CUST_LVL             VARCHAR(2),     -- 客户等级
    LVL_CRIT             VARCHAR(2),     -- 临界等级
    DEPO_CURNT_DEPO_BAL  NUMBER(20,2),   -- 活期余额
    FIXD_DEPO_BAL        NUMBER(20,2),   -- 定期余额
    FIN_AMT              NUMBER(20,2),   -- 理财余额
    CNTCT_STATE          VARCHAR(1),     -- 接触状态
    QUAL_STATE           VARCHAR(1),     -- 时点达标状态：0否，1是
    POST_ID              VARCHAR(20),    -- 管户经理
    ORG_ID               VARCHAR(7),     -- 归属机构
    STATIS_CYCLE         VARCHAR(2)      -- 统计周期：M-月,Q-季,Y-年
);

COMMENT ON TABLE ADS_CUST_POTN_UPGRADE_CUST_DTL IS '潜力提升客户明细列表';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_CUST_DTL.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_CUST_DTL.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_CUST_DTL.CUST_ID IS '客户编号';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_CUST_DTL.CUST_NAME IS '客户名称';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_CUST_DTL.CUST_LVL IS '客户等级';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_CUST_DTL.LVL_CRIT IS '临界等级';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_CUST_DTL.DEPO_CURNT_DEPO_BAL IS '活期余额';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_CUST_DTL.FIXD_DEPO_BAL IS '定期余额';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_CUST_DTL.FIN_AMT IS '理财余额';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_CUST_DTL.CNTCT_STATE IS '接触状态';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_CUST_DTL.QUAL_STATE IS '时点达标状态：0否，1是';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_CUST_DTL.POST_ID IS '管户经理';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_CUST_DTL.ORG_ID IS '归属机构';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_CUST_DTL.STATIS_CYCLE IS '统计周期：M-月,Q-季,Y-年';
