/*
 * ADS_CUST_INDV_POTEN
 * 中文名称: 零售潜在客户信息
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_INDV_POTEN (
    POTEN_CUST_ID VARCHAR(40) NOT NULL COMMENT '潜在客户号(自增键)',
    POTEN_CUST_NAME VARCHAR(100) NULL COMMENT '潜在客户名称',
    POTEN_TYP VARCHAR(6) NULL COMMENT '潜客类型',
    POTEN_CUST_TYP VARCHAR(6) NULL COMMENT '潜在客户类型',
    GENDER VARCHAR(6) NULL COMMENT '性别',
    CERT_TYP VARCHAR(6) NULL COMMENT '证件类型',
    CERT_ID VARCHAR(32) NULL COMMENT '证件号码',
    TEL_NO VARCHAR(32) NULL COMMENT '联系电话',
    INTENT_DSC VARCHAR(400) NULL COMMENT '备注说明',
    DTL_ADDRS VARCHAR(400) NULL COMMENT '居住地址',
    CREATR VARCHAR(20) NULL COMMENT '创建人',
    CREAT_TIME VARCHAR(20) NULL COMMENT '创建时间',
    POTEN_CUST_STATE VARCHAR(6) NULL COMMENT '潜在客户状态',
    LPR_ID VARCHAR(4) NULL COMMENT '法人行号',
    SRC_TYP VARCHAR(6) NULL COMMENT '来源类型',
    MKT_PERSN VARCHAR(20) NULL COMMENT '客户经理',
    ALLO_DATE VARCHAR(8) NULL COMMENT '分配日期(创建时和创建日期一致)',
    MKT_ORG VARCHAR(6) NULL COMMENT '归属机构',
    SERV_ENTER VARCHAR(200) NULL COMMENT '工作单位',
    POST VARCHAR(6) NULL COMMENT '职位',
    MTH_INCOM NUMBER(20,2) NULL COMMENT '月收入',
    YR_INCOM NUMBER(20,2) NULL COMMENT '年收入',
    RMARK VARCHAR(400) NULL COMMENT '备注',
    INF_KLKT_DATE VARCHAR(10) NULL COMMENT '潜客转化日期',
    UNIT_ADDRS VARCHAR(200) NULL COMMENT '工作单位地址',
    INTN_PRDKT VARCHAR(60) NULL COMMENT '意向产品',
    NO_BAT VARCHAR(40) NULL COMMENT '批次号',
    CUST_ID VARCHAR(21) NULL COMMENT '转化后核心客户号',
    POT_CNVRT_PRDKT VARCHAR(60) NULL COMMENT '潜客转化产品',
    POT_CNVRT_ORG VARCHAR(6) NULL COMMENT '潜客转化机构'
);

COMMENT ON TABLE ADS_CUST_INDV_POTEN IS '零售潜在客户信息';
