/*
 * ADS_CUST_PRDKT_RCMD
 * 中文名称: 到期承接推荐产品
 * 版本: v2.1
 * 创建时间: 2026-08-25 (v1.0) / 2026-08-26 (v2.0 对齐10列定稿) / 2026-09-02 (v2.1)
 * 需求版本: REQ-RCMD-001 (V1.1)
 * 变更记录:
 *   v1.0 2026-08-25 首建(9列)
 *   v2.0 2026-08-26 按业务定稿对齐10列: 新增PERSN_LEGAL_BK_CODE(法人行号);
 *        MATCH_DEG_PRDKT语义调整为百分制加权总分(0-100,2位小数);
 *        维度分不落表(审计载体=MKT_SCRIPT推荐理由)
 *   v2.1 2026-09-02 业务确认: PRDKT_ID长度30→40(对齐DWD源表最大长度, N-2消解);
 *        RATE_INTRI精度NUMBER(22,2)→NUMBER(12,7)(按原有值落表不做截断, N-3消解)
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_PRDKT_RCMD (
    PERSN_LEGAL_BK_CODE VARCHAR(4) NOT NULL, -- 法人行号
    DATA_DATE VARCHAR(8) NOT NULL, -- 数据日期
    CUST_ID VARCHAR(20) NOT NULL, -- 客户编号
    PRDKT_ID VARCHAR(40) NOT NULL, -- 产品编号(对齐DWD源表40长度; 空候选占位行=NA)
    PRDKT_NAME VARCHAR(100), -- 产品名称
    MATCH_DEG_PRDKT NUMBER(22,2), -- 产品匹配度(四维加权总分0-100, 四舍五入2位)
    PRDKT_TYP VARCHAR(6), -- 产品类型
    RATE_INTRI NUMBER(12,7), -- 利率或预期收益率(按原有精度, 不做截断)
    RISK_LVL VARCHAR(10), -- 风险等级
    MKT_SCRIPT VARCHAR(1000) -- 营销话术(推荐理由/暂无适配产品)
);

COMMENT ON TABLE ADS_CUST_PRDKT_RCMD IS '到期承接推荐产品';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.CUST_ID IS '客户编号';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.PRDKT_ID IS '产品编号(空候选占位行=NA)';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.PRDKT_NAME IS '产品名称';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.MATCH_DEG_PRDKT IS '产品匹配度(四维加权总分0-100)';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.PRDKT_TYP IS '产品类型';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.RATE_INTRI IS '利率或预期收益率';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.RISK_LVL IS '风险等级';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.MKT_SCRIPT IS '营销话术(推荐理由/暂无适配产品)';
