/*
 * ADS_CUST_OTHERS_RMND
 * 中文名称: 其他事件提醒
 * 版本: v1.0.0
 * 创建时间: 2026-07-29
 * 来源: Mapping Excel (ADS应用层数据模型)
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_OTHERS_RMND (
    RMND_ID              VARCHAR2, -- 提醒ID
    RMND_CATE_BIG        VARCHAR2, -- 提醒类型(1-贷款逾期提醒,2-贷款欠息提醒,3-贷款还款余额不足提醒,4-收单商户长期无交易提醒,5-销户提醒,6-客户分配,7-客户回收,8-客户移交,9-客户调配)
    RMND_CATE_SML        VARCHAR2, -- 提醒名称
    MNGR_POST_ID         VARCHAR2, -- 客户经理编号
    MNGR_NAME            VARCHAR2, -- 客户经理名称
    ORG_ID               VARCHAR2, -- 机构编号
    CUST_TYP             VARCHAR2, -- 客户类型
    CUST_ID              VARCHAR2, -- 客户ID
    CUST_NAME            VARCHAR2, -- 客户名称
    PHONE_NO             VARCHAR2, -- 手机号
    RMND_INF             VARCHAR2, -- 提醒内容
    HDLE_STATE           VARCHAR2, -- 处理状态(0未读 1已读)
    RMND_DATE            VARCHAR2, -- 提醒日期
    PERSN_LEGAL_BK_CODE  VARCHAR2, -- 法人行号
    HDLE_TIME            VARCHAR2, -- 处理时间
    DEL_FLG              VARCHAR2, -- 删除标志
    HDLE_DSC             VARCHAR2  -- 处理说明
);

COMMENT ON TABLE ADS_CUST_OTHERS_RMND IS '其他事件提醒';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.RMND_ID IS '提醒ID';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.RMND_CATE_BIG IS '提醒类型(1-贷款逾期提醒,2-贷款欠息提醒,3-贷款还款余额不足提醒,4-收单商户长期无交易提醒,5-销户提醒,6-客户分配,7-客户回收,8-客户移交,9-客户调配)';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.RMND_CATE_SML IS '提醒名称';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.MNGR_POST_ID IS '客户经理编号';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.MNGR_NAME IS '客户经理名称';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.ORG_ID IS '机构编号';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.CUST_TYP IS '客户类型';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.CUST_ID IS '客户ID';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.CUST_NAME IS '客户名称';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.PHONE_NO IS '手机号';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.RMND_INF IS '提醒内容';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.HDLE_STATE IS '处理状态(0未读 1已读)';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.RMND_DATE IS '提醒日期';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.HDLE_TIME IS '处理时间';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.DEL_FLG IS '删除标志';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.HDLE_DSC IS '处理说明';
