/*
 * ADS_MKT_ACT_TSK_MON
 * 中文名称: 营销活动任务监控
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_MKT_ACT_TSK_MON (
    DATA_DATE VARCHAR(8),
    STAT_OBJ VARCHAR(2),
    MKT_ACT_ID VARCHAR(40),
    CUST_CNT NUMBER(8),
    CTKT_COVER_RATE NUMBER(10,
    2),
    PLAN_SUPPORT_CUST_CNT NUMBER(8),
    FURTHER_MKT_CUST_CNT NUMBER(8),
    NOT_SUPPORT_CUST_CNT NUMBER(8),
    MKT_SUCCESS_RATE NUMBER(10,
    2)
);

COMMENT ON TABLE ADS_MKT_ACT_TSK_MON IS '营销活动任务监控';
COMMENT ON COLUMN ADS_MKT_ACT_TSK_MON.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_MKT_ACT_TSK_MON.STAT_OBJ IS '统计对象';
COMMENT ON COLUMN ADS_MKT_ACT_TSK_MON.MKT_ACT_ID IS '营销活动编号';
COMMENT ON COLUMN ADS_MKT_ACT_TSK_MON.CUST_CNT IS '客户数';
COMMENT ON COLUMN ADS_MKT_ACT_TSK_MON.CTKT_COVER_RATE IS '接触覆盖率';
COMMENT ON COLUMN ADS_MKT_ACT_TSK_MON.PLAN_SUPPORT_CUST_CNT IS '拟支持客户数';
COMMENT ON COLUMN ADS_MKT_ACT_TSK_MON.FURTHER_MKT_CUST_CNT IS '进一步营销客户数';
COMMENT ON COLUMN ADS_MKT_ACT_TSK_MON.NOT_SUPPORT_CUST_CNT IS '不予支持客户数';
COMMENT ON COLUMN ADS_MKT_ACT_TSK_MON.MKT_SUCCESS_RATE IS '营销成功率';