/*
 * ads_cust_lost_statis
 * 中文名称: 客户挽回统计表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS ads_cust_lost_statis (
    DATA_DATE VARCHAR(8) NOT NULL COMMENT '数据日期',
    STATIS_OBJ VARCHAR(2) NULL COMMENT '统计对象',
    STATIS_CYCLE VARCHAR(2) NULL COMMENT '统计周期',
    LVL_CHURN VARCHAR(1) NULL COMMENT '流失等级',
    CUST_CNT NUMBER(8) NULL COMMENT '客户数',
    CNTCT_CUST_CNT NUMBER(8) NULL COMMENT '已接触客户',
    CNTCT_RATE NUMBER(20,2) NULL COMMENT '接触率',
    RESCUED_CUST_CNT NUMBER(8) NULL COMMENT '已挽回客户',
    RESCUE_RATE NUMBER(20,2) NULL COMMENT '挽回率',
    RESCUED_FINA_ASSET NUMBER(20,2) NULL COMMENT '已挽回金融资产'
);

COMMENT ON TABLE ads_cust_lost_statis IS '客户挽回统计表';
