/*
 * ADS_CUST_PRDKT_RCMD
 * 中文名称: 到期承接推荐产品
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_PRDKT_RCMD (
    DATA_DATE VARCHAR(8),
    CUST_ID VARCHAR(20),
    PRDKT_ID VARCHAR(30),
    PRDKT_NAME VARCHAR(100),
    MATCH_DEG_PRDKT NUMBER(18,
    2),
    PRDKT_TYP VARCHAR(6),
    RATE_INTRI NUMBER(18,
    2),
    RISK_LVL VARCHAR(10),
    MKT_SCRIPT VARCHAR(1000)
);

COMMENT ON TABLE ADS_CUST_PRDKT_RCMD IS '到期承接推荐产品';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.CUST_ID IS '客户编号';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.PRDKT_ID IS '产品编号';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.PRDKT_NAME IS '产品名称';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.MATCH_DEG_PRDKT IS '产品匹配度';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.PRDKT_TYP IS '产品类型';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.RATE_INTRI IS '利率或预期收益率';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.RISK_LVL IS '风险等级';
COMMENT ON COLUMN ADS_CUST_PRDKT_RCMD.MKT_SCRIPT IS '营销话术';