/*
 * ADS_CUST_SLEEP_WAKE_STATIS
 * 中文名称: 睡眠户唤醒统计表
 * 版本: v2.16.0
 * 创建时间: 2026-07-30
 * 说明: 仅统计睡眠客户总数/接触/唤醒，不区分存量/新增类型。
 *       v2.12.1 版本同步至存储过程v2.12.1
 *       v2.16.0 版本同步至存储过程v2.16.0（统计逻辑不变，随明细口径切换）
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_SLEEP_WAKE_STATIS (
    PERSN_LEGAL_BK_CODE VARCHAR(4),
    DATA_DATE VARCHAR(8),
    STATIS_OBJ VARCHAR(20),
    STATIS_CYCLE VARCHAR(2),
    CUST_CNT NUMBER(8),
    CNTCT_CUST_CNT NUMBER(8),
    CNTCT_RATE NUMBER(20,2),
    WAKE_CUST_CNT NUMBER(8),
    WAKE_RATE NUMBER(20,2)
);

COMMENT ON TABLE ADS_CUST_SLEEP_WAKE_STATIS IS '睡眠户唤醒统计表';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.PERSN_LEGAL_BK_CODE IS '法人行号：VARCHAR(4)，统计业务键组成部分，取值为法人行编码。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.DATA_DATE IS '数据日期：VARCHAR(8)，YYYYMMDD，统计快照日期。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.STATIS_OBJ IS '统计对象：VARCHAR(20)，机构编号或客户经理编号，由统计维度决定。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.STATIS_CYCLE IS '统计周期：VARCHAR(2)，固定取值M，表示月度统计。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.CUST_CNT IS '睡眠客户总数：NUMBER(8)，非负整数，按当前清单客户记录计数。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.CNTCT_CUST_CNT IS '已接触客户数：NUMBER(8)，非负整数，CNTCT_STATE=1的客户数。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.CNTCT_RATE IS '接触率：NUMBER(20,2)，0至100，已接触客户数/睡眠客户总数×100%，总数为0时取0。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.WAKE_CUST_CNT IS '已唤醒客户数：NUMBER(8)，非负整数，WAKE_STATE=1的客户数。';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.WAKE_RATE IS '唤醒率：NUMBER(20,2)，0至100，已唤醒客户数/睡眠客户总数×100%，总数为0时取0。';
