/*
 * ADS_MKT_ACT_TSK_MON_ZB
 * 中文名称: 营销活动任务监控附表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS ADS_MKT_ACT_TSK_MON_ZB (
    DATA_DATE VARCHAR(8) NOT NULL COMMENT '数据日期',
    STAT_OBJ VARCHAR(2) NULL COMMENT '统计对象',
    MKT_ACT_ID VARCHAR(40) NULL COMMENT '营销活动编号',
    BASE_VAL NUMBER(20,2) NULL COMMENT '基准值',
    CURNT_VAL NUMBER(20,2) NULL COMMENT '当前值',
    INCR NUMBER(20,2) NULL COMMENT '增量',
    GROWTH_RATE NUMBER(10,2) NULL COMMENT '增长率'
);

COMMENT ON TABLE ADS_MKT_ACT_TSK_MON_ZB IS '营销活动任务监控附表';
