/*
 * ADS_MKT_TASK_INDX_SUB_CMPLT
 * 中文名称: 指标任务完成情况
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS ADS_MKT_TASK_INDX_SUB_CMPLT (
    TSK_INDX_ID VARCHAR(40) NOT NULL COMMENT '指标任务映射编号',
    TSK_ID VARCHAR(40) NULL COMMENT '任务编号',
    MAIN_TSK_ID VARCHAR(40) NULL COMMENT '主任务编号',
    INDX_ID VARCHAR(40) NULL COMMENT '指标ID',
    TSK_NEXT_SEND_TYP VARCHAR(6) NULL COMMENT '任务下发类型(0总行下发,1分行/区行下发,2支行下发)',
    RSV_OBJ VARCHAR(6) NULL COMMENT '接收对象0机构1客户经理',
    RSV_OBJ_ID VARCHAR(30) NULL COMMENT '接收对象ID',
    TSK_BGN_DATE VARCHAR(10) NULL COMMENT '任务开始时间',
    TSK_END_DATE VARCHAR(10) NULL COMMENT '任务结束时间',
    INDX_UNIT VARCHAR(20) NULL COMMENT '指标单位(万元/个数/百分比)',
    INDX_VAL NUMBER(18,4) NULL COMMENT '指标额',
    INDX_VAL_ADD NUMBER(18,4) NULL COMMENT '指标加码',
    ACUM_CMPLT_INDX NUMBER(18,4) NULL COMMENT '累计完成指标',
    DAY_CURNT_CMPLT_INDX NUMBER(18,4) NULL COMMENT '当天完成指标',
    BASE_VAL NUMBER(18,4) NULL COMMENT '基准值',
    CURNT_VAL NUMBER(18,4) NULL COMMENT '当前值',
    PERSN_LEGAL_BK_CODE VARCHAR(30) NULL COMMENT '法人行号'
);

COMMENT ON TABLE ADS_MKT_TASK_INDX_SUB_CMPLT IS '指标任务完成情况';
