/*
 * ADS_CUST_SLEEP_WAKE_STATIS
 * 中文名称: 睡眠户唤醒统计表
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_SLEEP_WAKE_STATIS (
    PERSN_LEGAL_BK_CODE VARCHAR(4),
    DATA_DATE VARCHAR(8),
    STATIS_OBJ VARCHAR(20),
    STATIS_CYCLE VARCHAR(2),
    CUST_CNT NUMBER(8),
    CNTCT_CUST_CNT NUMBER(8),
    CNTCT_RATE NUMBER(20,
    2),
    WAKE_CUST_CNT NUMBER(8),
    WAKE_RATE NUMBER(20,
    2)
);

COMMENT ON TABLE ADS_CUST_SLEEP_WAKE_STATIS IS '睡眠户唤醒统计表';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.STATIS_OBJ IS '统计对象';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.STATIS_CYCLE IS '统计周期(月/季/年)';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.CUST_CNT IS '客户数';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.CNTCT_CUST_CNT IS '已接触客户';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.CNTCT_RATE IS '接触率';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.WAKE_CUST_CNT IS '已唤醒客户';
COMMENT ON COLUMN ADS_CUST_SLEEP_WAKE_STATIS.WAKE_RATE IS '唤醒率';