/*
 * ADS_STAT_INDX_BASELINE_DTL
 * 中文名称: 指标基准-明细表
 * 版本: v1.0
 * 创建时间: 2026-08-26
 * 来源: prc_ads_stat_indx_plan_002.sql 3.2节 (逐客户状态基准: INDX_0052/0053/0054/0063)
 */

CREATE TABLE IF NOT EXISTS ADS_STAT_INDX_BASELINE_DTL (
    STATIS_CALIB        VARCHAR(100),
    STATIS_DIM          VARCHAR(100),
    INDX_CODE           VARCHAR(100),
    DATA_BLNG           VARCHAR(100),
    CUST_ID             VARCHAR(20),
    PERSN_LEGAL_BK_CODE VARCHAR(30),
    BASE_DATA_DATE      VARCHAR(10),
    BASE_RUN_DATE       VARCHAR(10),
    BASE_CUST_LVL       VARCHAR(2),
    BASE_MTH_AVG_AUM    NUMBER(20,2)
);

COMMENT ON TABLE ADS_STAT_INDX_BASELINE_DTL IS '指标基准-明细表';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.STATIS_CALIB IS '统计口径: 营销活动/目标任务';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.STATIS_DIM IS '统计维度: 活动ID或任务ID';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.INDX_CODE IS '指标编码: INDX_0052/0053/0054/0063';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.DATA_BLNG IS '数据归属: ORG_机构/MGR_客户经理';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.CUST_ID IS '客户号';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.BASE_DATA_DATE IS '基准数据日期(YYYYMMDD)';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.BASE_RUN_DATE IS '基准跑批日期(YYYYMMDD)';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.BASE_CUST_LVL IS '基准客户等级';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.BASE_MTH_AVG_AUM IS '基准月均AUM';
