/*
 * ADS_MKT_TSK_INFO
 * 中文名称: 营销任务表
 * 版本: v1.0.0
 * 创建时间: 2026-07-29
 * 来源: Mapping Excel (ADS应用层数据模型)
 */

CREATE TABLE IF NOT EXISTS ADS_MKT_TSK_INFO (
    MKT_TSK_ID           VARCHAR2(40) , -- 营销任务编号
    MKT_ACT_ID           VARCHAR2(40) , -- 活动编号
    CUST_ID              VARCHAR2(21) , -- 客户编号
    CUST_NAME            VARCHAR2(200), -- 客户名称
    COVER_FLG            VARCHAR2(1)  , -- 是否接触
    CONVRS_FLG           VARCHAR2(1)  , -- 是否成功
    MKT_PERSN            VARCHAR2(30) , -- 营销人
    MKT_PERSN_ORG        VARCHAR2(7)  , -- 营销人机构
    CREATR               VARCHAR2(64) , -- 创建人
    CREAT_TIME           VARCHAR2(20) , -- 创建时间
    CREAT_ORG            VARCHAR2(7)  , -- 创建机构
    BASE_VAL             NUMBER(18,4) , -- 基数
    CURNT_VAL            NUMBER(18,4) , -- 当前值
    DATA_DATE            VARCHAR2(30) , -- 数据日期
    PERSN_LEGAL_BK_CODE  VARCHAR2(30)   -- 法人行号
);

COMMENT ON TABLE ADS_MKT_TSK_INFO IS '营销任务表';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.MKT_TSK_ID IS '营销任务编号';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.MKT_ACT_ID IS '活动编号';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.CUST_ID IS '客户编号';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.CUST_NAME IS '客户名称';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.COVER_FLG IS '是否接触';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.CONVRS_FLG IS '是否成功';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.MKT_PERSN IS '营销人';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.MKT_PERSN_ORG IS '营销人机构';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.CREATR IS '创建人';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.CREAT_TIME IS '创建时间';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.CREAT_ORG IS '创建机构';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.BASE_VAL IS '基数';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.CURNT_VAL IS '当前值';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.PERSN_LEGAL_BK_CODE IS '法人行号';
