/*
 * ADS_MKT_ACT_TSK_MON_ZB
 * 中文名称: 营销活动任务监控附表
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_MKT_ACT_TSK_MON_ZB (
    DATA_DATE VARCHAR(8),
    STAT_OBJ VARCHAR(2),
    MKT_ACT_ID VARCHAR(40),
    BASE_VAL NUMBER(20,
    2),
    CURNT_VAL NUMBER(20,
    2),
    INCR NUMBER(20,
    2),
    GROWTH_RATE NUMBER(10,
    2)
);

COMMENT ON TABLE ADS_MKT_ACT_TSK_MON_ZB IS '营销活动任务监控附表';
COMMENT ON COLUMN ADS_MKT_ACT_TSK_MON_ZB.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_MKT_ACT_TSK_MON_ZB.STAT_OBJ IS '统计对象';
COMMENT ON COLUMN ADS_MKT_ACT_TSK_MON_ZB.MKT_ACT_ID IS '营销活动编号';
COMMENT ON COLUMN ADS_MKT_ACT_TSK_MON_ZB.BASE_VAL IS '基准值';
COMMENT ON COLUMN ADS_MKT_ACT_TSK_MON_ZB.CURNT_VAL IS '当前值';
COMMENT ON COLUMN ADS_MKT_ACT_TSK_MON_ZB.INCR IS '增量';
COMMENT ON COLUMN ADS_MKT_ACT_TSK_MON_ZB.GROWTH_RATE IS '增长率';