/*
 * ADS_CUST_POTN_UPGRADE_STATIS
 * 中文名称: 潜力提升统计表
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_POTN_UPGRADE_STATIS (
    PERSN_LEGAL_BK_CODE VARCHAR(4),
    DATA_DATE VARCHAR(8),
    STATIS_OBJ VARCHAR(20),
    STATIS_CYCLE VARCHAR(2),
    LVL_CRIT VARCHAR(2),
    TTL_CUST_CNT NUMBER(8),
    MTH_AVG_QUAL_CNT NUMBER(8),
    MTH_AVG_QUAL_RATE NUMBER(20,
    2),
    PNT_QUAL_CNT NUMBER(8),
    PNT_QUAL_RATE NUMBER(20,
    2),
    CNTCT_CUST_CNT NUMBER(8),
    CNTCT_RATE NUMBER(20,
    2)
);

COMMENT ON TABLE ADS_CUST_POTN_UPGRADE_STATIS IS '潜力提升统计表';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.STATIS_OBJ IS '统计对象';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.STATIS_CYCLE IS '统计周期(月/季/年)';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.LVL_CRIT IS '临界等级';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.TTL_CUST_CNT IS '总客户数';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.MTH_AVG_QUAL_CNT IS '月均达标';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.MTH_AVG_QUAL_RATE IS '月均达标率';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.PNT_QUAL_CNT IS '时点达标';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.PNT_QUAL_RATE IS '时点达标率';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.CNTCT_CUST_CNT IS '已接触客户';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.CNTCT_RATE IS '接触率';