/*
 * ADS_MKT_TASK_INDX_SUB_CMPLT
 * 中文名称: 指标任务完成情况
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_MKT_TASK_INDX_SUB_CMPLT (
    TSK_INDX_ID VARCHAR(40),
    TSK_ID VARCHAR(40),
    MAIN_TSK_ID VARCHAR(40),
    INDX_ID VARCHAR(40),
    TSK_NEXT_SEND_TYP VARCHAR(6),
    RSV_OBJ VARCHAR(6),
    RSV_OBJ_ID VARCHAR(30),
    TSK_BGN_DATE VARCHAR(10),
    TSK_END_DATE VARCHAR(10),
    INDX_UNIT VARCHAR(20),
    INDX_VAL NUMBER(18,
    4),
    INDX_VAL_ADD NUMBER(18,
    4),
    ACUM_CMPLT_INDX NUMBER(18,
    4),
    DAY_CURNT_CMPLT_INDX NUMBER(18,
    4),
    BASE_VAL NUMBER(18,
    4),
    CURNT_VAL NUMBER(18,
    4),
    PERSN_LEGAL_BK_CODE VARCHAR(30)
);

COMMENT ON TABLE ADS_MKT_TASK_INDX_SUB_CMPLT IS '指标任务完成情况';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.TSK_INDX_ID IS '指标任务映射编号';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.TSK_ID IS '任务编号';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.MAIN_TSK_ID IS '主任务编号';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.INDX_ID IS '指标ID';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.TSK_NEXT_SEND_TYP IS '任务下发类型(0总行下发,1分行/区行下发,2支行下发)';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.RSV_OBJ IS '接收对象0机构1客户经理';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.RSV_OBJ_ID IS '接收对象ID';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.TSK_BGN_DATE IS '任务开始时间';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.TSK_END_DATE IS '任务结束时间';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.INDX_UNIT IS '指标单位(万元/个数/百分比)';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.INDX_VAL IS '指标额';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.INDX_VAL_ADD IS '指标加码';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.ACUM_CMPLT_INDX IS '累计完成指标';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.DAY_CURNT_CMPLT_INDX IS '当天完成指标';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.BASE_VAL IS '基准值';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.CURNT_VAL IS '当前值';
COMMENT ON COLUMN ADS_MKT_TASK_INDX_SUB_CMPLT.PERSN_LEGAL_BK_CODE IS '法人行号';