/*
 * ADS_STAT_INDX_BASELINE_SUM
 * 中文名称: 指标基准-汇总表
 * 版本: v1.0
 * 创建时间: 2026-08-26
 * 来源: prc_ads_stat_indx_plan_002.sql 3.3节 + 3.3b节
 *       常规汇总: INDX_0050/0051/0055/0056/0057/0058/0059/0060/0062 (16列全量)
 *       补跑(仅存款): INDX_0050/0051 已开始活动补基准 (仅YR_DEPO/MTH_DEPO)
 */

CREATE TABLE IF NOT EXISTS ADS_STAT_INDX_BASELINE_SUM (
    STATIS_CALIB          VARCHAR(100),
    STATIS_DIM            VARCHAR(100),
    INDX_CODE             VARCHAR(100),
    DATA_BLNG             VARCHAR(100),
    PERSN_LEGAL_BK_CODE   VARCHAR(30),
    BASE_DATA_DATE        VARCHAR(10),
    BASE_RUN_DATE         VARCHAR(10),
    BASE_LOAN_BAL         NUMBER(20,2),
    BASE_YR_AVG_FIN       NUMBER(20,2),
    BASE_MTH_AVG_FIN      NUMBER(20,2),
    BASE_YR_AVG_AGEN_FIN  NUMBER(20,2),
    BASE_MTH_AVG_AGEN_FIN NUMBER(20,2),
    BASE_FIN_BAL          NUMBER(20,2),
    BASE_AGEN_FIN_BAL     NUMBER(20,2),
    BASE_YR_AVG_DEPO      NUMBER(20,2),
    BASE_MTH_AVG_DEPO     NUMBER(20,2)
);

COMMENT ON TABLE ADS_STAT_INDX_BASELINE_SUM IS '指标基准-汇总表';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.STATIS_CALIB IS '统计口径: 营销活动/目标任务';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.STATIS_DIM IS '统计维度: 活动ID或任务ID';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.INDX_CODE IS '指标编码';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.DATA_BLNG IS '数据归属: ORG_机构/MGR_客户经理';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.BASE_DATA_DATE IS '基准数据日期(YYYYMMDD)';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.BASE_RUN_DATE IS '基准跑批日期(YYYYMMDD)';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.BASE_LOAN_BAL IS '基准贷款余额(bal_type=1贷款类)';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.BASE_YR_AVG_FIN IS '基准年日均理财(bal_type=4年日均理财)';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.BASE_MTH_AVG_FIN IS '基准月日均理财(bal_type=2月日均理财)';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.BASE_YR_AVG_AGEN_FIN IS '基准年日均代发理财(bal_type=4未开放+已开放之和)';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.BASE_MTH_AVG_AGEN_FIN IS '基准月日均代发理财(bal_type=2未开放+已开放之和)';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.BASE_FIN_BAL IS '基准理财余额(bal_type=1时=理财余额)';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.BASE_AGEN_FIN_BAL IS '基准代发理财余额(bal_type=1时代发理财)';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.BASE_YR_AVG_DEPO IS '基准年日均存款(bal_type=4存款)';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.BASE_MTH_AVG_DEPO IS '基准月日均存款(bal_type=2存款)';
