/*
 * ADS_STAT_INDX_BASELINE_MEMBER
 * 中文名称: 指标基准-成员表
 * 版本: v1.0
 * 创建时间: 2026-08-26
 * 来源: prc_ads_stat_indx_plan_002.sql 3.1节 (活动开始前一日建立成员快照)
 */

CREATE TABLE IF NOT EXISTS ADS_STAT_INDX_BASELINE_MEMBER (
    STATIS_CALIB        VARCHAR(100),
    STATIS_DIM          VARCHAR(100),
    DATA_BLNG           VARCHAR(100),
    CUST_ID             VARCHAR(20),
    PERSN_LEGAL_BK_CODE VARCHAR(30),
    BASE_DATA_DATE      VARCHAR(10),
    BASE_RUN_DATE       VARCHAR(10)
);

COMMENT ON TABLE ADS_STAT_INDX_BASELINE_MEMBER IS '指标基准-成员表';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_MEMBER.STATIS_CALIB IS '统计口径: 营销活动/目标任务';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_MEMBER.STATIS_DIM IS '统计维度: 活动ID或任务ID';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_MEMBER.DATA_BLNG IS '数据归属: ORG_机构/MGR_客户经理';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_MEMBER.CUST_ID IS '客户号';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_MEMBER.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_MEMBER.BASE_DATA_DATE IS '基准数据日期(YYYYMMDD)';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_MEMBER.BASE_RUN_DATE IS '基准跑批日期(YYYYMMDD)';
