/*
 * ADS_CRM_R_SALRY_PAYROL_BASE
 * 中文名称: 代发工资客户基准表
 * 版本: v1.0
 * 创建时间: 2026-08-26
 * 来源: prc_ads_stat_indx_plan_006.sql 7.0节 (INDX_0064 代发工资户标志)
 */

CREATE TABLE IF NOT EXISTS ADS_CRM_R_SALRY_PAYROL_BASE (
    PATH_CODE           VARCHAR(2),
    STATIS_DIM          VARCHAR(100),
    PERSN_LEGAL_BK_CODE VARCHAR(30),
    CUST_ID             VARCHAR(20),
    FRST_MARK_DATE      VARCHAR(8)
);

COMMENT ON TABLE ADS_CRM_R_SALRY_PAYROL_BASE IS '代发工资客户基准表';
COMMENT ON COLUMN ADS_CRM_R_SALRY_PAYROL_BASE.PATH_CODE IS '统计路径: A=营销活动, B=目标任务';
COMMENT ON COLUMN ADS_CRM_R_SALRY_PAYROL_BASE.STATIS_DIM IS '统计维度: 活动ID或任务ID';
COMMENT ON COLUMN ADS_CRM_R_SALRY_PAYROL_BASE.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CRM_R_SALRY_PAYROL_BASE.CUST_ID IS '客户号';
COMMENT ON COLUMN ADS_CRM_R_SALRY_PAYROL_BASE.FRST_MARK_DATE IS '首次标记日期(YYYYMMDD); 新活动初始=19000101, 活动期内续=跑批日';
