/*
 * ADS_CUST_LOST_DTL
 * 中文名称: 客户流失清单
 * 版本: v1.0.0
 * 创建时间: 2026-07-29
 * 来源: Mapping Excel (ADS应用层数据模型)
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_LOST_DTL (
    PERSN_LEGAL_BK_CODE  VARCHAR2(4)  , -- 法人行号
    DATA_DATE            VARCHAR2(8)  , -- 数据日期
    CUST_ID              VARCHAR2(20) , -- 客户编号
    CUST_NAME            VARCHAR2(100), -- 客户名称
    CUST_LVL             VARCHAR2(2)  , -- 客户等级
    LVL_CHURN            VARCHAR2(2)  , -- 流失等级
    DEPO_CURNT_DEPO_BAL  NUMBER(20,2) , -- 活期余额
    FIXD_DEPO_BAL        NUMBER(20,2) , -- 定期余额
    FIN_AMT              NUMBER(20,2) , -- 理财余额
    CNTCT_STATE          VARCHAR2(1)  , -- 接触状态
    RESCUE_STATE         VARCHAR2(1)  , -- 挽回状态
    POST_ID              VARCHAR2(20) , -- 管户经理
    ORG_ID               VARCHAR2(7)  , -- 归属机构
    STATIS_CYCLE         VARCHAR2(2)    -- 统计周期(月/季/年)
);

COMMENT ON TABLE ADS_CUST_LOST_DTL IS '客户流失清单';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.CUST_ID IS '客户编号';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.CUST_NAME IS '客户名称';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.CUST_LVL IS '客户等级';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.LVL_CHURN IS '流失等级';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.DEPO_CURNT_DEPO_BAL IS '活期余额';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.FIXD_DEPO_BAL IS '定期余额';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.FIN_AMT IS '理财余额';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.CNTCT_STATE IS '接触状态';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.RESCUE_STATE IS '挽回状态';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.POST_ID IS '管户经理';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.ORG_ID IS '归属机构';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.STATIS_CYCLE IS '统计周期(月/季/年)';
