/*
 * ADS_CUST_POTN_UPGRADE_STATIS
 * 中文名称: 潜力提升统计表
 * 版本: v2.2.0
 * 创建时间: 2026-07-20
 * 变更记录:
 *   v2.2.0 2026-07-28 修复NUMBER格式断裂、补行内注释、年码值N→Y
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_POTN_UPGRADE_STATIS (
    PERSN_LEGAL_BK_CODE  VARCHAR(4),     -- 法人行号
    DATA_DATE            VARCHAR(8),     -- 数据日期
    STATIS_OBJ           VARCHAR(20),    -- 统计对象
    STATIS_CYCLE         VARCHAR(2),     -- 统计周期：M-月,Q-季,Y-年
    LVL_CRIT             VARCHAR(2),     -- 临界等级
    TTL_CUST_CNT         NUMBER(8),      -- 总客户数
    MTH_AVG_QUAL_CNT     NUMBER(8),      -- 月均达标客户数
    MTH_AVG_QUAL_RATE    NUMBER(20,2),   -- 月均达标率
    PNT_QUAL_CNT         NUMBER(8),      -- 时点达标客户数
    PNT_QUAL_RATE        NUMBER(20,2),   -- 时点达标率
    CNTCT_CUST_CNT       NUMBER(8),      -- 已接触客户数
    CNTCT_RATE           NUMBER(20,2)    -- 接触率
);

COMMENT ON TABLE ADS_CUST_POTN_UPGRADE_STATIS IS '潜力提升统计表';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.STATIS_OBJ IS '统计对象';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.STATIS_CYCLE IS '统计周期：M-月,Q-季,Y-年';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.LVL_CRIT IS '临界等级';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.TTL_CUST_CNT IS '总客户数';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.MTH_AVG_QUAL_CNT IS '月均达标客户数';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.MTH_AVG_QUAL_RATE IS '月均达标率';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.PNT_QUAL_CNT IS '时点达标客户数';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.PNT_QUAL_RATE IS '时点达标率';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.CNTCT_CUST_CNT IS '已接触客户数';
COMMENT ON COLUMN ADS_CUST_POTN_UPGRADE_STATIS.CNTCT_RATE IS '接触率';
