/*
 * ADS_STAT_INDX_DATA
 * 中文名称: 指标数据统计
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_STAT_INDX_DATA (
    INDX_CODE VARCHAR(100),
    DATA_BLNG VARCHAR(100),
    STATIS_DIM VARCHAR(100),
    STATIS_CALIB VARCHAR(100),
    CURNT_VAL NUMBER(20,2),
    TERM_LAST_VAL NUMBER(20,2),
    MTH_END_VAL NUMBER(20,2),
    YR_BGN_VAL NUMBER(20,2),
    MTH_LAST_END_AVG_DAY_VAL NUMBER(20,2),
    YR_LAST_END_AVG_DAY_VAL NUMBER(20,2),
    DATA_DATE VARCHAR(10),
    PERSN_LEGAL_BK_CODE VARCHAR(30),
    ID VARCHAR(10)
);

COMMENT ON TABLE ADS_STAT_INDX_DATA IS '指标数据统计';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.INDX_CODE IS '指标编码';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.DATA_BLNG IS '数据归属';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.STATIS_DIM IS '统计维度';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.STATIS_CALIB IS '统计口径';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.CURNT_VAL IS '本期值';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.TERM_LAST_VAL IS '上期值';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.MTH_END_VAL IS '月末值';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.YR_BGN_VAL IS '年初值';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.MTH_LAST_END_AVG_DAY_VAL IS '上月末日均值';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.YR_LAST_END_AVG_DAY_VAL IS '上年末日均值';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.ID IS '[NULL]';