/*
 * ADS_STAT_INDX_BASELINE_SUM
 * 中文名称: 指标活动任务金额基准汇总
 * 用途: 保存金额类指标按最终统计粒度汇总的上期基准值。
 */

CREATE TABLE IF NOT EXISTS ADS_STAT_INDX_BASELINE_SUM (
    STATIS_CALIB VARCHAR(100) NOT NULL, -- 统计口径
    STATIS_DIM VARCHAR(100) NOT NULL, -- 活动编号/任务编号
    INDX_CODE VARCHAR(100) NOT NULL, -- 指标编码
    DATA_BLNG VARCHAR(100) NOT NULL, -- 数据归属
    PERSN_LEGAL_BK_CODE VARCHAR(30) NOT NULL, -- 法人行号
    BASE_DATA_DATE VARCHAR(8) NOT NULL, -- 基准业务日期
    BASE_RUN_DATE VARCHAR(8) NOT NULL, -- 基准值跑批日期
    BASE_LOAN_BAL NUMBER(20,2) NULL, -- 贷款余额基准总额
    BASE_YR_AVG_FIN NUMBER(20,2) NULL, -- 年日均理财基准总额
    BASE_MTH_AVG_FIN NUMBER(20,2) NULL, -- 月日均理财基准总额
    BASE_YR_AVG_AGEN_FIN NUMBER(20,2) NULL, -- 年日均代销理财基准总额
    BASE_MTH_AVG_AGEN_FIN NUMBER(20,2) NULL, -- 月日均代销理财基准总额
    BASE_FIN_BAL NUMBER(20,2) NULL, -- 理财余额基准总额（0057）
    BASE_AGEN_FIN_BAL NUMBER(20,2) NULL, -- 代销理财余额基准总额（0060）
    BASE_YR_AVG_DEPO NUMBER(20,2) NULL, -- 年日均储蓄存款基准总额（0050）
    BASE_MTH_AVG_DEPO NUMBER(20,2) NULL, -- 月日均储蓄存款基准总额（0051）
    PRIMARY KEY (STATIS_CALIB, STATIS_DIM, INDX_CODE, DATA_BLNG, PERSN_LEGAL_BK_CODE)
);

COMMENT ON TABLE ADS_STAT_INDX_BASELINE_SUM IS '指标活动任务金额基准汇总';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.STATIS_CALIB IS '统计口径';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.STATIS_DIM IS '活动编号/任务编号';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.INDX_CODE IS '指标编码';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.DATA_BLNG IS '数据归属';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.BASE_DATA_DATE IS '基准业务日期';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.BASE_RUN_DATE IS '基准值跑批日期';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.BASE_YR_AVG_DEPO IS '年日均储蓄存款基准总额（0050）';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_SUM.BASE_MTH_AVG_DEPO IS '月日均储蓄存款基准总额（0051）';
