/*
 * ADS_CUST_NEW_CUST_DTL
 * 中文名称: 新客经营明细
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_NEW_CUST_DTL (
    PERSN_LEGAL_BK_CODE VARCHAR(4),
    DATA_DATE VARCHAR(8),
    CUST_ID VARCHAR(20),
    CUST_NAME VARCHAR(100),
    CUST_LVL VARCHAR(2),
    NEW_CUST_CYCLE VARCHAR(1),
    DEPO_CURNT_DEPO_BAL NUMBER(20,
    2),
    FIXD_DEPO_BAL NUMBER(20,
    2),
    FIN_AMT NUMBER(20,
    2),
    CNTCT_STATE VARCHAR(1),
    KYC_STATE VARCHAR(1),
    POST_ID VARCHAR(20),
    ORG_ID VARCHAR(7),
    STATIS_CYCLE VARCHAR(2)
);

COMMENT ON TABLE ADS_CUST_NEW_CUST_DTL IS '新客经营明细';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_DTL.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_DTL.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_DTL.CUST_ID IS '客户编号';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_DTL.CUST_NAME IS '客户名称';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_DTL.CUST_LVL IS '客户等级';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_DTL.NEW_CUST_CYCLE IS '新客周期';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_DTL.DEPO_CURNT_DEPO_BAL IS '活期余额';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_DTL.FIXD_DEPO_BAL IS '定期余额';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_DTL.FIN_AMT IS '理财余额';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_DTL.CNTCT_STATE IS '接触状态';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_DTL.KYC_STATE IS 'KYC状态';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_DTL.POST_ID IS '管户经理';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_DTL.ORG_ID IS '归属机构';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_DTL.STATIS_CYCLE IS '统计周期(月/季/年)';