/*
 * ADS_CUST_INDV_POTEN
 * 中文名称: 零售潜在客户信息
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_INDV_POTEN (
    POTEN_CUST_ID VARCHAR(40),
    POTEN_CUST_NAME VARCHAR(100),
    POTEN_TYP VARCHAR(6),
    POTEN_CUST_TYP VARCHAR(6),
    GENDER VARCHAR(6),
    CERT_TYP VARCHAR(6),
    CERT_ID VARCHAR(32),
    TEL_NO VARCHAR(32),
    INTENT_DSC VARCHAR(400),
    DTL_ADDRS VARCHAR(400),
    CREATR VARCHAR(20),
    CREAT_TIME VARCHAR(20),
    POTEN_CUST_STATE VARCHAR(6),
    LPR_ID VARCHAR(4),
    SRC_TYP VARCHAR(6),
    MKT_PERSN VARCHAR(20),
    ALLO_DATE VARCHAR(8),
    MKT_ORG VARCHAR(7),
    SERV_ENTER VARCHAR(200),
    POST VARCHAR(6),
    MTH_INCOM NUMBER(20,
    2),
    YR_INCOM NUMBER(20,
    2),
    RMARK VARCHAR(400),
    INF_KLKT_DATE VARCHAR(10),
    UNIT_ADDRS VARCHAR(200),
    INTN_PRDKT VARCHAR(60),
    NO_BAT VARCHAR(40),
    CUST_ID VARCHAR(21),
    POT_CNVRT_PRDKT VARCHAR(60),
    POT_CNVRT_ORG VARCHAR(6)
);

COMMENT ON TABLE ADS_CUST_INDV_POTEN IS '零售潜在客户信息';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.POTEN_CUST_ID IS '潜在客户号(自增键)';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.POTEN_CUST_NAME IS '潜在客户名称';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.POTEN_TYP IS '潜客类型';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.POTEN_CUST_TYP IS '潜在客户类型';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.GENDER IS '性别';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.CERT_TYP IS '证件类型';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.CERT_ID IS '证件号码';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.TEL_NO IS '联系电话';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.INTENT_DSC IS '备注说明';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.DTL_ADDRS IS '居住地址';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.CREATR IS '创建人';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.CREAT_TIME IS '创建时间';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.POTEN_CUST_STATE IS '潜在客户状态';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.LPR_ID IS '法人行号';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.SRC_TYP IS '来源类型';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.MKT_PERSN IS '客户经理';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.ALLO_DATE IS '分配日期(创建时和创建日期一致)';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.MKT_ORG IS '归属机构';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.SERV_ENTER IS '工作单位';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.POST IS '职位';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.MTH_INCOM IS '月收入';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.YR_INCOM IS '年收入';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.RMARK IS '备注';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.INF_KLKT_DATE IS '潜客转化日期';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.UNIT_ADDRS IS '工作单位地址';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.INTN_PRDKT IS '意向产品';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.NO_BAT IS '批次号';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.CUST_ID IS '转化后核心客户号';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.POT_CNVRT_PRDKT IS '潜客转化产品';
COMMENT ON COLUMN ADS_CUST_INDV_POTEN.POT_CNVRT_ORG IS '潜客转化机构';