/*
 * ADS_CUST_DEADLINE_RMND_STATIS
 * 中文名称: 到期承接统计表
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_DEADLINE_RMND_STATIS (
    PERSN_LEGAL_BK_CODE VARCHAR(4),
    DATA_DATE VARCHAR(8),
    STATIS_OBJ VARCHAR(20),
    STATIS_CYCLE VARCHAR(2),
    STATIS_TYP VARCHAR(2),
    EXPR_CUST_CNT NUMBER(8),
    TTL_EXPR_CUST_CNT NUMBER(8),
    EXPR_AMT NUMBER(20,
    2),
    TTL_EXPR_AMT NUMBER(20,
    2),
    CUST_UNDTAKE_RATE NUMBER(20,
    2),
    ASSET_KEEP_RATE NUMBER(20,
    2),
    ASSET_UNDTAKE_RATE NUMBER(20,
    2),
    DEPO_TO_FIN_CONVRS_RATE NUMBER(20,
    2),
    INSUR_CONVRS_RATE NUMBER(20,
    2),
    FIN_TO_DEPO_CONVRS_RATE NUMBER(20,
    2)
);

COMMENT ON TABLE ADS_CUST_DEADLINE_RMND_STATIS IS '到期承接统计表';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.STATIS_OBJ IS '统计对象';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.STATIS_CYCLE IS '统计周期';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.STATIS_TYP IS '承接类型0-全部1-存款2-理财';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.EXPR_CUST_CNT IS '已到期客户数';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.TTL_EXPR_CUST_CNT IS '总到期客户数';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.EXPR_AMT IS '已到期金额';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.TTL_EXPR_AMT IS '总到期金额';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.CUST_UNDTAKE_RATE IS '客户承接率';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.ASSET_KEEP_RATE IS '资产留存率';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.ASSET_UNDTAKE_RATE IS '资产承接率';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.DEPO_TO_FIN_CONVRS_RATE IS '存款转理财转化率';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.INSUR_CONVRS_RATE IS '保险转化率';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.FIN_TO_DEPO_CONVRS_RATE IS '理财转存款转化率';