/*
 * ADS_CRM_R_SALRY_PAYROL_BASE
 * 中文名称: 代发薪客户基数表（指标0064）
 * 版本: v1.0.0
 * 创建时间: 2026-08-24
 * 需求: 指标数据统计 v1.9（INDX_0064 代发薪客户净增）
 * 说明: 每日跑批由 PRC_ADS_STAT_INDX_PLAN_006 刷新；
 *       范围内客户标签 ADS_CRM_R_CUST_LABLE.IS_NOT_SALRY_PAYROL_BK='1' 入基数，
 *       新活动/任务首次出现记 '19000101'（活动前基数），活动期间新增标记记跑批日。
 */

CREATE TABLE IF NOT EXISTS ADS_CRM_R_SALRY_PAYROL_BASE (
    PATH_CODE           VARCHAR(1)   NOT NULL,
    STATIS_DIM          VARCHAR(100) NOT NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(30)  NOT NULL,
    CUST_ID             VARCHAR(20)  NOT NULL,
    FRST_MARK_DATE      VARCHAR(8)   NOT NULL,
    PRIMARY KEY (PATH_CODE, STATIS_DIM, CUST_ID, PERSN_LEGAL_BK_CODE)
);

COMMENT ON TABLE ADS_CRM_R_SALRY_PAYROL_BASE IS '代发薪客户基数表(指标0064)';
COMMENT ON COLUMN ADS_CRM_R_SALRY_PAYROL_BASE.PATH_CODE IS '统计路径: A营销活动/B目标任务';
COMMENT ON COLUMN ADS_CRM_R_SALRY_PAYROL_BASE.STATIS_DIM IS '营销活动编号或目标任务编号';
COMMENT ON COLUMN ADS_CRM_R_SALRY_PAYROL_BASE.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CRM_R_SALRY_PAYROL_BASE.CUST_ID IS '客户号';
COMMENT ON COLUMN ADS_CRM_R_SALRY_PAYROL_BASE.FRST_MARK_DATE IS '首次标记为代发薪客户日期(基数19000101/新增=跑批日)';
