/*
 * ADS_MKT_ACT_TSK_MON
 * 中文名称: 营销活动任务监控
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS ADS_MKT_ACT_TSK_MON (
    DATA_DATE VARCHAR(8) NOT NULL COMMENT '数据日期',
    STAT_OBJ VARCHAR(2) NULL COMMENT '统计对象',
    MKT_ACT_ID VARCHAR(40) NULL COMMENT '营销活动编号',
    CUST_CNT NUMBER(8) NULL COMMENT '客户数',
    CTKT_COVER_RATE NUMBER(10,2) NULL COMMENT '接触覆盖率',
    PLAN_SUPPORT_CUST_CNT NUMBER(8) NULL COMMENT '拟支持客户数',
    FURTHER_MKT_CUST_CNT NUMBER(8) NULL COMMENT '进一步营销客户数',
    NOT_SUPPORT_CUST_CNT NUMBER(8) NULL COMMENT '不予支持客户数',
    MKT_SUCCESS_RATE NUMBER(10,2) NULL COMMENT '营销成功率'
);

COMMENT ON TABLE ADS_MKT_ACT_TSK_MON IS '营销活动任务监控';
