/*
 * ADS_REPORT_0001
 * 中文名称: 机构客户层级资产月报表
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_REPORT_0001 (
    DATA_DATE VARCHAR(8),
    BLNG_BRCH VARCHAR(7),
    BLNG_BRCH_SUB VARCHAR(7),
    BLNG_BRCH_NET VARCHAR(7),
    ORG_PATH VARCHAR(20),
    CUST_LVL VARCHAR(2),
    CUST_CNT NUMBER(8),
    AUM_BAL NUMBER(20,
    2),
    AUM_MTH_AVG NUMBER(20,
    2),
    COMN_FIXD_BAL NUMBER(20,
    2),
    LEHUI_BAL NUMBER(20,
    2),
    LARGEDP_BAL NUMBER(20,
    2),
    FIXD_SUM NUMBER(20,
    2),
    DEPO_CURNT_DEPO_BAL NUMBER(20,
    2),
    DEPO_SUM NUMBER(20,
    2),
    BIZ_SELF_FIN_BAL NUMBER(20,
    2),
    PROXY_SELL_FIN_BAL NUMBER(20,
    2),
    FIN_BAL_SUM NUMBER(20,
    2),
    INSUR_BAL NUMBER(20,
    2),
    LOAN_BAL NUMBER(20,
    2)
);

COMMENT ON TABLE ADS_REPORT_0001 IS '机构客户层级资产月报表';
COMMENT ON COLUMN ADS_REPORT_0001.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_REPORT_0001.BLNG_BRCH IS '所属分行';
COMMENT ON COLUMN ADS_REPORT_0001.BLNG_BRCH_SUB IS '所属支行';
COMMENT ON COLUMN ADS_REPORT_0001.BLNG_BRCH_NET IS '所属网点';
COMMENT ON COLUMN ADS_REPORT_0001.ORG_PATH IS '机构路径';
COMMENT ON COLUMN ADS_REPORT_0001.CUST_LVL IS '客户等级';
COMMENT ON COLUMN ADS_REPORT_0001.CUST_CNT IS '客户数';
COMMENT ON COLUMN ADS_REPORT_0001.AUM_BAL IS 'AUM余额';
COMMENT ON COLUMN ADS_REPORT_0001.AUM_MTH_AVG IS 'AUM月日均';
COMMENT ON COLUMN ADS_REPORT_0001.COMN_FIXD_BAL IS '普通定期余额';
COMMENT ON COLUMN ADS_REPORT_0001.LEHUI_BAL IS '乐惠存余额';
COMMENT ON COLUMN ADS_REPORT_0001.LARGEDP_BAL IS '大额存单余额';
COMMENT ON COLUMN ADS_REPORT_0001.FIXD_SUM IS '定期合计';
COMMENT ON COLUMN ADS_REPORT_0001.DEPO_CURNT_DEPO_BAL IS '活期余额';
COMMENT ON COLUMN ADS_REPORT_0001.DEPO_SUM IS '存款合计';
COMMENT ON COLUMN ADS_REPORT_0001.BIZ_SELF_FIN_BAL IS '自营理财余额';
COMMENT ON COLUMN ADS_REPORT_0001.PROXY_SELL_FIN_BAL IS '代销理财余额';
COMMENT ON COLUMN ADS_REPORT_0001.FIN_BAL_SUM IS '理财余额合计';
COMMENT ON COLUMN ADS_REPORT_0001.INSUR_BAL IS '保险余额';
COMMENT ON COLUMN ADS_REPORT_0001.LOAN_BAL IS '贷款余额';