/*
 * ADS_NEW_CUST_KYC
 * 中文名称: 客户级KYC完整度
 * 版本: v1.0
 * 创建时间: 2026-08-25
 */

CREATE TABLE IF NOT EXISTS ADS_NEW_CUST_KYC (
    PERSN_LEGAL_BK_CODE VARCHAR(4),
    CUST_ID VARCHAR(20),
    KYC_STATE VARCHAR(1),
    KYC_COMPL_RATE NUMBER(3)
);

COMMENT ON TABLE ADS_NEW_CUST_KYC IS '客户级KYC完整度';
COMMENT ON COLUMN ADS_NEW_CUST_KYC.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_NEW_CUST_KYC.CUST_ID IS '客户编号';
COMMENT ON COLUMN ADS_NEW_CUST_KYC.KYC_STATE IS 'KYC完整状态(1=≥23/28项非空,0=不完整)';
COMMENT ON COLUMN ADS_NEW_CUST_KYC.KYC_COMPL_RATE IS 'KYC完整度率值(非空字段数/28*100,ROUND取整整数百分比,如85)';