/*
 * ADS_CUST_DEADLINE_RMND_DTL
 * 中文名称: 到期承接明细表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_DEADLINE_RMND_DTL (
    DATA_DATE 8 NOT NULL COMMENT '数据日期',
    CUST_ID 20 NULL COMMENT '客户编号',
    CUST_NAME 100 NULL COMMENT '客户名称',
    CUST_LVL 2 NULL COMMENT '客户等级',
    DEPO_CURNT_DEPO_BAL 20 NULL COMMENT '活期余额',
    FIXD_DEPO_BAL 20 NULL COMMENT '定期余额',
    FIN_AMT 20 NULL COMMENT '理财余额',
    STAT_PERD 2 NULL COMMENT '统计周期',
    STATIS_TYP 2 NULL COMMENT '承接类型1-存款2-理财',
    EXPR_AMT 20 NULL COMMENT '到期金额',
    MATURE_TTL_AMT 20 NULL COMMENT '到期总金额',
    TAKE_RATE 10 NULL COMMENT '承接率',
    FIX_DEPO_MATURE_AMT 20 NULL COMMENT '定期存款到期金额',
    FIX_DEPO_MATURE_TTL_AMT 20 NULL COMMENT '定期存款到期总金额',
    FIX_DEPO_TAKE_RATE 10 NULL COMMENT '定期存款承接率',
    CNTCT_STATE 1 NULL COMMENT '接触状态',
    UNDTAKE_STATE 1 NULL COMMENT '承接状态',
    FIXED_FIN_MATURE_TRAN_INSUR_AMT 20 NULL COMMENT '定期理财到期转保险金额',
    FIN_MATURE_TRAN_FIXED_AMT 20 NULL COMMENT '理财到期转定期金额',
    FIXED_MATURE_TRAN_FIN_AMT 20 NULL COMMENT '定期到期转理财金额',
    FRST_MATURE_PK_BF_DAY_AUM_BAL 20 NULL COMMENT '本期第一笔到期产品前一日AUM余额',
    LAST_END_DATE 8 NULL COMMENT '本期最后一笔到期产品日期',
    POST_ID 20 NULL COMMENT '管户经理',
    ORG_ID 6 NULL COMMENT '归属机构'
);

COMMENT ON TABLE ADS_CUST_DEADLINE_RMND_DTL IS '到期承接明细表';
