/*
 * ADS_REPORT_0001
 * 中文名称: 机构客户层级资产月报表
 * 版本: v1.0.0
 * 创建时间: 2026-07-29
 * 来源: Mapping Excel (ADS应用层数据模型)
 */

CREATE TABLE IF NOT EXISTS ADS_REPORT_0001 (
    DATA_DATE            VARCHAR2(8) , -- 数据日期
    BLNG_BRCH            VARCHAR2(7) , -- 所属分行
    BLNG_BRCH_SUB        VARCHAR2(7) , -- 所属支行
    BLNG_BRCH_NET        VARCHAR2(7) , -- 所属网点
    ORG_PATH             VARCHAR2(20), -- 机构路径
    CUST_LVL             VARCHAR2(2) , -- 客户等级
    CUST_CNT             NUMBER(8)   , -- 客户数
    AUM_BAL              NUMBER(20,2), -- AUM余额
    AUM_MTH_AVG          NUMBER(20,2), -- AUM月日均
    COMN_FIXD_BAL        NUMBER(20,2), -- 普通定期余额
    LEHUI_BAL            NUMBER(20,2), -- 乐惠存余额
    LARGEDP_BAL          NUMBER(20,2), -- 大额存单余额
    FIXD_SUM             NUMBER(20,2), -- 定期合计
    DEPO_CURNT_DEPO_BAL  NUMBER(20,2), -- 活期余额
    DEPO_SUM             NUMBER(20,2), -- 存款合计
    BIZ_SELF_FIN_BAL     NUMBER(20,2), -- 自营理财余额
    PROXY_SELL_FIN_BAL   NUMBER(20,2), -- 代销理财余额
    FIN_BAL_SUM          NUMBER(20,2), -- 理财余额合计
    INSUR_BAL            NUMBER(20,2), -- 保险余额
    LOAN_BAL             NUMBER(20,2)  -- 贷款余额
);

COMMENT ON TABLE ADS_REPORT_0001 IS '机构客户层级资产月报表';
COMMENT ON COLUMN ADS_REPORT_0001.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_REPORT_0001.BLNG_BRCH IS '所属分行';
COMMENT ON COLUMN ADS_REPORT_0001.BLNG_BRCH_SUB IS '所属支行';
COMMENT ON COLUMN ADS_REPORT_0001.BLNG_BRCH_NET IS '所属网点';
COMMENT ON COLUMN ADS_REPORT_0001.ORG_PATH IS '机构路径';
COMMENT ON COLUMN ADS_REPORT_0001.CUST_LVL IS '客户等级';
COMMENT ON COLUMN ADS_REPORT_0001.CUST_CNT IS '客户数';
COMMENT ON COLUMN ADS_REPORT_0001.AUM_BAL IS 'AUM余额';
COMMENT ON COLUMN ADS_REPORT_0001.AUM_MTH_AVG IS 'AUM月日均';
COMMENT ON COLUMN ADS_REPORT_0001.COMN_FIXD_BAL IS '普通定期余额';
COMMENT ON COLUMN ADS_REPORT_0001.LEHUI_BAL IS '乐惠存余额';
COMMENT ON COLUMN ADS_REPORT_0001.LARGEDP_BAL IS '大额存单余额';
COMMENT ON COLUMN ADS_REPORT_0001.FIXD_SUM IS '定期合计';
COMMENT ON COLUMN ADS_REPORT_0001.DEPO_CURNT_DEPO_BAL IS '活期余额';
COMMENT ON COLUMN ADS_REPORT_0001.DEPO_SUM IS '存款合计';
COMMENT ON COLUMN ADS_REPORT_0001.BIZ_SELF_FIN_BAL IS '自营理财余额';
COMMENT ON COLUMN ADS_REPORT_0001.PROXY_SELL_FIN_BAL IS '代销理财余额';
COMMENT ON COLUMN ADS_REPORT_0001.FIN_BAL_SUM IS '理财余额合计';
COMMENT ON COLUMN ADS_REPORT_0001.INSUR_BAL IS '保险余额';
COMMENT ON COLUMN ADS_REPORT_0001.LOAN_BAL IS '贷款余额';
