/*
 * ADS_CUST_OTHERS_RMND
 * 中文名称: 其他事件提醒
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_OTHERS_RMND (
    RMND_ID VARCHAR(40),
    RMND_CATE_BIG VARCHAR(20),
    RMND_CATE_SML VARCHAR(100),
    MNGR_POST_ID VARCHAR(30),
    MNGR_NAME VARCHAR(120),
    ORG_ID VARCHAR(7),
    CUST_TYP VARCHAR(4),
    CUST_ID VARCHAR(20),
    CUST_NAME VARCHAR(200),
    PHONE_NO VARCHAR(32),
    RMND_INF VARCHAR(600),
    HDLE_STATE VARCHAR(2),
    RMND_DATE VARCHAR(20),
    PERSN_LEGAL_BK_CODE VARCHAR(30),
    HDLE_TIME VARCHAR(20),
    DEL_FLG VARCHAR(2),
    HDLE_DSC VARCHAR(400)
);

COMMENT ON TABLE ADS_CUST_OTHERS_RMND IS '其他事件提醒';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.RMND_ID IS '提醒ID';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.RMND_CATE_BIG IS '提醒类型(1-贷款逾期提醒,2-贷款欠息提醒,3-贷款还款余额不足提醒,4-收单商户长期无交易提醒,5-销户提醒,6-客户分配,7-客户回收,8-客户移交,9-客户调配)';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.RMND_CATE_SML IS '提醒名称';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.MNGR_POST_ID IS '客户经理编号';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.MNGR_NAME IS '客户经理名称';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.ORG_ID IS '机构编号';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.CUST_TYP IS '客户类型';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.CUST_ID IS '客户ID';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.CUST_NAME IS '客户名称';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.PHONE_NO IS '手机号';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.RMND_INF IS '提醒内容';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.HDLE_STATE IS '处理状态(0未读 1已读)';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.RMND_DATE IS '提醒日期';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.HDLE_TIME IS '处理时间';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.DEL_FLG IS '删除标志';
COMMENT ON COLUMN ADS_CUST_OTHERS_RMND.HDLE_DSC IS '处理说明';