/*
 * ADS_CUST_LOST_DTL
 * 中文名称: 客户流失清单
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_LOST_DTL (
    PERSN_LEGAL_BK_CODE VARCHAR(4),
    DATA_DATE VARCHAR(8),
    CUST_ID VARCHAR(20),
    CUST_NAME VARCHAR(100),
    CUST_LVL VARCHAR(2),
    LVL_CHURN VARCHAR(2),
    DEPO_CURNT_DEPO_BAL NUMBER(20,
    2),
    FIXD_DEPO_BAL NUMBER(20,
    2),
    FIN_AMT NUMBER(20,
    2),
    CNTCT_STATE VARCHAR(1),
    RESCUE_STATE VARCHAR(1),
    POST_ID VARCHAR(20),
    ORG_ID VARCHAR(7),
    STATIS_CYCLE VARCHAR(2)
);

COMMENT ON TABLE ADS_CUST_LOST_DTL IS '客户流失清单';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.CUST_ID IS '客户编号';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.CUST_NAME IS '客户名称';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.CUST_LVL IS '客户等级';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.LVL_CHURN IS '流失等级';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.DEPO_CURNT_DEPO_BAL IS '活期余额';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.FIXD_DEPO_BAL IS '定期余额';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.FIN_AMT IS '理财余额';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.CNTCT_STATE IS '接触状态';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.RESCUE_STATE IS '挽回状态';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.POST_ID IS '管户经理';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.ORG_ID IS '归属机构';
COMMENT ON COLUMN ADS_CUST_LOST_DTL.STATIS_CYCLE IS '统计周期(月/季/年)';