/*
 * ADS_STAT_INDX_BASELINE_MEMBER
 * 中文名称: 指标活动任务冻结客户成员
 * 用途: 增量指标按活动/任务和归属冻结考核客户范围；不按指标重复存储。
 */
CREATE TABLE IF NOT EXISTS ADS_STAT_INDX_BASELINE_MEMBER (
    STATIS_CALIB VARCHAR(100) NOT NULL,
    STATIS_DIM VARCHAR(100) NOT NULL,
    DATA_BLNG VARCHAR(100) NOT NULL,
    CUST_ID VARCHAR(20) NOT NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(30) NOT NULL,
    BASE_DATA_DATE VARCHAR(8) NOT NULL,
    BASE_RUN_DATE VARCHAR(8) NOT NULL,
    PRIMARY KEY (STATIS_CALIB, STATIS_DIM, DATA_BLNG, CUST_ID, PERSN_LEGAL_BK_CODE)
);

COMMENT ON TABLE ADS_STAT_INDX_BASELINE_MEMBER IS '指标活动任务冻结客户成员';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_MEMBER.STATIS_CALIB IS '统计口径';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_MEMBER.STATIS_DIM IS '活动编号/任务编号';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_MEMBER.DATA_BLNG IS '数据归属';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_MEMBER.CUST_ID IS '客户编号';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_MEMBER.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_MEMBER.BASE_DATA_DATE IS '基准业务日期';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_MEMBER.BASE_RUN_DATE IS '基准值跑批日期';
