/*
 * ads_cust_prdkt_rcmd
 * 中文名称: 客户产品推荐表
 * 版本: v1.0
 * 创建时间: 2026-07-19
 */

CREATE TABLE IF NOT EXISTS ads_cust_prdkt_rcmd (
    DATA_DATE VARCHAR(8) NOT NULL COMMENT '数据日期',
    CUST_ID VARCHAR(20) NOT NULL COMMENT '客户编号',
    PRDKT_ID VARCHAR(40) NOT NULL COMMENT '产品编号',
    PRDKT_NAME VARCHAR(100) NULL COMMENT '产品名称',
    RCMD_RANK VARCHAR(1) NULL COMMENT '推荐排序(1/2/3)',
    TOTAL_SCORE NUMBER(5,2) NULL COMMENT '总分(100分制)',
    RETURN_SCORE NUMBER(5,2) NULL COMMENT '收益吸引力得分(0-35)',
    DURATION_SCORE NUMBER(5,2) NULL COMMENT '期限匹配度得分(0-30)',
    RISK_COMFORT_SCORE NUMBER(5,2) NULL COMMENT '风险舒适度得分(0-20)',
    HIST_PREF_SCORE NUMBER(5,2) NULL COMMENT '历史偏好得分(0-15)',
    RCMD_REASON VARCHAR(500) NULL COMMENT '推荐理由',
    CUST_RISK_LVL VARCHAR(2) NULL COMMENT '客户风险承受等级(C1-C5)',
    PRDKT_RISK_LVL VARCHAR(2) NULL COMMENT '产品风险等级(R1-R5)',
    PRDKT_RATE NUMBER(18,4) NULL COMMENT '产品预期收益率',
    PRDKT_DURATION NUMBER(10) NULL COMMENT '产品期限(天)',
    PRDKT_STATE VARCHAR(10) NULL COMMENT '产品状态',
    PRDKT_CATE_BIG VARCHAR(10) NULL COMMENT '产品大类',
    ISSU_ORG VARCHAR(6) NULL COMMENT '发行机构',
    BGN_DATE VARCHAR(10) NULL COMMENT '产品开始日期',
    END_DATE VARCHAR(10) NULL COMMENT '产品结束日期',
    CUST_NAME VARCHAR(100) NULL COMMENT '客户名称',
    POST_ID VARCHAR(20) NULL COMMENT '管户经理',
    ORG_ID VARCHAR(6) NULL COMMENT '归属机构'
);

COMMENT ON TABLE ads_cust_prdkt_rcmd IS '客户产品推荐表';