/*
 * ADS_STAT_INDX_BASELINE_DTL
 * 中文名称: 指标活动任务客户基准明细
 * 用途: 冻结活动/任务开始日前的客户状态基准。
 *       仅用于0052~0054、0063；金额指标客户范围由ADS_STAT_INDX_BASELINE_MEMBER冻结，
 *       金额期初汇总另存ADS_STAT_INDX_BASELINE_SUM。
 */

CREATE TABLE IF NOT EXISTS ADS_STAT_INDX_BASELINE_DTL (
    STATIS_CALIB VARCHAR(100) NOT NULL, -- 统计口径
    STATIS_DIM VARCHAR(100) NOT NULL, -- 活动编号/任务编号
    INDX_CODE VARCHAR(100) NOT NULL, -- 指标编码
    DATA_BLNG VARCHAR(100) NOT NULL, -- 数据归属
    CUST_ID VARCHAR(20) NOT NULL, -- 客户编号
    PERSN_LEGAL_BK_CODE VARCHAR(30) NOT NULL, -- 法人行号
    BASE_DATA_DATE VARCHAR(8) NOT NULL, -- 基准业务日期
    BASE_RUN_DATE VARCHAR(8) NOT NULL, -- 基准值跑批日期
    BASE_CUST_LVL VARCHAR(2) NULL, -- 客户等级基准值
    BASE_MTH_AVG_AUM NUMBER(20,2) NULL, -- 月日均AUM基准值
    PRIMARY KEY (STATIS_CALIB, STATIS_DIM, INDX_CODE, DATA_BLNG, CUST_ID, PERSN_LEGAL_BK_CODE)
);

COMMENT ON TABLE ADS_STAT_INDX_BASELINE_DTL IS '指标活动任务客户基准明细';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.STATIS_CALIB IS '统计口径';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.STATIS_DIM IS '活动编号/任务编号';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.INDX_CODE IS '指标编码';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.DATA_BLNG IS '数据归属';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.CUST_ID IS '客户编号';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.BASE_DATA_DATE IS '基准业务日期';
COMMENT ON COLUMN ADS_STAT_INDX_BASELINE_DTL.BASE_RUN_DATE IS '基准值跑批日期';
