/*
 * ADS_STAT_INDX_DATA
 * 中文名称: 机构客户层级资产月报表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS ADS_STAT_INDX_DATA (
    DATA_DATE VARCHAR(8) NOT NULL COMMENT '数据日期',
    BLNG_BRCH VARCHAR(6) NULL COMMENT '所属分行',
    BLNG_BRCH_SUB VARCHAR(6) NULL COMMENT '所属支行',
    BLNG_BRCH_NET VARCHAR(6) NULL COMMENT '所属网点',
    ORG_PATH VARCHAR(20) NULL COMMENT '机构路径',
    CUST_LVL VARCHAR(2) NULL COMMENT '客户等级',
    CUST_CNT NUMBER(8) NULL COMMENT '客户数',
    AUM_BAL NUMBER(20,2) NULL COMMENT 'AUM余额',
    AUM_MTH_AVG NUMBER(20,2) NULL COMMENT 'AUM月日均',
    COMN_FIXD_BAL NUMBER(20,2) NULL COMMENT '普通定期余额',
    LEHUI_BAL NUMBER(20,2) NULL COMMENT '乐惠存余额',
    LARGEDP_BAL NUMBER(20,2) NULL COMMENT '大额存单余额',
    FIXD_SUM NUMBER(20,2) NULL COMMENT '定期合计',
    DEPO_CURNT_DEPO_BAL NUMBER(20,2) NULL COMMENT '活期余额',
    DEPO_SUM NUMBER(20,2) NULL COMMENT '存款合计',
    BIZ_SELF_FIN_BAL NUMBER(20,2) NULL COMMENT '自营理财余额',
    PROXY_SELL_FIN_BAL NUMBER(20,2) NULL COMMENT '代销理财余额',
    FIN_BAL_SUM NUMBER(20,2) NULL COMMENT '理财余额合计',
    INSUR_BAL NUMBER(20,2) NULL COMMENT '保险余额',
    LOAN_BAL NUMBER(20,2) NULL COMMENT '贷款余额'
);

COMMENT ON TABLE ADS_STAT_INDX_DATA IS '机构客户层级资产月报表';
