/*
 * ADS_CUST_NEW_CUST_STATIS
 * 中文名称: 新客经营统计表
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_NEW_CUST_STATIS (
    PERSN_LEGAL_BK_CODE VARCHAR(4),
    DATA_DATE VARCHAR(8),
    STATIS_OBJ VARCHAR(20),
    STATIS_CYCLE VARCHAR(2),
    NEW_CUST_CYCLE VARCHAR(1),
    NEW_CUST_CNT NUMBER(8),
    CNTCT_CUST_CNT NUMBER(8),
    ASSET_BAL_SEG1_CUST_CNT NUMBER(8),
    ASSET_BAL_SEG2_CUST_CNT NUMBER(8),
    ASSET_BAL_SEG3_CUST_CNT NUMBER(8),
    ASSET_BAL_SEG4_CUST_CNT NUMBER(8),
    ASSET_BAL_SEG5_CUST_CNT NUMBER(8),
    CNTCT_RATE NUMBER(20,
    2),
    KYC_CUST_CNT NUMBER(8),
    COMP_RATE NUMBER(20,
    2)
);

COMMENT ON TABLE ADS_CUST_NEW_CUST_STATIS IS '新客经营统计表';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_STATIS.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_STATIS.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_STATIS.STATIS_OBJ IS '统计对象';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_STATIS.STATIS_CYCLE IS '统计周期(月/季/年)';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_STATIS.NEW_CUST_CYCLE IS '新客周期';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_STATIS.NEW_CUST_CNT IS '新客数';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_STATIS.CNTCT_CUST_CNT IS '已接触客户';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_STATIS.ASSET_BAL_SEG1_CUST_CNT IS '资产余额区间1客户数';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_STATIS.ASSET_BAL_SEG2_CUST_CNT IS '资产余额区间2客户数';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_STATIS.ASSET_BAL_SEG3_CUST_CNT IS '资产余额区间3客户数';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_STATIS.ASSET_BAL_SEG4_CUST_CNT IS '资产余额区间4客户数';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_STATIS.ASSET_BAL_SEG5_CUST_CNT IS '资产余额区间5客户数';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_STATIS.CNTCT_RATE IS '接触率';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_STATIS.KYC_CUST_CNT IS 'KYC客户';
COMMENT ON COLUMN ADS_CUST_NEW_CUST_STATIS.COMP_RATE IS '完成率';