/*
 * ADS_MKT_REC_INFO
 * 中文名称: 营销记录表
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_MKT_REC_INFO (
    MKT_REC_SEQ_ID VARCHAR(40),
    REL_ID VARCHAR(40),
    MKT_TYP VARCHAR(6),
    REL_TYP VARCHAR(6),
    CUST_ID VARCHAR(20),
    CUST_NAME VARCHAR(100),
    MKT_SITE VARCHAR(200),
    MKT_TIME VARCHAR(20),
    MKT_PERSN VARCHAR(30),
    MKT_PERSN_NAME VARCHAR(64),
    MKT_ORG VARCHAR(7),
    MKT_DURA VARCHAR(20),
    MKT_DTL_SITU VARCHAR(400),
    MKT_APDIX_ID VARCHAR(40),
    TEMP_ID VARCHAR(40),
    TEMP_NAME VARCHAR(100),
    MSG_SHORT_SEQ_ID VARCHAR(40),
    PERSN_LEGAL_BK_CODE VARCHAR(30),
    CORDNAT_VISITOR VARCHAR(100),
    CORDNAT_VISITOR_NAME VARCHAR(200),
    LGTUD VARCHAR(40),
    LATTUD VARCHAR(40),
    TEL_NO VARCHAR(40),
    CHNL_NO VARCHAR(6),
    RMARK VARCHAR(400),
    NO_BAT VARCHAR(40),
    MSG_SHORT_INF VARCHAR(500)
);

COMMENT ON TABLE ADS_MKT_REC_INFO IS '营销记录表';
COMMENT ON COLUMN ADS_MKT_REC_INFO.MKT_REC_SEQ_ID IS '营销记录流水号';
COMMENT ON COLUMN ADS_MKT_REC_INFO.REL_ID IS '关联ID(商机ID、客户群ID/营销活动ID)';
COMMENT ON COLUMN ADS_MKT_REC_INFO.MKT_TYP IS '营销类型(1面访/2电话/3短信/4企微)';
COMMENT ON COLUMN ADS_MKT_REC_INFO.REL_TYP IS '关联类型(客户群/商机/营销活动)';
COMMENT ON COLUMN ADS_MKT_REC_INFO.CUST_ID IS '客户ID';
COMMENT ON COLUMN ADS_MKT_REC_INFO.CUST_NAME IS '客户名称';
COMMENT ON COLUMN ADS_MKT_REC_INFO.MKT_SITE IS '营销地点';
COMMENT ON COLUMN ADS_MKT_REC_INFO.MKT_TIME IS '营销时间';
COMMENT ON COLUMN ADS_MKT_REC_INFO.MKT_PERSN IS '营销人ID';
COMMENT ON COLUMN ADS_MKT_REC_INFO.MKT_PERSN_NAME IS '营销人名称';
COMMENT ON COLUMN ADS_MKT_REC_INFO.MKT_ORG IS '营销机构';
COMMENT ON COLUMN ADS_MKT_REC_INFO.MKT_DURA IS '营销时长';
COMMENT ON COLUMN ADS_MKT_REC_INFO.MKT_DTL_SITU IS '营销详细情况';
COMMENT ON COLUMN ADS_MKT_REC_INFO.MKT_APDIX_ID IS '营销附件ID(录音/图片)';
COMMENT ON COLUMN ADS_MKT_REC_INFO.TEMP_ID IS '模板ID';
COMMENT ON COLUMN ADS_MKT_REC_INFO.TEMP_NAME IS '模板名称';
COMMENT ON COLUMN ADS_MKT_REC_INFO.MSG_SHORT_SEQ_ID IS '短信流水号';
COMMENT ON COLUMN ADS_MKT_REC_INFO.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_MKT_REC_INFO.CORDNAT_VISITOR IS '协同拜访人';
COMMENT ON COLUMN ADS_MKT_REC_INFO.CORDNAT_VISITOR_NAME IS '协同拜访人名称';
COMMENT ON COLUMN ADS_MKT_REC_INFO.LGTUD IS '经度';
COMMENT ON COLUMN ADS_MKT_REC_INFO.LATTUD IS '纬度';
COMMENT ON COLUMN ADS_MKT_REC_INFO.TEL_NO IS '联系电话';
COMMENT ON COLUMN ADS_MKT_REC_INFO.CHNL_NO IS '渠道编号';
COMMENT ON COLUMN ADS_MKT_REC_INFO.RMARK IS '备注';
COMMENT ON COLUMN ADS_MKT_REC_INFO.NO_BAT IS '批次号';
COMMENT ON COLUMN ADS_MKT_REC_INFO.MSG_SHORT_INF IS '短信内容';