/*
 * ADS_MKT_TSK_INFO
 * 中文名称: 营销任务表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS ADS_MKT_TSK_INFO (
    MKT_TSK_ID VARCHAR(40) NOT NULL COMMENT '营销任务编号',
    MKT_ACT_ID VARCHAR(40) NULL COMMENT '活动编号',
    CUST_ID VARCHAR(21) NULL COMMENT '客户编号',
    CUST_NAME VARCHAR(200) NULL COMMENT '客户名称',
    COVER_FLG VARCHAR(1) NULL COMMENT '是否接触',
    CONVRS_FLG VARCHAR(1) NULL COMMENT '是否成功',
    MKT_PERSN VARCHAR(30) NULL COMMENT '营销人',
    MKT_PERSN_ORG VARCHAR(30) NULL COMMENT '营销人机构',
    CREATR VARCHAR(64) NULL COMMENT '创建人',
    CREAT_TIME VARCHAR(20) NULL COMMENT '创建时间',
    CREAT_ORG VARCHAR(30) NULL COMMENT '创建机构',
    BASE_VAL NUMBER(18,4) NULL COMMENT '基数',
    CURNT_VAL NUMBER(18,4) NULL COMMENT '当前值',
    DATA_DATE VARCHAR(30) NULL COMMENT '数据日期',
    PERSN_LEGAL_BK_CODE VARCHAR(30) NULL COMMENT '法人行号',
    ACT_DSC VARCHAR(2000) NULL COMMENT '备注'
);

COMMENT ON TABLE ADS_MKT_TSK_INFO IS '营销任务表';
