/*
 * ADS_STAT_INDX_DATA_MKT
 * 中文名称: 指标数据统计-营销中间表
 * 版本: v1.0
 * 创建时间: 2026-09-10
 * 来源: prc_ads_stat_indx_plan_010.sql v1.3 两段式发布
 *       机构树上卷后先发布到本表（单事务），再按当日+指标范围转 ADS_STAT_INDX_DATA 主表
 * 说明: 列结构=主表 ADS_STAT_INDX_DATA 中 plan_010 实际写入的 8 列
 *       （不含 MTH_END_VAL/YR_BGN_VAL/MTH_LAST_END_AVG_DAY_VAL/YR_LAST_END_AVG_DAY_VAL 四个主表扩展列）
 */

DROP TABLE ADS_STAT_INDX_DATA_MKT;
CREATE TABLE ADS_STAT_INDX_DATA_MKT (
    INDX_CODE             VARCHAR(100),
    DATA_BLNG             VARCHAR(100),
    STATIS_DIM            VARCHAR(100),
    STATIS_CALIB          VARCHAR(100),
    CURNT_VAL             NUMBER(20,2),
    TERM_LAST_VAL         NUMBER(20,2),
    DATA_DATE             VARCHAR(10),
    PERSN_LEGAL_BK_CODE   VARCHAR(30)
);

COMMENT ON TABLE ADS_STAT_INDX_DATA_MKT IS '指标数据统计-营销中间表';
COMMENT ON COLUMN ADS_STAT_INDX_DATA_MKT.INDX_CODE IS '指标编码';
COMMENT ON COLUMN ADS_STAT_INDX_DATA_MKT.DATA_BLNG IS '数据归属: 机构编码/客户经理编码（裸值，无ORG_/MGR_前缀）';
COMMENT ON COLUMN ADS_STAT_INDX_DATA_MKT.STATIS_DIM IS '统计维度: 08营销活动/09目标任务';
COMMENT ON COLUMN ADS_STAT_INDX_DATA_MKT.STATIS_CALIB IS '统计口径: 活动ID或任务ID';
COMMENT ON COLUMN ADS_STAT_INDX_DATA_MKT.CURNT_VAL IS '本期值';
COMMENT ON COLUMN ADS_STAT_INDX_DATA_MKT.TERM_LAST_VAL IS '上期值';
COMMENT ON COLUMN ADS_STAT_INDX_DATA_MKT.DATA_DATE IS '数据日期(YYYYMMDD)';
COMMENT ON COLUMN ADS_STAT_INDX_DATA_MKT.PERSN_LEGAL_BK_CODE IS '法人行号';
