/*
 * ADS_MKT_TSK_INFO
 * 中文名称: 营销任务表
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_MKT_TSK_INFO (
    MKT_TSK_ID VARCHAR(40),
    MKT_ACT_ID VARCHAR(40),
    CUST_ID VARCHAR(21),
    CUST_NAME VARCHAR(200),
    COVER_FLG VARCHAR(1),
    CONVRS_FLG VARCHAR(1),
    MKT_PERSN VARCHAR(30),
    MKT_PERSN_ORG VARCHAR(7),
    CREATR VARCHAR(64),
    CREAT_TIME VARCHAR(20),
    CREAT_ORG VARCHAR(7),
    BASE_VAL NUMBER(18,
    4),
    CURNT_VAL NUMBER(18,
    4),
    DATA_DATE VARCHAR(30),
    PERSN_LEGAL_BK_CODE VARCHAR(30),
    ACT_DSC VARCHAR(2000)
);

COMMENT ON TABLE ADS_MKT_TSK_INFO IS '营销任务表';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.MKT_TSK_ID IS '营销任务编号';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.MKT_ACT_ID IS '活动编号';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.CUST_ID IS '客户编号';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.CUST_NAME IS '客户名称';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.COVER_FLG IS '是否接触';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.CONVRS_FLG IS '是否成功';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.MKT_PERSN IS '营销人';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.MKT_PERSN_ORG IS '营销人机构';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.CREATR IS '创建人';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.CREAT_TIME IS '创建时间';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.CREAT_ORG IS '创建机构';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.BASE_VAL IS '基数';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.CURNT_VAL IS '当前值';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_MKT_TSK_INFO.ACT_DSC IS '备注';