/*
 * ADS_CUST_DEADLINE_RMND_STATIS
 * 中文名称: 到期承接统计表
 * 版本: v1.0.0
 * 创建时间: 2026-07-29
 * 来源: Mapping Excel (ADS应用层数据模型)
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_DEADLINE_RMND_STATIS (
    PERSN_LEGAL_BK_CODE      VARCHAR2(4) , -- 法人行号
    DATA_DATE                VARCHAR2(8) , -- 数据日期
    STATIS_OBJ               VARCHAR2(20), -- 统计对象
    STATIS_CYCLE             VARCHAR2(2) , -- 统计周期
    STATIS_TYP               VARCHAR2(2) , -- 承接类型1-存款2-理财
    EXPR_CUST_CNT            NUMBER(8)   , -- 已到期客户数
    TTL_EXPR_CUST_CNT        NUMBER(8)   , -- 总到期客户数
    EXPR_AMT                 NUMBER(20,2), -- 已到期金额
    TTL_EXPR_AMT             NUMBER(20,2), -- 总到期金额
    CUST_UNDTAKE_RATE        NUMBER(20,2), -- 客户承接率
    ASSET_KEEP_RATE          NUMBER(20,2), -- 资产留存率
    ASSET_UNDTAKE_RATE       NUMBER(20,2), -- 资产承接率
    DEPO_TO_FIN_CONVRS_RATE  NUMBER(20,2), -- 存款转理财转化率
    INSUR_CONVRS_RATE        NUMBER(20,2), -- 保险转化率
    FIN_TO_DEPO_CONVRS_RATE  NUMBER(20,2)  -- 理财转存款转化率
);

COMMENT ON TABLE ADS_CUST_DEADLINE_RMND_STATIS IS '到期承接统计表';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.STATIS_OBJ IS '统计对象';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.STATIS_CYCLE IS '统计周期';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.STATIS_TYP IS '承接类型1-存款2-理财';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.EXPR_CUST_CNT IS '已到期客户数';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.TTL_EXPR_CUST_CNT IS '总到期客户数';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.EXPR_AMT IS '已到期金额';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.TTL_EXPR_AMT IS '总到期金额';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.CUST_UNDTAKE_RATE IS '客户承接率';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.ASSET_KEEP_RATE IS '资产留存率';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.ASSET_UNDTAKE_RATE IS '资产承接率';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.DEPO_TO_FIN_CONVRS_RATE IS '存款转理财转化率';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.INSUR_CONVRS_RATE IS '保险转化率';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_STATIS.FIN_TO_DEPO_CONVRS_RATE IS '理财转存款转化率';
