/*
 * ADS_STAT_INDX_DATA
 * 中文名称: 指标数据统计
 * 版本: v1.0.0
 * 创建时间: 2026-07-29
 * 来源: Mapping Excel (ADS应用层数据模型)
 */

CREATE TABLE IF NOT EXISTS ADS_STAT_INDX_DATA (
    INDX_CODE                 VARCHAR2(100), -- 指标编码
    DATA_BLNG                 VARCHAR2(100), -- 数据归属
    STATIS_DIM                VARCHAR2(100), -- 统计维度
    STATIS_CALIB              VARCHAR2(100), -- 统计口径
    CURNT_VAL                 NUMBER(20,2) , -- 本期值
    TERM_LAST_VAL             NUMBER(20,2) , -- 上期值
    MTH_END_VAL               NUMBER(20,2) , -- 月末值
    YR_BGN_VAL                NUMBER(20,2) , -- 年初值
    MTH_LAST_END_AVG_DAY_VAL  NUMBER(20,2) , -- 上月末日均值
    YR_LAST_END_AVG_DAY_VAL   NUMBER(20,2) , -- 上年末日均值
    DATA_DATE                 VARCHAR2(10) , -- 数据日期
    PERSN_LEGAL_BK_CODE       VARCHAR2(30) , -- 法人行号
    ID                        VARCHAR2(10)   -- [NULL]
);

COMMENT ON TABLE ADS_STAT_INDX_DATA IS '指标数据统计';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.INDX_CODE IS '指标编码';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.DATA_BLNG IS '数据归属';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.STATIS_DIM IS '统计维度';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.STATIS_CALIB IS '统计口径';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.CURNT_VAL IS '本期值';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.TERM_LAST_VAL IS '上期值';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.MTH_END_VAL IS '月末值';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.YR_BGN_VAL IS '年初值';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.MTH_LAST_END_AVG_DAY_VAL IS '上月末日均值';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.YR_LAST_END_AVG_DAY_VAL IS '上年末日均值';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_STAT_INDX_DATA.ID IS '[NULL]';
