/*
 * ADS_CUST_DEADLINE_RMND_DTL
 * 中文名称: 到期承接明细表
 * 版本: v1.0
 * 创建时间: 2026-07-20
 */

CREATE TABLE IF NOT EXISTS ADS_CUST_DEADLINE_RMND_DTL (
    PERSN_LEGAL_BK_CODE VARCHAR(4),
    DATA_DATE VARCHAR(8),
    CUST_ID VARCHAR(20),
    CUST_NAME VARCHAR(100),
    CUST_HRAKY VARCHAR(2),
    DEPO_CURNT_DEPO_BAL NUMBER(20,
    2),
    FIXD_DEPO_BAL NUMBER(20,
    2),
    FIN_AMT NUMBER(20,
    2),
    STAT_PERD VARCHAR(2),
    STATIS_TYP VARCHAR(2),
    EXPR_AMT NUMBER(20,
    2),
    MATURE_TTL_AMT NUMBER(20,
    2),
    TAKE_RATE NUMBER(10,
    2),
    FIX_DEPO_MATURE_AMT NUMBER(20,
    2),
    FIX_DEPO_MATURE_TTL_AMT NUMBER(20,
    2),
    FIX_DEPO_TAKE_RATE NUMBER(10,
    2),
    CNTCT_STATE VARCHAR(1),
    UNDTAKE_STATE VARCHAR(1),
    FIXED_FIN_MATURE_TRAN_INSUR_AMT NUMBER(20,
    2),
    FIN_MATURE_TRAN_FIXED_AMT NUMBER(20,
    2),
    FIXED_MATURE_TRAN_FIN_AMT NUMBER(20,
    2),
    FRST_MATURE_PK_BF_DAY_AUM_BAL NUMBER(20,
    2),
    LAST_END_DATE VARCHAR(8),
    POST_ID VARCHAR(20),
    ORG_ID VARCHAR(7)
);

COMMENT ON TABLE ADS_CUST_DEADLINE_RMND_DTL IS '到期承接明细表';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.DATA_DATE IS '数据日期';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.CUST_ID IS '客户编号';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.CUST_NAME IS '客户名称';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.CUST_HRAKY IS '客户等级';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.DEPO_CURNT_DEPO_BAL IS '活期余额';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.FIXD_DEPO_BAL IS '定期余额';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.FIN_AMT IS '理财余额';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.STAT_PERD IS '统计周期';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.STATIS_TYP IS '承接类型0-全部1-存款2-理财';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.EXPR_AMT IS '到期金额';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.MATURE_TTL_AMT IS '到期总金额';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.TAKE_RATE IS '承接率';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.FIX_DEPO_MATURE_AMT IS '定期存款到期金额';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.FIX_DEPO_MATURE_TTL_AMT IS '定期存款到期总金额';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.FIX_DEPO_TAKE_RATE IS '定期存款承接率';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.CNTCT_STATE IS '接触状态';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.UNDTAKE_STATE IS '承接状态';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.FIXED_FIN_MATURE_TRAN_INSUR_AMT IS '定期理财到期转保险金额';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.FIN_MATURE_TRAN_FIXED_AMT IS '理财到期转定期金额';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.FIXED_MATURE_TRAN_FIN_AMT IS '定期到期转理财金额';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.FRST_MATURE_PK_BF_DAY_AUM_BAL IS '本期第一笔到期产品前一日AUM余额';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.LAST_END_DATE IS '本期最后一笔到期产品日期';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.POST_ID IS '管户经理';
COMMENT ON COLUMN ADS_CUST_DEADLINE_RMND_DTL.ORG_ID IS '归属机构';