-- ============================================================
-- Functional validation: new-customer detail + statis assertions
-- ============================================================
SET PAGESIZE 200
SET LINESIZE 250

PROMPT ============ F1 Detail rows & cycle classification (expect 14) ============
SELECT NEW_CUST_CYCLE, COUNT(*) AS CNT FROM ADS_CUST_NEW_CUST_DTL GROUP BY NEW_CUST_CYCLE ORDER BY NEW_CUST_CYCLE;
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_NEW_CUST_DTL) = 14
             AND (SELECT COUNT(*) FROM ADS_CUST_NEW_CUST_DTL WHERE NEW_CUST_CYCLE='1') = 5
             AND (SELECT COUNT(*) FROM ADS_CUST_NEW_CUST_DTL WHERE NEW_CUST_CYCLE='2') = 6
             AND (SELECT COUNT(*) FROM ADS_CUST_NEW_CUST_DTL WHERE NEW_CUST_CYCLE='3') = 3
            THEN 'PASS' ELSE 'FAIL' END AS F1_CYCLES
  FROM dual;

PROMPT ============ F2 Exclusion (N06 181d, N07 no snapshot) ============
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_NEW_CUST_DTL WHERE CUST_ID IN ('N06','N07')) = 0
            THEN 'PASS' ELSE 'FAIL' END AS F2_EXCLUSIONS
  FROM dual;

PROMPT ============ F3 Current-month rating = 'not rated' (未评级) ============
SELECT CUST_ID, CUST_LVL FROM ADS_CUST_NEW_CUST_DTL WHERE CUST_ID IN ('N01','N02','N03','N09','N14','N16') ORDER BY CUST_ID;
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_NEW_CUST_DTL
                  WHERE (CUST_ID IN ('N01','N02','N08','N11','N13') AND CUST_LVL='未评级')
                     OR (CUST_ID='N03' AND CUST_LVL='04')
                     OR (CUST_ID='N14' AND CUST_LVL='07')
                     OR (CUST_ID='N16' AND CUST_LVL='05')
                     OR (CUST_ID='N09' AND CUST_LVL='04')) = 9
            THEN 'PASS' ELSE 'FAIL' END AS F3_RATING
  FROM dual;

PROMPT ============ F4 KYC threshold (18/22) ============
SELECT CUST_ID, KYC_STATE FROM ADS_CUST_NEW_CUST_DTL WHERE CUST_ID IN ('N01','N02','N11','N15','N16') ORDER BY CUST_ID;
SELECT CASE WHEN (SELECT KYC_STATE FROM ADS_CUST_NEW_CUST_DTL WHERE CUST_ID='N01') = '1'
             AND (SELECT KYC_STATE FROM ADS_CUST_NEW_CUST_DTL WHERE CUST_ID='N02') = '0'
             AND (SELECT KYC_STATE FROM ADS_CUST_NEW_CUST_DTL WHERE CUST_ID='N11') = '1'
             AND (SELECT KYC_STATE FROM ADS_CUST_NEW_CUST_DTL WHERE CUST_ID='N15') = '1'
             AND (SELECT KYC_STATE FROM ADS_CUST_NEW_CUST_DTL WHERE CUST_ID='N16') = '0'
            THEN 'PASS' ELSE 'FAIL' END AS F4_KYC
  FROM dual;

PROMPT ============ F5 Contact state (person/type/time) ============
SELECT CASE WHEN (SELECT CNTCT_STATE FROM ADS_CUST_NEW_CUST_DTL WHERE CUST_ID='N01') = '1'
             AND (SELECT CNTCT_STATE FROM ADS_CUST_NEW_CUST_DTL WHERE CUST_ID='N11') = '0'
             AND (SELECT CNTCT_STATE FROM ADS_CUST_NEW_CUST_DTL WHERE CUST_ID='N12') = '0'
             AND (SELECT CNTCT_STATE FROM ADS_CUST_NEW_CUST_DTL WHERE CUST_ID='N13') = '0'
            THEN 'PASS' ELSE 'FAIL' END AS F5_CNTCT
  FROM dual;

PROMPT ============ F6 Cycle boundary (29/30/100/180 days) ============
SELECT CASE WHEN (SELECT NEW_CUST_CYCLE FROM ADS_CUST_NEW_CUST_DTL WHERE CUST_ID='N02') = '1'
             AND (SELECT NEW_CUST_CYCLE FROM ADS_CUST_NEW_CUST_DTL WHERE CUST_ID='N03') = '2'
             AND (SELECT NEW_CUST_CYCLE FROM ADS_CUST_NEW_CUST_DTL WHERE CUST_ID='N04') = '3'
             AND (SELECT NEW_CUST_CYCLE FROM ADS_CUST_NEW_CUST_DTL WHERE CUST_ID='N05') = '3'
            THEN 'PASS' ELSE 'FAIL' END AS F6_BOUNDARY
  FROM dual;

PROMPT ============ F7 Statis completeness (DEFECT-NEWCUST-002 probe) ============
PROMPT -- expected 14 in cycle 4 if org-less customers were kept; actual implementation drops N09/N10
SELECT STATIS_OBJ, NEW_CUST_CYCLE, NEW_CUST_CNT FROM ADS_CUST_NEW_CUST_STATIS
 WHERE STATIS_OBJ='ORG100' ORDER BY NEW_CUST_CYCLE;
SELECT CASE WHEN (SELECT NEW_CUST_CNT FROM ADS_CUST_NEW_CUST_STATIS
                  WHERE STATIS_OBJ='ORG100' AND NEW_CUST_CYCLE='4') = 14
            THEN 'PASS' ELSE 'FAIL' END AS F7_STATIS_COMPLETE
  FROM dual;

PROMPT ============ F8 Statis rates & asset segments (per current impl) ============
SELECT NEW_CUST_CYCLE, NEW_CUST_CNT, CNTCT_CUST_CNT, CNTCT_RATE, KYC_CUST_CNT, COMP_RATE,
       ASSET_BAL_SEG1_CUST_CNT, ASSET_BAL_SEG2_CUST_CNT, ASSET_BAL_SEG3_CUST_CNT, ASSET_BAL_SEG4_CUST_CNT, ASSET_BAL_SEG5_CUST_CNT
  FROM ADS_CUST_NEW_CUST_STATIS
 WHERE STATIS_OBJ='ORG100' ORDER BY NEW_CUST_CYCLE;
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_NEW_CUST_STATIS
                  WHERE STATIS_OBJ='ORG100'
                    AND ((NEW_CUST_CYCLE='1' AND NEW_CUST_CNT=5 AND CNTCT_CUST_CNT=1 AND CNTCT_RATE=20
                          AND KYC_CUST_CNT=2 AND COMP_RATE=40 AND ASSET_BAL_SEG1_CUST_CNT=3 AND ASSET_BAL_SEG2_CUST_CNT=2)
                      OR (NEW_CUST_CYCLE='3' AND NEW_CUST_CNT=3 AND ASSET_BAL_SEG2_CUST_CNT=1
                          AND ASSET_BAL_SEG3_CUST_CNT=1 AND ASSET_BAL_SEG5_CUST_CNT=1))) = 2
            THEN 'PASS' ELSE 'FAIL' END AS F8_SEGMENTS
  FROM dual;

EXIT
