-- ============================================================
-- Sleep-wake batch sequence + assertions
-- ============================================================
SET SERVEROUTPUT ON
SET PAGESIZE 200
SET LINESIZE 240

VARIABLE rc NUMBER

PROMPT ============ Run 20260630 (previous month end) ============
EXEC PRC_ADS_CUST_SLEEP_WAKE_DTL('20260630', :rc)
PRINT :rc
SELECT COUNT(*) AS D0630_CNT FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260630';
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260630') = 8
             AND (SELECT COUNT(*) FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260630' AND CUST_ID='S06') = 0
            THEN 'PASS' ELSE 'FAIL' END AS A1_0630
  FROM dual;

PROMPT ============ Run 20260701 (month start: review + reset + new) ============
EXEC PRC_ADS_CUST_SLEEP_WAKE_DTL('20260701', :rc)
PRINT :rc
EXEC PRC_ADS_CUST_SLEEP_WAKE_STATIS('20260701', :rc)
PRINT :rc
SELECT COUNT(*) AS D0701_CNT FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260701';
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260701') = 10
             AND (SELECT COUNT(*) FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260701' AND CUST_ID IN ('S07','S11')) = 0
             AND (SELECT SUM(WAKE_STATE) FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260701') = 0
             AND (SELECT SUM(CNTCT_STATE) FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260701') = 0
            THEN 'PASS' ELSE 'FAIL' END AS A2_MONTH_START
  FROM dual;

PROMPT ============ Run 20260702 (in-month: wake on new holding) ============
EXEC PRC_ADS_CUST_SLEEP_WAKE_DTL('20260702', :rc)
PRINT :rc
EXEC PRC_ADS_CUST_SLEEP_WAKE_STATIS('20260702', :rc)
PRINT :rc
SELECT CUST_ID, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_AMT, INSUR_AMT, CNTCT_STATE, WAKE_STATE
  FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260702' ORDER BY CUST_ID;
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260702') = 10
             AND (SELECT WAKE_STATE FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260702' AND CUST_ID='S03') = '1'
             AND (SELECT WAKE_STATE FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260702' AND CUST_ID='S05') = '1'
             AND (SELECT WAKE_STATE FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260702' AND CUST_ID='S12') = '1'
             AND (SELECT WAKE_STATE FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260702' AND CUST_ID='S01') = '0'
             AND (SELECT CNTCT_STATE FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260702' AND CUST_ID='S13') = '0'
            THEN 'PASS' ELSE 'FAIL' END AS A3_WAKE_NEW
  FROM dual;

PROMPT ============ Run 20260703 (irreversibility + contact) ============
EXEC PRC_ADS_CUST_SLEEP_WAKE_DTL('20260703', :rc)
PRINT :rc
EXEC PRC_ADS_CUST_SLEEP_WAKE_STATIS('20260703', :rc)
PRINT :rc
SELECT CUST_ID, FIXD_DEPO_BAL, CNTCT_STATE, WAKE_STATE
  FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260703' AND CUST_ID IN ('S02','S03','S05') ORDER BY CUST_ID;
SELECT CASE WHEN (SELECT WAKE_STATE FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260703' AND CUST_ID='S05') = '1'
             AND (SELECT CNTCT_STATE FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260703' AND CUST_ID='S02') = '1'
             AND (SELECT WAKE_STATE FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260703' AND CUST_ID='S01') = '0'
            THEN 'PASS' ELSE 'FAIL' END AS A4_IRREVERSIBLE
  FROM dual;

PROMPT ============ Statis on 07-02 (ORG100) ============
SELECT STATIS_OBJ, CUST_CNT, CNTCT_CUST_CNT, CNTCT_RATE, WAKE_CUST_CNT, WAKE_RATE
  FROM ADS_CUST_SLEEP_WAKE_STATIS
 WHERE DATA_DATE='20260702' AND STATIS_OBJ='ORG100';
SELECT CASE WHEN (SELECT WAKE_CUST_CNT FROM ADS_CUST_SLEEP_WAKE_STATIS
                  WHERE DATA_DATE='20260702' AND STATIS_OBJ='ORG100') = 3
             AND (SELECT WAKE_RATE FROM ADS_CUST_SLEEP_WAKE_STATIS
                  WHERE DATA_DATE='20260702' AND STATIS_OBJ='ORG100') = 30
            THEN 'PASS' ELSE 'FAIL' END AS A5_STATIS
  FROM dual;

PROMPT ============ S09 no-snapshot retention (07-02) ============
SELECT CUST_ID, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL
  FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260702' AND CUST_ID='S09';
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_SLEEP_WAKE_DTL
                  WHERE DATA_DATE='20260702' AND CUST_ID='S09') = 1
            THEN 'PASS' ELSE 'FAIL' END AS A6_S09_KEPT
  FROM dual;

EXIT
