SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF

-- ============================================================
-- v2.14.0 Full Regression Test
-- Covers: sleep detection, wake (account table date-driven),
--          month-begin review, F-10 retention, contact state,
--          F-1 DWS→TMP reuse, F-2 string range compare, F-3 step split
-- ============================================================

BEGIN DBMS_OUTPUT.PUT_LINE('=== v2.14.0 Full Regression ==='); END;
/

-- ============================================================
-- Phase 0: Clean
-- ============================================================
DELETE FROM ADS_CUST_SLEEP_WAKE_DTL;
DELETE FROM ADS_CUST_SLEEP_WAKE_STATIS;
DELETE FROM DWD_ACCT_DEPO;
DELETE FROM DWD_ACCT_FIN;
DELETE FROM DWD_ACCT_INSUR;
DELETE FROM DWD_CUST_INDV_INFO;
DELETE FROM DWS_CUST_ASSE_LIAB;
DELETE FROM DWD_CUST_MAN;
DELETE FROM DWS_CUST_LVL_INFO;
DELETE FROM DWD_SYS_ORG;
DELETE FROM DWD_TX_ASET;
DELETE FROM ADS_MKT_REC_INFO;

BEGIN
  EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_ADS_SLEEP_WAKE_BASE';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_ADS_SLEEP_DWS_WAKE';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_ADS_SLEEP_CNTCT';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_ADS_SLEEP_WAKE_PROD';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_ADS_SLEEP_ACTIVE_TXN';
END;
/

-- ============================================================
-- Phase 1: Org & Customers
-- ============================================================
INSERT INTO DWD_SYS_ORG (ORG_ID, SUP_ORG_ID, ORG_NAME, PERSN_LEGAL_BK_CODE) VALUES ('ORG001', NULL, 'Root', 'BK01');
INSERT INTO DWD_SYS_ORG (ORG_ID, SUP_ORG_ID, ORG_NAME, PERSN_LEGAL_BK_CODE) VALUES ('ORG002', 'ORG001', 'Branch1', 'BK01');
INSERT INTO DWD_SYS_ORG (ORG_ID, SUP_ORG_ID, ORG_NAME, PERSN_LEGAL_BK_CODE) VALUES ('ORG003', 'ORG001', 'Branch2', 'BK01');

INSERT INTO DWD_CUST_INDV_INFO (CUST_ID, CUST_NAME, CUST_TYP, OPEN_DATE, OPEN_ORG, PERSN_LEGAL_BK_CODE)
SELECT 'C'||LPAD(LEVEL,3,'0'), 'Test'||LPAD(LEVEL,3,'0'), '01', '20250101', 'ORG001', 'BK01' FROM DUAL CONNECT BY LEVEL<=15;

INSERT INTO DWS_CUST_LVL_INFO (DATA_DATE, CUST_ID, CUST_LVL, PERSN_LEGAL_BK_CODE)
SELECT '20260801'||'', 'C'||LPAD(LEVEL,3,'0'), '01', 'BK01' FROM DUAL CONNECT BY LEVEL<=15;

INSERT INTO DWD_CUST_MAN (CUST_ID, MNGR_POST_ID, ORG_ID, MNG_TYP, PERSN_LEGAL_BK_CODE)
SELECT 'C'||LPAD(LEVEL,3,'0'), 'MGR'||LPAD(LEVEL,3,'0'), 'ORG001', '1', 'BK01' FROM DUAL CONNECT BY LEVEL<=15;

-- ============================================================
-- Phase 2: T-1 DTL (20260731, month-end)
-- ============================================================
INSERT INTO DWS_CUST_ASSE_LIAB (DATA_DATE, PERSN_LEGAL_BK_CODE, CUST_ID, ORG_ID, BAL_TYPE, AUM_BAL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_BAL, INSUR_BAL)
SELECT '20260731', 'BK01', 'C'||LPAD(LEVEL,3,'0'), 'ORG001', '1', 50, 50, 0, 0, 0 FROM DUAL CONNECT BY LEVEL<=12;

-- T-1 DTL: C010(still sleep), C011(AUM>=100), C012(F-10 wake retention)
-- T-1 DTL: C004(fixd wake), C007(fin wake), C008(insur wake), C010(still sleep), C011(AUM>=100), C012(F-10)
INSERT INTO ADS_CUST_SLEEP_WAKE_DTL(PERSN_LEGAL_BK_CODE, DATA_DATE, CUST_ID, CUST_NAME, CUST_LVL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_AMT, INSUR_AMT, CNTCT_STATE, WAKE_STATE, POST_ID, ORG_ID, STATIS_CYCLE)
VALUES ('BK01', '20260731', 'C004', 'WakeFixd', '01', 50, 0, 0, 0, '0', '0', 'MGR004', 'ORG001', 'M');
INSERT INTO ADS_CUST_SLEEP_WAKE_DTL(PERSN_LEGAL_BK_CODE, DATA_DATE, CUST_ID, CUST_NAME, CUST_LVL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_AMT, INSUR_AMT, CNTCT_STATE, WAKE_STATE, POST_ID, ORG_ID, STATIS_CYCLE)
VALUES ('BK01', '20260731', 'C007', 'WakeFin', '01', 50, 0, 0, 0, '0', '0', 'MGR007', 'ORG001', 'M');
INSERT INTO ADS_CUST_SLEEP_WAKE_DTL(PERSN_LEGAL_BK_CODE, DATA_DATE, CUST_ID, CUST_NAME, CUST_LVL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_AMT, INSUR_AMT, CNTCT_STATE, WAKE_STATE, POST_ID, ORG_ID, STATIS_CYCLE)
VALUES ('BK01', '20260731', 'C008', 'WakeInsur', '01', 50, 0, 0, 0, '0', '0', 'MGR008', 'ORG001', 'M');
INSERT INTO ADS_CUST_SLEEP_WAKE_DTL(PERSN_LEGAL_BK_CODE, DATA_DATE, CUST_ID, CUST_NAME, CUST_LVL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_AMT, INSUR_AMT, CNTCT_STATE, WAKE_STATE, POST_ID, ORG_ID, STATIS_CYCLE)
VALUES ('BK01', '20260731', 'C010', 'StillSleep', '01', 30, 0, 0, 0, '0', '0', 'MGR010', 'ORG001', 'M');
INSERT INTO ADS_CUST_SLEEP_WAKE_DTL(PERSN_LEGAL_BK_CODE, DATA_DATE, CUST_ID, CUST_NAME, CUST_LVL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_AMT, INSUR_AMT, CNTCT_STATE, WAKE_STATE, POST_ID, ORG_ID, STATIS_CYCLE)
VALUES ('BK01', '20260731', 'C011', 'AUM100+NoWake', '01', 150, 0, 0, 0, '0', '0', 'MGR011', 'ORG001', 'M');
INSERT INTO ADS_CUST_SLEEP_WAKE_DTL(PERSN_LEGAL_BK_CODE, DATA_DATE, CUST_ID, CUST_NAME, CUST_LVL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_AMT, INSUR_AMT, CNTCT_STATE, WAKE_STATE, POST_ID, ORG_ID, STATIS_CYCLE)
VALUES ('BK01', '20260731', 'C012', 'F10WakeKeep', '01', 0, 100, 0, 0, '0', '1', 'MGR012', 'ORG001', 'M');

-- ============================================================
-- Phase 3: 20260801 Data
-- ============================================================
-- C001 intentionally NOT in DWS (test: customer not in DWS should be excluded)
INSERT INTO DWS_CUST_ASSE_LIAB (DATA_DATE, PERSN_LEGAL_BK_CODE, CUST_ID, ORG_ID, BAL_TYPE, AUM_BAL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_BAL, INSUR_BAL)
VALUES ('20260801', 'BK01', 'C002', 'ORG001', '1', 50, 50, 0, 0, 0);
INSERT INTO DWS_CUST_ASSE_LIAB (DATA_DATE, PERSN_LEGAL_BK_CODE, CUST_ID, ORG_ID, BAL_TYPE, AUM_BAL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_BAL, INSUR_BAL)
VALUES ('20260801', 'BK01', 'C003', 'ORG001', '1', 50, 50, 0, 0, 0);
INSERT INTO DWS_CUST_ASSE_LIAB (DATA_DATE, PERSN_LEGAL_BK_CODE, CUST_ID, ORG_ID, BAL_TYPE, AUM_BAL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_BAL, INSUR_BAL)
VALUES ('20260801', 'BK01', 'C004', 'ORG001', '1', 10050, 50, 10000, 0, 0);
INSERT INTO DWS_CUST_ASSE_LIAB (DATA_DATE, PERSN_LEGAL_BK_CODE, CUST_ID, ORG_ID, BAL_TYPE, AUM_BAL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_BAL, INSUR_BAL)
VALUES ('20260801', 'BK01', 'C005', 'ORG001', '1', 99.99, 99.99, 0, 0, 0);
INSERT INTO DWS_CUST_ASSE_LIAB (DATA_DATE, PERSN_LEGAL_BK_CODE, CUST_ID, ORG_ID, BAL_TYPE, AUM_BAL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_BAL, INSUR_BAL)
VALUES ('20260801', 'BK01', 'C006', 'ORG001', '1', 100, 100, 0, 0, 0);
INSERT INTO DWS_CUST_ASSE_LIAB (DATA_DATE, PERSN_LEGAL_BK_CODE, CUST_ID, ORG_ID, BAL_TYPE, AUM_BAL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_BAL, INSUR_BAL)
VALUES ('20260801', 'BK01', 'C007', 'ORG001', '1', 5050, 50, 0, 5000, 0);
INSERT INTO DWS_CUST_ASSE_LIAB (DATA_DATE, PERSN_LEGAL_BK_CODE, CUST_ID, ORG_ID, BAL_TYPE, AUM_BAL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_BAL, INSUR_BAL)
VALUES ('20260801', 'BK01', 'C008', 'ORG001', '1', 5050, 50, 0, 0, 5000);
INSERT INTO DWS_CUST_ASSE_LIAB (DATA_DATE, PERSN_LEGAL_BK_CODE, CUST_ID, ORG_ID, BAL_TYPE, AUM_BAL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_BAL, INSUR_BAL)
VALUES ('20260801', 'BK01', 'C009', 'ORG001', '1', 0.01, 0.01, 0, 0, 0);
INSERT INTO DWS_CUST_ASSE_LIAB (DATA_DATE, PERSN_LEGAL_BK_CODE, CUST_ID, ORG_ID, BAL_TYPE, AUM_BAL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_BAL, INSUR_BAL)
VALUES ('20260801', 'BK01', 'C010', 'ORG001', '1', 30, 30, 0, 0, 0);
INSERT INTO DWS_CUST_ASSE_LIAB (DATA_DATE, PERSN_LEGAL_BK_CODE, CUST_ID, ORG_ID, BAL_TYPE, AUM_BAL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_BAL, INSUR_BAL)
VALUES ('20260801', 'BK01', 'C011', 'ORG001', '1', 150, 150, 0, 0, 0);
INSERT INTO DWS_CUST_ASSE_LIAB (DATA_DATE, PERSN_LEGAL_BK_CODE, CUST_ID, ORG_ID, BAL_TYPE, AUM_BAL, DEPO_CURNT_DEPO_BAL, FIXD_DEPO_BAL, FIN_BAL, INSUR_BAL)
VALUES ('20260801', 'BK01', 'C012', 'ORG001', '1', 200, 50, 150, 0, 0);

-- Active txn: C003
INSERT INTO DWD_TX_ASET (SEQ_ID, CUST_ID, PERSN_LEGAL_BK_CODE, TX_DATE, JIOYCFFS)
VALUES ('TX'||LPAD(1,10,'0'), 'C003', 'BK01', '2026-03-15', '0');

-- Account tables for wake (v2.12.0+): date in current month
INSERT INTO DWD_ACCT_DEPO (CUST_ID, ACCT_ID, INTRI_BGN_DATE, PERSN_LEGAL_BK_CODE, OPEN_ACCT_ORG, FIX_CURNT_FLG, BAL, RMB_BAL)
VALUES ('C004', 'ACCT_D004', '20260801', 'BK01', 'ORG001', '1', 10000, 10000);
INSERT INTO DWD_ACCT_DEPO (CUST_ID, ACCT_ID, INTRI_BGN_DATE, PERSN_LEGAL_BK_CODE, OPEN_ACCT_ORG, FIX_CURNT_FLG, BAL, RMB_BAL)
VALUES ('C012', 'ACCT_D012', '20260801', 'BK01', 'ORG001', '1', 150, 150);

INSERT INTO DWD_ACCT_FIN (CUST_ID, ACCT_ID, ISSU_DATE, PERSN_LEGAL_BK_CODE, ISSU_ORG, FIN_AMT, PRDKT_CATE_BIG)
VALUES ('C007', 'ACCT_F007', '20260801', 'BK01', 'ORG001', 5000, '2');

INSERT INTO DWD_ACCT_INSUR (CUST_ID, ACCT_ID, LAST_TX_DATE, PERSN_LEGAL_BK_CODE, TX_ORG, INSUR_AMT, PRDKT_ID, INSUR_BID_FORM_NO, POLICY_STATE)
VALUES ('C008', 'ACCT_I008', '20260801', 'BK01', 'ORG001', 5000, 'PRD_I008', 'BID008', '1');

COMMIT;

BEGIN DBMS_OUTPUT.PUT_LINE('Setup done: 15 customers, 3 in T-1 DTL, 12 in DWS'); END;
/

-- ============================================================
-- Phase 4: Execute DTL 20260801 (month begin)
-- ============================================================
DECLARE v_out INTEGER;
BEGIN PRC_ADS_CUST_SLEEP_WAKE_DTL('20260801', v_out); DBMS_OUTPUT.PUT_LINE('DTL return: '||v_out); END;
/

-- ============================================================
-- Phase 5: DTL Verification
-- ============================================================
DECLARE
  v_cnt INTEGER; v_wake CHAR(1); v_pass INTEGER:=0; v_fail INTEGER:=0;
  PROCEDURE ASSERT(p_name VARCHAR2, p_cond BOOLEAN) IS
  BEGIN
    IF p_cond THEN DBMS_OUTPUT.PUT_LINE('PASS: '||p_name); v_pass:=v_pass+1;
    ELSE DBMS_OUTPUT.PUT_LINE('FAIL: '||p_name); v_fail:=v_fail+1; END IF;
  END;
BEGIN
  DBMS_OUTPUT.PUT_LINE('=== DTL Assertions ===');

  SELECT COUNT(*) INTO v_cnt FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801';
  ASSERT('Total=8 (C002,C004,C005,C007,C008,C009,C010,C012)', v_cnt=8);

  -- Sleep detection
  SELECT COUNT(*) INTO v_cnt FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C002';
  ASSERT('C002 new sleep (AUM=50)', v_cnt=1);
  SELECT WAKE_STATE INTO v_wake FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C002';
  ASSERT('C002 WAKE=0', v_wake='0');

  SELECT COUNT(*) INTO v_cnt FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C001';
  ASSERT('C001 excluded (CUST_ID not in DWS)', v_cnt=0);

  SELECT COUNT(*) INTO v_cnt FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C003';
  ASSERT('C003 excluded (active txn via TMP_ACTIVE_TXN)', v_cnt=0);

  -- Wake by FIXD (account table driven)
  SELECT COUNT(*) INTO v_cnt FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C004';
  ASSERT('C004 in DTL (wake by FIXD ACCT_DEPO)', v_cnt=1);
  SELECT WAKE_STATE INTO v_wake FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C004';
  ASSERT('C004 WAKE=1 (INTRI_BGN_DATE in month)', v_wake='1');

  -- AUM edge cases
  SELECT COUNT(*) INTO v_cnt FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C005';
  ASSERT('C005 in DTL (AUM=99.99)', v_cnt=1);
  SELECT COUNT(*) INTO v_cnt FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C006';
  ASSERT('C006 excluded (AUM=100)', v_cnt=0);
  SELECT COUNT(*) INTO v_cnt FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C009';
  ASSERT('C009 in DTL (AUM=0.01)', v_cnt=1);

  -- Wake by FIN (account FIN ISSU_DATE)
  SELECT COUNT(*) INTO v_cnt FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C007';
  ASSERT('C007 in DTL (wake by FIN)', v_cnt=1);
  SELECT WAKE_STATE INTO v_wake FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C007';
  ASSERT('C007 WAKE=1', v_wake='1');

  -- Wake by INSUR (account INSUR LAST_TX_DATE)
  SELECT COUNT(*) INTO v_cnt FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C008';
  ASSERT('C008 in DTL (wake by INSUR)', v_cnt=1);
  SELECT WAKE_STATE INTO v_wake FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C008';
  ASSERT('C008 WAKE=1', v_wake='1');

  -- Month-begin review
  SELECT COUNT(*) INTO v_cnt FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C010';
  ASSERT('C010 kept (still sleep)', v_cnt=1);
  SELECT COUNT(*) INTO v_cnt FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C011';
  ASSERT('C011 removed (AUM>=100,no wake)', v_cnt=0);
  SELECT COUNT(*) INTO v_cnt FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C012';
  ASSERT('C012 kept (F-10 wake retention)', v_cnt=1);
  SELECT WAKE_STATE INTO v_wake FROM ADS_CUST_SLEEP_WAKE_DTL WHERE DATA_DATE='20260801' AND CUST_ID='C012';
  ASSERT('C012 WAKE=1', v_wake='1');

  DBMS_OUTPUT.PUT_LINE('Total: '||v_pass||' PASS / '||v_fail||' FAIL');
  IF v_fail > 0 THEN RAISE_APPLICATION_ERROR(-20001, 'FAILED'); END IF;
END;
/

-- ============================================================
-- Phase 6: Execute STATIS
-- ============================================================
DECLARE v_out INTEGER;
BEGIN PRC_ADS_CUST_SLEEP_WAKE_STATIS('20260801', v_out); DBMS_OUTPUT.PUT_LINE('STATIS return: '||v_out); END;
/

DECLARE
  v_total NUMBER; v_wake NUMBER; v_ctct NUMBER;
BEGIN
  SELECT SUM(CUST_CNT), SUM(WAKE_CUST_CNT), SUM(CNTCT_CUST_CNT)
    INTO v_total, v_wake, v_ctct
    FROM ADS_CUST_SLEEP_WAKE_STATIS WHERE DATA_DATE='20260801' AND STATIS_OBJ='ORG001';
  DBMS_OUTPUT.PUT_LINE('STATIS ORG001: total='||v_total||' wake='||v_wake||' ctct='||v_ctct);
  IF v_total=8 AND v_wake=4 AND v_ctct=0 THEN
    DBMS_OUTPUT.PUT_LINE('PASS: STATIS aggregation correct');
  ELSE
    DBMS_OUTPUT.PUT_LINE('FAIL: expected total=8 wake=4 ctct=0');
    RAISE_APPLICATION_ERROR(-20001, 'STATIS FAILED');
  END IF;
END;
/

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== ALL TESTS PASSED ===');
  DBMS_OUTPUT.PUT_LINE('v2.13.0 optimizations verified:');
  DBMS_OUTPUT.PUT_LINE('  O-01: TMP_ADS_SLEEP_ACTIVE_TXN (C003 excluded via TMP)');
  DBMS_OUTPUT.PUT_LINE('  O-02: Merged B+C (direct INSERT to BASE)');
  DBMS_OUTPUT.PUT_LINE('  O-03: Split D1+D2 (2 simple UPDATEs)');
  DBMS_OUTPUT.PUT_LINE('  O-04: TMP_ADS_SLEEP_ORG_HIER (STATIS pre-materialized)');
END;
/
