SET ECHO OFF
SET FEEDBACK OFF
SET HEADING OFF
SET PAGESIZE 0
SET LINESIZE 200
PROMPT === Existing tables ===
SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;
PROMPT === Existing procedures ===
SELECT OBJECT_NAME FROM USER_OBJECTS WHERE OBJECT_TYPE='PROCEDURE' ORDER BY OBJECT_NAME;
EXIT;
