SET ECHO OFF
SET FEEDBACK OFF
SET HEADING OFF
SET PAGESIZE 0
SET LINESIZE 200
-- Check sys_fun_deal_date
PROMPT === sys_fun_deal_date ===
SELECT OBJECT_NAME FROM USER_OBJECTS WHERE OBJECT_NAME='SYS_FUN_DEAL_DATE';
PROMPT === DWS_CUST_ASSE_LIAB sample ===
SELECT DATA_DATE, CUST_ID, PERSN_LEGAL_BK_CODE, BAL_TYPE, AUM_BAL, FIXD_DEPO_BAL, FIN_BAL, INSUR_BAL, ORG_ID FROM DWS_CUST_ASSE_LIAB WHERE ROWNUM <= 3;
PROMPT === DWD_CUST_INDV_INFO sample ===
SELECT CUST_ID, CUST_NAME, PERSN_LEGAL_BK_CODE, OPEN_DATE FROM DWD_CUST_INDV_INFO WHERE ROWNUM <= 3;
PROMPT === ADS_MKT_REC_INFO sample ===
SELECT CUST_ID, PERSN_LEGAL_BK_CODE, MKT_PERSN, MKT_TYP, MKT_TIME FROM ADS_MKT_REC_INFO WHERE ROWNUM <= 3;
PROMPT === DWD_TX_ASET sample ===
SELECT CUST_ID, PERSN_LEGAL_BK_CODE, TX_DATE, JIOYCFFS FROM DWD_TX_ASET WHERE ROWNUM <= 3;
EXIT;
