SET DEFINE OFF
CREATE OR REPLACE PROCEDURE PRC_ADS_CUST_SLEEP_WAKE_STATIS(
    V_SYSDAT IN VARCHAR,
    OUTCDE   OUT INTEGER
)
AS
  V_PRC_DESC             VARCHAR2(100) := 'sleep wake statis';
  V_PRC_NAME             VARCHAR2(64)  := 'PRC_ADS_CUST_SLEEP_WAKE_STATIS';
  V_LOG_MSG              VARCHAR2(4000);
  V_LOG_FLG              INTEGER;
  V_LOG_BUTTON           INTEGER := 1;
  V_NO_ID                VARCHAR2(10);
  V_BGN_DATE             DATE;
  V_END_DATE             DATE;
  V_DURA_DATE            INTEGER;
  V_DATA_DATE            VARCHAR2(8);
  V_HISTORY_CUTOFF_DATE  VARCHAR2(8);

  PROCEDURE TRUNC_TMP(P_TABLE_NAME VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || P_TABLE_NAME;
  END;

BEGIN
  V_NO_ID := 'TMP1';
  V_BGN_DATE := SYSDATE;

  IF V_SYSDAT IS NULL OR NOT REGEXP_LIKE(V_SYSDAT, '^[0-9]{8}$') THEN
    RAISE_APPLICATION_ERROR(-20001, 'V_SYSDAT must be YYYYMMDD');
  END IF;

  V_DATA_DATE := V_SYSDAT;
  V_HISTORY_CUTOFF_DATE := sys_fun_deal_date(V_SYSDAT, 19);

  DELETE FROM ADS_CUST_SLEEP_WAKE_STATIS s
   WHERE s.DATA_DATE = V_DATA_DATE;

  DELETE FROM ADS_CUST_SLEEP_WAKE_STATIS s
   WHERE s.DATA_DATE < V_HISTORY_CUTOFF_DATE;

  TRUNC_TMP('TMP_ADS_SLEEP_STAT_SRC');
  TRUNC_TMP('TMP_ADS_SLEEP_ORG_HIER');
  COMMIT;

  V_END_DATE := SYSDATE;
  V_DURA_DATE := TRUNC((V_END_DATE - V_BGN_DATE) * 24 * 60 * 60);
  OUTCDE := 0;
  V_LOG_MSG := 'TMP1: cleanup done';
  V_LOG_FLG := OUTCDE;
  SYS_PRC_STEP_LOGS(V_SYSDAT,V_PRC_NAME,V_PRC_DESC,V_NO_ID,
      V_BGN_DATE,V_END_DATE,V_DURA_DATE,V_LOG_MSG,V_LOG_FLG,V_LOG_BUTTON);

  V_NO_ID := 'TMP2';
  V_BGN_DATE := SYSDATE;

  INSERT INTO TMP_ADS_SLEEP_ORG_HIER (LEAF_ORG_ID, ANCESTOR_ORG_ID)
  SELECT DISTINCT
         CONNECT_BY_ROOT o.ORG_ID AS LEAF_ORG_ID,
         o.ORG_ID AS ANCESTOR_ORG_ID
    FROM DWD_SYS_ORG o
   START WITH o.ORG_ID IN (
         SELECT DISTINCT d1.ORG_ID
           FROM ADS_CUST_SLEEP_WAKE_DTL d1
          WHERE d1.DATA_DATE = V_DATA_DATE
            AND d1.ORG_ID IS NOT NULL
   )
 CONNECT BY NOCYCLE PRIOR o.SUP_ORG_ID = o.ORG_ID;
  COMMIT;

  INSERT INTO TMP_ADS_SLEEP_STAT_SRC (
      PERSN_LEGAL_BK_CODE, DATA_DATE, STATIS_CYCLE, STATIS_OBJ,
      CNTCT_STATE, WAKE_STATE
  )
  SELECT d.PERSN_LEGAL_BK_CODE,
         d.DATA_DATE,
         d.STATIS_CYCLE,
         o.ANCESTOR_ORG_ID,
         d.CNTCT_STATE,
         d.WAKE_STATE
    FROM ADS_CUST_SLEEP_WAKE_DTL d
    JOIN TMP_ADS_SLEEP_ORG_HIER o
      ON o.LEAF_ORG_ID = d.ORG_ID
   WHERE d.DATA_DATE = V_DATA_DATE

  UNION ALL

  SELECT d.PERSN_LEGAL_BK_CODE,
         d.DATA_DATE,
         d.STATIS_CYCLE,
         d.POST_ID,
         d.CNTCT_STATE,
         d.WAKE_STATE
    FROM ADS_CUST_SLEEP_WAKE_DTL d
   WHERE d.DATA_DATE = V_DATA_DATE
     AND d.POST_ID IS NOT NULL;
  COMMIT;

  V_END_DATE := SYSDATE;
  V_DURA_DATE := TRUNC((V_END_DATE - V_BGN_DATE) * 24 * 60 * 60);
  OUTCDE := 0;
  V_LOG_MSG := 'TMP2: org hier + dims done v2.12.0';
  V_LOG_FLG := OUTCDE;
  SYS_PRC_STEP_LOGS(V_SYSDAT,V_PRC_NAME,V_PRC_DESC,V_NO_ID,
      V_BGN_DATE,V_END_DATE,V_DURA_DATE,V_LOG_MSG,V_LOG_FLG,V_LOG_BUTTON);

  V_NO_ID := '3';
  V_BGN_DATE := SYSDATE;

  INSERT INTO ADS_CUST_SLEEP_WAKE_STATIS (
      PERSN_LEGAL_BK_CODE, DATA_DATE, STATIS_OBJ, STATIS_CYCLE,
      CUST_CNT, CNTCT_CUST_CNT, CNTCT_RATE,
      WAKE_CUST_CNT, WAKE_RATE
  )
  SELECT s.PERSN_LEGAL_BK_CODE,
         s.DATA_DATE,
         s.STATIS_OBJ,
         s.STATIS_CYCLE,
         COUNT(*) AS CUST_CNT,
         SUM(CASE WHEN s.CNTCT_STATE='1' THEN 1 ELSE 0 END) AS CNTCT,
         CASE WHEN COUNT(*)=0 THEN 0
              ELSE ROUND(SUM(CASE WHEN s.CNTCT_STATE='1' THEN 1 ELSE 0 END)/COUNT(*)*100,2)
         END AS CNTCT_RATE,
         SUM(CASE WHEN s.WAKE_STATE='1' THEN 1 ELSE 0 END) AS WAKE,
         CASE WHEN COUNT(*)=0 THEN 0
              ELSE ROUND(SUM(CASE WHEN s.WAKE_STATE='1' THEN 1 ELSE 0 END)/COUNT(*)*100,2)
         END AS WAKE_RATE
    FROM TMP_ADS_SLEEP_STAT_SRC s
   GROUP BY s.PERSN_LEGAL_BK_CODE, s.DATA_DATE, s.STATIS_OBJ, s.STATIS_CYCLE;
  COMMIT;

  V_END_DATE := SYSDATE;
  V_DURA_DATE := TRUNC((V_END_DATE - V_BGN_DATE) * 24 * 60 * 60);
  OUTCDE := 0;
  V_LOG_MSG := 'Step3: write sleep wake statis v2.12.0';
  V_LOG_FLG := OUTCDE;
  SYS_PRC_STEP_LOGS(V_SYSDAT,V_PRC_NAME,V_PRC_DESC,V_NO_ID,
      V_BGN_DATE,V_END_DATE,V_DURA_DATE,V_LOG_MSG,V_LOG_FLG,V_LOG_BUTTON);

EXCEPTION
  WHEN OTHERS THEN
    OUTCDE := -1;
    ROLLBACK;
    V_END_DATE := SYSDATE;
    V_DURA_DATE := CASE WHEN V_BGN_DATE IS NOT NULL AND V_END_DATE IS NOT NULL
                        THEN TRUNC((V_END_DATE - V_BGN_DATE) * 24 * 60 * 60) END;
    V_LOG_MSG := SUBSTR(SQLERRM, 1, 1000);
    V_LOG_FLG := OUTCDE;
    SYS_PRC_STEP_LOGS(V_SYSDAT,V_PRC_NAME,V_PRC_DESC,V_NO_ID,
        V_BGN_DATE,V_END_DATE,V_DURA_DATE,V_LOG_MSG,V_LOG_FLG,V_LOG_BUTTON);
    RAISE;
END;
/
