SET SERVEROUTPUT ON
SET PAGESIZE 300
SET LINESIZE 400
SET FEEDBACK ON

PROMPT ==== CALL PRC_ADS_CUST_DEADLINE_RMND_DTL(20260731) ====
VARIABLE rc NUMBER
EXEC PRC_ADS_CUST_DEADLINE_RMND_DTL('20260731', :rc)
PRINT :rc

PROMPT ==== CALL PRC_ADS_CUST_DEADLINE_RMND_ST(20260731) ====
EXEC PRC_ADS_CUST_DEADLINE_RMND_ST('20260731', :rc)
PRINT :rc

PROMPT ==== TMP_CDR_DTL_MATURE_SRC (maturity source) ====
SELECT CUST_ID, STATIS_TYP, ACCT_ID, EXPR_AMT,
       TO_CHAR(EXPR_DT,'YYYYMMDD') AS EXPR_DT, ORG_ID
  FROM TMP_CDR_DTL_MATURE_SRC
 ORDER BY CUST_ID, STATIS_TYP;

PROMPT ==== TMP_CDR_DTL_DUE_WIN (due window) ====
SELECT STAT_PERD, CUST_ID, STATIS_TYP,
       TO_CHAR(FIRST_EXPR_DT,'YYYYMMDD') AS FIRST_EXPR_DT,
       TO_CHAR(LAST_EXPR_DT,'YYYYMMDD') AS LAST_EXPR_DT,
       EXPR_AMT, MATURE_TTL_AMT,
       TO_CHAR(TAKE_END_DT_30D,'YYYYMMDD') AS TAKE_END_30D, ORG_ID
  FROM TMP_CDR_DTL_DUE_WIN
 ORDER BY CUST_ID, STATIS_TYP;

PROMPT ==== TMP_CDR_DTL_TAKE_AMT (take amount) ====
SELECT STAT_PERD, CUST_ID, STATIS_TYP, TAKE_AMT_30D,
       BUY_DEPO_AMT_30D, BUY_FIN_AMT_30D, BUY_INSUR_AMT_30D,
       TO_CHAR(FIRST_BUY_DT_30D,'YYYYMMDD') AS FIRST_BUY_DT
  FROM TMP_CDR_DTL_TAKE_AMT
 ORDER BY CUST_ID, STATIS_TYP;

PROMPT ==== ADS_CUST_DEADLINE_RMND_DTL (final detail) ====
SELECT PERSN_LEGAL_BK_CODE, DATA_DATE, CUST_ID, CUST_NAME, CUST_LVL,
       STAT_PERD, STATIS_TYP, EXPR_AMT, MATURE_TTL_AMT, TAKE_RATE,
       FIX_DEPO_MATURE_AMT, FIX_DEPO_MATURE_TTL_AMT, FIX_DEPO_TAKE_RATE,
       CNTCT_STATE, UNDTAKE_STATE,
       FIXED_FIN_TRAN_INSUR_AMT, FIN_MATURE_TRAN_FIXED_AMT, FIXED_MATURE_TRAN_FIN_AMT,
       FRST_MATURE_PK_BF_DAY_AUM_BAL, LAST_END_DATE, POST_ID, ORG_ID
  FROM ADS_CUST_DEADLINE_RMND_DTL
 ORDER BY CUST_ID, STATIS_TYP;

PROMPT ==== ADS_CUST_DEADLINE_RMND_STATIS (final statis) ====
SELECT PERSN_LEGAL_BK_CODE, DATA_DATE, STATIS_OBJ, STATIS_CYCLE, STATIS_TYP,
       EXPR_CUST_CNT, TTL_EXPR_CUST_CNT, EXPR_AMT, TTL_EXPR_AMT,
       CUST_UNDTAKE_RATE, ASSET_KEEP_RATE, ASSET_UNDTAKE_RATE,
       DEPO_TO_FIN_CONVRS_RATE, INSUR_CONVRS_RATE, FIN_TO_DEPO_CONVRS_RATE
  FROM ADS_CUST_DEADLINE_RMND_STATIS
 ORDER BY STATIS_OBJ, STATIS_CYCLE, STATIS_TYP;

PROMPT ==== SYS_PRC_STEP_LOG (step logs) ====
SELECT DATA_DATE, PRC_NAME, STEP_NO, LOG_FLG, LOG_MSG
  FROM SYS_PRC_STEP_LOG
 ORDER BY BGN_DATE;

EXIT
