-- ============================================================
-- Batch runner: 30 consecutive days + check days.
-- Each run archives detail rows and due-window rows so daily
-- progression can be asserted afterwards.
-- ============================================================
SET SERVEROUTPUT ON

-- Clear target tables first so no residual rows from earlier runs are archived.
TRUNCATE TABLE ADS_CUST_DEADLINE_RMND_DTL;
TRUNCATE TABLE ADS_CUST_DEADLINE_RMND_STATIS;

DROP TABLE TEST_RESULT_ARCHIVE;
CREATE TABLE TEST_RESULT_ARCHIVE (
  BATCH_DATE          VARCHAR2(8),
  CUST_ID             VARCHAR2(20),
  DATA_DATE           VARCHAR2(8),
  STAT_PERD           VARCHAR2(2),
  STATIS_TYP          VARCHAR2(2),
  EXPR_AMT            NUMBER(20,2),
  MATURE_TTL_AMT      NUMBER(20,2),
  TAKE_RATE           NUMBER(10,2),
  FIX_DEPO_TAKE_RATE  NUMBER(10,2),
  CNTCT_STATE         VARCHAR2(1),
  UNDTAKE_STATE       VARCHAR2(1),
  FIN_TRAN_FIXED      NUMBER(20,2),
  FIXED_TRAN_FIN      NUMBER(20,2),
  FRST_AUM            NUMBER(20,2),
  LAST_END_DATE       VARCHAR2(8),
  POST_ID             VARCHAR2(20),
  ORG_ID              VARCHAR2(7)
);

DROP TABLE TEST_WINDOW_ARCHIVE;
CREATE TABLE TEST_WINDOW_ARCHIVE (
  BATCH_DATE    VARCHAR2(8),
  CUST_ID       VARCHAR2(20),
  STAT_PERD     VARCHAR2(1),
  STATIS_TYP    VARCHAR2(1),
  FIRST_EXPR_DT VARCHAR2(8),
  LAST_EXPR_DT  VARCHAR2(8),
  TAKE_END_30D  VARCHAR2(8),
  EXPR_AMT      NUMBER(20,2),
  MATURE_TTL_AMT NUMBER(20,2)
);

-- ---------- 30 consecutive batch days ----------
DECLARE
  v_dt VARCHAR2(8);
  v_rc NUMBER;
BEGIN
  FOR i IN 0..29 LOOP
    v_dt := TO_CHAR(TO_DATE('20260601','YYYYMMDD') + i, 'YYYYMMDD');
    PRC_ADS_CUST_DEADLINE_RMND_DTL(v_dt, v_rc);
    IF v_rc <> 0 THEN DBMS_OUTPUT.PUT_LINE('DTL_FAIL '||v_dt||' rc='||v_rc); END IF;
    PRC_ADS_CUST_DEADLINE_RMND_ST(v_dt, v_rc);
    IF v_rc <> 0 THEN DBMS_OUTPUT.PUT_LINE('STATIS_FAIL '||v_dt||' rc='||v_rc); END IF;

    INSERT INTO TEST_RESULT_ARCHIVE
      (BATCH_DATE, CUST_ID, DATA_DATE, STAT_PERD, STATIS_TYP, EXPR_AMT, MATURE_TTL_AMT,
       TAKE_RATE, FIX_DEPO_TAKE_RATE, CNTCT_STATE, UNDTAKE_STATE,
       FIN_TRAN_FIXED, FIXED_TRAN_FIN, FRST_AUM, LAST_END_DATE, POST_ID, ORG_ID)
    SELECT v_dt, CUST_ID, DATA_DATE, STAT_PERD, STATIS_TYP, EXPR_AMT, MATURE_TTL_AMT,
           TAKE_RATE, FIX_DEPO_TAKE_RATE, CNTCT_STATE, UNDTAKE_STATE,
           FIN_MATURE_TRAN_FIXED_AMT, FIXED_MATURE_TRAN_FIN_AMT,
           FRST_MATURE_PK_BF_DAY_AUM_BAL, LAST_END_DATE, POST_ID, ORG_ID
      FROM ADS_CUST_DEADLINE_RMND_DTL;

    INSERT INTO TEST_WINDOW_ARCHIVE
      (BATCH_DATE, CUST_ID, STAT_PERD, STATIS_TYP, FIRST_EXPR_DT, LAST_EXPR_DT,
       TAKE_END_30D, EXPR_AMT, MATURE_TTL_AMT)
    SELECT v_dt, CUST_ID, STAT_PERD, STATIS_TYP,
           TO_CHAR(FIRST_EXPR_DT,'YYYYMMDD'), TO_CHAR(LAST_EXPR_DT,'YYYYMMDD'),
           TO_CHAR(TAKE_END_DT_30D,'YYYYMMDD'), EXPR_AMT, MATURE_TTL_AMT
      FROM TMP_CDR_DTL_DUE_WIN;
  END LOOP;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('BATCH30_DONE');
END;
/

-- ---------- check days ----------
DECLARE
  v_dt VARCHAR2(8);
  v_rc NUMBER;
BEGIN
  FOR v_dt IN (SELECT '20260705' dt FROM dual UNION ALL SELECT '20260731' FROM dual UNION ALL
               SELECT '20260930' FROM dual UNION ALL SELECT '20261231' FROM dual) LOOP
    PRC_ADS_CUST_DEADLINE_RMND_DTL(v_dt.dt, v_rc);
    IF v_rc <> 0 THEN DBMS_OUTPUT.PUT_LINE('DTL_FAIL '||v_dt.dt||' rc='||v_rc); END IF;
    PRC_ADS_CUST_DEADLINE_RMND_ST(v_dt.dt, v_rc);
    IF v_rc <> 0 THEN DBMS_OUTPUT.PUT_LINE('STATIS_FAIL '||v_dt.dt||' rc='||v_rc); END IF;

    INSERT INTO TEST_RESULT_ARCHIVE
      (BATCH_DATE, CUST_ID, DATA_DATE, STAT_PERD, STATIS_TYP, EXPR_AMT, MATURE_TTL_AMT,
       TAKE_RATE, FIX_DEPO_TAKE_RATE, CNTCT_STATE, UNDTAKE_STATE,
       FIN_TRAN_FIXED, FIXED_TRAN_FIN, FRST_AUM, LAST_END_DATE, POST_ID, ORG_ID)
    SELECT v_dt.dt, CUST_ID, DATA_DATE, STAT_PERD, STATIS_TYP, EXPR_AMT, MATURE_TTL_AMT,
           TAKE_RATE, FIX_DEPO_TAKE_RATE, CNTCT_STATE, UNDTAKE_STATE,
           FIN_MATURE_TRAN_FIXED_AMT, FIXED_MATURE_TRAN_FIN_AMT,
           FRST_MATURE_PK_BF_DAY_AUM_BAL, LAST_END_DATE, POST_ID, ORG_ID
      FROM ADS_CUST_DEADLINE_RMND_DTL;

    INSERT INTO TEST_WINDOW_ARCHIVE
      (BATCH_DATE, CUST_ID, STAT_PERD, STATIS_TYP, FIRST_EXPR_DT, LAST_EXPR_DT,
       TAKE_END_30D, EXPR_AMT, MATURE_TTL_AMT)
    SELECT v_dt.dt, CUST_ID, STAT_PERD, STATIS_TYP,
           TO_CHAR(FIRST_EXPR_DT,'YYYYMMDD'), TO_CHAR(LAST_EXPR_DT,'YYYYMMDD'),
           TO_CHAR(TAKE_END_DT_30D,'YYYYMMDD'), EXPR_AMT, MATURE_TTL_AMT
      FROM TMP_CDR_DTL_DUE_WIN;
  END LOOP;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('CHECKDAYS_DONE');
END;
/

EXIT
