-- ============================================================
-- Requirement-by-requirement assertions (memory card v2.14.0)
-- PASS/FAIL markers + evidence queries.
-- ============================================================
SET PAGESIZE 300
SET LINESIZE 300

PROMPT ================= A1 EXPR_AMT cutoff must be V_SYSDAT (rule 12) ================
-- C10 maturities 06-05/10/15; on batch 06-01 none has matured yet.
-- Expected EXPR_AMT=0 on 06-01; implementation uses SYSDATE => 230000.
SELECT CASE WHEN (SELECT EXPR_AMT FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260601' AND CUST_ID='C10'
                     AND STAT_PERD='M' AND STATIS_TYP='1') = 0
            THEN 'PASS' ELSE 'FAIL' END AS A1_M0601_CUTOFF,
       (SELECT EXPR_AMT FROM TEST_RESULT_ARCHIVE
         WHERE BATCH_DATE='20260601' AND CUST_ID='C10'
           AND STAT_PERD='M' AND STATIS_TYP='1') AS ACTUAL_EXPR_AMT
  FROM dual;

PROMPT -- C10 M-slice EXPR_AMT progression across 30 batch days (expected step-up 06-05/06-10/06-15)
SELECT BATCH_DATE, EXPR_AMT, MATURE_TTL_AMT
  FROM TEST_RESULT_ARCHIVE
 WHERE CUST_ID='C10' AND STAT_PERD='M' AND STATIS_TYP='1'
 ORDER BY BATCH_DATE;

PROMPT ================= A2 Maturity window calculation (rules 4/9/16) ================
PROMPT -- C10: 06-05/10/15 no next maturity -> TAKE_END = 06-15+30 = 07-15
SELECT CASE WHEN (SELECT TAKE_END_30D FROM TEST_WINDOW_ARCHIVE
                   WHERE BATCH_DATE='20260630' AND CUST_ID='C10'
                     AND STAT_PERD='M' AND STATIS_TYP='1') = '20260715'
            THEN 'PASS' ELSE 'FAIL' END AS A2_C10_WINDOW,
       (SELECT TAKE_END_30D FROM TEST_WINDOW_ARCHIVE
         WHERE BATCH_DATE='20260630' AND CUST_ID='C10'
           AND STAT_PERD='M' AND STATIS_TYP='1') AS C10_TAKE_END
  FROM dual;
PROMPT -- C11: next maturity 07-05 inside +30 -> TAKE_END = 07-04
SELECT CASE WHEN (SELECT TAKE_END_30D FROM TEST_WINDOW_ARCHIVE
                   WHERE BATCH_DATE='20260630' AND CUST_ID='C11'
                     AND STAT_PERD='M' AND STATIS_TYP='1') = '20260704'
            THEN 'PASS' ELSE 'FAIL' END AS A2_C11_WINDOW,
       (SELECT TAKE_END_30D FROM TEST_WINDOW_ARCHIVE
         WHERE BATCH_DATE='20260630' AND CUST_ID='C11'
           AND STAT_PERD='M' AND STATIS_TYP='1') AS C11_TAKE_END
  FROM dual;

PROMPT ================= A3 Purchase inside window incl. cross-period (rule 26) ================
PROMPT -- C10 batch 06-30 M: TAKE = 60000+20000+30000=110000, insur 40000 excluded -> TAKE_RATE 47.83
SELECT CASE WHEN (SELECT TAKE_RATE FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260630' AND CUST_ID='C10'
                     AND STAT_PERD='M' AND STATIS_TYP='1') = 47.83
            THEN 'PASS' ELSE 'FAIL' END AS A3_C10_TAKE_RATE,
       (SELECT TAKE_RATE FROM TEST_RESULT_ARCHIVE
         WHERE BATCH_DATE='20260630' AND CUST_ID='C10'
           AND STAT_PERD='M' AND STATIS_TYP='1') AS C10_RATE
  FROM dual;
PROMPT -- C11 batch 06-30: purchase 07-03 in window (40k) vs 07-05 out (30k) -> 40.00
SELECT CASE WHEN (SELECT TAKE_RATE FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260630' AND CUST_ID='C11'
                     AND STAT_PERD='M' AND STATIS_TYP='1') = 40
            THEN 'PASS' ELSE 'FAIL' END AS A3_C11_TAKE_RATE,
       (SELECT TAKE_RATE FROM TEST_RESULT_ARCHIVE
         WHERE BATCH_DATE='20260630' AND CUST_ID='C11'
           AND STAT_PERD='M' AND STATIS_TYP='1') AS C11_RATE
  FROM dual;
PROMPT -- C12 batch 07-05: maturity 06-28, purchase 07-05 counts into June slice -> 75.00
SELECT CASE WHEN (SELECT TAKE_RATE FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260705' AND CUST_ID='C12'
                     AND STAT_PERD='M' AND STATIS_TYP='1') = 75
            THEN 'PASS' ELSE 'FAIL' END AS A3_C12_CROSS_PERIOD,
       (SELECT TAKE_RATE FROM TEST_RESULT_ARCHIVE
         WHERE BATCH_DATE='20260705' AND CUST_ID='C12'
           AND STAT_PERD='M' AND STATIS_TYP='1') AS C12_RATE
  FROM dual;

PROMPT ================= A4 Month/Quarter/Year slice consistency (C13, batch 06-30) ================
SELECT STAT_PERD, EXPR_AMT, MATURE_TTL_AMT
  FROM TEST_RESULT_ARCHIVE
 WHERE BATCH_DATE='20260630' AND CUST_ID='C13' AND STATIS_TYP='1'
 ORDER BY STAT_PERD;
PROMPT -- expected: M=100000/100000 ; Q=200000/200000 ; Y=200000/400000
SELECT CASE WHEN (SELECT COUNT(*) FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260630' AND CUST_ID='C13' AND STATIS_TYP='1'
                     AND ((STAT_PERD='M' AND EXPR_AMT=100000 AND MATURE_TTL_AMT=100000)
                       OR (STAT_PERD='Q' AND EXPR_AMT=200000 AND MATURE_TTL_AMT=200000)
                       OR (STAT_PERD='Y' AND EXPR_AMT=200000 AND MATURE_TTL_AMT=400000))) = 3
            THEN 'PASS' ELSE 'FAIL' END AS A4_MQY_CONSISTENCY
  FROM dual;

PROMPT ================= A5 Contact state cutoff must be V_SYSDAT (rule 21/30) ================
-- C12 batch 07-05: MKT_TIME=07-20 > V_SYSDAT but inside window 06-28..07-28
-- expected CNTCT_STATE=0, implementation only checks window -> 1
SELECT CASE WHEN (SELECT CNTCT_STATE FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260705' AND CUST_ID='C12'
                     AND STAT_PERD='M' AND STATIS_TYP='1') = '0'
            THEN 'PASS' ELSE 'FAIL' END AS A5_CNTCT_CUTOFF,
       (SELECT CNTCT_STATE FROM TEST_RESULT_ARCHIVE
         WHERE BATCH_DATE='20260705' AND CUST_ID='C12'
           AND STAT_PERD='M' AND STATIS_TYP='1') AS C12_CNTCT
  FROM dual;
PROMPT -- C10 batch 06-30: in-window record -> CNTCT=1
SELECT CASE WHEN (SELECT CNTCT_STATE FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260630' AND CUST_ID='C10'
                     AND STAT_PERD='M' AND STATIS_TYP='1') = '1'
            THEN 'PASS' ELSE 'FAIL' END AS A5_C10_CNTCT
  FROM dual;

PROMPT ================= A6 NULL handling (rules 20/24) ================
PROMPT -- C15: DP151 BAL NULL -> 0 + DP153 30000; CUST_NAME NULL; POST NULL; CNTCT=1
SELECT a.CUST_ID, c.CUST_NAME, a.EXPR_AMT, a.MATURE_TTL_AMT, a.FRST_AUM, a.POST_ID, a.ORG_ID, a.CNTCT_STATE
  FROM TEST_RESULT_ARCHIVE a
  LEFT JOIN DWD_CUST_INDV_INFO c ON c.CUST_ID = a.CUST_ID
 WHERE a.BATCH_DATE='20260630' AND a.CUST_ID='C15'
   AND a.STAT_PERD='M' AND a.STATIS_TYP='1'
 ORDER BY a.STAT_PERD, a.STATIS_TYP;

PROMPT ================= A7 Abnormal values (C16) ================
SELECT CUST_ID, STAT_PERD, STATIS_TYP, EXPR_AMT, MATURE_TTL_AMT
  FROM TEST_RESULT_ARCHIVE
 WHERE BATCH_DATE='20260630' AND CUST_ID='C16'
 ORDER BY STAT_PERD, STATIS_TYP;

PROMPT ================= A8 Filter rules (C18: notice 04, open finance 1/3) ================
SELECT CUST_ID, STATIS_TYP, EXPR_AMT, MATURE_TTL_AMT
  FROM TEST_RESULT_ARCHIVE
 WHERE BATCH_DATE='20260630' AND CUST_ID='C18'
 ORDER BY STATIS_TYP;

PROMPT ================= A9 Boundary dates (C17: 06-01/06-30/03-31 maturities) ================
SELECT STAT_PERD, EXPR_AMT, MATURE_TTL_AMT, TAKE_RATE, CNTCT_STATE
  FROM TEST_RESULT_ARCHIVE
 WHERE BATCH_DATE='20260630' AND CUST_ID='C17' AND STATIS_TYP='1'
 ORDER BY STAT_PERD;

PROMPT ================= A10 Statis rollup sanity (batch 06-30, M) ================
SELECT STATIS_OBJ, STATIS_TYP, EXPR_CUST_CNT, TTL_EXPR_CUST_CNT, EXPR_AMT, TTL_EXPR_AMT, CUST_UNDTAKE_RATE
  FROM ADS_CUST_DEADLINE_RMND_STATIS
 WHERE DATA_DATE='20260630' AND STATIS_CYCLE='M'
 ORDER BY STATIS_OBJ, STATIS_TYP;

PROMPT ================= A13 Cross-period aggregation defect probes (C17) ================
PROMPT -- Q1 slice (DATA_DATE=20260331) must have TAKE_RATE=0 (no purchase inside 03-31..04-30)
SELECT CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS A13_Q1_NO_DUP,
       COUNT(*) AS Q1_ROW_CNT
  FROM TEST_RESULT_ARCHIVE
 WHERE BATCH_DATE='20260630' AND CUST_ID='C17' AND STAT_PERD='Q'
   AND DATA_DATE='20260331' AND STATIS_TYP='1';
SELECT TAKE_RATE AS Q1_TAKE_RATE_ACTUAL
  FROM TEST_RESULT_ARCHIVE
 WHERE BATCH_DATE='20260630' AND CUST_ID='C17' AND STAT_PERD='Q'
   AND DATA_DATE='20260331' AND STATIS_TYP='1'
   AND ROWNUM = 1;
PROMPT -- expected: 1 row, TAKE_RATE=0 (window 03-31..04-30 has no purchase)
PROMPT -- actual defects: duplicate rows (AUM_BAL join w/o DATA_DATE) and
PROMPT -- wrong 70 (TAKE_AMT aggregated by STAT_PERD merges Q1/Q2)

PROMPT ================= A11 Statis cross-check vs detail (ORG100 M0) ================
SELECT CASE WHEN (SELECT EXPR_CUST_CNT FROM ADS_CUST_DEADLINE_RMND_STATIS
                   WHERE DATA_DATE='20260630' AND STATIS_CYCLE='M'
                     AND STATIS_OBJ='ORG100' AND STATIS_TYP='0') =
              (SELECT COUNT(DISTINCT CUST_ID) FROM TEST_RESULT_ARCHIVE
                WHERE BATCH_DATE='20260630' AND STAT_PERD='M' AND STATIS_TYP='0'
                  AND ORG_ID IN ('ORG100','ORG101') AND EXPR_AMT > 0)
            THEN 'PASS' ELSE 'FAIL' END AS A11_ROLLUP_CONSISTENT
  FROM dual;

PROMPT ================= A12 Date function across month/quarter/year boundaries ================
SELECT SYS_FUN_DEAL_DATE('20260630',2) AS PREV_MONTH_END,
       SYS_FUN_DEAL_DATE('20260630',3) AS PREV_Q_END,
       SYS_FUN_DEAL_DATE('20260630',4) AS PREV_Y_END,
       SYS_FUN_DEAL_DATE('20260630',10) AS CURR_MONTH_END,
       SYS_FUN_DEAL_DATE('20260630',12) AS CURR_Q_END,
       SYS_FUN_DEAL_DATE('20260630',14) AS CURR_Y_END,
       SYS_FUN_DEAL_DATE('20260101',1) AS PREV_DAY_0101
  FROM dual;

EXIT
