-- ============================================================
-- Slice independence validation (natural month/quarter/year)
-- Uses archived results from 06_run_batches.sql.
-- ============================================================
SET PAGESIZE 200
SET LINESIZE 300

PROMPT ============ S1 Natural month slices (C13, batch 06-30) ============
PROMPT -- M slice must contain ONLY June maturities (06-15, 100000), DATA_DATE=20260630
SELECT STAT_PERD, DATA_DATE, STATIS_TYP, EXPR_AMT, MATURE_TTL_AMT
  FROM TEST_RESULT_ARCHIVE
 WHERE BATCH_DATE='20260630' AND CUST_ID='C13' AND STAT_PERD='M'
 ORDER BY STATIS_TYP;
SELECT CASE WHEN (SELECT COUNT(*) FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260630' AND CUST_ID='C13' AND STAT_PERD='M') = 2
             AND (SELECT COUNT(*) FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260630' AND CUST_ID='C13' AND STAT_PERD='M'
                     AND DATA_DATE='20260630' AND EXPR_AMT=100000) = 2
            THEN 'PASS' ELSE 'FAIL' END AS S1_M_NATURAL_MONTH
  FROM dual;

PROMPT ============ S2 Natural quarter slices (C13, batch 09-30) ============
PROMPT -- Q3 (current) contains only 09-15; Q2 (previous) contains 04-15+06-15
SELECT STAT_PERD, DATA_DATE, STATIS_TYP, EXPR_AMT, MATURE_TTL_AMT
  FROM TEST_RESULT_ARCHIVE
 WHERE BATCH_DATE='20260930' AND CUST_ID='C13' AND STAT_PERD='Q'
 ORDER BY DATA_DATE, STATIS_TYP;
SELECT CASE WHEN (SELECT COUNT(*) FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260930' AND CUST_ID='C13' AND STAT_PERD='Q'
                     AND DATA_DATE='20260930' AND EXPR_AMT=100000) = 2
             AND (SELECT COUNT(*) FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260930' AND CUST_ID='C13' AND STAT_PERD='Q'
                     AND DATA_DATE='20260630' AND EXPR_AMT=200000) = 2
            THEN 'PASS' ELSE 'FAIL' END AS S2_Q_NATURAL_QUARTER
  FROM dual;

PROMPT ============ S3 Natural year slice (C13, batch 12-31) ============
PROMPT -- Y slice contains all four maturities; EXPR_AMT=400000 proves DEFECT-004 fix
SELECT STAT_PERD, DATA_DATE, STATIS_TYP, EXPR_AMT, MATURE_TTL_AMT
  FROM TEST_RESULT_ARCHIVE
 WHERE BATCH_DATE='20261231' AND CUST_ID='C13' AND STAT_PERD='Y'
 ORDER BY STATIS_TYP;
SELECT CASE WHEN (SELECT EXPR_AMT FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20261231' AND CUST_ID='C13'
                     AND STAT_PERD='Y' AND STATIS_TYP='1') = 400000
            THEN 'PASS' ELSE 'FAIL' END AS S3_Y_NATURAL_YEAR
  FROM dual;

PROMPT ============ S4 Previous/current period independence (C12, batch 07-05) ============
PROMPT -- June M (previous) has TAKE_RATE=75; July M (current) must have NO row for C12
SELECT STAT_PERD, DATA_DATE, STATIS_TYP, EXPR_AMT, TAKE_RATE
  FROM TEST_RESULT_ARCHIVE
 WHERE BATCH_DATE='20260705' AND CUST_ID='C12' AND STAT_PERD='M'
 ORDER BY DATA_DATE, STATIS_TYP;
SELECT CASE WHEN (SELECT COUNT(*) FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260705' AND CUST_ID='C12' AND STAT_PERD='M'
                     AND DATA_DATE='20260731') = 0
             AND (SELECT COUNT(*) FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260705' AND CUST_ID='C12' AND STAT_PERD='M'
                     AND DATA_DATE='20260630' AND TAKE_RATE=75) = 2
            THEN 'PASS' ELSE 'FAIL' END AS S4_PERIOD_INDEPENDENCE
  FROM dual;

PROMPT ============ S5 Period-end dates (DATA_DATE semantics) ============
PROMPT -- M=month end, Q=quarter end, Y=year end
SELECT CASE WHEN (SELECT MAX(DATA_DATE) FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260630' AND CUST_ID='C13' AND STAT_PERD='M') = '20260630'
             AND (SELECT MAX(DATA_DATE) FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260630' AND CUST_ID='C13' AND STAT_PERD='Q') = '20260630'
             AND (SELECT MAX(DATA_DATE) FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260630' AND CUST_ID='C13' AND STAT_PERD='Y') = '20261231'
            THEN 'PASS' ELSE 'FAIL' END AS S5_PERIOD_END_DATES
  FROM dual;

EXIT
