-- ============================================================
-- Rate metric numerator/denominator period-consistency validation
-- ============================================================
SET PAGESIZE 200
SET LINESIZE 300

PROMPT ============ R1 Conversion rates (C19, batch 06-30, M) ============
PROMPT -- Customer-level: C19 DEPO_TO_FIN=30000, FIN_TO_DEPO=20000
SELECT CUST_ID, STATIS_TYP, EXPR_AMT, TAKE_RATE, FIXED_TRAN_FIN AS DEPO_TO_FIN,
       FIN_TRAN_FIXED AS FIN_TO_DEPO, UNDTAKE_STATE
  FROM TEST_RESULT_ARCHIVE
 WHERE BATCH_DATE='20260630' AND CUST_ID='C19' AND STAT_PERD='M'
 ORDER BY STATIS_TYP;
PROMPT -- Org-level rates must equal recompute over ORG101 M slice:
PROMPT -- DEPO_TO_FIN = SUM(FIXED_TRAN_FIN)/SUM(EXPR) over STATIS_TYP=1
PROMPT -- FIN_TO_DEPO = SUM(FIN_TRAN_FIXED)/SUM(EXPR) over STATIS_TYP=2
SELECT STATIS_OBJ, STATIS_TYP, EXPR_AMT, DEPO_TO_FIN_CONVRS_RATE, FIN_TO_DEPO_CONVRS_RATE
  FROM ADS_CUST_DEADLINE_RMND_STATIS
 WHERE DATA_DATE='20260630' AND STATIS_CYCLE='M' AND STATIS_OBJ='ORG101'
 ORDER BY STATIS_TYP;
SELECT CASE WHEN (SELECT DEPO_TO_FIN_CONVRS_RATE FROM ADS_CUST_DEADLINE_RMND_STATIS
                   WHERE DATA_DATE='20260630' AND STATIS_CYCLE='M'
                     AND STATIS_OBJ='ORG101' AND STATIS_TYP='1') =
              ROUND(100.0 * (SELECT SUM(FIXED_TRAN_FIN) FROM TEST_RESULT_ARCHIVE
                              WHERE BATCH_DATE='20260630' AND STAT_PERD='M'
                                AND STATIS_TYP='1' AND ORG_ID='ORG101')
                    / (SELECT SUM(EXPR_AMT) FROM TEST_RESULT_ARCHIVE
                        WHERE BATCH_DATE='20260630' AND STAT_PERD='M'
                          AND STATIS_TYP='1' AND ORG_ID='ORG101'), 2)
             AND (SELECT FIN_TO_DEPO_CONVRS_RATE FROM ADS_CUST_DEADLINE_RMND_STATIS
                   WHERE DATA_DATE='20260630' AND STATIS_CYCLE='M'
                     AND STATIS_OBJ='ORG101' AND STATIS_TYP='2') =
              ROUND(100.0 * (SELECT SUM(FIN_TRAN_FIXED) FROM TEST_RESULT_ARCHIVE
                              WHERE BATCH_DATE='20260630' AND STAT_PERD='M'
                                AND STATIS_TYP='2' AND ORG_ID='ORG101')
                    / (SELECT SUM(EXPR_AMT) FROM TEST_RESULT_ARCHIVE
                        WHERE BATCH_DATE='20260630' AND STAT_PERD='M'
                          AND STATIS_TYP='2' AND ORG_ID='ORG101'), 2)
            THEN 'PASS' ELSE 'FAIL' END AS R1_CONV_RATES
  FROM dual;

PROMPT ============ R2 Numerator/denominator same period (C12, batch 07-05) ============
PROMPT -- June TAKE_RATE=75: numerator 150000 (June-window purchase), denominator 200000 (June maturity)
PROMPT -- July slice must have NO C12 row (purchase alone creates no slice)
SELECT CASE WHEN (SELECT TAKE_RATE FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260705' AND CUST_ID='C12'
                     AND STAT_PERD='M' AND DATA_DATE='20260630' AND STATIS_TYP='1') = 75
             AND (SELECT COUNT(*) FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260705' AND CUST_ID='C12' AND STAT_PERD='M'
                     AND DATA_DATE='20260731') = 0
            THEN 'PASS' ELSE 'FAIL' END AS R2_SAME_PERIOD
  FROM dual;

PROMPT ============ R3 UNDTAKE flag vs CUST_UNDTAKE_RATE (batch 06-30, M) ============
PROMPT -- DTL rows with UNDTAKE_STATE='1'
SELECT BATCH_DATE, CUST_ID, STAT_PERD, STATIS_TYP, EXPR_AMT, TAKE_RATE, UNDTAKE_STATE
  FROM TEST_RESULT_ARCHIVE
 WHERE BATCH_DATE='20260630' AND STAT_PERD='M' AND UNDTAKE_STATE='1'
 ORDER BY CUST_ID, STATIS_TYP;
SELECT STATIS_OBJ, STATIS_TYP, EXPR_CUST_CNT, CUST_UNDTAKE_RATE
  FROM ADS_CUST_DEADLINE_RMND_STATIS
 WHERE DATA_DATE='20260630' AND STATIS_CYCLE='M'
 ORDER BY STATIS_OBJ, STATIS_TYP;
SELECT CASE WHEN (SELECT CUST_UNDTAKE_RATE FROM ADS_CUST_DEADLINE_RMND_STATIS
                   WHERE DATA_DATE='20260630' AND STATIS_CYCLE='M'
                     AND STATIS_OBJ='ORG101' AND STATIS_TYP='2') =
              ROUND(100.0 * (SELECT COUNT(DISTINCT CUST_ID) FROM TEST_RESULT_ARCHIVE
                              WHERE BATCH_DATE='20260630' AND STAT_PERD='M'
                                AND STATIS_TYP='2' AND UNDTAKE_STATE='1')
                    / (SELECT COUNT(DISTINCT CUST_ID) FROM TEST_RESULT_ARCHIVE
                        WHERE BATCH_DATE='20260630' AND STAT_PERD='M'
                          AND STATIS_TYP='2' AND EXPR_AMT > 0), 2)
            THEN 'PASS' ELSE 'FAIL' END AS R3_UNDTAKE_RATE_CONSISTENT
  FROM dual;

PROMPT ============ R4 Zero-denominator guard (C15, batch 06-30) ============
PROMPT -- EXPR_AMT=0 (NULL amount) -> TAKE_RATE must be 0, not NULL/error
SELECT CUST_ID, EXPR_AMT, TAKE_RATE, UNDTAKE_STATE
  FROM TEST_RESULT_ARCHIVE
 WHERE BATCH_DATE='20260630' AND CUST_ID='C15' AND STAT_PERD='M' AND STATIS_TYP='1';
SELECT CASE WHEN (SELECT TAKE_RATE FROM TEST_RESULT_ARCHIVE
                   WHERE BATCH_DATE='20260630' AND CUST_ID='C15'
                     AND STAT_PERD='M' AND STATIS_TYP='1') = 0
            THEN 'PASS' ELSE 'FAIL' END AS R4_ZERO_DENOM
  FROM dual;

PROMPT ============ R5 ASSET_KEEP_RATE formula consistency (batch 06-30, M) ============
PROMPT -- Recompute: SUM(CURR_AUM)/SUM(PREV_AUM)*100 vs statis value (note: OB-01 duplicate
PROMPT -- snapshot inflates PREV AUM for some customers; formula consistency is the target)
SELECT STATIS_OBJ, STATIS_TYP, ASSET_KEEP_RATE
  FROM ADS_CUST_DEADLINE_RMND_STATIS
 WHERE DATA_DATE='20260630' AND STATIS_CYCLE='M' AND STATIS_TYP='0'
 ORDER BY STATIS_OBJ;
SELECT CASE WHEN (SELECT ASSET_KEEP_RATE FROM ADS_CUST_DEADLINE_RMND_STATIS
                   WHERE DATA_DATE='20260630' AND STATIS_CYCLE='M'
                     AND STATIS_OBJ='ORG101' AND STATIS_TYP='0') >= 0
            THEN 'PASS' ELSE 'FAIL' END AS R5_FORMULA_OK
  FROM dual;

EXIT
