-- ============================================================
-- Performance: DTL + STATIS under 10k / 30k / 50k customers
-- ============================================================
SET SERVEROUTPUT ON
SET PAGESIZE 200

DECLARE
  v_rc   NUMBER;
  v_t1   NUMBER;
  v_t2   NUMBER;
  v_dtl  NUMBER;
  v_stat NUMBER;
  v_d0   NUMBER;
  v_s0   NUMBER;
  v_batch VARCHAR2(8) := '20260630';
BEGIN
  FOR rec IN (SELECT 10000 AS n FROM dual UNION ALL
              SELECT 30000 FROM dual UNION ALL
              SELECT 50000 FROM dual) LOOP
    EXECUTE IMMEDIATE 'TRUNCATE TABLE DWD_CUST_INDV_INFO';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE DWS_CUST_LVL_INFO';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE DWD_CUST_MAN';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE DWS_CUST_ASSE_LIAB';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE DWD_ACCT_DEPO';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE ADS_CUST_DEADLINE_RMND_DTL';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE ADS_CUST_DEADLINE_RMND_STATIS';

    EXECUTE IMMEDIATE
      'INSERT INTO DWD_SYS_ORG(ORG_ID,SUP_ORG_ID,ORG_NAME,ORG_STATE,PERSN_LEGAL_BK_CODE) SELECT ''ORG100'',NULL,''R'',''1'',''BK10'' FROM dual';
    EXECUTE IMMEDIATE
      'INSERT INTO DWD_CUST_INDV_INFO(CUST_ID,CUST_NAME,CUST_TYP,PERSN_LEGAL_BK_CODE,ORG_LEAD)
       SELECT ''PERF''||LPAD(LEVEL,8,''0''),''C''||LEVEL,''1'',''BK10'',''ORG100'' FROM dual CONNECT BY LEVEL <= '||rec.n;
    EXECUTE IMMEDIATE
      'INSERT INTO DWS_CUST_LVL_INFO(DATA_DATE,CUST_ID,CUST_LVL,PERSN_LEGAL_BK_CODE)
       SELECT ''20260630'',''PERF''||LPAD(LEVEL,8,''0''),''1'',''BK10'' FROM dual CONNECT BY LEVEL <= '||rec.n;
    EXECUTE IMMEDIATE
      'INSERT INTO DWD_CUST_MAN(CUST_ID,MNGR_POST_ID,ORG_ID,MNG_TYP,VALID_DATE,PERSN_LEGAL_BK_CODE)
       SELECT ''PERF''||LPAD(LEVEL,8,''0''),''PM100'',''ORG100'',''1'',''20260630'',''BK10'' FROM dual CONNECT BY LEVEL <= '||rec.n;
    EXECUTE IMMEDIATE
      'INSERT INTO DWS_CUST_ASSE_LIAB(DATA_DATE,PERSN_LEGAL_BK_CODE,CUST_ID,ORG_ID,BAL_TYPE,AUM_BAL,DEPO_BAL,DEPO_CURNT_DEPO_BAL,FIXD_DEPO_BAL,FIN_BAL)
       SELECT ''20260630'',''BK10'',''PERF''||LPAD(LEVEL,8,''0''),''ORG100'',''1'',500000,300000,50000,250000,100000 FROM dual CONNECT BY LEVEL <= '||rec.n;
    EXECUTE IMMEDIATE
      'INSERT INTO DWS_CUST_ASSE_LIAB(DATA_DATE,PERSN_LEGAL_BK_CODE,CUST_ID,ORG_ID,BAL_TYPE,AUM_BAL)
       SELECT ''20260619'',''BK10'',''PERF''||LPAD(LEVEL,8,''0''),''ORG100'',''1'',450000 FROM dual CONNECT BY LEVEL <= '||rec.n;
    -- maturity + purchase accounts
    EXECUTE IMMEDIATE
      'INSERT INTO DWD_ACCT_DEPO(CUST_ID,ACCT_ID,PRDKT_ID,PRDKT_NAME,PRDKT_CATE_BIG,BAL,OPEN_ACCT_ORG,INTRI_BGN_DATE,EXPR_DATE,ACCT_STATE,PERSN_LEGAL_BK_CODE,FIX_CURNT_FLG)
       SELECT ''PERF''||LPAD(LEVEL,8,''0''),''A''||LEVEL,''P1'',''FD'',''01'',100000,''ORG100'',''2025-12-20'',''2026-06-20'',''1'',''BK10'',''1'' FROM dual CONNECT BY LEVEL <= '||rec.n;
    EXECUTE IMMEDIATE
      'INSERT INTO DWD_ACCT_DEPO(CUST_ID,ACCT_ID,PRDKT_ID,PRDKT_NAME,PRDKT_CATE_BIG,BAL,OPEN_ACCT_ORG,INTRI_BGN_DATE,EXPR_DATE,ACCT_STATE,PERSN_LEGAL_BK_CODE,FIX_CURNT_FLG)
       SELECT ''PERF''||LPAD(LEVEL,8,''0''),''B''||LEVEL,''P2'',''FD2'',''01'',90000,''ORG100'',''2026-06-25'',''2027-06-25'',''1'',''BK10'',''1'' FROM dual CONNECT BY LEVEL <= '||rec.n;

    v_t1 := DBMS_UTILITY.GET_TIME;
    PRC_ADS_CUST_DEADLINE_RMND_DTL(v_batch, v_rc);
    v_t2 := DBMS_UTILITY.GET_TIME;
    v_dtl := (v_t2 - v_t1) / 100;

    v_t1 := DBMS_UTILITY.GET_TIME;
    PRC_ADS_CUST_DEADLINE_RMND_ST(v_batch, v_rc);
    v_t2 := DBMS_UTILITY.GET_TIME;
    v_stat := (v_t2 - v_t1) / 100;

    SELECT COUNT(*) INTO v_d0 FROM ADS_CUST_DEADLINE_RMND_DTL;
    SELECT COUNT(*) INTO v_s0 FROM ADS_CUST_DEADLINE_RMND_STATIS;
    DBMS_OUTPUT.PUT_LINE('N='||rec.n||' | DTL_SEC='||ROUND(v_dtl,2)||
                         ' | STATIS_SEC='||ROUND(v_stat,2)||
                         ' | DTL_ROWS='||v_d0||' | STATIS_ROWS='||v_s0);
  END LOOP;
END;
/

EXIT
