-- ============================================================
-- Full-row equivalence check for PRC_DWD_ACCT_INSUR v3.3.0.
--
-- Phase A: before deploying v3.3.0, run the BASELINE section after the
--          pre-optimization process has completed for the same source data.
-- Phase B: deploy v3.3.0, run it with the same V_SYSDAT, then run the
--          CANDIDATE section. Both MINUS counts must be zero.
-- ============================================================
SET SERVEROUTPUT ON
SET PAGESIZE 200

-- ======================= BASELINE ===========================
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TMP_DWD_ACCT_INSUR_BASELINE PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE TMP_DWD_ACCT_INSUR_BASELINE AS
SELECT
    CUST_ID, CUST_TYP, ACCT_ID, PRDKT_ID, PRDKT_NAME, PRDKT_CATE_BIG,
    INSUR_BID_FORM_NO, TX_DATE, LAST_TX_DATE, TX_ORG, TX_CHNL, MKT_ORG,
    BGN_INSUR_DATE, CANCL_INSUR_DATE, ACTL_TERM_DATE, PAY_UPTO_DATE,
    INSUR_PERIOD_TYP, INSUR_PERIOD, PAY_PERIOD_TYP, PAY_PERIOD, PAY_PATRN,
    NEW_INSUR_AMT, INSUR_AMT, POLICY_STATE, TX_TYP, PERSN_LEGAL_BK_CODE
FROM DWD_ACCT_INSUR;

SELECT COUNT(*) AS BASELINE_ROW_COUNT
FROM TMP_DWD_ACCT_INSUR_BASELINE;

-- ======================= CANDIDATE ==========================
-- Deploy v3.3.0 and execute:
-- VARIABLE rc NUMBER
-- EXEC PRC_DWD_ACCT_INSUR('20260803', :rc)
-- PRINT :rc

SELECT COUNT(*) AS BASELINE_MINUS_CANDIDATE
FROM (
    SELECT
        CUST_ID, CUST_TYP, ACCT_ID, PRDKT_ID, PRDKT_NAME, PRDKT_CATE_BIG,
        INSUR_BID_FORM_NO, TX_DATE, LAST_TX_DATE, TX_ORG, TX_CHNL, MKT_ORG,
        BGN_INSUR_DATE, CANCL_INSUR_DATE, ACTL_TERM_DATE, PAY_UPTO_DATE,
        INSUR_PERIOD_TYP, INSUR_PERIOD, PAY_PERIOD_TYP, PAY_PERIOD, PAY_PATRN,
        NEW_INSUR_AMT, INSUR_AMT, POLICY_STATE, TX_TYP, PERSN_LEGAL_BK_CODE
    FROM TMP_DWD_ACCT_INSUR_BASELINE
    MINUS
    SELECT
        CUST_ID, CUST_TYP, ACCT_ID, PRDKT_ID, PRDKT_NAME, PRDKT_CATE_BIG,
        INSUR_BID_FORM_NO, TX_DATE, LAST_TX_DATE, TX_ORG, TX_CHNL, MKT_ORG,
        BGN_INSUR_DATE, CANCL_INSUR_DATE, ACTL_TERM_DATE, PAY_UPTO_DATE,
        INSUR_PERIOD_TYP, INSUR_PERIOD, PAY_PERIOD_TYP, PAY_PERIOD, PAY_PATRN,
        NEW_INSUR_AMT, INSUR_AMT, POLICY_STATE, TX_TYP, PERSN_LEGAL_BK_CODE
    FROM DWD_ACCT_INSUR
);

SELECT COUNT(*) AS CANDIDATE_MINUS_BASELINE
FROM (
    SELECT
        CUST_ID, CUST_TYP, ACCT_ID, PRDKT_ID, PRDKT_NAME, PRDKT_CATE_BIG,
        INSUR_BID_FORM_NO, TX_DATE, LAST_TX_DATE, TX_ORG, TX_CHNL, MKT_ORG,
        BGN_INSUR_DATE, CANCL_INSUR_DATE, ACTL_TERM_DATE, PAY_UPTO_DATE,
        INSUR_PERIOD_TYP, INSUR_PERIOD, PAY_PERIOD_TYP, PAY_PERIOD, PAY_PATRN,
        NEW_INSUR_AMT, INSUR_AMT, POLICY_STATE, TX_TYP, PERSN_LEGAL_BK_CODE
    FROM DWD_ACCT_INSUR
    MINUS
    SELECT
        CUST_ID, CUST_TYP, ACCT_ID, PRDKT_ID, PRDKT_NAME, PRDKT_CATE_BIG,
        INSUR_BID_FORM_NO, TX_DATE, LAST_TX_DATE, TX_ORG, TX_CHNL, MKT_ORG,
        BGN_INSUR_DATE, CANCL_INSUR_DATE, ACTL_TERM_DATE, PAY_UPTO_DATE,
        INSUR_PERIOD_TYP, INSUR_PERIOD, PAY_PERIOD_TYP, PAY_PERIOD, PAY_PATRN,
        NEW_INSUR_AMT, INSUR_AMT, POLICY_STATE, TX_TYP, PERSN_LEGAL_BK_CODE
    FROM TMP_DWD_ACCT_INSUR_BASELINE
);

EXIT
