-- ============================================================
-- Regression: ACCEPT_DATE and latest successful payment date.
-- Prerequisite: run 01_setup_tables.sql and deploy PRC_DWD_ACCT_INSUR.sql.
-- ============================================================
TRUNCATE TABLE YBT_YBT_POLICY_BASE_INFO;
TRUNCATE TABLE YBT_YBT_POLICY_FEE_LIST;
TRUNCATE TABLE IBP_IB_LIST_PLAT;
TRUNCATE TABLE YBT_YBT_POLICY_INSURANCE_INFO;
TRUNCATE TABLE YBT_YBT_PRODUCT_INFO;
TRUNCATE TABLE DWD_ACCT_INSUR;

INSERT INTO YBT_YBT_PRODUCT_INFO (PRODUCT_ID, PRODUCT_NAME, PRODUCT_BIG_TYPE)
VALUES ('P001', 'Life', '01');

INSERT INTO YBT_YBT_POLICY_BASE_INFO (
    PLAT_POLICY_SERIAL, ITEM_ID, CONT_NO, PROPOSAL_PRT_NO, ACCEPT_DATE,
    VALI_DATE, PRODUCT_ID, PRODUCT_NAME, CONT_STATUS, CONT_SOURCE, ACC_NO, THROW_COM
) VALUES (
    'PL001', '104001', 'C001', 'B001', '20260110',
    '20260110', 'P001', 'Life', '1', '0', 'ACCT01', '150000000001'
);

INSERT INTO YBT_YBT_POLICY_INSURANCE_INFO (
    PLAT_POLICY_SERIAL, PAY_TYPE, PAY_PER_UNIT, PAY_PER_NUM, VALID_PER_UNIT, VALID_PER_NUM
) VALUES ('PL001', '1', '12', 10, '12', 20);

-- C001 has two successful payments and one later failed order.
INSERT ALL
  INTO YBT_YBT_POLICY_FEE_LIST (
      PLAT_POLICY_SERIAL, ORD_AMT, ORD_PAY_SERIAL, ORD_CREATE_DATE, TRAN_TYPE, ORD_TRAN_STATUS
  ) VALUES ('PL001', 10000, 'ORD001', '20260110', '0', '2')
  INTO YBT_YBT_POLICY_FEE_LIST (
      PLAT_POLICY_SERIAL, ORD_AMT, ORD_PAY_SERIAL, ORD_CREATE_DATE, TRAN_TYPE, ORD_TRAN_STATUS
  ) VALUES ('PL001', 10000, 'ORD002', '20260301', '1', '2')
  INTO YBT_YBT_POLICY_FEE_LIST (
      PLAT_POLICY_SERIAL, ORD_AMT, ORD_PAY_SERIAL, ORD_CREATE_DATE, TRAN_TYPE, ORD_TRAN_STATUS
  ) VALUES ('PL001', 10000, 'ORD003', '20260401', '1', '3')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO IBP_IB_LIST_PLAT (PLAT_SERIAL, PLAT_DATE, PLAT_TRAD_STATUS, USER_ID, TRAN_DATE)
  VALUES ('ORD001', '20260110', '2', '100000000001', '20260110')
  INTO IBP_IB_LIST_PLAT (PLAT_SERIAL, PLAT_DATE, PLAT_TRAD_STATUS, USER_ID, TRAN_DATE)
  VALUES ('ORD002', '20260301', '2', '100000000001', '20260301')
  INTO IBP_IB_LIST_PLAT (PLAT_SERIAL, PLAT_DATE, PLAT_TRAD_STATUS, USER_ID, TRAN_DATE)
  VALUES ('ORD003', '20260401', '2', '100000000001', '20260401')
SELECT 1 FROM DUAL;

VARIABLE rc NUMBER
EXEC PRC_DWD_ACCT_INSUR('20260803', :rc)
PRINT :rc

SELECT CASE
           WHEN (SELECT TX_DATE FROM DWD_ACCT_INSUR WHERE INSUR_BID_FORM_NO = 'C001') = '20260110'
            AND (SELECT LAST_TX_DATE FROM DWD_ACCT_INSUR WHERE INSUR_BID_FORM_NO = 'C001') = '20260301'
           THEN 'PASS'
           ELSE 'FAIL'
       END AS TX_DATE_REGRESSION
FROM DUAL;

EXIT
