WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MBK_CUST_INFO';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE <> -942 THEN RAISE; END IF;
END;
/
CREATE TABLE MBK_CUST_INFO (
    CUST_NO VARCHAR2(32) NOT NULL,
    CERT_ID VARCHAR2(64) NULL,
    INCORP_NO VARCHAR2(16) NULL,
    CUST_CORE_NO VARCHAR2(16) NULL,
    CUST_NAME VARCHAR2(64) NULL,
    CUST_CERT_TYPE VARCHAR2(6) NULL,
    CUST_CERT_NO VARCHAR2(80) NULL,
    CUST_MOBILE VARCHAR2(11) NOT NULL,
    CUST_LGN_NAME VARCHAR2(32) NULL,
    CUST_CAP_LVL VARCHAR2(2) NOT NULL,
    CUST_IS_IDTFY_VERIFY CHAR(1) NOT NULL,
    CUST_ORG_NO VARCHAR2(16) NULL,
    CUST_OPEN_DATE VARCHAR2(10) NOT NULL,
    CUST_OPEN_TIME VARCHAR2(8) NOT NULL,
    CUST_OPEN_CHNL VARCHAR2(3) NOT NULL,
    CUST_STATUS CHAR(1) NOT NULL,
    CUST_FREEZE_DATE VARCHAR2(10) NULL,
    CUST_FREEZE_TIME VARCHAR2(8) NULL,
    CUST_CLOSE_DATE VARCHAR2(10) NULL,
    CUST_CLOSE_TIME VARCHAR2(8) NULL,
    CUST_IDTFY_VERIFY_NUM VARCHAR2(10) NULL,
    CUST_IS_OLD CHAR(1) NULL,
    CUST_OLD_PASSWORD CHAR(1) NULL,
    ENCRYPT_TYPE CHAR(1) NULL,
    IS_FIRST VARCHAR2(1) NULL,
    USER_LAST_LOGIN_DATE VARCHAR2(10) NULL,
    RYZD VARCHAR2(1) NULL,
    CONSTRAINT PK_MBK_CUST_INFO PRIMARY KEY (CUST_NO)
);
EXIT SUCCESS
