WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET DEFINE OFF
SET SERVEROUTPUT ON
BEGIN
  FOR x IN (SELECT object_name, object_type FROM user_objects WHERE object_name IN (
    'ADS_STAT_INDX_RULE','ADS_STAT_INDX_DATA','ADS_STAT_INDX_BASELINE_MEMBER','ADS_STAT_INDX_BASELINE_DTL','ADS_STAT_INDX_BASELINE_SUM','TMP_STAT_INDX_SCOPE','TMP_STAT_INDX_BAL_AGGR','TMP_STAT_INDX_CUST_STATE','TMP_STAT_INDX_AGGR','TMP_STAT_INDX_AGGR_A','TMP_STAT_INDX_AGGR_B','DWD_MKT_ACT_INFO','DWD_MKT_ACT_TARGT','DWD_MKT_TSK_INFO','DWD_MKT_INDX_TSK','DWD_MKT_TSK_INDX_SUB','DWS_CUST_LVL_INFO','DWD_CUST_MAN','DWS_CUST_ASSE_LIAB','DWD_CUST_INDV_INFO','DWD_ACCT_FIN','DWD_ACCT_INSUR','DWD_ACCT_DEPO','MBK_CUST_INFO','MBK_CUST_LOG_LOGIN','CRM_SYS_POST','UEPP_PAY_MCT_INFO','UEPP_PAY_ORDER_INFO','UEPP_PAY_MCT_SETTLE_ACCOUNT','DEPO_VALUE_INIT','CRM_SYS_POST','SYS_PRC_STEP_LOGS_DUMMY')) LOOP
    BEGIN EXECUTE IMMEDIATE 'DROP ' || x.object_type || ' ' || x.object_name; EXCEPTION WHEN OTHERS THEN NULL; END;
  END LOOP;
END;
/
CREATE TABLE TMP_STAT_INDX_SCOPE (path_code VARCHAR2(1), statis_dim VARCHAR2(100), indx_code VARCHAR2(100), data_blng VARCHAR2(100), blng_type VARCHAR2(1), blng_id VARCHAR2(40), term_begin_date VARCHAR2(8), persn_legal_bk_code VARCHAR2(30));
CREATE TABLE TMP_STAT_INDX_BAL_AGGR (path_code VARCHAR2(1), statis_dim VARCHAR2(100), data_blng VARCHAR2(100), persn_legal_bk_code VARCHAR2(30), curnt_aum NUMBER, yr_begin_aum NUMBER, mth_end_aum NUMBER, qrt_end_aum NUMBER, curnt_yr_avg_aum NUMBER, prev_yr_avg_aum NUMBER, curnt_mth_avg_aum NUMBER, prev_mth_avg_aum NUMBER);
CREATE TABLE TMP_STAT_INDX_CUST_STATE (path_code VARCHAR2(1), statis_dim VARCHAR2(100), indx_code VARCHAR2(100), data_blng VARCHAR2(100), cust_id VARCHAR2(20), persn_legal_bk_code VARCHAR2(30), base_cust_lvl VARCHAR2(2), curnt_cust_lvl VARCHAR2(2), base_mth_avg_aum NUMBER, curnt_mth_avg_aum NUMBER);
CREATE TABLE TMP_STAT_INDX_AGGR (path_code VARCHAR2(1), data_date VARCHAR2(8), data_blng VARCHAR2(100), statis_dim VARCHAR2(100), statis_calib VARCHAR2(100), indx_code VARCHAR2(100), curnt_val NUMBER, term_last_val NUMBER, persn_legal_bk_code VARCHAR2(30));
CREATE TABLE ADS_STAT_INDX_DATA (data_date VARCHAR2(8), data_blng VARCHAR2(100), statis_dim VARCHAR2(100), statis_calib VARCHAR2(100), indx_code VARCHAR2(100), curnt_val NUMBER, term_last_val NUMBER, persn_legal_bk_code VARCHAR2(30));
CREATE TABLE ADS_STAT_INDX_BASELINE_MEMBER (statis_calib VARCHAR2(100), statis_dim VARCHAR2(100), data_blng VARCHAR2(100), cust_id VARCHAR2(20), persn_legal_bk_code VARCHAR2(30), base_data_date VARCHAR2(8), base_run_date VARCHAR2(8));
CREATE TABLE ADS_STAT_INDX_BASELINE_DTL (statis_calib VARCHAR2(100), statis_dim VARCHAR2(100), indx_code VARCHAR2(100), data_blng VARCHAR2(100), cust_id VARCHAR2(20), persn_legal_bk_code VARCHAR2(30), base_data_date VARCHAR2(8), base_run_date VARCHAR2(8), base_cust_lvl VARCHAR2(2), base_mth_avg_aum NUMBER);
CREATE TABLE ADS_STAT_INDX_BASELINE_SUM (statis_calib VARCHAR2(100), statis_dim VARCHAR2(100), indx_code VARCHAR2(100), data_blng VARCHAR2(100), persn_legal_bk_code VARCHAR2(30), base_data_date VARCHAR2(8), base_run_date VARCHAR2(8), base_loan_bal NUMBER, base_yr_avg_fin NUMBER, base_mth_avg_fin NUMBER, base_yr_avg_agen_fin NUMBER, base_mth_avg_agen_fin NUMBER);
CREATE TABLE ADS_STAT_INDX_RULE (indx_code VARCHAR2(100) PRIMARY KEY, indx_name VARCHAR2(200), calc_class VARCHAR2(30), is_enabled CHAR(1), effective_bgn_date VARCHAR2(8), effective_end_date VARCHAR2(8), stat_unit VARCHAR2(20), sort_no NUMBER, remark VARCHAR2(1000));
-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\dwd\dwd_mkt_act_info.sql
CREATE TABLE DWD_MKT_ACT_INFO (
    MKT_ACT_ID VARCHAR2(4000) NULL,
    CAMP_ACT_NAME VARCHAR2(4000) NULL,
    CAMP_ACT_TYP VARCHAR2(4000) NULL,
    ACT_BGN_DATE VARCHAR2(4000) NULL,
    ACT_END_DATE VARCHAR2(4000) NULL,
    ACT_DSC VARCHAR2(4000) NULL,
    CREAT_TIME VARCHAR2(4000) NULL,
    CREATOR VARCHAR2(4000) NULL,
    CREAT_ORG VARCHAR2(4000) NULL,
    ACT_STATE VARCHAR2(4000) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR2(4000) NULL,
    APPRVR VARCHAR2(4000) NULL,
    APPRV_TIME DATE NULL,
    APPRV_ORG VARCHAR2(4000) NULL,
    STATIS_STOP_DATE VARCHAR2(4000) NULL
);
/

-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\dwd\dwd_mkt_act_targt.sql
CREATE TABLE DWD_MKT_ACT_TARGT (
    PK_ID VARCHAR2(4000) NULL,
    MKT_ACT_ID VARCHAR2(4000) NULL,
    PRTSPT_ORG VARCHAR2(4000) NULL,
    INDX_ID VARCHAR2(4000) NULL,
    INDX_VAL NUMBER NULL
);
/

-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\dwd\dwd_mkt_tsk_info.sql
CREATE TABLE DWD_MKT_TSK_INFO (
    MKT_TSK_ID VARCHAR2(4000) NULL,
    MKT_ACT_ID VARCHAR2(4000) NULL,
    CUST_ID VARCHAR2(4000) NULL,
    CUST_NAME VARCHAR2(4000) NULL,
    COVER_FLG VARCHAR2(4000) NULL,
    CONVRS_FLG VARCHAR2(4000) NULL,
    MKT_PERSN VARCHAR2(4000) NULL,
    MKT_PERSN_ORG VARCHAR2(4000) NULL,
    CREATR VARCHAR2(4000) NULL,
    CREAT_TIME VARCHAR2(4000) NULL,
    CREAT_ORG VARCHAR2(4000) NULL,
    BASE_VAL NUMBER NULL,
    CURNT_VAL NUMBER NULL,
    DATA_DATE VARCHAR2(4000) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR2(4000) NULL,
    ACT_DSC VARCHAR2(4000) NULL
);
/

-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\dwd\dwd_mkt_indx_tsk.sql
CREATE TABLE DWD_MKT_INDX_TSK (
    TSK_ID VARCHAR2(4000) NULL,
    SUP_TSK_ID VARCHAR2(4000) NULL,
    MAIN_TSK_ID VARCHAR2(4000) NULL,
    TSK_TITL VARCHAR2(4000) NULL,
    TSK_ALOKT_TYP VARCHAR2(4000) NULL,
    TSK_INF VARCHAR2(4000) NULL,
    TSK_BGN_DATE VARCHAR2(4000) NULL,
    TSK_END_DATE VARCHAR2(4000) NULL,
    TSK_NEXT_SEND_TYP VARCHAR2(4000) NULL,
    RSV_OBJ VARCHAR2(4000) NULL,
    RSV_OBJ_ID VARCHAR2(4000) NULL,
    TSK_APDIX_ID VARCHAR2(4000) NULL,
    CREATR VARCHAR2(4000) NULL,
    CREAT_ORG VARCHAR2(4000) NULL,
    CREAT_TIME VARCHAR2(4000) NULL,
    TSK_NEXT_SEND_TIME VARCHAR2(4000) NULL,
    TSK_STATE VARCHAR2(4000) NULL,
    TSK_TYP VARCHAR2(4000) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR2(4000) NULL,
    RSV_OBJ_NAME VARCHAR2(4000) NULL,
    BIZ_LINE VARCHAR2(4000) NULL,
    TSK_YEAR VARCHAR2(4000) NULL
);
/

-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\dwd\dwd_mkt_tsk_indx_sub.sql
CREATE TABLE DWD_MKT_TSK_INDX_SUB (
    TSK_INDX_ID VARCHAR2(40) NULL,
    TSK_ID VARCHAR2(40) NULL,
    MAIN_TSK_ID VARCHAR2(40) NULL,
    INDX_ID VARCHAR2(40) NULL,
    TSK_DSC VARCHAR2(500) NULL,
    TSK_BGN_DATE VARCHAR2(10) NULL,
    TSK_END_DATE VARCHAR2(10) NULL,
    INDX_UNIT VARCHAR2(6) NULL,
    INDX_VAL NUMBER(22) NULL,
    INDX_VAL_ADD NUMBER(22) NULL,
    BASE_VAL NUMBER(22) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR2(30) NULL
);
/

-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\dws\dws_cust_lvl_info.sql
CREATE TABLE DWS_CUST_LVL_INFO (
    PERSN_LEGAL_BK_CODE VARCHAR2(7) NULL,
    DATA_DATE VARCHAR2(8) NOT NULL,
    CUST_ID VARCHAR2(20) NOT NULL,
    CUST_LVL VARCHAR2(2) NOT NULL,
    ORG_ID VARCHAR2(8) NULL,
    CUST_HRAKY VARCHAR2(2) NULL
);
/

-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\dwd\dwd_cust_man.sql
CREATE TABLE DWD_CUST_MAN (
    CUST_ID VARCHAR2(4000) NOT NULL,
    MNGR_POST_ID VARCHAR2(4000) NOT NULL,
    ORG_ID VARCHAR2(4000) NOT NULL,
    MNG_TYP VARCHAR2(4000) NOT NULL,
    MODF_TIME VARCHAR2(4000) NOT NULL,
    MODF_TYP VARCHAR2(4000) NULL,
    DATA_SRC VARCHAR2(4000) NULL,
    VALID_DATE VARCHAR2(4000) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR2(4000) NULL
);
/

-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\dws\dws_cust_asse_liab.sql
CREATE TABLE DWS_CUST_ASSE_LIAB (
    DATA_DATE VARCHAR2(8) NOT NULL,
    CUST_ID VARCHAR2(20) NOT NULL,
    ORG_ID VARCHAR2(7) NOT NULL,
    ORG_ID_LOAN VARCHAR2(6) NULL,
    BAL_TYPE CHAR(1) NOT NULL,
    AUM_BAL NUMBER(20,2) NULL,
    DEPO_BAL NUMBER(20,2) NULL,
    DEPO_CURNT_DEPO_BAL NUMBER(20,2) NULL,
    FIXD_DEPO_BAL NUMBER(20,2) NULL,
    LEHUI_BAL NUMBER(20,2) NULL,
    LARGEDP_BAL NUMBER(20,2) NULL,
    FIN_BAL NUMBER(20,2) NULL,
    CLOSE_AGEN_FIN_BAL NUMBER(20,2) NULL,
    OPEN_AGEN_FIN_BAL NUMBER(20,2) NULL,
    CLOSE_SELF_FIN_BAL NUMBER(20,2) NULL,
    OPEN_SELF_FIN_BAL NUMBER(20,2) NULL,
    INSUR_BAL NUMBER(20,2) NULL,
    LOAN_BAL NUMBER(20,2) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR2(7) NULL
);
/

-- SOURCE DDL: DWD_ACCT_FIN（0057/0060 理财产品销量回归最小字段集）
CREATE TABLE DWD_ACCT_FIN (
    CUST_ID VARCHAR2(20) NOT NULL,
    CUST_TYP VARCHAR2(2) NOT NULL,
    ACCT_ID VARCHAR2(40) NOT NULL,
    CARD_NO VARCHAR2(30) NOT NULL,
    PRDKT_ID VARCHAR2(40) NOT NULL,
    PRDKT_NAME VARCHAR2(100) NULL,
    PRDKT_CATE_BIG VARCHAR2(64) NULL,
    ESTAB_DATE VARCHAR2(10) NULL,
    FIN_AMT NUMBER(20,2) NULL,
    RATE_INTRI NUMBER(20,2) NULL,
    ACCT_STATE VARCHAR2(10) NULL,
    INTRI_BGN_DATE VARCHAR2(10) NULL,
    EXPR_DATE VARCHAR2(10) NULL,
    OPRT_ORG VARCHAR2(7) NULL,
    CHNL_NO VARCHAR2(10) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR2(4) NULL,
    ISSU_ORG VARCHAR2(6) NULL,
    ISSU_DATE VARCHAR2(10) NULL,
    RISK_LVL VARCHAR2(2) NULL,
    CFM_AMT NUMBER(20,2) NULL
);
/

-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\dwd\dwd_cust_indv_info.sql
CREATE TABLE DWD_CUST_INDV_INFO (
    CUST_ID VARCHAR2(20) NOT NULL,
    CUST_NAME VARCHAR2(100) NULL,
    CERT_TYP VARCHAR2(6) NULL,
    CERT_ID VARCHAR2(32) NULL,
    CERT_PRD_VLID VARCHAR2(10) NULL,
    CERT_PRD_VLID_END VARCHAR2(10) NULL,
    CERT_ISSUING VARCHAR2(100) NULL,
    CERT_ISSUING_AUTHORITY VARCHAR2(100) NULL,
    CUST_TYP VARCHAR2(2) NULL,
    OPEN_DATE VARCHAR2(10) NULL,
    OPEN_ORG VARCHAR2(20) NULL,
    NATIONALITY VARCHAR2(6) NULL,
    NATION VARCHAR2(6) NULL,
    MARI_SITU VARCHAR2(6) NULL,
    MAX_DEG_EDU VARCHAR2(6) NULL,
    NOW_ENTER VARCHAR2(120) NULL,
    OCCU_CLS VARCHAR2(6) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR2(4) NOT NULL,
    GEND VARCHAR2(2) NULL,
    PHONE_NO VARCHAR2(20) NULL,
    CONTACT_ADDRESS VARCHAR2(254) NULL,
    CONTACT_ADDRESS_DETAIL VARCHAR2(254) NULL,
    ID_ADDRESS VARCHAR2(254) NULL,
    ID_ADDRESS_DETAIL VARCHAR2(254) NULL,
    HOME_ADDRESS VARCHAR2(254) NULL,
    HOME_ADDRESS_DETAIL VARCHAR2(254) NULL,
    RESIDENCE_ADDRESS VARCHAR2(254) NULL,
    RESIDENCE_ADDRESS_DETAIL VARCHAR2(254) NULL,
    OFFICE_ADDRESS VARCHAR2(254) NULL,
    OFFICE_ADDRESS_DETAIL VARCHAR2(254) NULL,
    HOST_CUST_MNGR_POST_ID VARCHAR2(20) NULL,
    HOST_CUST_MNGR_NAME VARCHAR2(60) NULL,
    HOST_CUST_MNGR_EMP_ID VARCHAR2(6) NULL,
    ORG_LEAD VARCHAR2(7) NULL,
    ORG_LEAD_PATH VARCHAR2(50) NULL,
    COSPSR_CUST_MNGR_POST_ID VARCHAR2(20) NULL,
    COSPSR_CUST_MNGR_NAME VARCHAR2(60) NULL,
    COSPSR_CUST_MNGR_EMP_ID VARCHAR2(6) NULL,
    COSPSR_ORG VARCHAR2(7) NULL,
    COSPSR_ORG_PATH VARCHAR2(50) NULL
);
/

-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\dwd\dwd_acct_insur.sql
CREATE TABLE DWD_ACCT_INSUR (
    CUST_ID VARCHAR2(20) NOT NULL,
    CUST_TYP VARCHAR2(4) NULL,
    ACCT_ID VARCHAR2(40) NOT NULL,
    PRDKT_ID VARCHAR2(40) NOT NULL,
    PRDKT_NAME VARCHAR2(100) NULL,
    PRDKT_CATE_BIG VARCHAR2(64) NULL,
    INSUR_BID_FORM_NO VARCHAR2(40) NOT NULL,
    TX_DATE VARCHAR2(8) NULL,
    TX_ORG VARCHAR2(7) NULL,
    TX_CHNL VARCHAR2(10) NULL,
    MKT_ORG VARCHAR2(7) NULL,
    BGN_INSUR_DATE VARCHAR2(10) NULL,
    CANCL_INSUR_DATE VARCHAR2(10) NULL,
    PAY_UPTO_DATE VARCHAR2(8) NULL,
    INSUR_PERIOD_TYP VARCHAR2(2) NULL,
    INSUR_PERIOD VARCHAR2(6) NULL,
    PAY_PERIOD_TYP VARCHAR2(2) NULL,
    PAY_PERIOD VARCHAR2(6) NULL,
    PAY_PATRN VARCHAR2(2) NULL,
    INSUR_AMT NUMBER(20,2) NULL,
    POLICY_STATE VARCHAR2(8) NOT NULL,
    TX_TYP VARCHAR2(1) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR2(4) NULL,
    LAST_TX_DATE VARCHAR2(8) NULL,
    ACTL_TERM_DATE VARCHAR2(8) NULL,
    NEW_INSUR_AMT NUMBER(20,2) NULL
);
/

-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\dwd\dwd_acct_depo.sql
CREATE TABLE DWD_ACCT_DEPO (
    CUST_ID VARCHAR2(20) NOT NULL,
    CUST_TYP VARCHAR2(2) NULL,
    ACCT_ID VARCHAR2(40) NULL,
    CARD_NO VARCHAR2(40) NULL,
    PRDKT_ID VARCHAR2(30) NULL,
    PRDKT_NAME VARCHAR2(200) NULL,
    PRDKT_CATE_BIG VARCHAR2(64) NULL,
    ACCT_TYP VARCHAR2(10) NULL,
    CCY_CD VARCHAR2(4) NULL,
    BAL NUMBER(20,2) NULL,
    RMB_BAL NUMBER(20,2) NULL,
    OPEN_ACCT_ORG VARCHAR2(6) NULL,
    OPEN_DATE VARCHAR2(10) NULL,
    RATE_INTRI NUMBER(20,2) NULL,
    INTRI_BGN_DATE VARCHAR2(10) NULL,
    EXPR_DATE VARCHAR2(10) NULL,
    ACCT_CLOZ_DATE VARCHAR2(10) NULL,
    ACCT_STATE VARCHAR2(10) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR2(4) NULL,
    VCHR_TYP VARCHAR2(10) NULL,
    CUNQ VARCHAR2(10) NULL,
    FIX_CURNT_FLG VARCHAR2(1) NULL
);
/

-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\ods\mbk\mbk_cust_info.sql
CREATE TABLE MBK_CUST_INFO (
    CUST_NO VARCHAR2(32) NOT NULL,
    CERT_ID VARCHAR2(64) NULL,
    INCORP_NO VARCHAR2(16) NULL,
    CUST_CORE_NO VARCHAR2(16) NULL,
    CUST_NAME VARCHAR2(64) NULL,
    CUST_CERT_TYPE VARCHAR2(6) NULL,
    CUST_CERT_NO VARCHAR2(80) NULL,
    CUST_MOBILE VARCHAR2(11) NOT NULL,
    CUST_LGN_NAME VARCHAR2(32) NULL,
    CUST_CAP_LVL VARCHAR2(2) NOT NULL,
    CUST_IS_IDTFY_VERIFY CHAR(1) NOT NULL,
    CUST_ORG_NO VARCHAR2(16) NULL,
    CUST_OPEN_DATE VARCHAR2(10) NOT NULL,
    CUST_OPEN_TIME VARCHAR2(8) NOT NULL,
    CUST_OPEN_CHNL VARCHAR2(3) NOT NULL,
    CUST_STATUS CHAR(1) NOT NULL,
    CUST_FREEZE_DATE VARCHAR2(10) NULL,
    CUST_FREEZE_TIME VARCHAR2(8) NULL,
    CUST_CLOSE_DATE VARCHAR2(10) NULL,
    CUST_CLOSE_TIME VARCHAR2(8) NULL,
    CUST_IDTFY_VERIFY_NUM VARCHAR2(10) NULL,
    CUST_IS_OLD CHAR(1) NULL,
    CUST_OLD_PASSWORD CHAR(1) NULL,
    ENCRYPT_TYPE CHAR(1) NULL,
    IS_FIRST VARCHAR2(1) NULL,
    USER_LAST_LOGIN_DATE VARCHAR2(10) NULL,
    RYZD VARCHAR2(1) NULL,
    PRIMARY KEY (CUST_NO)
);
/

-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\ods\mbk\mbk_cust_log_login.sql
CREATE TABLE MBK_CUST_LOG_LOGIN (
    TRAN_SN VARCHAR2(32) NOT NULL,
    CUST_NO VARCHAR2(32) NOT NULL,
    LGN_DATE VARCHAR2(10) NOT NULL,
    LGN_TIME VARCHAR2(8) NOT NULL,
    LGT_DATE_TIME VARCHAR2(20) NULL,
    LGT_TYPE VARCHAR2(6) NULL,
    LGN_STATUS VARCHAR2(2) NOT NULL,
    LGN_ERR_CODE VARCHAR2(32) NULL,
    LGN_ERR_MSG VARCHAR2(150) NULL,
    LGN_CHNL VARCHAR2(3) NULL,
    LGN_ADDR VARCHAR2(64) NULL,
    LGN_IP VARCHAR2(15) NULL,
    LGN_MAC VARCHAR2(128) NULL,
    LGN_CLIENT_ID VARCHAR2(128) NULL,
    LGN_SESS_ID VARCHAR2(64) NULL,
    LGN_OS VARCHAR2(64) NULL,
    LGN_CLIENT_TYPE CHAR(1) NULL,
    LGN_CLIENT_VER VARCHAR2(10) NULL,
    LGN_X_LINE VARCHAR2(10) NULL,
    LGN_Y_LINE VARCHAR2(10) NULL,
    RYZD VARCHAR2(1) NULL,
    PRIMARY KEY (TRAN_SN, CUST_NO)
);
/

-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\ods\crm\crm_sys_post.sql
CREATE TABLE CRM_SYS_POST (
    POST_ID VARCHAR2(40) NOT NULL,
    EMP_ID VARCHAR2(40) NULL,
    POST_NAME VARCHAR2(64) NULL,
    JOB_NAME VARCHAR2(64) NULL,
    JOB_CLS VARCHAR2(6) NULL,
    POST_STATE VARCHAR2(6) NULL,
    BIZ_LINE VARCHAR2(6) NULL,
    ORG_ID VARCHAR2(30) NULL,
    ORG_CATE VARCHAR2(6) NULL,
    STAT_ORG_ID VARCHAR2(30) NULL,
    DIRECT_UNDER_ORG VARCHAR2(40) NULL,
    SUP_POST_ID VARCHAR2(40) NULL,
    DEL_FLG VARCHAR2(1) NULL,
    USR_NAME VARCHAR2(64) NULL,
    CREATR VARCHAR2(64) NULL,
    CREAT_TIME VARCHAR2(20) NULL,
    CREAT_ORG VARCHAR2(20) NULL,
    UPDATR VARCHAR2(64) NULL,
    UPD_TIME VARCHAR2(20) NULL,
    MAIN_POS_FLAG VARCHAR2(1) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR2(30) NULL
);
/

-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\ods\uepp\uepp_pay_mct_info.sql
CREATE TABLE UEPP_PAY_MCT_INFO (
    MCT_ID VARCHAR2(40) NOT NULL,
    SHORT_NAME VARCHAR2(100) NOT NULL,
    CATEGORY_ID VARCHAR2(40) NULL,
    MCT_TYPE VARCHAR2(20) NULL,
    PHONE VARCHAR2(20) NULL,
    EMAIL VARCHAR2(200) NULL,
    WEBSITE VARCHAR2(300) NULL,
    CONTACTS VARCHAR2(40) NULL,
    CONTACTS_CERT_TYPE VARCHAR2(2) NULL,
    CONTACTS_CERT_NO VARCHAR2(50) NULL,
    CONTACTS_CERT_BACK_URL VARCHAR2(300) NULL,
    CONTACTS_CERT_FACE_URL VARCHAR2(300) NULL,
    CONTACTS_PHONE VARCHAR2(20) NULL,
    CUSTOMER_PHONE VARCHAR2(20) NULL,
    CHAIN_ID VARCHAR2(40) NULL,
    MCT_DEPT_ID VARCHAR2(40) NULL,
    IS_OWN_DATA VARCHAR2(1) NULL,
    IS_SETTLE_ACC VARCHAR2(1) NULL,
    AGREE_URL VARCHAR2(300) NULL,
    SHOP_URL VARCHAR2(300) NULL,
    SETTLE_TYPE VARCHAR2(2) NULL,
    PROVINCE VARCHAR2(10) NULL,
    CITY VARCHAR2(10) NULL,
    AREA VARCHAR2(10) NULL,
    ADDRESS VARCHAR2(300) NULL,
    DIT_ID VARCHAR2(40) NULL,
    ORG_ID VARCHAR2(40) NULL,
    JOB_ID VARCHAR2(40) NULL,
    REMARK VARCHAR2(300) NULL,
    CHECK_STATUS VARCHAR2(2) NULL,
    STATUS VARCHAR2(2) NULL,
    CREATE_USER VARCHAR2(40) NULL,
    CREATE_TIME VARCHAR2(20) NULL,
    UPDATE_USER VARCHAR2(40) NULL,
    UPDATE_TIME VARCHAR2(20) NULL,
    LNG VARCHAR2(30) NULL,
    LAT VARCHAR2(30) NULL,
    SIGN_DATE VARCHAR2(10) NULL,
    IS_BECOME_T0_FLAG VARCHAR2(1) NULL,
    MCT_LOGO_URL VARCHAR2(100) NULL,
    CHECK_TASK_ID VARCHAR2(40) NULL,
    BANKER_ID VARCHAR2(40) NULL,
    BANKER_NAME VARCHAR2(100) NULL,
    CATEGORY_PARENT_ID VARCHAR2(40) NULL,
    RISK_LEVEL VARCHAR2(2) NULL,
    RADE_AREA_ID VARCHAR2(10) NULL,
    FROM_WAY VARCHAR2(10) NULL,
    CANCEL_DATE VARCHAR2(8) NULL,
    LAST_ORG_TRF_ID VARCHAR2(40) NULL,
    LAST_CMG_TRF_ID VARCHAR2(40) NULL,
    MONTH_DEPOSIT NUMBER(16, 2) NULL,
    SEASON_DEPOSIT NUMBER(16, 2) NULL,
    SHOP_BACK_URL VARCHAR2(300) NULL,
    YUNHORN VARCHAR2(20) NULL,
    EXPIRE_CHECK_TYPE VARCHAR2(2) NULL,
    COMPANY_SIZE VARCHAR2(2) NULL,
    ORDER_REMARK_FLAG VARCHAR2(1) NULL,
    MCT_POWER VARCHAR2(10) NULL,
    PUSH_START VARCHAR2(10) NULL,
    ASSIST_REMARK VARCHAR2(1000) NULL,
    ASSIST_DATA1 VARCHAR2(60) NULL,
    ASSIST_DATA2 VARCHAR2(60) NULL,
    ASSIST_DATA3 VARCHAR2(60) NULL,
    ASSIST_DATA4 VARCHAR2(60) NULL,
    ASSIST_DATA5 VARCHAR2(60) NULL,
    COLLECT_FLAG VARCHAR2(10) NULL,
    WX_CATEGORY_CODE VARCHAR2(20) NULL,
    ALI_CATEGORY_CODE VARCHAR2(20) NULL,
    ALI_MCC VARCHAR2(20) NULL,
    UNION_MCC VARCHAR2(20) NULL,
    XCX_PUSH_START VARCHAR2(20) NULL,
    XCX_PUSH_CASHIER VARCHAR2(2) NULL,
    RYZD VARCHAR2(1) NULL,
    PRIMARY KEY (MCT_ID)
);
/

-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\ods\uepp\uepp_pay_order_info.sql
CREATE TABLE UEPP_PAY_ORDER_INFO (
    ORDER_ID VARCHAR2(40) NOT NULL,
    ORDER_TYPE VARCHAR2(10) NULL,
    CHANNEL VARCHAR2(40) NULL,
    PAY_TYPE VARCHAR2(40) NULL,
    MCT_ID VARCHAR2(40) NOT NULL,
    DIT_ID VARCHAR2(40) NOT NULL,
    ORDER_AMT NUMBER(16, 2) NOT NULL,
    PAY_AMT NUMBER(16, 2) NULL,
    DIS_AMT NUMBER(16, 2) NULL,
    DIS_AUTH_ID VARCHAR2(40) NULL,
    PAY_TIME VARCHAR2(20) NULL,
    JUNGLE_TYPE VARCHAR2(2) NULL,
    JUNGLE_AMT NUMBER(16, 2) NULL,
    SERVER_ID VARCHAR2(40) NULL,
    MCT_FEE NUMBER(16, 2) NULL,
    DIT_FEE NUMBER(16, 2) NULL,
    BUYER_PAY_AMT NUMBER(16, 2) NULL,
    BUYER_USER_ID VARCHAR2(200) NULL,
    THIRD_MCH_ID VARCHAR2(40) NULL,
    THIRD_SUB_MCH_ID VARCHAR2(40) NULL,
    THIRD_PAY_FEE NUMBER(16, 2) NULL,
    THIRD_TRADE_NO VARCHAR2(40) NULL,
    THIRD_END_TIME VARCHAR2(20) NULL,
    SETTLE_DATE VARCHAR2(8) NULL,
    TIMEOUT_EXPRESS VARCHAR2(20) NULL,
    LIMIT_PAY VARCHAR2(20) NULL,
    OUT_TRADE_NO VARCHAR2(40) NULL,
    OR_ORDER_ID VARCHAR2(40) NULL,
    WEB_NOTIFY_URL VARCHAR2(256) NULL,
    NOTIFY_URL VARCHAR2(500) NULL,
    ORDER_BODY VARCHAR2(200) NULL,
    ORDER_DETAIL VARCHAR2(1000) NULL,
    TERM_ID VARCHAR2(100) NULL,
    DEV_INFO VARCHAR2(500) NULL,
    AUTH_CODE VARCHAR2(200) NULL,
    QR_CODE VARCHAR2(300) NULL,
    REMARK VARCHAR2(300) NULL,
    STATUS VARCHAR2(2) NULL,
    CREATE_USER VARCHAR2(40) NULL,
    CREATE_TIME VARCHAR2(20) NULL,
    UPDATE_USER VARCHAR2(40) NULL,
    UPDATE_TIME VARCHAR2(20) NULL,
    BUYER_USER_NAME VARCHAR2(200) NULL,
    PAY_CARD_TYPE VARCHAR2(2) NULL,
    CLIENT_ID VARCHAR2(40) NULL,
    CLIENT_INFO VARCHAR2(300) NULL,
    COST_RATE NUMBER(16, 4) NULL,
    DIT_FEE_RATE NUMBER(16, 4) NULL,
    MCT_FEE_RATE NUMBER(16, 4) NULL,
    SETTLE_FLAG VARCHAR2(2) NULL,
    BALA_FLAG VARCHAR2(1) NULL,
    SETTLE_SERIAL_NO VARCHAR2(40) NULL,
    SETTLE_UPDATE_DATE VARCHAR2(8) NULL,
    BALA_UPDATE_DATE VARCHAR2(8) NULL,
    SETTLE_TYPE VARCHAR2(2) NULL,
    ACTIVITY_RATE NUMBER(16, 4) NULL,
    ACTIVITY_FEE NUMBER(16, 2) NULL,
    MCT_REAL_FEE NUMBER(16, 2) NULL,
    ACTIVITY_ID VARCHAR2(32) NULL,
    ISSCODE VARCHAR2(11) NULL,
    IP VARCHAR2(16) NULL,
    TR_MAC VARCHAR2(32) NULL,
    CORE_ID VARCHAR2(40) NULL,
    MCT_RELATED_ID VARCHAR2(32) NULL,
    CONSUMER_ID VARCHAR2(40) NULL,
    IDC_FLAG VARCHAR2(10) NULL,
    DEVICE_IP VARCHAR2(64) NULL,
    DEVICE_LOCATION VARCHAR2(32) NULL,
    USER_ID VARCHAR2(128) NULL,
    IS_NEXT_REFUND VARCHAR2(10) NULL,
    STORE_ID VARCHAR2(40) NULL,
    WAL_ACCT_AMT NUMBER(16, 2) NULL,
    WAL_ACCT_STATUS VARCHAR2(2) NULL,
    WAL_ACCT_NO VARCHAR2(40) NULL,
    REFUND_MODE VARCHAR2(2) NULL,
    PAY_ZH VARCHAR2(2) NULL,
    WAL_TRADE_NO VARCHAR2(40) NULL,
    WAL_END_TIME VARCHAR2(20) NULL,
    WAL_BALA_FLAG VARCHAR2(1) NULL,
    CALC_FEE_FLAG VARCHAR2(2) NULL,
    MCT_REAL_FEE_TYPE VARCHAR2(2) NULL,
    APP_REFUNDABLE_FLAG VARCHAR2(1) NULL,
    RYZD VARCHAR2(1) NULL,
    PRIMARY KEY (ORDER_ID)
);
/

-- SOURCE DDL: D:\AI\AI-Workspace\Kingbase-CRM-AI-Development-Guide\data_assets\ddl\ods\uepp\uepp_pay_mct_settle_account.sql
CREATE TABLE UEPP_PAY_MCT_SETTLE_ACCOUNT (
    MCT_ID VARCHAR2(40) NOT NULL,
    ACCT_TYPE VARCHAR2(2) NULL,
    BANK_ACCOUNT VARCHAR2(50) NULL,
    BANK_ACCT_NAME VARCHAR2(100) NULL,
    PROVICE VARCHAR2(10) NULL,
    CITY VARCHAR2(10) NULL,
    OPEN_BANKNO VARCHAR2(20) NULL,
    OPEN_BANKNAME VARCHAR2(60) NULL,
    IS_SELF VARCHAR2(1) NULL,
    CERT_PHONE VARCHAR2(11) NULL,
    CERT_TYPE VARCHAR2(2) NULL,
    CERT_NO VARCHAR2(50) NULL,
    STATUS VARCHAR2(1) NULL,
    REMARK VARCHAR2(100) NULL,
    CHANNEL VARCHAR2(40) NOT NULL,
    CREATE_USER VARCHAR2(40) NULL,
    CREATE_TIME VARCHAR2(20) NULL,
    UPDATE_USER VARCHAR2(40) NULL,
    UPDATE_TIME VARCHAR2(20) NULL,
    CHECK_STATUS VARCHAR2(2) NULL,
    CHECK_TASK_ID VARCHAR2(40) NULL,
    IS_DEFAULT VARCHAR2(1) NULL,
    CUST_NO VARCHAR2(32) NULL,
    CUST_CN_NAME VARCHAR2(500) NULL,
    ACC_BAL VARCHAR2(40) NULL,
    OLD_CUST_NO VARCHAR2(40) NULL,
    RYZD VARCHAR2(1) NULL,
    PRIMARY KEY (MCT_ID, CHANNEL)
);
/

-- DEPO_VALUE_INIT: four columns confirmed by the indicator requirements card.
CREATE TABLE DEPO_VALUE_INIT (ORG_ID VARCHAR2(7), PERSN_LEGAL_BK_CODE VARCHAR2(4), MNGR_POST_ID VARCHAR2(20), VALUE_INIT NUMBER(20,2));
-- PRC_ADS_STAT_INDX_DATA, SYS_FUN_DEAL_DATE, SYS_PRC_STEP_LOGS are preserved: test the objects already deployed in SCOTT.
-- DWD_SYS_ORG was already verified against the real DDL; it is preserved and truncated by the loader.
