WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET SERVEROUTPUT ON
SET LINESIZE 240
SET PAGESIZE 500

DECLARE
  v_bad NUMBER := 0;
  v_org_depth NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_bad
    FROM (
      SELECT table_name
        FROM user_tables
       WHERE table_name IN ('DWD_SYS_ORG','DWD_MKT_ACT_INFO','DWD_MKT_ACT_TARGT','DWD_MKT_TSK_INFO','DWD_MKT_INDX_TSK','DWD_MKT_TSK_INDX_SUB','DWS_CUST_LVL_INFO','DWD_CUST_MAN','DWS_CUST_ASSE_LIAB','DWD_CUST_INDV_INFO','DWD_ACCT_INSUR','DWD_ACCT_DEPO','MBK_CUST_INFO','MBK_CUST_LOG_LOGIN','CRM_SYS_POST','UEPP_PAY_MCT_INFO','UEPP_PAY_ORDER_INFO','UEPP_PAY_MCT_SETTLE_ACCOUNT','DEPO_VALUE_INIT')
       MINUS
      SELECT table_name
        FROM user_tab_columns
       WHERE table_name IN ('DWD_SYS_ORG','DWD_MKT_ACT_INFO','DWD_MKT_ACT_TARGT','DWD_MKT_TSK_INFO','DWD_MKT_INDX_TSK','DWD_MKT_TSK_INDX_SUB','DWS_CUST_LVL_INFO','DWD_CUST_MAN','DWS_CUST_ASSE_LIAB','DWD_CUST_INDV_INFO','DWD_ACCT_INSUR','DWD_ACCT_DEPO','MBK_CUST_INFO','MBK_CUST_LOG_LOGIN','CRM_SYS_POST','UEPP_PAY_MCT_INFO','UEPP_PAY_ORDER_INFO','UEPP_PAY_MCT_SETTLE_ACCOUNT','DEPO_VALUE_INIT')
       GROUP BY table_name
    );
  IF v_bad <> 0 THEN RAISE_APPLICATION_ERROR(-20920, 'source table metadata missing'); END IF;

  SELECT COUNT(*) INTO v_bad
    FROM user_tables t
   WHERE t.table_name IN ('DWD_SYS_ORG','DWD_MKT_ACT_INFO','DWD_MKT_ACT_TARGT','DWD_MKT_TSK_INFO','DWD_MKT_INDX_TSK','DWD_MKT_TSK_INDX_SUB','DWS_CUST_LVL_INFO','DWD_CUST_MAN','DWS_CUST_ASSE_LIAB','DWD_CUST_INDV_INFO','DWD_ACCT_INSUR','DWD_ACCT_DEPO','MBK_CUST_INFO','MBK_CUST_LOG_LOGIN','CRM_SYS_POST','UEPP_PAY_MCT_INFO','UEPP_PAY_ORDER_INFO','UEPP_PAY_MCT_SETTLE_ACCOUNT','DEPO_VALUE_INIT')
     AND (SELECT COUNT(*) FROM user_tab_columns c WHERE c.table_name = t.table_name) >= 0
     AND CASE t.table_name
       WHEN 'DWD_SYS_ORG' THEN (SELECT COUNT(*) FROM DWD_SYS_ORG)
       WHEN 'DWD_MKT_ACT_INFO' THEN (SELECT COUNT(*) FROM DWD_MKT_ACT_INFO)
       WHEN 'DWD_MKT_ACT_TARGT' THEN (SELECT COUNT(*) FROM DWD_MKT_ACT_TARGT)
       WHEN 'DWD_MKT_TSK_INFO' THEN (SELECT COUNT(*) FROM DWD_MKT_TSK_INFO)
       WHEN 'DWD_MKT_INDX_TSK' THEN (SELECT COUNT(*) FROM DWD_MKT_INDX_TSK)
       WHEN 'DWD_MKT_TSK_INDX_SUB' THEN (SELECT COUNT(*) FROM DWD_MKT_TSK_INDX_SUB)
       WHEN 'DWS_CUST_LVL_INFO' THEN (SELECT COUNT(*) FROM DWS_CUST_LVL_INFO)
       WHEN 'DWD_CUST_MAN' THEN (SELECT COUNT(*) FROM DWD_CUST_MAN)
       WHEN 'DWS_CUST_ASSE_LIAB' THEN (SELECT COUNT(*) FROM DWS_CUST_ASSE_LIAB)
       WHEN 'DWD_CUST_INDV_INFO' THEN (SELECT COUNT(*) FROM DWD_CUST_INDV_INFO)
       WHEN 'DWD_ACCT_INSUR' THEN (SELECT COUNT(*) FROM DWD_ACCT_INSUR)
       WHEN 'DWD_ACCT_DEPO' THEN (SELECT COUNT(*) FROM DWD_ACCT_DEPO)
       WHEN 'MBK_CUST_INFO' THEN (SELECT COUNT(*) FROM MBK_CUST_INFO)
       WHEN 'MBK_CUST_LOG_LOGIN' THEN (SELECT COUNT(*) FROM MBK_CUST_LOG_LOGIN)
       WHEN 'CRM_SYS_POST' THEN (SELECT COUNT(*) FROM CRM_SYS_POST)
       WHEN 'UEPP_PAY_MCT_INFO' THEN (SELECT COUNT(*) FROM UEPP_PAY_MCT_INFO)
       WHEN 'UEPP_PAY_ORDER_INFO' THEN (SELECT COUNT(*) FROM UEPP_PAY_ORDER_INFO)
       WHEN 'UEPP_PAY_MCT_SETTLE_ACCOUNT' THEN (SELECT COUNT(*) FROM UEPP_PAY_MCT_SETTLE_ACCOUNT)
       WHEN 'DEPO_VALUE_INIT' THEN (SELECT COUNT(*) FROM DEPO_VALUE_INIT)
     END < 20;
  IF v_bad <> 0 THEN RAISE_APPLICATION_ERROR(-20921, 'one or more source tables have fewer than 20 rows'); END IF;

  SELECT MAX(depth) INTO v_org_depth
    FROM (
      SELECT org_id, LEVEL depth FROM DWD_SYS_ORG START WITH sup_org_id IS NULL CONNECT BY NOCYCLE PRIOR org_id = sup_org_id
    );
  IF v_org_depth < 4 THEN RAISE_APPLICATION_ERROR(-20922, 'DWD_SYS_ORG depth=' || v_org_depth); END IF;
  DBMS_OUTPUT.PUT_LINE('STRUCTURE_AND_DATA_PASS source_tables=19 org_depth=' || v_org_depth);
END;
/
EXIT SUCCESS
