WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
CREATE OR REPLACE FUNCTION SYS_FUN_DEAL_DATE(p_dat VARCHAR2, p_pd NUMBER) RETURN VARCHAR2 AS
  d DATE := TO_DATE(p_dat,'YYYYMMDD');
BEGIN
  RETURN CASE p_pd
    WHEN 1 THEN TO_CHAR(d-1,'YYYYMMDD')
    WHEN 2 THEN TO_CHAR(TRUNC(d,'MM')-1,'YYYYMMDD')
    WHEN 3 THEN TO_CHAR(TRUNC(d,'Q')-1,'YYYYMMDD')
    WHEN 4 THEN TO_CHAR(TRUNC(d,'YYYY')-1,'YYYYMMDD')
    WHEN 9 THEN TO_CHAR(TRUNC(d,'MM'),'YYYYMMDD')
    WHEN 10 THEN TO_CHAR(LAST_DAY(d),'YYYYMMDD')
    WHEN 13 THEN TO_CHAR(TRUNC(d,'YYYY'),'YYYYMMDD')
    WHEN 27 THEN TO_CHAR(d-180,'YYYYMMDD')
    WHEN 28 THEN TO_CHAR(d+1,'YYYYMMDD')
  END;
END;
/
ALTER PROCEDURE PRC_ADS_STAT_INDX_DATA COMPILE;
SELECT object_name, object_type, status FROM user_objects WHERE object_name IN ('SYS_FUN_DEAL_DATE','PRC_ADS_STAT_INDX_DATA') ORDER BY object_name;
SELECT name,type,line,position,text FROM user_errors WHERE name='PRC_ADS_STAT_INDX_DATA' ORDER BY sequence;
EXIT SUCCESS
