-- ============================================================
-- Functional validation: detail + statis assertions (batch 20260630)
-- ============================================================
SET PAGESIZE 200
SET LINESIZE 250

PROMPT ============ F1 Detail classification (8 rows) ============
SELECT CUST_ID, LVL_CHURN, RESCUE_STATE, CNTCT_STATE, RESCUED_FINA_ASSET
  FROM ADS_CUST_LOST_DTL ORDER BY LVL_CHURN, CUST_ID;
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_LOST_DTL) = 8
             AND (SELECT COUNT(*) FROM ADS_CUST_LOST_DTL
                  WHERE (CUST_ID='L01' AND LVL_CHURN='1' AND RESCUE_STATE='0' AND CNTCT_STATE='0')
                     OR (CUST_ID='L02' AND LVL_CHURN='2' AND RESCUE_STATE='0')
                     OR (CUST_ID='L05' AND LVL_CHURN='1' AND RESCUE_STATE='1' AND CNTCT_STATE='1' AND RESCUED_FINA_ASSET=15000)
                     OR (CUST_ID='L06' AND LVL_CHURN='1' AND CNTCT_STATE='0')
                     OR (CUST_ID='L07' AND LVL_CHURN='2' AND RESCUE_STATE='1' AND CNTCT_STATE='1' AND RESCUED_FINA_ASSET=150000)
                     OR (CUST_ID='L08' AND LVL_CHURN='1')
                     OR (CUST_ID='L10' AND LVL_CHURN='2')
                     OR (CUST_ID='L15' AND LVL_CHURN='1')) = 8
            THEN 'PASS' ELSE 'FAIL' END AS F1_DETAIL
  FROM dual;

PROMPT ============ F2 Exclusion rules (L03/L04/L09/L11/L12 absent) ============
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_LOST_DTL
                  WHERE CUST_ID IN ('L03','L04','L09','L11','L12')) = 0
            THEN 'PASS' ELSE 'FAIL' END AS F2_EXCLUSIONS
  FROM dual;

PROMPT ============ F3 Boundary (L08 49999.99 not reached / L09 50000 reached) ============
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_LOST_DTL WHERE CUST_ID='L08' AND LVL_CHURN='1') = 1
             AND (SELECT COUNT(*) FROM ADS_CUST_LOST_DTL WHERE CUST_ID='L09') = 0
            THEN 'PASS' ELSE 'FAIL' END AS F3_BOUNDARY
  FROM dual;

PROMPT ============ F4 FULL JOIN only prev-prev record (L10) ============
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_LOST_DTL WHERE CUST_ID='L10' AND LVL_CHURN='2') = 1
            THEN 'PASS' ELSE 'FAIL' END AS F4_FULLJOIN
  FROM dual;

PROMPT ============ F5 Contact state (window/invalid type/batch day) ============
SELECT CASE WHEN (SELECT CNTCT_STATE FROM ADS_CUST_LOST_DTL WHERE CUST_ID='L05') = '1'
             AND (SELECT CNTCT_STATE FROM ADS_CUST_LOST_DTL WHERE CUST_ID='L06') = '0'
             AND (SELECT CNTCT_STATE FROM ADS_CUST_LOST_DTL WHERE CUST_ID='L07') = '1'
            THEN 'PASS' ELSE 'FAIL' END AS F5_CNTCT
  FROM dual;

PROMPT ============ F6 Rescued asset formula ============
PROMPT -- L05=60000-45000=15000 ; L07=400000-250000=150000 ; un-rescued=0
SELECT CASE WHEN (SELECT RESCUED_FINA_ASSET FROM ADS_CUST_LOST_DTL WHERE CUST_ID='L05') = 15000
             AND (SELECT RESCUED_FINA_ASSET FROM ADS_CUST_LOST_DTL WHERE CUST_ID='L07') = 150000
             AND (SELECT SUM(RESCUED_FINA_ASSET) FROM ADS_CUST_LOST_DTL WHERE RESCUE_STATE='0') = 0
            THEN 'PASS' ELSE 'FAIL' END AS F6_ASSET
  FROM dual;

PROMPT ============ F7 Output completeness ============
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_LOST_DTL
                  WHERE DATA_DATE='20260630' AND STATIS_CYCLE='M') = 8
             AND (SELECT COUNT(*) FROM ADS_CUST_LOST_DTL WHERE POST_ID IS NULL) = 3
            THEN 'PASS' ELSE 'FAIL' END AS F7_COMPLETENESS
  FROM dual;

PROMPT ============ F8 Statis rollup ============
SELECT STATIS_OBJ, LVL_CHURN, CUST_CNT, CNTCT_CUST_CNT, CNTCT_RATE,
       RESCUED_CUST_CNT, RESCUE_RATE, RESCUED_FINA_ASSET
  FROM ADS_CUST_LOST_STATIS
 ORDER BY STATIS_OBJ, LVL_CHURN;
SELECT CASE WHEN (SELECT COUNT(*) FROM ADS_CUST_LOST_STATIS
                  WHERE (STATIS_OBJ='ORG100' AND LVL_CHURN='1' AND CUST_CNT=5 AND CNTCT_CUST_CNT=1
                         AND CNTCT_RATE=20 AND RESCUED_CUST_CNT=1 AND RESCUE_RATE=20 AND RESCUED_FINA_ASSET=15000)
                     OR (STATIS_OBJ='ORG100' AND LVL_CHURN='2' AND CUST_CNT=3 AND CNTCT_CUST_CNT=1
                         AND CNTCT_RATE=33.33 AND RESCUED_CUST_CNT=1 AND RESCUE_RATE=33.33 AND RESCUED_FINA_ASSET=150000)
                     OR (STATIS_OBJ='PM100' AND LVL_CHURN='1' AND CUST_CNT=3 AND CNTCT_RATE=33.33 AND RESCUE_RATE=33.33 AND RESCUED_FINA_ASSET=15000)
                     OR (STATIS_OBJ='PM100' AND LVL_CHURN='2' AND CUST_CNT=2 AND CNTCT_RATE=50 AND RESCUE_RATE=50 AND RESCUED_FINA_ASSET=150000)) = 4
            THEN 'PASS' ELSE 'FAIL' END AS F8_ROLLUP
  FROM dual;

EXIT
