/*
 * DWD_MKT_ACT_INFO
 * 中文名称: 营销活动表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_MKT_ACT_INFO (
    MKT_ACT_ID VARCHAR NULL, -- 营销活动编号
    CAMP_ACT_NAME VARCHAR NULL, -- 活动名称
    CAMP_ACT_TYP VARCHAR NULL, -- 活动类型
    ACT_BGN_DATE VARCHAR NULL, -- 活动开始日期
    ACT_END_DATE VARCHAR NULL, -- 活动结束日期
    ACT_DSC VARCHAR NULL, -- 活动说明
    CREAT_TIME VARCHAR NULL, -- 创建日期
    CREATOR VARCHAR NULL, -- 创建人
    CREAT_ORG VARCHAR NULL, -- 创建机构
    ACT_STATE VARCHAR NULL, -- 活动状态(0:待提交 1:待审批 2:审核通过 3:审核不通过)
    PERSN_LEGAL_BK_CODE VARCHAR NULL, -- 法人行号
    APPRVR VARCHAR NULL, -- 审批人
    APPRV_TIME DATE NULL, -- 审批时间
    APPRV_ORG VARCHAR NULL, -- 审批机构
    STATIS_STOP_DATE VARCHAR NULL -- 统计截止日期
);

COMMENT ON TABLE DWD_MKT_ACT_INFO IS '营销活动表';
COMMENT ON COLUMN DWD_MKT_ACT_INFO.MKT_ACT_ID IS '营销活动编号';
COMMENT ON COLUMN DWD_MKT_ACT_INFO.CAMP_ACT_NAME IS '活动名称';
COMMENT ON COLUMN DWD_MKT_ACT_INFO.CAMP_ACT_TYP IS '活动类型';
COMMENT ON COLUMN DWD_MKT_ACT_INFO.ACT_BGN_DATE IS '活动开始日期';
COMMENT ON COLUMN DWD_MKT_ACT_INFO.ACT_END_DATE IS '活动结束日期';
COMMENT ON COLUMN DWD_MKT_ACT_INFO.ACT_DSC IS '活动说明';
COMMENT ON COLUMN DWD_MKT_ACT_INFO.CREAT_TIME IS '创建日期';
COMMENT ON COLUMN DWD_MKT_ACT_INFO.CREATOR IS '创建人';
COMMENT ON COLUMN DWD_MKT_ACT_INFO.CREAT_ORG IS '创建机构';
COMMENT ON COLUMN DWD_MKT_ACT_INFO.ACT_STATE IS '活动状态(0:待提交 1:待审批 2:审核通过 3:审核不通过)';
COMMENT ON COLUMN DWD_MKT_ACT_INFO.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_MKT_ACT_INFO.APPRVR IS '审批人';
COMMENT ON COLUMN DWD_MKT_ACT_INFO.APPRV_TIME IS '审批时间';
COMMENT ON COLUMN DWD_MKT_ACT_INFO.APPRV_ORG IS '审批机构';
COMMENT ON COLUMN DWD_MKT_ACT_INFO.STATIS_STOP_DATE IS '统计截止日期';
