/*
 * DWD_PRDKT_INFO
 * 中文名称: 产品信息表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_PRDKT_INFO (
    PRDKT_ID VARCHAR(40) NOT NULL COMMENT '产品编号',
    PRDKT_NAME VARCHAR(100) NULL COMMENT '产品名称',
    PRDKT_CATE_BIG VARCHAR(10) NULL COMMENT '产品大类',
    BGN_DATE VARCHAR(10) NULL COMMENT '开始日期',
    END_DATE VARCHAR(10) NULL COMMENT '结束日期',
    PRDKT_LINE VARCHAR(10) NULL COMMENT '产品条线',
    SUP_PRDKT_ID VARCHAR(30) NULL COMMENT '上级产品编号',
    MDL_BIZ_RATE_FEE NUMBER(18,4) NULL COMMENT '中间业务费率',
    PRDKT_RATE NUMBER(18,4) NULL COMMENT '产品利率',
    SYS_SRC VARCHAR(6) NULL COMMENT '系统来源',
    PRDKT_STATE VARCHAR(10) NULL COMMENT '产品状态(在售/停售)',
    PERSN_LEGAL_BK_CODE VARCHAR(30) NULL COMMENT '法人行号'
);

COMMENT ON TABLE DWD_PRDKT_INFO IS '产品信息表';
