/*
 * DWD_CUST_INDIV_CRDT
 * 中文名称: 个人客户授信信息
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_INDIV_CRDT (
    CUST_ID VARCHAR(100) NOT NULL COMMENT '客户编号',
    CUST_NAME VARCHAR(100) NULL COMMENT '客户名称',
    CRDT_AGRE_NO VARCHAR(100) NULL COMMENT '授信协议号',
    CRDT_AGRE_TYP VARCHAR(100) NULL COMMENT '授信协议类型',
    CRDT_TTL_LMT VARCHAR(100) NULL COMMENT '授信额度',
    BGN_DATE VARCHAR(100) NULL COMMENT '开始日期',
    EXPR_DATE VARCHAR(100) NULL COMMENT '到期日期',
    CRDT_STATUS VARCHAR(100) NULL COMMENT '授信状态',
    PERSN_LEGAL_BK_CODE VARCHAR(100) NULL COMMENT '法人行号'
);

COMMENT ON TABLE DWD_CUST_INDIV_CRDT IS '个人客户授信信息';
