/*
 * DWD_CUST_INDV_INFO
 * 中文名称: 客户基本信息
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_INDV_INFO (
    CUST_ID VARCHAR(20) NOT NULL,
    CUST_NAME VARCHAR(100) NULL,
    CERT_TYP VARCHAR(6) NULL,
    CERT_ID VARCHAR(32) NULL,
    CERT_PRD_VLID VARCHAR(10) NULL,
    CERT_PRD_VLID_END VARCHAR(10) NULL,
    CERT_ISSUING_AUTHORITY VARCHAR(100) NULL,
    CUST_TYP VARCHAR(2) NULL,
    NATIONALITY VARCHAR(6) NULL,
    NATION VARCHAR(6) NULL,
    MARI_SITU VARCHAR(6) NULL,
    MAX_DEG_EDU VARCHAR(6) NULL,
    NOW_ENTER VARCHAR(120) NULL,
    OCCU_CLS VARCHAR(6) NULL,
    CUST_HRAKY VARCHAR(2) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL,
    GEND VARCHAR(2) NULL,
    PHONE_NO VARCHAR(20) NULL,
    CONTACT_ADDRESS VARCHAR(254) NULL,
    CONTACT_ADDRESS_DETAIL VARCHAR(254) NULL,
    ID_ADDRESS VARCHAR(254) NULL,
    ID_ADDRESS_DETAIL VARCHAR(254) NULL,
    HOME_ADDRESS VARCHAR(254) NULL,
    HOME_ADDRESS_DETAIL VARCHAR(254) NULL,
    RESIDENCE_ADDRESS VARCHAR(254) NULL,
    RESIDENCE_ADDRESS_DETAIL VARCHAR(254) NULL,
    OFFICE_ADDRESS VARCHAR(254) NULL,
    OFFICE_ADDRESS_DETAIL VARCHAR(254) NULL,
    HOST_CUST_MNGR_POST_ID VARCHAR(20) NULL,
    HOST_CUST_MNGR_NAME VARCHAR(60) NULL,
    HOST_CUST_MNGR_EMP_ID VARCHAR(6) NULL,
    ORG_LEAD VARCHAR(7) NULL,
    ORG_LEAD_PATH VARCHAR(50) NULL,
    COSPSR_CUST_MNGR_POST_ID VARCHAR(20) NULL,
    COSPSR_CUST_MNGR_NAME VARCHAR(60) NULL,
    COSPSR_CUST_MNGR_EMP_ID VARCHAR(6) NULL,
    COSPSR_ORG VARCHAR(7) NULL,
    COSPSR_ORG_PATH VARCHAR(50) NULL
);

COMMENT ON TABLE DWD_CUST_INDV_INFO IS '客户基本信息';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CUST_NAME IS '客户名称';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CERT_TYP IS '证件类型';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CERT_ID IS '证件号码';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CERT_PRD_VLID IS '证件有效期起';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CERT_PRD_VLID_END IS '证件有效期止';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CERT_ISSUING_AUTHORITY IS '签发机关所在地';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CUST_TYP IS '客户类型';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.NATIONALITY IS '国籍';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.NATION IS '民族';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.MARI_SITU IS '婚姻状况';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.MAX_DEG_EDU IS '最高学历';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.NOW_ENTER IS '现工作单位';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.OCCU_CLS IS '职业分类';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CUST_HRAKY IS '客户等级';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.GEND IS '性别';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.PHONE_NO IS '手机号码';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CONTACT_ADDRESS IS '联系地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CONTACT_ADDRESS_DETAIL IS '联系地址详细地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.ID_ADDRESS IS '证件地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.ID_ADDRESS_DETAIL IS '证件地址详细地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.HOME_ADDRESS IS '家庭地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.HOME_ADDRESS_DETAIL IS '家庭地址详细地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.RESIDENCE_ADDRESS IS '住宅地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.RESIDENCE_ADDRESS_DETAIL IS '住宅地址详细地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.OFFICE_ADDRESS IS '办公地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.OFFICE_ADDRESS_DETAIL IS '办公地址详细地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.HOST_CUST_MNGR_POST_ID IS '主办客户经理职位编号';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.HOST_CUST_MNGR_NAME IS '主办客户经理名称';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.HOST_CUST_MNGR_EMP_ID IS '主办客户经理工号';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.ORG_LEAD IS '主办机构(归属机构)';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.ORG_LEAD_PATH IS '主办机构路径';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.COSPSR_CUST_MNGR_POST_ID IS '信贷客户经理职位编号';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.COSPSR_CUST_MNGR_NAME IS '信贷客户经理名称';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.COSPSR_CUST_MNGR_EMP_ID IS '信贷客户经理工号';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.COSPSR_ORG IS '信贷机构';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.COSPSR_ORG_PATH IS '信贷机构路径';