/*
 * DWD_MKT_TSK_INFO
 * 中文名称: 营销任务表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_MKT_TSK_INFO (
    MKT_TSK_ID VARCHAR NULL, -- 营销任务编号
    MKT_ACT_ID VARCHAR NULL, -- 活动编号
    CUST_ID VARCHAR NULL, -- 客户编号
    CUST_NAME VARCHAR NULL, -- 客户名称
    COVER_FLG VARCHAR NULL, -- 是否接触
    CONVRS_FLG VARCHAR NULL, -- 是否成功
    MKT_PERSN VARCHAR NULL, -- 营销人
    MKT_PERSN_ORG VARCHAR NULL, -- 营销人机构
    CREATR VARCHAR NULL, -- 创建人
    CREAT_TIME VARCHAR NULL, -- 创建时间
    CREAT_ORG VARCHAR NULL, -- 创建机构
    BASE_VAL NUMBER NULL, -- 基准值
    CURNT_VAL NUMBER NULL, -- 当前值
    DATA_DATE VARCHAR NULL, -- 数据日期
    PERSN_LEGAL_BK_CODE VARCHAR NULL, -- 法人行号
    ACT_DSC VARCHAR NULL -- 备注
);

COMMENT ON TABLE DWD_MKT_TSK_INFO IS '营销任务表';
COMMENT ON COLUMN DWD_MKT_TSK_INFO.MKT_TSK_ID IS '营销任务编号';
COMMENT ON COLUMN DWD_MKT_TSK_INFO.MKT_ACT_ID IS '活动编号';
COMMENT ON COLUMN DWD_MKT_TSK_INFO.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_MKT_TSK_INFO.CUST_NAME IS '客户名称';
COMMENT ON COLUMN DWD_MKT_TSK_INFO.COVER_FLG IS '是否接触';
COMMENT ON COLUMN DWD_MKT_TSK_INFO.CONVRS_FLG IS '是否成功';
COMMENT ON COLUMN DWD_MKT_TSK_INFO.MKT_PERSN IS '营销人';
COMMENT ON COLUMN DWD_MKT_TSK_INFO.MKT_PERSN_ORG IS '营销人机构';
COMMENT ON COLUMN DWD_MKT_TSK_INFO.CREATR IS '创建人';
COMMENT ON COLUMN DWD_MKT_TSK_INFO.CREAT_TIME IS '创建时间';
COMMENT ON COLUMN DWD_MKT_TSK_INFO.CREAT_ORG IS '创建机构';
COMMENT ON COLUMN DWD_MKT_TSK_INFO.BASE_VAL IS '基准值';
COMMENT ON COLUMN DWD_MKT_TSK_INFO.CURNT_VAL IS '当前值';
COMMENT ON COLUMN DWD_MKT_TSK_INFO.DATA_DATE IS '数据日期';
COMMENT ON COLUMN DWD_MKT_TSK_INFO.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_MKT_TSK_INFO.ACT_DSC IS '备注';
