/*
 * DWD_MKT_INDX_TSK
 * 中文名称: 指标任务表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_MKT_INDX_TSK (
    TSK_ID VARCHAR NULL, -- 任务编号
    SUP_TSK_ID VARCHAR NULL, -- 上级任务编号
    MAIN_TSK_ID VARCHAR NULL, -- 主任务编号
    TSK_TITL VARCHAR NULL, -- 任务标题
    TSK_ALOKT_TYP VARCHAR NULL, -- 任务分发类型(0分解式下发,1导入式下发)
    TSK_INF VARCHAR NULL, -- 任务内容
    TSK_BGN_DATE VARCHAR NULL, -- 任务开始时间
    TSK_END_DATE VARCHAR NULL, -- 任务结束时间
    TSK_NEXT_SEND_TYP VARCHAR NULL, -- 任务下发类型0总行1分行/区域2支行
    RSV_OBJ VARCHAR NULL, -- 接收对象(0机构1客户经理)
    RSV_OBJ_ID VARCHAR NULL, -- 接收对象ID
    TSK_APDIX_ID VARCHAR NULL, -- 任务附件ID
    CREATR VARCHAR NULL, -- 任务创建/下发人
    CREAT_ORG VARCHAR NULL, -- 任务创建/下发机构
    CREAT_TIME VARCHAR NULL, -- 任务创建时间
    TSK_NEXT_SEND_TIME VARCHAR NULL, -- 任务下发时间
    TSK_STATE VARCHAR NULL, -- 任务状态(待提交，待审核，审核通过，审核拒绝，0未下发,1已下发,2已接收,9已删除)
    TSK_TYP VARCHAR NULL, -- 任务类型(0年度任务，1季度任务，2月度任务，3阶段任务)
    PERSN_LEGAL_BK_CODE VARCHAR NULL, -- 法人行号
    RSV_OBJ_NAME VARCHAR NULL, -- 接收对象名称
    BIZ_LINE VARCHAR NULL, -- 条线(公司/零售)
    TSK_YEAR VARCHAR NULL -- 任务年份
);

COMMENT ON TABLE DWD_MKT_INDX_TSK IS '指标任务表';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.TSK_ID IS '任务编号';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.SUP_TSK_ID IS '上级任务编号';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.MAIN_TSK_ID IS '主任务编号';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.TSK_TITL IS '任务标题';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.TSK_ALOKT_TYP IS '任务分发类型(0分解式下发,1导入式下发)';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.TSK_INF IS '任务内容';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.TSK_BGN_DATE IS '任务开始时间';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.TSK_END_DATE IS '任务结束时间';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.TSK_NEXT_SEND_TYP IS '任务下发类型0总行1分行/区域2支行';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.RSV_OBJ IS '接收对象(0机构1客户经理)';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.RSV_OBJ_ID IS '接收对象ID';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.TSK_APDIX_ID IS '任务附件ID';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.CREATR IS '任务创建/下发人';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.CREAT_ORG IS '任务创建/下发机构';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.CREAT_TIME IS '任务创建时间';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.TSK_NEXT_SEND_TIME IS '任务下发时间';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.TSK_STATE IS '任务状态(待提交，待审核，审核通过，审核拒绝，0未下发,1已下发,2已接收,9已删除)';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.TSK_TYP IS '任务类型(0年度任务，1季度任务，2月度任务，3阶段任务)';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.RSV_OBJ_NAME IS '接收对象名称';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.BIZ_LINE IS '条线(公司/零售)';
COMMENT ON COLUMN DWD_MKT_INDX_TSK.TSK_YEAR IS '任务年份';
