/*
 * DWD_CUST_INDV_CAR_KYC
 * 中文名称: 客户车辆KYC信息表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_INDV_CAR_KYC (
    PK_ID VARCHAR NULL, -- 主键
    PERSN_LEGAL_BK_CODE VARCHAR NULL, -- 法人行号
    CUST_ID VARCHAR NOT NULL, -- 客户编号
    CUST_NAME VARCHAR NULL, -- 客户名称
    VEHICLE_PLATE_NO VARCHAR NULL, -- 车牌号
    USAGE_NATURE VARCHAR NULL, -- 使用性质
    IS_CAR_LOAN VARCHAR NULL, -- 是否有车贷
    IS_CAR_MORTGAGED VARCHAR NULL, -- 是否抵押
    CREATR VARCHAR NULL, -- 创建人
    CREAT_ORG VARCHAR NULL, -- 创建机构
    CREAT_TIME VARCHAR NULL -- 创建时间
);

COMMENT ON TABLE DWD_CUST_INDV_CAR_KYC IS '客户车辆KYC信息表';
COMMENT ON COLUMN DWD_CUST_INDV_CAR_KYC.PK_ID IS '主键';
COMMENT ON COLUMN DWD_CUST_INDV_CAR_KYC.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_CUST_INDV_CAR_KYC.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_INDV_CAR_KYC.CUST_NAME IS '客户名称';
COMMENT ON COLUMN DWD_CUST_INDV_CAR_KYC.VEHICLE_PLATE_NO IS '车牌号';
COMMENT ON COLUMN DWD_CUST_INDV_CAR_KYC.USAGE_NATURE IS '使用性质';
COMMENT ON COLUMN DWD_CUST_INDV_CAR_KYC.IS_CAR_LOAN IS '是否有车贷';
COMMENT ON COLUMN DWD_CUST_INDV_CAR_KYC.IS_CAR_MORTGAGED IS '是否抵押';
COMMENT ON COLUMN DWD_CUST_INDV_CAR_KYC.CREATR IS '创建人';
COMMENT ON COLUMN DWD_CUST_INDV_CAR_KYC.CREAT_ORG IS '创建机构';
COMMENT ON COLUMN DWD_CUST_INDV_CAR_KYC.CREAT_TIME IS '创建时间';
