/*
 * DWD_CUST_INDIV_RISK_INVST
 * 中文名称: 客户风险评估
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_INDIV_RISK_INVST (
    CUST_ID VARCHAR(100) NOT NULL,
    FIN_INVEST_TYP VARCHAR(100) NULL,
    FIN_ESTIM_RSLT VARCHAR(100) NULL,
    FIN_SCORE VARCHAR(100) NULL,
    FIN_RISK_LVL VARCHAR(100) NULL,
    FIN_ESTIM_DATE VARCHAR(100) NULL,
    FIN_EXPR_DATE VARCHAR(100) NULL,
    INS_INVEST_TYP VARCHAR(100) NULL,
    INS_ESTIM_RSLT VARCHAR(100) NULL,
    INS_SCORE VARCHAR(100) NULL,
    INS_RISK_LVL VARCHAR(100) NULL,
    INS_ESTIM_DATE VARCHAR(100) NULL,
    INS_EXPR_DATE VARCHAR(100) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(100) NULL
);

COMMENT ON TABLE DWD_CUST_INDIV_RISK_INVST IS '客户风险评估';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.FIN_INVEST_TYP IS '理财投资类型';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.FIN_ESTIM_RSLT IS '理财评估结果';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.FIN_SCORE IS '理财分数';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.FIN_RISK_LVL IS '理财风险级别';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.FIN_ESTIM_DATE IS '理财评估日期';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.FIN_EXPR_DATE IS '理财到期日期';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.INS_INVEST_TYP IS '保险投资类型';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.INS_ESTIM_RSLT IS '保险评估结果';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.INS_SCORE IS '保险分数';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.INS_RISK_LVL IS '保险风险级别';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.INS_ESTIM_DATE IS '保险评估日期';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.INS_EXPR_DATE IS '保险到期日期';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.PERSN_LEGAL_BK_CODE IS '法人行号';