/*
 * DWD_CUST_INDV_KYC_OTHR
 * 中文名称: KYC其他信息表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_INDV_KYC_OTHR (
    PK_ID VARCHAR NULL, -- 主键
    PERSN_LEGAL_BK_CODE VARCHAR NULL, -- 法人行号
    CUST_ID VARCHAR NOT NULL, -- 客户编号
    KYC_INF VARCHAR NULL, -- KYC信息
    CREATR VARCHAR NULL, -- 创建人
    CREAT_ORG VARCHAR NULL, -- 创建机构
    CREAT_TIME VARCHAR NULL, -- 创建时间
    APDIX_ID VARCHAR NULL -- 附件ID
);

COMMENT ON TABLE DWD_CUST_INDV_KYC_OTHR IS 'KYC其他信息表';
COMMENT ON COLUMN DWD_CUST_INDV_KYC_OTHR.PK_ID IS '主键';
COMMENT ON COLUMN DWD_CUST_INDV_KYC_OTHR.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_CUST_INDV_KYC_OTHR.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_INDV_KYC_OTHR.KYC_INF IS 'KYC信息';
COMMENT ON COLUMN DWD_CUST_INDV_KYC_OTHR.CREATR IS '创建人';
COMMENT ON COLUMN DWD_CUST_INDV_KYC_OTHR.CREAT_ORG IS '创建机构';
COMMENT ON COLUMN DWD_CUST_INDV_KYC_OTHR.CREAT_TIME IS '创建时间';
COMMENT ON COLUMN DWD_CUST_INDV_KYC_OTHR.APDIX_ID IS '附件ID';
