/*
 * DWD_ACCT_INSUR
 * 中文名称: 保险账户信息
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_ACCT_INSUR (
    CUST_ID VARCHAR(20) NOT NULL, -- 客户编号
    CUST_TYP VARCHAR(4) NULL, -- 客户类型
    ACCT_ID VARCHAR(40) NOT NULL, -- 账户
    PRDKT_ID VARCHAR(40) NOT NULL, -- 产品ID
    PRDKT_NAME VARCHAR(100) NULL, -- 产品名称
    PRDKT_CATE_BIG VARCHAR(64) NULL, -- 产品大类
    INSUR_BID_FORM_NO VARCHAR(40) NOT NULL, -- 投保单号
    TX_DATE VARCHAR(8) NULL, -- 首次交易日期
    TX_ORG VARCHAR(7) NULL, -- 交易机构
    TX_CHNL VARCHAR(10) NULL, -- 交易渠道
    MKT_ORG VARCHAR(7) NULL, -- 归属机构
    BGN_INSUR_DATE VARCHAR(10) NULL, -- 起保日期
    CANCL_INSUR_DATE VARCHAR(10) NULL, -- 保险期间结束日期(推算值,仅参考)
    PAY_UPTO_DATE VARCHAR(8) NULL, -- 缴费截止日期
    INSUR_PERIOD_TYP VARCHAR(2) NULL, -- 保险期间类型
    INSUR_PERIOD VARCHAR(6) NULL, -- 保险期间值
    PAY_PERIOD_TYP VARCHAR(2) NULL, -- 缴费期间类型
    PAY_PERIOD VARCHAR(6) NULL, -- 缴费期间值
    PAY_PATRN VARCHAR(2) NULL, -- 缴费方式
    INSUR_AMT NUMBER(20,2) NULL, -- 当前保险金额
    POLICY_STATE VARCHAR(8) NOT NULL, -- 保单状态
    TX_TYP VARCHAR(1) NULL, -- 交易类型
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL, -- 法人行号
    LAST_TX_DATE VARCHAR(8) NULL, -- 最近交易日期
    ACTL_TERM_DATE VARCHAR(8) NULL, -- 实际终止日期
    NEW_INSUR_AMT NUMBER(20,2) NULL -- 首期保费(新单保费)
);

COMMENT ON TABLE DWD_ACCT_INSUR IS '保险账户信息';
COMMENT ON COLUMN DWD_ACCT_INSUR.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_ACCT_INSUR.CUST_TYP IS '客户类型';
COMMENT ON COLUMN DWD_ACCT_INSUR.ACCT_ID IS '账户';
COMMENT ON COLUMN DWD_ACCT_INSUR.PRDKT_ID IS '产品ID';
COMMENT ON COLUMN DWD_ACCT_INSUR.PRDKT_NAME IS '产品名称';
COMMENT ON COLUMN DWD_ACCT_INSUR.PRDKT_CATE_BIG IS '产品大类';
COMMENT ON COLUMN DWD_ACCT_INSUR.INSUR_BID_FORM_NO IS '投保单号';
COMMENT ON COLUMN DWD_ACCT_INSUR.TX_DATE IS '首次交易日期';
COMMENT ON COLUMN DWD_ACCT_INSUR.TX_ORG IS '交易机构';
COMMENT ON COLUMN DWD_ACCT_INSUR.TX_CHNL IS '交易渠道';
COMMENT ON COLUMN DWD_ACCT_INSUR.MKT_ORG IS '归属机构';
COMMENT ON COLUMN DWD_ACCT_INSUR.BGN_INSUR_DATE IS '起保日期';
COMMENT ON COLUMN DWD_ACCT_INSUR.CANCL_INSUR_DATE IS '保险期间结束日期(推算值,仅参考)';
COMMENT ON COLUMN DWD_ACCT_INSUR.PAY_UPTO_DATE IS '缴费截止日期';
COMMENT ON COLUMN DWD_ACCT_INSUR.INSUR_PERIOD_TYP IS '保险期间类型';
COMMENT ON COLUMN DWD_ACCT_INSUR.INSUR_PERIOD IS '保险期间值';
COMMENT ON COLUMN DWD_ACCT_INSUR.PAY_PERIOD_TYP IS '缴费期间类型';
COMMENT ON COLUMN DWD_ACCT_INSUR.PAY_PERIOD IS '缴费期间值';
COMMENT ON COLUMN DWD_ACCT_INSUR.PAY_PATRN IS '缴费方式';
COMMENT ON COLUMN DWD_ACCT_INSUR.INSUR_AMT IS '当前保险金额';
COMMENT ON COLUMN DWD_ACCT_INSUR.POLICY_STATE IS '保单状态';
COMMENT ON COLUMN DWD_ACCT_INSUR.TX_TYP IS '交易类型';
COMMENT ON COLUMN DWD_ACCT_INSUR.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_ACCT_INSUR.LAST_TX_DATE IS '最近交易日期';
COMMENT ON COLUMN DWD_ACCT_INSUR.ACTL_TERM_DATE IS '实际终止日期';
COMMENT ON COLUMN DWD_ACCT_INSUR.NEW_INSUR_AMT IS '首期保费(新单保费)';
