/*
 * DWD_MKT_ACT_TARGT
 * 中文名称: 营销活动目标表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_MKT_ACT_TARGT (
    PK_ID VARCHAR NULL, -- 主键
    MKT_ACT_ID VARCHAR NULL, -- 营销活动编号
    PRTSPT_ORG VARCHAR NULL, -- 参与机构
    INDX_ID VARCHAR NULL, -- 指标ID
    INDX_VAL NUMBER NULL -- 指标值
);

COMMENT ON TABLE DWD_MKT_ACT_TARGT IS '营销活动目标表';
COMMENT ON COLUMN DWD_MKT_ACT_TARGT.PK_ID IS '主键';
COMMENT ON COLUMN DWD_MKT_ACT_TARGT.MKT_ACT_ID IS '营销活动编号';
COMMENT ON COLUMN DWD_MKT_ACT_TARGT.PRTSPT_ORG IS '参与机构';
COMMENT ON COLUMN DWD_MKT_ACT_TARGT.INDX_ID IS '指标ID';
COMMENT ON COLUMN DWD_MKT_ACT_TARGT.INDX_VAL IS '指标值';
