/*
 * DWD_MKT_ACT_ORG_REL
 * 中文名称: 营销活动机构关系表
 * 来源: Mapping Excel 同步
 */

DROP TABLE DWD_MKT_ACT_ORG_REL;
CREATE TABLE DWD_MKT_ACT_ORG_REL (
    MKT_ACT_ID VARCHAR NULL, -- 营销活动编号
    PRTSPT_ORG VARCHAR NULL -- 参与机构
);

COMMENT ON TABLE DWD_MKT_ACT_ORG_REL IS '营销活动机构关系表';
COMMENT ON COLUMN DWD_MKT_ACT_ORG_REL.MKT_ACT_ID IS '营销活动编号';
COMMENT ON COLUMN DWD_MKT_ACT_ORG_REL.PRTSPT_ORG IS '参与机构';
