/*
 * DWD_CUST_INDV_INFO
 * 中文名称: 客户基本信息
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_INDV_INFO (
    CUST_ID VARCHAR(20) NOT NULL, -- 客户编号
    CUST_NAME VARCHAR(100) NULL, -- 客户名称
    CERT_TYP VARCHAR(6) NULL, -- 证件类型
    CERT_ID VARCHAR(32) NULL, -- 证件号码
    CERT_PRD_VLID VARCHAR(10) NULL, -- 证件有效期起
    CERT_PRD_VLID_END VARCHAR(10) NULL, -- 证件有效期止
    CERT_ISSUING VARCHAR(100) NULL, -- 签发机关
    CERT_ISSUING_AUTHORITY VARCHAR(100) NULL, -- 签发机关所在地
    CUST_TYP VARCHAR(2) NULL, -- 客户类型
    OPEN_DATE VARCHAR(10) NULL, -- 开户日期
    OPEN_ORG VARCHAR(20) NULL, -- 开户机构
    NATIONALITY VARCHAR(6) NULL, -- 国籍
    NATION VARCHAR(6) NULL, -- 民族
    MARI_SITU VARCHAR(6) NULL, -- 婚姻状况
    MAX_DEG_EDU VARCHAR(6) NULL, -- 最高学历
    NOW_ENTER VARCHAR(120) NULL, -- 现工作单位
    OCCU_CLS VARCHAR(6) NULL, -- 职业分类
    PERSN_LEGAL_BK_CODE VARCHAR(4) NOT NULL, -- 法人行号
    GEND VARCHAR(2) NULL, -- 性别
    PHONE_NO VARCHAR(20) NULL, -- 手机号码
    CONTACT_ADDRESS VARCHAR(254) NULL, -- 联系地址
    CONTACT_ADDRESS_DETAIL VARCHAR(254) NULL, -- 联系地址详细地址
    ID_ADDRESS VARCHAR(254) NULL, -- 证件地址
    ID_ADDRESS_DETAIL VARCHAR(254) NULL, -- 证件地址详细地址
    HOME_ADDRESS VARCHAR(254) NULL, -- 家庭地址
    HOME_ADDRESS_DETAIL VARCHAR(254) NULL, -- 家庭地址详细地址
    RESIDENCE_ADDRESS VARCHAR(254) NULL, -- 住宅地址
    RESIDENCE_ADDRESS_DETAIL VARCHAR(254) NULL, -- 住宅地址详细地址
    OFFICE_ADDRESS VARCHAR(254) NULL, -- 办公地址
    OFFICE_ADDRESS_DETAIL VARCHAR(254) NULL, -- 办公地址详细地址
    HOST_CUST_MNGR_POST_ID VARCHAR(20) NULL, -- 主办客户经理职位编号
    HOST_CUST_MNGR_NAME VARCHAR(60) NULL, -- 主办客户经理名称
    HOST_CUST_MNGR_EMP_ID VARCHAR(6) NULL, -- 主办客户经理工号
    ORG_LEAD VARCHAR(7) NULL, -- 主办机构(归属机构)
    ORG_LEAD_PATH VARCHAR(50) NULL, -- 主办机构路径
    COSPSR_CUST_MNGR_POST_ID VARCHAR(20) NULL, -- 信贷客户经理职位编号
    COSPSR_CUST_MNGR_NAME VARCHAR(60) NULL, -- 信贷客户经理名称
    COSPSR_CUST_MNGR_EMP_ID VARCHAR(6) NULL, -- 信贷客户经理工号
    COSPSR_ORG VARCHAR(7) NULL, -- 信贷机构
    COSPSR_ORG_PATH VARCHAR(50) NULL -- 信贷机构路径
);

COMMENT ON TABLE DWD_CUST_INDV_INFO IS '客户基本信息';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CUST_NAME IS '客户名称';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CERT_TYP IS '证件类型';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CERT_ID IS '证件号码';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CERT_PRD_VLID IS '证件有效期起';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CERT_PRD_VLID_END IS '证件有效期止';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CERT_ISSUING IS '签发机关';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CERT_ISSUING_AUTHORITY IS '签发机关所在地';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CUST_TYP IS '客户类型';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.OPEN_DATE IS '开户日期';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.OPEN_ORG IS '开户机构';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.NATIONALITY IS '国籍';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.NATION IS '民族';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.MARI_SITU IS '婚姻状况';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.MAX_DEG_EDU IS '最高学历';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.NOW_ENTER IS '现工作单位';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.OCCU_CLS IS '职业分类';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.GEND IS '性别';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.PHONE_NO IS '手机号码';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CONTACT_ADDRESS IS '联系地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.CONTACT_ADDRESS_DETAIL IS '联系地址详细地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.ID_ADDRESS IS '证件地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.ID_ADDRESS_DETAIL IS '证件地址详细地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.HOME_ADDRESS IS '家庭地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.HOME_ADDRESS_DETAIL IS '家庭地址详细地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.RESIDENCE_ADDRESS IS '住宅地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.RESIDENCE_ADDRESS_DETAIL IS '住宅地址详细地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.OFFICE_ADDRESS IS '办公地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.OFFICE_ADDRESS_DETAIL IS '办公地址详细地址';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.HOST_CUST_MNGR_POST_ID IS '主办客户经理职位编号';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.HOST_CUST_MNGR_NAME IS '主办客户经理名称';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.HOST_CUST_MNGR_EMP_ID IS '主办客户经理工号';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.ORG_LEAD IS '主办机构(归属机构)';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.ORG_LEAD_PATH IS '主办机构路径';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.COSPSR_CUST_MNGR_POST_ID IS '信贷客户经理职位编号';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.COSPSR_CUST_MNGR_NAME IS '信贷客户经理名称';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.COSPSR_CUST_MNGR_EMP_ID IS '信贷客户经理工号';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.COSPSR_ORG IS '信贷机构';
COMMENT ON COLUMN DWD_CUST_INDV_INFO.COSPSR_ORG_PATH IS '信贷机构路径';
