/*
 * DWD_SYS_ORG
 * 中文名称: 机构表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_SYS_ORG (
    ORG_ID 40 NOT NULL COMMENT '机构编号',
    SUP_ORG_ID 40 NULL COMMENT '上级机构编号',
    ORG_PATH 200 NULL COMMENT '机构路径',
    ORG_NAME 100 NULL COMMENT '机构名称',
    SUP_ORG_NAME 100 NULL COMMENT '上级机构名称',
    DIRECT_UNDER_ORG 40 NULL COMMENT '直属机构',
    ORG_TYP 10 NULL COMMENT '机构类型',
    ORG_HARCY 10 NULL COMMENT '机构层级',
    ORG_ADDRS 800 NULL COMMENT '机构地址',
    ORG_STATE 1 NULL COMMENT '机构状态',
    DSPLY_SEQ VARCHAR(100) NULL COMMENT '显示顺序',
    CREATR 64 NULL COMMENT '创建人',
    CREAT_TIME 20 NULL COMMENT '创建时间',
    CREAT_ORG 20 NULL COMMENT '创建机构',
    PERSN_LEGAL_BK_CODE 30 NULL COMMENT '法人行号',
    HR_MS_ORG_ID 80 NULL COMMENT '人力资源系统机构号',
    ORG_LGTUD 30 NULL COMMENT '机构经度',
    ORG_LATTUD 30 NULL COMMENT '机构纬度',
    ORG_RSPONR 40 NULL COMMENT '机构负责人',
    ORG_TEL 30 NULL COMMENT '机构电话'
);

COMMENT ON TABLE DWD_SYS_ORG IS '机构表';
