/*
 * DWD_CUST_DORMANT_ACCOUT
 * 中文名称: 睡眠户信息表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_DORMANT_ACCOUT (
    DATA_DATE VARCHAR NULL, -- 数据日期
    CUST_ID VARCHAR NULL, -- 客户编号
    PERSN_LEGAL_BK_CODE VARCHAR NULL -- 法人行号
);

COMMENT ON TABLE DWD_CUST_DORMANT_ACCOUT IS '睡眠户信息表';
COMMENT ON COLUMN DWD_CUST_DORMANT_ACCOUT.DATA_DATE IS '数据日期';
COMMENT ON COLUMN DWD_CUST_DORMANT_ACCOUT.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_DORMANT_ACCOUT.PERSN_LEGAL_BK_CODE IS '法人行号';
