/*
 * DWD_ACCT_INSUR
 * 中文名称: 保险账户信息
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_ACCT_INSUR (
    CUST_ID VARCHAR(20) NOT NULL,
    CUST_TYP VARCHAR(4) NULL,
    ACCT_ID VARCHAR(40) NULL,
    PRDKT_ID VARCHAR(40) NULL,
    PRDKT_NAME VARCHAR(100) NULL,
    PRDKT_CATE_BIG VARCHAR(64) NULL,
    INSUR_BID_FORM_NO VARCHAR(40) NULL,
    TX_DATE VARCHAR(10) NULL,
    TX_ORG VARCHAR(7) NULL,
    TX_CHNL VARCHAR(10) NULL,
    MKT_ORG VARCHAR(7) NULL,
    BGN_INSUR_DATE VARCHAR(10) NULL,
    CANCL_INSUR_DATE VARCHAR(10) NULL,
    INSUR_PERIOD_TYP VARCHAR(2) NULL,
    INSUR_PERIOD VARCHAR(6) NULL,
    PAY_PERIOD_TYP VARCHAR(2) NULL,
    PAY_PERIOD VARCHAR(6) NULL,
    PAY_PATRN VARCHAR(2) NULL,
    INSUR_AMT NUMBER(20,
    2) NULL,
    POLICY_STATE VARCHAR(10) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL
);

COMMENT ON TABLE DWD_ACCT_INSUR IS '保险账户信息';
COMMENT ON COLUMN DWD_ACCT_INSUR.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_ACCT_INSUR.CUST_TYP IS '客户类型';
COMMENT ON COLUMN DWD_ACCT_INSUR.ACCT_ID IS '账户';
COMMENT ON COLUMN DWD_ACCT_INSUR.PRDKT_ID IS '产品ID';
COMMENT ON COLUMN DWD_ACCT_INSUR.PRDKT_NAME IS '产品名称';
COMMENT ON COLUMN DWD_ACCT_INSUR.PRDKT_CATE_BIG IS '产品大类';
COMMENT ON COLUMN DWD_ACCT_INSUR.INSUR_BID_FORM_NO IS '投保单号';
COMMENT ON COLUMN DWD_ACCT_INSUR.TX_DATE IS '交易日期';
COMMENT ON COLUMN DWD_ACCT_INSUR.TX_ORG IS '交易机构';
COMMENT ON COLUMN DWD_ACCT_INSUR.TX_CHNL IS '交易渠道';
COMMENT ON COLUMN DWD_ACCT_INSUR.MKT_ORG IS '归属机构';
COMMENT ON COLUMN DWD_ACCT_INSUR.BGN_INSUR_DATE IS '起保日期';
COMMENT ON COLUMN DWD_ACCT_INSUR.CANCL_INSUR_DATE IS '退保日期';
COMMENT ON COLUMN DWD_ACCT_INSUR.INSUR_PERIOD_TYP IS '保险期间类型';
COMMENT ON COLUMN DWD_ACCT_INSUR.INSUR_PERIOD IS '保险期间值';
COMMENT ON COLUMN DWD_ACCT_INSUR.PAY_PERIOD_TYP IS '缴费期间类型';
COMMENT ON COLUMN DWD_ACCT_INSUR.PAY_PERIOD IS '缴费期间值';
COMMENT ON COLUMN DWD_ACCT_INSUR.PAY_PATRN IS '缴费方式';
COMMENT ON COLUMN DWD_ACCT_INSUR.INSUR_AMT IS '保费金额';
COMMENT ON COLUMN DWD_ACCT_INSUR.POLICY_STATE IS '保单状态';
COMMENT ON COLUMN DWD_ACCT_INSUR.PERSN_LEGAL_BK_CODE IS '法人行号';