/*
 * DWD_CUST_INDIV_MNER
 * 中文名称: 家庭成员信息表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_INDIV_MNER (
    PK_ID VARCHAR(40) NOT NULL, -- 主键
    CUST_ID VARCHAR(20) NULL, -- 客户编号
    MBER_NAME VARCHAR(200) NULL, -- 成员姓名
    MBER_REL VARCHAR(6) NULL, -- 成员关系
    GEND VARCHAR(6) NULL, -- 性别
    TEL_NO VARCHAR(32) NULL, -- 联系电话
    BK_SELF_CUST_FLG VARCHAR(1) NULL, -- 是否本行客户
    INNER_BK_CUST_ID VARCHAR(20) NULL, -- 行内客户编号
    BTH_DATE VARCHAR(10) NULL, -- 出生日期
    MARI_DAY_MEM VARCHAR(10) NULL, -- 结婚纪念日
    CERT_ID VARCHAR(40) NULL, -- 证件号码
    CERT_TYP VARCHAR(10) NULL, -- 证件类型
    SYS_SRC VARCHAR(500) NULL, -- 系统来源
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL, -- 法人行号
    POST_ID VARCHAR(20) NULL, -- 维护人
    REMARK VARCHAR(200) NULL -- 备注
);

COMMENT ON TABLE DWD_CUST_INDIV_MNER IS '家庭成员信息表';
COMMENT ON COLUMN DWD_CUST_INDIV_MNER.PK_ID IS '主键';
COMMENT ON COLUMN DWD_CUST_INDIV_MNER.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_INDIV_MNER.MBER_NAME IS '成员姓名';
COMMENT ON COLUMN DWD_CUST_INDIV_MNER.MBER_REL IS '成员关系';
COMMENT ON COLUMN DWD_CUST_INDIV_MNER.GEND IS '性别';
COMMENT ON COLUMN DWD_CUST_INDIV_MNER.TEL_NO IS '联系电话';
COMMENT ON COLUMN DWD_CUST_INDIV_MNER.BK_SELF_CUST_FLG IS '是否本行客户';
COMMENT ON COLUMN DWD_CUST_INDIV_MNER.INNER_BK_CUST_ID IS '行内客户编号';
COMMENT ON COLUMN DWD_CUST_INDIV_MNER.BTH_DATE IS '出生日期';
COMMENT ON COLUMN DWD_CUST_INDIV_MNER.MARI_DAY_MEM IS '结婚纪念日';
COMMENT ON COLUMN DWD_CUST_INDIV_MNER.CERT_ID IS '证件号码';
COMMENT ON COLUMN DWD_CUST_INDIV_MNER.CERT_TYP IS '证件类型';
COMMENT ON COLUMN DWD_CUST_INDIV_MNER.SYS_SRC IS '系统来源';
COMMENT ON COLUMN DWD_CUST_INDIV_MNER.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_CUST_INDIV_MNER.POST_ID IS '维护人';
COMMENT ON COLUMN DWD_CUST_INDIV_MNER.REMARK IS '备注';
