/*
 * DWD_CUST_INDIV_RISK_INVST
 * 中文名称: 客户风险评估
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_INDIV_RISK_INVST (
    CUST_ID VARCHAR(100) NOT NULL COMMENT '客户编号',
    INVEST_TYP VARCHAR(100) NULL COMMENT '投资类型',
    ESTIM_RSLT VARCHAR(100) NULL COMMENT '评估结果',
    SCORE VARCHAR(100) NULL COMMENT '分数',
    RISK_LVL VARCHAR(100) NULL COMMENT '风险级别',
    ESTIM_DATE VARCHAR(100) NULL COMMENT '评估日期',
    EXPR_DATE VARCHAR(100) NULL COMMENT '到期日期',
    PERSN_LEGAL_BK_CODE VARCHAR(100) NULL COMMENT '法人行号',
    CUST_ID VARCHAR(100) NULL COMMENT '客户编号',
    INVEST_TYP VARCHAR(100) NULL COMMENT '投资类型',
    ESTIM_RSLT VARCHAR(100) NULL COMMENT '评估结果',
    SCORE VARCHAR(100) NULL COMMENT '分数',
    RISK_LVL VARCHAR(100) NULL COMMENT '风险级别',
    ESTIM_DATE VARCHAR(100) NULL COMMENT '评估日期',
    EXPR_DATE VARCHAR(100) NULL COMMENT '到期日期',
    PERSN_LEGAL_BK_CODE VARCHAR(100) NULL COMMENT '法人行号'
);

COMMENT ON TABLE DWD_CUST_INDIV_RISK_INVST IS '客户风险评估';
