/*
 * DWD_CUST_INDIV_CRDT
 * 中文名称: 个人客户授信信息
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_INDIV_CRDT (
    CUST_ID VARCHAR(100) NOT NULL,
    CUST_NAME VARCHAR(100) NULL,
    CRDT_AGRE_NO VARCHAR(100) NULL,
    CRDT_AGRE_TYP VARCHAR(100) NULL,
    CRDT_TTL_LMT VARCHAR(100) NULL,
    BGN_DATE VARCHAR(100) NULL,
    EXPR_DATE VARCHAR(100) NULL,
    CRDT_STATUS VARCHAR(100) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(100) NULL
);

COMMENT ON TABLE DWD_CUST_INDIV_CRDT IS '个人客户授信信息';
COMMENT ON COLUMN DWD_CUST_INDIV_CRDT.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_INDIV_CRDT.CUST_NAME IS '客户名称';
COMMENT ON COLUMN DWD_CUST_INDIV_CRDT.CRDT_AGRE_NO IS '授信协议号';
COMMENT ON COLUMN DWD_CUST_INDIV_CRDT.CRDT_AGRE_TYP IS '授信协议类型';
COMMENT ON COLUMN DWD_CUST_INDIV_CRDT.CRDT_TTL_LMT IS '授信额度';
COMMENT ON COLUMN DWD_CUST_INDIV_CRDT.BGN_DATE IS '开始日期';
COMMENT ON COLUMN DWD_CUST_INDIV_CRDT.EXPR_DATE IS '到期日期';
COMMENT ON COLUMN DWD_CUST_INDIV_CRDT.CRDT_STATUS IS '授信状态';
COMMENT ON COLUMN DWD_CUST_INDIV_CRDT.PERSN_LEGAL_BK_CODE IS '法人行号';