/*
 * DWD_CUST_MAN
 * 中文名称: 信贷管户关系表
 * 版本: v1.0
 * 创建时间: 2026-07-23
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_MAN (
    CUST_ID VARCHAR(20) NULL,
    MNGR_POST_ID VARCHAR(20) NULL,
    ORG_ID VARCHAR(6) NULL,
    MNG_TYP VARCHAR(1) NULL,
    MODF_TIME VARCHAR(20) NULL,
    MODF_TYP VARCHAR(10) NULL,
    DATA_SRC VARCHAR(10) NULL,
    VALID_DATE VARCHAR(8) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL
);

COMMENT ON TABLE DWD_CUST_MAN IS '信贷管户关系表';
COMMENT ON COLUMN DWD_CUST_MAN.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_MAN.MNGR_POST_ID IS '客户经理编号';
COMMENT ON COLUMN DWD_CUST_MAN.ORG_ID IS '机构编号';
COMMENT ON COLUMN DWD_CUST_MAN.MNG_TYP IS '管理类型(1-理财管户，2-信贷管户)';
COMMENT ON COLUMN DWD_CUST_MAN.MODF_TIME IS '变更时间';
COMMENT ON COLUMN DWD_CUST_MAN.MODF_TYP IS '变更类型';
COMMENT ON COLUMN DWD_CUST_MAN.DATA_SRC IS '数据来源';
COMMENT ON COLUMN DWD_CUST_MAN.VALID_DATE IS '有效日期';
COMMENT ON COLUMN DWD_CUST_MAN.PERSN_LEGAL_BK_CODE IS '法人行号';
