/*
 * DWD_CUST_CTRAKT_INFO
 * 中文名称: 客户合同信息
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_CTRAKT_INFO (
    CUST_ID VARCHAR(100) NOT NULL COMMENT '客户编号',
    CTRAKT_ID VARCHAR(100) NULL COMMENT '合同编号',
    LOAN_ACCT VARCHAR(100) NULL COMMENT '贷款账号',
    CRDT_LMT VARCHAR(100) NULL COMMENT '授信额度',
    LOAN_BAL VARCHAR(100) NULL COMMENT '贷款余额',
    GUARANT_MODE VARCHAR(100) NULL COMMENT '担保方式',
    CATE_5LVL VARCHAR(100) NULL COMMENT '五级分类',
    CCY_CD VARCHAR(100) NULL COMMENT '币种',
    RATE_INTRI VARCHAR(100) NULL COMMENT '利率',
    CONTR_AMT VARCHAR(100) NULL COMMENT '合同金额',
    BGN_DATE VARCHAR(100) NULL COMMENT '发放日期',
    END_DATE VARCHAR(100) NULL COMMENT '结束日期',
    OPRTR VARCHAR(100) NULL COMMENT '经办人',
    OPRT_ORG VARCHAR(100) NULL COMMENT '经办机构',
    PERSN_LEGAL_BK_CODE VARCHAR(100) NULL COMMENT '法人行号'
);

COMMENT ON TABLE DWD_CUST_CTRAKT_INFO IS '客户合同信息';
