/*
 * DWD_ACCT_LOAN
 * 中文名称: 贷款账户
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_ACCT_LOAN (
    CUST_ID VARCHAR(20) NOT NULL,
    CUST_TYP VARCHAR(6) NULL,
    ACCT_ID VARCHAR(40) NULL,
    PRDKT_ID VARCHAR(40) NULL,
    PRDKT_NAME VARCHAR(100) NULL,
    PRDKT_CATE_BIG VARCHAR(60) NULL,
    LOAN_ISSU_AMT NUMBER(20,
    2) NULL,
    LOAN_ISSU_DATE VARCHAR(10) NULL,
    BAL NUMBER(20,
    2) NULL,
    RATE_INTRI NUMBER(10,
    4) NULL,
    EXPR_DATE VARCHAR(10) NULL,
    ACCT_STATE VARCHAR(10) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL,
    OPRT_ORG VARCHAR(7) NULL,
    IOU_NO VARCHAR(100) NULL,
    INT_ARREARS_TTL NUMBER(20,
    2) NULL,
    REPAY_TYP VARCHAR(4) NULL,
    REPAY_ACCT_NO VARCHAR(30) NULL,
    CATE_5LVL VARCHAR(2) NULL
);

COMMENT ON TABLE DWD_ACCT_LOAN IS '贷款账户';
COMMENT ON COLUMN DWD_ACCT_LOAN.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_ACCT_LOAN.CUST_TYP IS '客户类型';
COMMENT ON COLUMN DWD_ACCT_LOAN.ACCT_ID IS '账号';
COMMENT ON COLUMN DWD_ACCT_LOAN.PRDKT_ID IS '产品编号';
COMMENT ON COLUMN DWD_ACCT_LOAN.PRDKT_NAME IS '产品名称';
COMMENT ON COLUMN DWD_ACCT_LOAN.PRDKT_CATE_BIG IS '产品大类';
COMMENT ON COLUMN DWD_ACCT_LOAN.LOAN_ISSU_AMT IS '借据金额';
COMMENT ON COLUMN DWD_ACCT_LOAN.LOAN_ISSU_DATE IS '贷款发放日期';
COMMENT ON COLUMN DWD_ACCT_LOAN.BAL IS '余额';
COMMENT ON COLUMN DWD_ACCT_LOAN.RATE_INTRI IS '利率';
COMMENT ON COLUMN DWD_ACCT_LOAN.EXPR_DATE IS '到期日期';
COMMENT ON COLUMN DWD_ACCT_LOAN.ACCT_STATE IS '账户状态';
COMMENT ON COLUMN DWD_ACCT_LOAN.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_ACCT_LOAN.OPRT_ORG IS '经办机构';
COMMENT ON COLUMN DWD_ACCT_LOAN.IOU_NO IS '借据号';
COMMENT ON COLUMN DWD_ACCT_LOAN.INT_ARREARS_TTL IS '欠息(合计)';
COMMENT ON COLUMN DWD_ACCT_LOAN.REPAY_TYP IS '还款方式';
COMMENT ON COLUMN DWD_ACCT_LOAN.REPAY_ACCT_NO IS '还款账号';
COMMENT ON COLUMN DWD_ACCT_LOAN.CATE_5LVL IS '五级分类';