/*
 * DWD_ACCT_DEPO
 * 中文名称: 存款账户信息表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_ACCT_DEPO (
    CUST_ID VARCHAR(20) NOT NULL COMMENT '客户编号',
    CUST_TYP VARCHAR(2) NULL COMMENT '客户类型',
    ACCT_ID VARCHAR(40) NULL COMMENT '账户',
    CARD_NO VARCHAR(40) NULL COMMENT '卡/折号',
    PRDKT_ID VARCHAR(30) NULL COMMENT '产品编号',
    PRDKT_NAME VARCHAR(200) NULL COMMENT '产品名称',
    PRDKT_CATE_BIG VARCHAR(64) NULL COMMENT '产品大类',
    ACCT_TYP VARCHAR(10) NULL COMMENT '账户类型',
    CCY_CD VARCHAR(4) NULL COMMENT '币种',
    BAL NUMBER(20,2) NULL COMMENT '余额',
    RMB_BAL NUMBER(20,2) NULL COMMENT '折人民币余额',
    OPEN_ACCT_ORG VARCHAR(6) NULL COMMENT '归属机构',
    OPEN_DATE VARCHAR(10) NULL COMMENT '开户日期',
    RATE_INTRI NUMBER(20,2) NULL COMMENT '利率',
    INTRI_BGN_DATE VARCHAR(10) NULL COMMENT '起息日期',
    EXPR_DATE VARCHAR(10) NULL COMMENT '到期日期',
    ACCT_CLOZ_DATE VARCHAR(10) NULL COMMENT '销户日期',
    ACCT_STATE VARCHAR(10) NULL COMMENT '账户状态',
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL COMMENT '法人行号',
    VCHR_TYP VARCHAR(10) NULL COMMENT '凭证类型',
    CUNQ VARCHAR(10) NULL COMMENT '存期',
    FIX_CURNT_FLG VARCHAR(1) NULL COMMENT '定活标志'
);

COMMENT ON TABLE DWD_ACCT_DEPO IS '存款账户信息表';
