/*
 * DWD_ACCT_LOAN
 * 中文名称: 贷款账户
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_ACCT_LOAN (
    CUST_ID VARCHAR(20) NOT NULL, -- 客户编号
    CUST_TYP VARCHAR(6) NULL, -- 客户类型
    ACCT_ID VARCHAR(40) NOT NULL, -- 账号
    PRDKT_ID VARCHAR(40) NOT NULL, -- 产品编号
    PRDKT_NAME VARCHAR(100) NULL, -- 产品名称
    PRDKT_CATE_BIG VARCHAR(60) NULL, -- 产品大类
    LOAN_ISSU_AMT NUMBER(20,2) NULL, -- 借据金额
    LOAN_ISSU_DATE VARCHAR(10) NULL, -- 贷款发放日期
    BAL NUMBER(20,2) NULL, -- 余额
    RATE_INTRI NUMBER(10,4) NULL, -- 利率
    EXPR_DATE VARCHAR(10) NULL, -- 到期日期
    ACCT_STATE VARCHAR(10) NULL, -- 账户状态
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL, -- 法人行号
    OPRT_ORG VARCHAR(7) NULL, -- 经办机构
    IOU_NO VARCHAR(100) NULL, -- 借据号
    INT_ARREARS_TTL NUMBER(20,2) NULL, -- 欠息(合计)
    REPAY_TYP VARCHAR(4) NULL, -- 还款方式
    REPAY_ACCT_NO VARCHAR(30) NULL, -- 还款账号
    CATE_5LVL VARCHAR(2) NULL, -- 五级分类
    CTRAKT_ID VARCHAR(100) NULL, -- 合同编号
    CMS_CUST_ID VARCHAR(50) NULL, -- 信贷客户编号
    OVER_DAYS VARCHAR(10) NULL, -- 逾期天数
    GUARANT_MODE VARCHAR(4) NULL -- 担保方式
);

COMMENT ON TABLE DWD_ACCT_LOAN IS '贷款账户';
COMMENT ON COLUMN DWD_ACCT_LOAN.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_ACCT_LOAN.CUST_TYP IS '客户类型';
COMMENT ON COLUMN DWD_ACCT_LOAN.ACCT_ID IS '账号';
COMMENT ON COLUMN DWD_ACCT_LOAN.PRDKT_ID IS '产品编号';
COMMENT ON COLUMN DWD_ACCT_LOAN.PRDKT_NAME IS '产品名称';
COMMENT ON COLUMN DWD_ACCT_LOAN.PRDKT_CATE_BIG IS '产品大类';
COMMENT ON COLUMN DWD_ACCT_LOAN.LOAN_ISSU_AMT IS '借据金额';
COMMENT ON COLUMN DWD_ACCT_LOAN.LOAN_ISSU_DATE IS '贷款发放日期';
COMMENT ON COLUMN DWD_ACCT_LOAN.BAL IS '余额';
COMMENT ON COLUMN DWD_ACCT_LOAN.RATE_INTRI IS '利率';
COMMENT ON COLUMN DWD_ACCT_LOAN.EXPR_DATE IS '到期日期';
COMMENT ON COLUMN DWD_ACCT_LOAN.ACCT_STATE IS '账户状态';
COMMENT ON COLUMN DWD_ACCT_LOAN.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_ACCT_LOAN.OPRT_ORG IS '经办机构';
COMMENT ON COLUMN DWD_ACCT_LOAN.IOU_NO IS '借据号';
COMMENT ON COLUMN DWD_ACCT_LOAN.INT_ARREARS_TTL IS '欠息(合计)';
COMMENT ON COLUMN DWD_ACCT_LOAN.REPAY_TYP IS '还款方式';
COMMENT ON COLUMN DWD_ACCT_LOAN.REPAY_ACCT_NO IS '还款账号';
COMMENT ON COLUMN DWD_ACCT_LOAN.CATE_5LVL IS '五级分类';
COMMENT ON COLUMN DWD_ACCT_LOAN.CTRAKT_ID IS '合同编号';
COMMENT ON COLUMN DWD_ACCT_LOAN.CMS_CUST_ID IS '信贷客户编号';
COMMENT ON COLUMN DWD_ACCT_LOAN.OVER_DAYS IS '逾期天数';
COMMENT ON COLUMN DWD_ACCT_LOAN.GUARANT_MODE IS '担保方式';
