/*
 * DWD_PRDKT_INFO
 * 中文名称: 产品信息表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_PRDKT_INFO (
    PRDKT_ID VARCHAR(40) NOT NULL, -- 产品编号
    PRDKT_NAME VARCHAR(100) NULL, -- 产品名称
    PRDKT_CATE_BIG VARCHAR(10) NULL, -- 产品大类
    BGN_DATE VARCHAR(10) NULL, -- 开始日期
    END_DATE VARCHAR(10) NULL, -- 结束日期
    PRDKT_LINE VARCHAR(10) NULL, -- 产品条线
    SUP_PRDKT_ID VARCHAR(30) NULL, -- 上级产品编号
    MDL_BIZ_RATE_FEE NUMBER(18,4) NULL, -- 中间业务费率
    PRDKT_RATE NUMBER(18,4) NULL, -- 产品利率
    SYS_SRC VARCHAR(6) NULL, -- 系统来源
    PRDKT_STATE VARCHAR(10) NULL, -- 产品状态(在售/停售)
    PERSN_LEGAL_BK_CODE VARCHAR(30) NULL -- 法人行号
);

COMMENT ON TABLE DWD_PRDKT_INFO IS '产品信息表';
COMMENT ON COLUMN DWD_PRDKT_INFO.PRDKT_ID IS '产品编号';
COMMENT ON COLUMN DWD_PRDKT_INFO.PRDKT_NAME IS '产品名称';
COMMENT ON COLUMN DWD_PRDKT_INFO.PRDKT_CATE_BIG IS '产品大类';
COMMENT ON COLUMN DWD_PRDKT_INFO.BGN_DATE IS '开始日期';
COMMENT ON COLUMN DWD_PRDKT_INFO.END_DATE IS '结束日期';
COMMENT ON COLUMN DWD_PRDKT_INFO.PRDKT_LINE IS '产品条线';
COMMENT ON COLUMN DWD_PRDKT_INFO.SUP_PRDKT_ID IS '上级产品编号';
COMMENT ON COLUMN DWD_PRDKT_INFO.MDL_BIZ_RATE_FEE IS '中间业务费率';
COMMENT ON COLUMN DWD_PRDKT_INFO.PRDKT_RATE IS '产品利率';
COMMENT ON COLUMN DWD_PRDKT_INFO.SYS_SRC IS '系统来源';
COMMENT ON COLUMN DWD_PRDKT_INFO.PRDKT_STATE IS '产品状态(在售/停售)';
COMMENT ON COLUMN DWD_PRDKT_INFO.PERSN_LEGAL_BK_CODE IS '法人行号';
