/*
 * DWD_SYS_ORG
 * 中文名称: 机构表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_SYS_ORG (
    ORG_ID VARCHAR(7) NOT NULL,
    SUP_ORG_ID VARCHAR(7) NULL,
    ORG_PATH VARCHAR(200) NULL,
    ORG_NAME VARCHAR(100) NULL,
    SUP_ORG_NAME VARCHAR(100) NULL,
    DIRECT_UNDER_ORG VARCHAR(7) NULL,
    ORG_TYP VARCHAR(10) NULL,
    ORG_HARCY VARCHAR(10) NULL,
    ORG_ADDRS VARCHAR(800) NULL,
    ORG_STATE VARCHAR(1) NULL,
    DSPLY_SEQ VARCHAR(100) NULL,
    CREATR VARCHAR(64) NULL,
    CREAT_TIME VARCHAR(20) NULL,
    CREAT_ORG VARCHAR(7) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL,
    HR_MS_ORG_ID VARCHAR(80) NULL,
    ORG_LGTUD VARCHAR(30) NULL,
    ORG_LATTUD VARCHAR(30) NULL,
    ORG_RSPONR VARCHAR(40) NULL,
    ORG_TEL VARCHAR(30) NULL
);

COMMENT ON TABLE DWD_SYS_ORG IS '机构表';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_ID IS '机构编号';
COMMENT ON COLUMN DWD_SYS_ORG.SUP_ORG_ID IS '上级机构编号';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_PATH IS '机构路径';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_NAME IS '机构名称';
COMMENT ON COLUMN DWD_SYS_ORG.SUP_ORG_NAME IS '上级机构名称';
COMMENT ON COLUMN DWD_SYS_ORG.DIRECT_UNDER_ORG IS '直属机构';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_TYP IS '机构类型';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_HARCY IS '机构层级';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_ADDRS IS '机构地址';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_STATE IS '机构状态';
COMMENT ON COLUMN DWD_SYS_ORG.DSPLY_SEQ IS '显示顺序';
COMMENT ON COLUMN DWD_SYS_ORG.CREATR IS '创建人';
COMMENT ON COLUMN DWD_SYS_ORG.CREAT_TIME IS '创建时间';
COMMENT ON COLUMN DWD_SYS_ORG.CREAT_ORG IS '创建机构';
COMMENT ON COLUMN DWD_SYS_ORG.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_SYS_ORG.HR_MS_ORG_ID IS '人力资源系统机构号';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_LGTUD IS '机构经度';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_LATTUD IS '机构纬度';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_RSPONR IS '机构负责人';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_TEL IS '机构电话';