/*
 * DWD_PRDKT_INFO_DETAIL
 * 中文名称: 产品详情表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_PRDKT_INFO_DETAIL (
    PK_ID VARCHAR NOT NULL, -- 主键
    PRDKT_CATLOG_PATH VARCHAR NULL, -- 产品目录
    COL_CODE VARCHAR NULL, -- 属性ID
    COL_NAME VARCHAR NULL, -- 属性名称
    COL_VALUE VARCHAR NULL, -- 属性值
    ORG_ID VARCHAR NULL, -- 机构号
    JIGOUHAO VARCHAR NULL, -- 机构号
    RN NUMBER NULL, -- 序号
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL -- 法人行号
);

COMMENT ON TABLE DWD_PRDKT_INFO_DETAIL IS '产品详情表';
COMMENT ON COLUMN DWD_PRDKT_INFO_DETAIL.PK_ID IS '主键';
COMMENT ON COLUMN DWD_PRDKT_INFO_DETAIL.PRDKT_CATLOG_PATH IS '产品目录';
COMMENT ON COLUMN DWD_PRDKT_INFO_DETAIL.COL_CODE IS '属性ID';
COMMENT ON COLUMN DWD_PRDKT_INFO_DETAIL.COL_NAME IS '属性名称';
COMMENT ON COLUMN DWD_PRDKT_INFO_DETAIL.COL_VALUE IS '属性值';
COMMENT ON COLUMN DWD_PRDKT_INFO_DETAIL.ORG_ID IS '机构号';
COMMENT ON COLUMN DWD_PRDKT_INFO_DETAIL.JIGOUHAO IS '机构号';
COMMENT ON COLUMN DWD_PRDKT_INFO_DETAIL.RN IS '序号';
COMMENT ON COLUMN DWD_PRDKT_INFO_DETAIL.PERSN_LEGAL_BK_CODE IS '法人行号';
