CREATE TABLE IF NOT EXISTS DWD_CUST_INDV_KYC (
    CUST_ID VARCHAR(20) NOT NULL,
    CUST_NM VARCHAR(100),
    BK_OUTER_DEPO NUMBER(20),
    BK_OUTER_FIN NUMBER(20),
    BK_OUTER_FUND NUMBER(20),
    BK_OUTER_INSUR NUMBER(20),
    BK_OUTER_GOLD NUMBER(20),
    STK_INVEST VARCHAR(2),
    ESTT_INF VARCHAR(2),
    PROP_OWNER_CERT_NO VARCHAR(60),
    HOUSE_AREA NUMBER(10),
    IS_HOUSE_MORTGAGED VARCHAR(1),
    RES_ADDRS VARCHAR(254),
    SHOP_INVEST VARCHAR(2),
    VIKL_INF VARCHAR(2),
    VEHICLE_PLATE_NO VARCHAR(10),
    USAGE_NATURE VARCHAR(100),
    IS_CAR_LOAN VARCHAR(2),
    IS_CAR_MORTGAGED VARCHAR(2),
    MTH_INCOM NUMBER(20),
    YR_INCOM NUMBER(20),
    BK_OUTER_LOAN_BAL NUMBER(20),
    BK_OUTER_CRDT_LMT NUMBER(20),
    AVAIL_LMT NUMBER(20),
    CREATR VARCHAR(20),
    CREAT_ORG VARCHAR(7),
    CREAT_TIME VARCHAR(20)
);
COMMENT ON TABLE DWD_CUST_INDV_KYC IS '客户KYC信息表';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.CUST_NM IS '客户名称';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_DEPO IS '行外存款';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_FIN IS '行外理财';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_FUND IS '行外基金';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_INSUR IS '行外保险';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_GOLD IS '行外贵金属';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.STK_INVEST IS '股票投资';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.ESTT_INF IS '住宅信息';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.PROP_OWNER_CERT_NO IS '房产证号';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.HOUSE_AREA IS '面积';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.IS_HOUSE_MORTGAGED IS '是否抵押';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.RES_ADDRS IS '地址';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.SHOP_INVEST IS '商铺投资';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.VIKL_INF IS '车辆信息';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.VEHICLE_PLATE_NO IS '车牌号';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.USAGE_NATURE IS '使用性质';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.IS_CAR_LOAN IS '是否有车贷';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.IS_CAR_MORTGAGED IS '是否抵押';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.MTH_INCOM IS '月收入';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.YR_INCOM IS '年收入';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_LOAN_BAL IS '行外贷款余额';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_CRDT_LMT IS '行外授信额度';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.AVAIL_LMT IS '可用额度';