/*
 * DWD_CUST_DORMANT_ACCOUT
 * 中文名称: 睡眠户信息表
 * 版本: v1.0
 * 创建时间: 2026-07-23
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_DORMANT_ACCOUT (
    DATA_DATE VARCHAR(8) NULL,
    CUST_ID VARCHAR(20) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(7) NULL
);

COMMENT ON TABLE DWD_CUST_DORMANT_ACCOUT IS '睡眠户信息表';
COMMENT ON COLUMN DWD_CUST_DORMANT_ACCOUT.DATA_DATE IS '数据日期';
COMMENT ON COLUMN DWD_CUST_DORMANT_ACCOUT.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_DORMANT_ACCOUT.PERSN_LEGAL_BK_CODE IS '法人行号';
