/*
 * DWD_CUST_INDV_KYC
 * 中文名称: 客户KYC信息表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_INDV_KYC (
    CUST_ID VARCHAR NOT NULL, -- 客户编号
    CUST_NM VARCHAR NULL, -- 客户名称
    BK_OUTER_DEPO NUMBER NULL, -- 行外存款
    BK_OUTER_FIN NUMBER NULL, -- 行外理财
    BK_OUTER_FUND NUMBER NULL, -- 行外基金
    BK_OUTER_INSUR NUMBER NULL, -- 行外保险
    BK_OUTER_GOLD NUMBER NULL, -- 行外贵金属
    STK_INVEST VARCHAR NULL, -- 股票投资
    ESTT_INF VARCHAR NULL, -- 住宅信息
    PROP_OWNER_CERT_NO VARCHAR NULL, -- 房产证号
    HOUSE_AREA NUMBER NULL, -- 面积
    IS_HOUSE_MORTGAGED VARCHAR NULL, -- 是否抵押
    RES_ADDRS VARCHAR NULL, -- 地址
    SHOP_INVEST VARCHAR NULL, -- 商铺投资
    VIKL_INF VARCHAR NULL, -- 车辆信息
    VEHICLE_PLATE_NO VARCHAR NULL, -- 车牌号
    USAGE_NATURE VARCHAR NULL, -- 使用性质
    IS_CAR_LOAN VARCHAR NULL, -- 是否有车贷
    IS_CAR_MORTGAGED VARCHAR NULL, -- 是否抵押
    MTH_INCOM NUMBER NULL, -- 月收入
    YR_INCOM NUMBER NULL, -- 年收入
    BK_OUTER_LOAN_BAL NUMBER NULL, -- 行外贷款余额
    BK_OUTER_CRDT_LMT NUMBER NULL, -- 行外授信额度
    AVAIL_LMT NUMBER NULL, -- 可用额度
    CREATR VARCHAR NULL, -- 创建人
    CREAT_ORG VARCHAR NULL, -- 创建机构
    CREAT_TIME VARCHAR NULL -- 创建时间
);

COMMENT ON TABLE DWD_CUST_INDV_KYC IS '客户KYC信息表';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.CUST_NM IS '客户名称';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_DEPO IS '行外存款';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_FIN IS '行外理财';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_FUND IS '行外基金';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_INSUR IS '行外保险';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_GOLD IS '行外贵金属';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.STK_INVEST IS '股票投资';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.ESTT_INF IS '住宅信息';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.PROP_OWNER_CERT_NO IS '房产证号';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.HOUSE_AREA IS '面积';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.IS_HOUSE_MORTGAGED IS '是否抵押';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.RES_ADDRS IS '地址';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.SHOP_INVEST IS '商铺投资';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.VIKL_INF IS '车辆信息';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.VEHICLE_PLATE_NO IS '车牌号';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.USAGE_NATURE IS '使用性质';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.IS_CAR_LOAN IS '是否有车贷';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.IS_CAR_MORTGAGED IS '是否抵押';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.MTH_INCOM IS '月收入';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.YR_INCOM IS '年收入';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_LOAN_BAL IS '行外贷款余额';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_CRDT_LMT IS '行外授信额度';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.AVAIL_LMT IS '可用额度';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.CREATR IS '创建人';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.CREAT_ORG IS '创建机构';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.CREAT_TIME IS '创建时间';
