/*
 * DWD_TX_ASET
 * 中文名称: 资产类交易
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_TX_ASET (
    DATA_DATE VARCHAR(8) NULL, -- 数据日期
    SEQ_ID VARCHAR(40) NOT NULL, -- 流水号
    CUST_ID VARCHAR(21) NULL, -- 客户编号
    CUST_NAME VARCHAR(100) NULL, -- 客户名称
    CUST_TYP VARCHAR(4) NULL, -- 客户类型
    ACCT_ID VARCHAR(40) NULL, -- 账户
    PRDKT_ID VARCHAR(40) NULL, -- 产品ID
    TX_CHNL VARCHAR(10) NULL, -- 交易渠道
    TX_DATE VARCHAR(10) NULL, -- 交易日期
    TX_TIME VARCHAR(20) NULL, -- 交易时间
    CCY_CD VARCHAR(6) NULL, -- 币种
    AMT NUMBER(18,4) NULL, -- 发生额
    TX_ORG VARCHAR(20) NULL, -- 交易机构
    OPRTR VARCHAR(20) NULL, -- 经办人
    LOAN_FLG VARCHAR(3) NULL, -- 借贷标识
    ACCT_BAL NUMBER(18,4) NULL, -- 账户余额
    TX_DSC VARCHAR(200) NULL, -- 交易说明
    OPNT_ACCT VARCHAR(32) NULL, -- 对方账户
    OPNT_ACCT_NAME_FST VARCHAR(200) NULL, -- 对方户名
    OPNT_BK_KEEP VARCHAR(20) NULL, -- 对方行
    OPNT_NAME_BK VARCHAR(200) NULL, -- 对方行名
    JIOYCFFS VARCHAR(1) NULL, -- 交易触发方式(0-主动 1-被动)
    XIANZZBZ VARCHAR(1) NULL, -- 现转标志(0-现金,1-转账)
    DUIFKHLX VARCHAR(2) NULL, -- 对方客户类型(00-同业客户,01-对私客户,02-对公客户,03-内部客户)
    CHONGZBZ VARCHAR(1) NULL, -- 冲正标志(0-无关,1-当日冲正,2-隔日冲正)
    ACCT_BLNG_ORG VARCHAR(20) NULL, -- 账户归属机构
    CARD_NO VARCHAR(30) NULL, -- 卡/折号
    PERSN_LEGAL_BK_CODE VARCHAR(30) NULL -- 法人行号
);

COMMENT ON TABLE DWD_TX_ASET IS '资产类交易';
COMMENT ON COLUMN DWD_TX_ASET.DATA_DATE IS '数据日期';
COMMENT ON COLUMN DWD_TX_ASET.SEQ_ID IS '流水号';
COMMENT ON COLUMN DWD_TX_ASET.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_TX_ASET.CUST_NAME IS '客户名称';
COMMENT ON COLUMN DWD_TX_ASET.CUST_TYP IS '客户类型';
COMMENT ON COLUMN DWD_TX_ASET.ACCT_ID IS '账户';
COMMENT ON COLUMN DWD_TX_ASET.PRDKT_ID IS '产品ID';
COMMENT ON COLUMN DWD_TX_ASET.TX_CHNL IS '交易渠道';
COMMENT ON COLUMN DWD_TX_ASET.TX_DATE IS '交易日期';
COMMENT ON COLUMN DWD_TX_ASET.TX_TIME IS '交易时间';
COMMENT ON COLUMN DWD_TX_ASET.CCY_CD IS '币种';
COMMENT ON COLUMN DWD_TX_ASET.AMT IS '发生额';
COMMENT ON COLUMN DWD_TX_ASET.TX_ORG IS '交易机构';
COMMENT ON COLUMN DWD_TX_ASET.OPRTR IS '经办人';
COMMENT ON COLUMN DWD_TX_ASET.LOAN_FLG IS '借贷标识';
COMMENT ON COLUMN DWD_TX_ASET.ACCT_BAL IS '账户余额';
COMMENT ON COLUMN DWD_TX_ASET.TX_DSC IS '交易说明';
COMMENT ON COLUMN DWD_TX_ASET.OPNT_ACCT IS '对方账户';
COMMENT ON COLUMN DWD_TX_ASET.OPNT_ACCT_NAME_FST IS '对方户名';
COMMENT ON COLUMN DWD_TX_ASET.OPNT_BK_KEEP IS '对方行';
COMMENT ON COLUMN DWD_TX_ASET.OPNT_NAME_BK IS '对方行名';
COMMENT ON COLUMN DWD_TX_ASET.JIOYCFFS IS '交易触发方式(0-主动 1-被动)';
COMMENT ON COLUMN DWD_TX_ASET.XIANZZBZ IS '现转标志(0-现金,1-转账)';
COMMENT ON COLUMN DWD_TX_ASET.DUIFKHLX IS '对方客户类型(00-同业客户,01-对私客户,02-对公客户,03-内部客户)';
COMMENT ON COLUMN DWD_TX_ASET.CHONGZBZ IS '冲正标志(0-无关,1-当日冲正,2-隔日冲正)';
COMMENT ON COLUMN DWD_TX_ASET.ACCT_BLNG_ORG IS '账户归属机构';
COMMENT ON COLUMN DWD_TX_ASET.CARD_NO IS '卡/折号';
COMMENT ON COLUMN DWD_TX_ASET.PERSN_LEGAL_BK_CODE IS '法人行号';
