/*
 * DWD_CUST_INDV_HOUSE_KYC
 * 中文名称: 客户房产KYC信息表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_INDV_HOUSE_KYC (
    PK_ID VARCHAR NULL, -- 主键
    PERSN_LEGAL_BK_CODE VARCHAR NULL, -- 法人行号
    CUST_ID VARCHAR NOT NULL, -- 客户编号
    CUST_NAME VARCHAR NULL, -- 客户名称
    PROP_OWNER_CERT_NO VARCHAR NULL, -- 房产证号
    HOUSE_AREA NUMBER NULL, -- 面积
    IS_HOUSE_MORTGAGED VARCHAR NULL, -- 是否抵押
    RES_ADDRS VARCHAR NULL, -- 地址
    CREATR VARCHAR NULL, -- 创建人
    CREAT_ORG VARCHAR NULL, -- 创建机构
    CREAT_TIME VARCHAR NULL -- 创建时间
);

COMMENT ON TABLE DWD_CUST_INDV_HOUSE_KYC IS '客户房产KYC信息表';
COMMENT ON COLUMN DWD_CUST_INDV_HOUSE_KYC.PK_ID IS '主键';
COMMENT ON COLUMN DWD_CUST_INDV_HOUSE_KYC.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_CUST_INDV_HOUSE_KYC.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_INDV_HOUSE_KYC.CUST_NAME IS '客户名称';
COMMENT ON COLUMN DWD_CUST_INDV_HOUSE_KYC.PROP_OWNER_CERT_NO IS '房产证号';
COMMENT ON COLUMN DWD_CUST_INDV_HOUSE_KYC.HOUSE_AREA IS '面积';
COMMENT ON COLUMN DWD_CUST_INDV_HOUSE_KYC.IS_HOUSE_MORTGAGED IS '是否抵押';
COMMENT ON COLUMN DWD_CUST_INDV_HOUSE_KYC.RES_ADDRS IS '地址';
COMMENT ON COLUMN DWD_CUST_INDV_HOUSE_KYC.CREATR IS '创建人';
COMMENT ON COLUMN DWD_CUST_INDV_HOUSE_KYC.CREAT_ORG IS '创建机构';
COMMENT ON COLUMN DWD_CUST_INDV_HOUSE_KYC.CREAT_TIME IS '创建时间';
