/*
 * DWD_CUST_SIGN_CTRAKT
 * 中文名称: 客户签约信息
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_SIGN_CTRAKT (
    CUST_ID VARCHAR(20) NOT NULL,
    CTRAKT_ACCT VARCHAR(40) NULL,
    CTRAKT_TYP VARCHAR(6) NULL,
    CTRAKT_DATE VARCHAR(10) NULL,
    PHONE_NO VARCHAR(32) NULL,
    CTRAKT_ORG VARCHAR(6) NULL,
    CTRAKT_OPRTR VARCHAR(20) NULL,
    CTRAKT_STATE VARCHAR(2) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL
);

COMMENT ON TABLE DWD_CUST_SIGN_CTRAKT IS '客户签约信息';
COMMENT ON COLUMN DWD_CUST_SIGN_CTRAKT.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_SIGN_CTRAKT.CTRAKT_ACCT IS '签约账户';
COMMENT ON COLUMN DWD_CUST_SIGN_CTRAKT.CTRAKT_TYP IS '签约类型';
COMMENT ON COLUMN DWD_CUST_SIGN_CTRAKT.CTRAKT_DATE IS '签约日期';
COMMENT ON COLUMN DWD_CUST_SIGN_CTRAKT.PHONE_NO IS '手机号';
COMMENT ON COLUMN DWD_CUST_SIGN_CTRAKT.CTRAKT_ORG IS '签约机构';
COMMENT ON COLUMN DWD_CUST_SIGN_CTRAKT.CTRAKT_OPRTR IS '签约经办人';
COMMENT ON COLUMN DWD_CUST_SIGN_CTRAKT.CTRAKT_STATE IS '签约状态';
COMMENT ON COLUMN DWD_CUST_SIGN_CTRAKT.PERSN_LEGAL_BK_CODE IS '法人行号';