/*
 * DWD_CUST_CTRAKT_INFO
 * 中文名称: 客户合同信息
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_CTRAKT_INFO (
    CUST_ID VARCHAR(100) NOT NULL,
    CTRAKT_ID VARCHAR(100) NULL,
    LOAN_ACCT VARCHAR(100) NULL,
    CRDT_LMT VARCHAR(100) NULL,
    LOAN_BAL VARCHAR(100) NULL,
    GUARANT_MODE VARCHAR(100) NULL,
    CATE_5LVL VARCHAR(100) NULL,
    CCY_CD VARCHAR(100) NULL,
    RATE_INTRI VARCHAR(100) NULL,
    CONTR_AMT VARCHAR(100) NULL,
    BGN_DATE VARCHAR(100) NULL,
    END_DATE VARCHAR(100) NULL,
    OPRTR VARCHAR(100) NULL,
    OPRT_ORG VARCHAR(7) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(7) NULL
);

COMMENT ON TABLE DWD_CUST_CTRAKT_INFO IS '客户合同信息';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.CTRAKT_ID IS '合同编号';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.LOAN_ACCT IS '贷款账号';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.CRDT_LMT IS '授信额度';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.LOAN_BAL IS '贷款余额';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.GUARANT_MODE IS '担保方式';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.CATE_5LVL IS '五级分类';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.CCY_CD IS '币种';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.RATE_INTRI IS '利率';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.CONTR_AMT IS '合同金额';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.BGN_DATE IS '发放日期';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.END_DATE IS '结束日期';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.OPRTR IS '经办人';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.OPRT_ORG IS '经办机构';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.PERSN_LEGAL_BK_CODE IS '法人行号';
