/*
 * DWD_CUST_ENTER_RELA
 * 中文名称: 客户关联关系表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_ENTER_RELA (
    CUST_ID VARCHAR(20) NULL, -- 客户编号
    REL_TYP VARCHAR(1) NULL, -- 关系类型
    REL_CUST_ID VARCHAR(20) NULL, -- 关联人客户编号
    REL_CUST_NAME VARCHAR(100) NULL, -- 关联人客户名称
    REL_VAL NUMBER NULL, -- 关联值
    BK_SELF_CUST_FLG VARCHAR(1) NULL, -- 是否我行客户
    REL_INF VARCHAR(800) NULL, -- 关系内容
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL -- 法人行号
);

COMMENT ON TABLE DWD_CUST_ENTER_RELA IS '客户关联关系表';
COMMENT ON COLUMN DWD_CUST_ENTER_RELA.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_ENTER_RELA.REL_TYP IS '关系类型';
COMMENT ON COLUMN DWD_CUST_ENTER_RELA.REL_CUST_ID IS '关联人客户编号';
COMMENT ON COLUMN DWD_CUST_ENTER_RELA.REL_CUST_NAME IS '关联人客户名称';
COMMENT ON COLUMN DWD_CUST_ENTER_RELA.REL_VAL IS '关联值';
COMMENT ON COLUMN DWD_CUST_ENTER_RELA.BK_SELF_CUST_FLG IS '是否我行客户';
COMMENT ON COLUMN DWD_CUST_ENTER_RELA.REL_INF IS '关系内容';
COMMENT ON COLUMN DWD_CUST_ENTER_RELA.PERSN_LEGAL_BK_CODE IS '法人行号';
