/*
 * DWD_TX_ASET
 * 中文名称: 资产类交易
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_TX_ASET (
    SEQ_ID VARCHAR(40) NOT NULL,
    CUST_ID VARCHAR(21) NULL,
    CUST_TYP VARCHAR(4) NULL,
    ACCT_ID VARCHAR(40) NULL,
    PRDKT_CATE_BIG VARCHAR(6) NULL,
    PRDKT_ID VARCHAR(40) NULL,
    TX_CHNL VARCHAR(10) NULL,
    TX_DATE VARCHAR(10) NULL,
    TX_TIME VARCHAR(20) NULL,
    CCY_CD VARCHAR(6) NULL,
    TX_TYP VARCHAR(6) NULL,
    AMT NUMBER(18,
    4) NULL,
    TX_TYP_NAME VARCHAR(80) NULL,
    TX_ORG VARCHAR(7) NULL,
    OPRTR VARCHAR(20) NULL,
    LOAN_FLG VARCHAR(3) NULL,
    ACCT_BAL NUMBER(18,
    4) NULL,
    TX_DSC VARCHAR(200) NULL,
    OPNT_ACCT VARCHAR(32) NULL,
    OPNT_ACCT_NAME_FST VARCHAR(200) NULL,
    OPNT_BK_KEEP VARCHAR(20) NULL,
    OPNT_NAME_BK VARCHAR(200) NULL,
    FEE_HAND NUMBER(18,
    4) NULL,
    ACCT_BLNG_ORG VARCHAR(7) NULL,
    CARD_NO VARCHAR(30) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(30) NULL
);

COMMENT ON TABLE DWD_TX_ASET IS '资产类交易';
COMMENT ON COLUMN DWD_TX_ASET.SEQ_ID IS '流水号';
COMMENT ON COLUMN DWD_TX_ASET.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_TX_ASET.CUST_TYP IS '客户类型';
COMMENT ON COLUMN DWD_TX_ASET.ACCT_ID IS '账户';
COMMENT ON COLUMN DWD_TX_ASET.PRDKT_CATE_BIG IS '产品大类';
COMMENT ON COLUMN DWD_TX_ASET.PRDKT_ID IS '产品ID';
COMMENT ON COLUMN DWD_TX_ASET.TX_CHNL IS '交易渠道';
COMMENT ON COLUMN DWD_TX_ASET.TX_DATE IS '交易日期';
COMMENT ON COLUMN DWD_TX_ASET.TX_TIME IS '交易时间';
COMMENT ON COLUMN DWD_TX_ASET.CCY_CD IS '币种';
COMMENT ON COLUMN DWD_TX_ASET.TX_TYP IS '交易类型';
COMMENT ON COLUMN DWD_TX_ASET.AMT IS '发生额';
COMMENT ON COLUMN DWD_TX_ASET.TX_TYP_NAME IS '交易类型名称';
COMMENT ON COLUMN DWD_TX_ASET.TX_ORG IS '交易机构';
COMMENT ON COLUMN DWD_TX_ASET.OPRTR IS '经办人';
COMMENT ON COLUMN DWD_TX_ASET.LOAN_FLG IS '借贷标识';
COMMENT ON COLUMN DWD_TX_ASET.ACCT_BAL IS '账户余额';
COMMENT ON COLUMN DWD_TX_ASET.TX_DSC IS '交易说明';
COMMENT ON COLUMN DWD_TX_ASET.OPNT_ACCT IS '对方账户';
COMMENT ON COLUMN DWD_TX_ASET.OPNT_ACCT_NAME_FST IS '对方户名';
COMMENT ON COLUMN DWD_TX_ASET.OPNT_BK_KEEP IS '对方行';
COMMENT ON COLUMN DWD_TX_ASET.OPNT_NAME_BK IS '对方行名';
COMMENT ON COLUMN DWD_TX_ASET.FEE_HAND IS '手续费';
COMMENT ON COLUMN DWD_TX_ASET.ACCT_BLNG_ORG IS '账户归属机构';
COMMENT ON COLUMN DWD_TX_ASET.CARD_NO IS '卡/折号';
COMMENT ON COLUMN DWD_TX_ASET.PERSN_LEGAL_BK_CODE IS '法人行号';