/*
 * DWD_PRDKT_INFO_ZB
 * 中文名称: 产品信息表子表(普通定期存款产品粒度)
 * 版本: v1.0
 * 创建时间: 2026-08-26
 * 需求版本: REQ-RCMD-001 (V1.0.2)
 * 来源: reference_logic/ALL_TB.sql 行13453 (资产入库同步)
 * 加工过程: PRC_DWD_PRDKT_INFO 首段 (reference_logic/ALL_PRC.sql 行35890)
 * 粒度说明: 产品编号 x 存期 x 币种, 一产品多存期档多行
 * 变更记录:
 *   v1.0 2026-08-26 首次入库, 从参考逻辑 ALL_TB.sql 同步 DDL
 */

CREATE TABLE IF NOT EXISTS DWD_PRDKT_INFO_ZB (
    PERSN_LEGAL_BK_CODE VARCHAR(4) NOT NULL, -- 法人行号
    DATA_DATE VARCHAR(8) NOT NULL, -- 数据日期
    PRDKT_ID VARCHAR(40) NOT NULL, -- 产品编号(CBS_||产品编号,关联DWD_PRDKT_INFO)
    PRDKT_TERM VARCHAR(10) NOT NULL, -- 存期(已归一化:1Y->12M,2Y->24M,3Y->36M,5Y->60M)
    PRDKT_CCY VARCHAR(10) NOT NULL, -- 币种
    PRDKT_RATE NUMBER(10,4) NOT NULL, -- 实际利率(生效日<=跑批日最新一条)
    PRDKT_LIMIT_AMT NUMBER(20,2), -- 起存金额(单次存入最小金额,缺省0)
    IS_SELL VARCHAR(10) -- 是否在售(是/否,来源CHAPZHUT产品状态)
);

COMMENT ON TABLE DWD_PRDKT_INFO_ZB IS '产品信息表子表(普通定期存款产品粒度)';
COMMENT ON COLUMN DWD_PRDKT_INFO_ZB.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_PRDKT_INFO_ZB.DATA_DATE IS '数据日期';
COMMENT ON COLUMN DWD_PRDKT_INFO_ZB.PRDKT_ID IS '产品编号(CBS_||产品编号,关联DWD_PRDKT_INFO)';
COMMENT ON COLUMN DWD_PRDKT_INFO_ZB.PRDKT_TERM IS '存期(已归一化:1Y->12M,2Y->24M,3Y->36M,5Y->60M)';
COMMENT ON COLUMN DWD_PRDKT_INFO_ZB.PRDKT_CCY IS '币种';
COMMENT ON COLUMN DWD_PRDKT_INFO_ZB.PRDKT_RATE IS '实际利率(生效日<=跑批日最新一条)';
COMMENT ON COLUMN DWD_PRDKT_INFO_ZB.PRDKT_LIMIT_AMT IS '起存金额(单次存入最小金额,缺省0)';
COMMENT ON COLUMN DWD_PRDKT_INFO_ZB.IS_SELL IS '是否在售(是/否,来源CHAPZHUT产品状态)';

CREATE INDEX IF NOT EXISTS IDX_DWD_PRDKT_INFO_ZB_1 ON DWD_PRDKT_INFO_ZB (PRDKT_ID);
