/*
 * DWD_CRM_SYS_XTHLCS
 * 中文名称: 货币汇率表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_CRM_SYS_XTHLCS (
    HUOBDAIH VARCHAR NOT NULL, -- 货币代号
    PJDANWEI NUMBER NOT NULL, -- 牌价单位
    HUOBFHAO VARCHAR NULL, -- 货币符号
    ZHNGJJIA NUMBER NULL, -- 中间价
    HL NUMBER NULL -- 汇率
);

COMMENT ON TABLE DWD_CRM_SYS_XTHLCS IS '货币汇率表';
COMMENT ON COLUMN DWD_CRM_SYS_XTHLCS.HUOBDAIH IS '货币代号';
COMMENT ON COLUMN DWD_CRM_SYS_XTHLCS.PJDANWEI IS '牌价单位';
COMMENT ON COLUMN DWD_CRM_SYS_XTHLCS.HUOBFHAO IS '货币符号';
COMMENT ON COLUMN DWD_CRM_SYS_XTHLCS.ZHNGJJIA IS '中间价';
COMMENT ON COLUMN DWD_CRM_SYS_XTHLCS.HL IS '汇率';
