/*
 * DWD_MKT_TSK_INDX_SUB
 * 中文名称: 指标任务详情
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_MKT_TSK_INDX_SUB (
    TSK_INDX_ID VARCHAR(40) NULL, -- 指标任务映射编号
    TSK_ID VARCHAR(40) NULL, -- 任务编号
    MAIN_TSK_ID VARCHAR(40) NULL, -- 主任务编号
    INDX_ID VARCHAR(40) NULL, -- 指标ID
    TSK_DSC VARCHAR(500) NULL, -- 指标任务说明
    TSK_BGN_DATE VARCHAR(10) NULL, -- 任务开始时间
    TSK_END_DATE VARCHAR(10) NULL, -- 任务结束时间
    INDX_UNIT VARCHAR(6) NULL, -- 指标单位(万元/个数/百分比)
    INDX_VAL NUMBER(22) NULL, -- 指标额
    INDX_VAL_ADD NUMBER(22) NULL, -- 指标加码
    BASE_VAL NUMBER(22) NULL, -- 基准值
    PERSN_LEGAL_BK_CODE VARCHAR(30) NULL -- 法人行号
);

COMMENT ON TABLE DWD_MKT_TSK_INDX_SUB IS '指标任务详情';
COMMENT ON COLUMN DWD_MKT_TSK_INDX_SUB.TSK_INDX_ID IS '指标任务映射编号';
COMMENT ON COLUMN DWD_MKT_TSK_INDX_SUB.TSK_ID IS '任务编号';
COMMENT ON COLUMN DWD_MKT_TSK_INDX_SUB.MAIN_TSK_ID IS '主任务编号';
COMMENT ON COLUMN DWD_MKT_TSK_INDX_SUB.INDX_ID IS '指标ID';
COMMENT ON COLUMN DWD_MKT_TSK_INDX_SUB.TSK_DSC IS '指标任务说明';
COMMENT ON COLUMN DWD_MKT_TSK_INDX_SUB.TSK_BGN_DATE IS '任务开始时间';
COMMENT ON COLUMN DWD_MKT_TSK_INDX_SUB.TSK_END_DATE IS '任务结束时间';
COMMENT ON COLUMN DWD_MKT_TSK_INDX_SUB.INDX_UNIT IS '指标单位(万元/个数/百分比)';
COMMENT ON COLUMN DWD_MKT_TSK_INDX_SUB.INDX_VAL IS '指标额';
COMMENT ON COLUMN DWD_MKT_TSK_INDX_SUB.INDX_VAL_ADD IS '指标加码';
COMMENT ON COLUMN DWD_MKT_TSK_INDX_SUB.BASE_VAL IS '基准值';
COMMENT ON COLUMN DWD_MKT_TSK_INDX_SUB.PERSN_LEGAL_BK_CODE IS '法人行号';
