/*
 * DWD_SYS_POST
 * 中文名称: 职位表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_SYS_POST (
    POST_ID VARCHAR NULL, -- 职位ID(员工号-条线-岗位分类-机构)
    EMP_ID VARCHAR NULL, -- 工号
    POST_NAME VARCHAR NULL, -- 职位名称
    JOB_NAME VARCHAR NULL, -- 岗位名称
    JOB_CLS VARCHAR NULL, -- 岗位分类(C客户经理岗/M管理岗)
    POST_STATE VARCHAR NULL, -- 职位状态
    BIZ_LINE VARCHAR NULL, -- 条线
    ORG_ID VARCHAR NULL, -- 机构ID
    ORG_CATE VARCHAR NULL, -- 机构类别
    STAT_ORG_ID VARCHAR NULL, -- 统计机构ID
    DIRECT_UNDER_ORG VARCHAR NULL, -- 直属机构
    SUP_POST_ID VARCHAR NULL, -- 上级职位编号
    DEL_FLG VARCHAR NULL, -- 是否删除
    USR_NAME VARCHAR NULL, -- 用户名称
    CREATR VARCHAR NULL, -- 创建人
    CREAT_TIME VARCHAR NULL, -- 创建时间
    CREAT_ORG VARCHAR NULL, -- 创建机构
    UPDATR VARCHAR NULL, -- 更新人
    UPD_TIME VARCHAR NULL, -- 更新时间
    MAIN_POS_FLAG VARCHAR NULL, -- 是否主职位
    PERSN_LEGAL_BK_CODE VARCHAR NULL -- 法人行号
);

COMMENT ON TABLE DWD_SYS_POST IS '职位表';
COMMENT ON COLUMN DWD_SYS_POST.POST_ID IS '职位ID(员工号-条线-岗位分类-机构)';
COMMENT ON COLUMN DWD_SYS_POST.EMP_ID IS '工号';
COMMENT ON COLUMN DWD_SYS_POST.POST_NAME IS '职位名称';
COMMENT ON COLUMN DWD_SYS_POST.JOB_NAME IS '岗位名称';
COMMENT ON COLUMN DWD_SYS_POST.JOB_CLS IS '岗位分类(C客户经理岗/M管理岗)';
COMMENT ON COLUMN DWD_SYS_POST.POST_STATE IS '职位状态';
COMMENT ON COLUMN DWD_SYS_POST.BIZ_LINE IS '条线';
COMMENT ON COLUMN DWD_SYS_POST.ORG_ID IS '机构ID';
COMMENT ON COLUMN DWD_SYS_POST.ORG_CATE IS '机构类别';
COMMENT ON COLUMN DWD_SYS_POST.STAT_ORG_ID IS '统计机构ID';
COMMENT ON COLUMN DWD_SYS_POST.DIRECT_UNDER_ORG IS '直属机构';
COMMENT ON COLUMN DWD_SYS_POST.SUP_POST_ID IS '上级职位编号';
COMMENT ON COLUMN DWD_SYS_POST.DEL_FLG IS '是否删除';
COMMENT ON COLUMN DWD_SYS_POST.USR_NAME IS '用户名称';
COMMENT ON COLUMN DWD_SYS_POST.CREATR IS '创建人';
COMMENT ON COLUMN DWD_SYS_POST.CREAT_TIME IS '创建时间';
COMMENT ON COLUMN DWD_SYS_POST.CREAT_ORG IS '创建机构';
COMMENT ON COLUMN DWD_SYS_POST.UPDATR IS '更新人';
COMMENT ON COLUMN DWD_SYS_POST.UPD_TIME IS '更新时间';
COMMENT ON COLUMN DWD_SYS_POST.MAIN_POS_FLAG IS '是否主职位';
COMMENT ON COLUMN DWD_SYS_POST.PERSN_LEGAL_BK_CODE IS '法人行号';
