/*
 * DWD_ACCT_INSUR
 * 中文名称: 保险账户信息
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_ACCT_INSUR (
    CUST_ID VARCHAR(20) NOT NULL COMMENT '客户编号',
    CUST_TYP VARCHAR(4) NULL COMMENT '客户类型',
    ACCT_ID VARCHAR(40) NULL COMMENT '账户',
    PRDKT_ID VARCHAR(40) NULL COMMENT '产品ID',
    PRDKT_NAME VARCHAR(100) NULL COMMENT '产品名称',
    PRDKT_CATE_BIG VARCHAR(64) NULL COMMENT '产品大类',
    INSUR_BID_FORM_NO VARCHAR(40) NULL COMMENT '投保单号',
    TX_DATE VARCHAR(10) NULL COMMENT '交易日期',
    TX_ORG VARCHAR(6) NULL COMMENT '交易机构',
    TX_CHNL VARCHAR(10) NULL COMMENT '交易渠道',
    MKT_ORG VARCHAR(6) NULL COMMENT '归属机构',
    BGN_INSUR_DATE VARCHAR(10) NULL COMMENT '起保日期',
    CANCL_INSUR_DATE VARCHAR(10) NULL COMMENT '退保日期',
    INSUR_PERIOD_TYP VARCHAR(2) NULL COMMENT '保险期间类型',
    INSUR_PERIOD VARCHAR(6) NULL COMMENT '保险期间值',
    PAY_PERIOD_TYP VARCHAR(2) NULL COMMENT '缴费期间类型',
    PAY_PERIOD VARCHAR(6) NULL COMMENT '缴费期间值',
    PAY_PATRN VARCHAR(2) NULL COMMENT '缴费方式',
    INSUR_AMT NUMBER(20,2) NULL COMMENT '保费金额',
    POLICY_STATE VARCHAR(10) NULL COMMENT '保单状态',
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL COMMENT '法人行号'
);

COMMENT ON TABLE DWD_ACCT_INSUR IS '保险账户信息';
