/*
 * DWD_SYS_ORG
 * 中文名称: 机构表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_SYS_ORG (
    ORG_ID VARCHAR NOT NULL, -- 机构编号
    SUP_ORG_ID VARCHAR NULL, -- 上级机构编号
    ORG_PATH VARCHAR NULL, -- 机构路径
    ORG_NAME VARCHAR NULL, -- 机构名称
    SUP_ORG_NAME VARCHAR NULL, -- 上级机构名称
    DIRECT_UNDER_ORG VARCHAR NULL, -- 直属机构
    ORG_TYP VARCHAR NULL, -- 机构类型
    ORG_HARCY VARCHAR NULL, -- 机构层级
    ORG_ADDRS VARCHAR NULL, -- 机构地址
    ORG_STATE VARCHAR NULL, -- 机构状态
    DSPLY_SEQ NUMBER NULL, -- 显示顺序
    CREATR VARCHAR NULL, -- 创建人
    CREAT_TIME VARCHAR NULL, -- 创建时间
    CREAT_ORG VARCHAR NULL, -- 创建机构
    PERSN_LEGAL_BK_CODE VARCHAR NULL, -- 法人行号
    HR_MS_ORG_ID VARCHAR NULL, -- 人力资源系统机构号
    ORG_LGTUD VARCHAR NULL, -- 机构经度
    ORG_LATTUD VARCHAR NULL, -- 机构纬度
    ORG_RSPONR VARCHAR NULL, -- 机构负责人
    ORG_TEL VARCHAR NULL -- 机构电话
);

COMMENT ON TABLE DWD_SYS_ORG IS '机构表';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_ID IS '机构编号';
COMMENT ON COLUMN DWD_SYS_ORG.SUP_ORG_ID IS '上级机构编号';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_PATH IS '机构路径';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_NAME IS '机构名称';
COMMENT ON COLUMN DWD_SYS_ORG.SUP_ORG_NAME IS '上级机构名称';
COMMENT ON COLUMN DWD_SYS_ORG.DIRECT_UNDER_ORG IS '直属机构';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_TYP IS '机构类型';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_HARCY IS '机构层级';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_ADDRS IS '机构地址';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_STATE IS '机构状态';
COMMENT ON COLUMN DWD_SYS_ORG.DSPLY_SEQ IS '显示顺序';
COMMENT ON COLUMN DWD_SYS_ORG.CREATR IS '创建人';
COMMENT ON COLUMN DWD_SYS_ORG.CREAT_TIME IS '创建时间';
COMMENT ON COLUMN DWD_SYS_ORG.CREAT_ORG IS '创建机构';
COMMENT ON COLUMN DWD_SYS_ORG.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_SYS_ORG.HR_MS_ORG_ID IS '人力资源系统机构号';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_LGTUD IS '机构经度';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_LATTUD IS '机构纬度';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_RSPONR IS '机构负责人';
COMMENT ON COLUMN DWD_SYS_ORG.ORG_TEL IS '机构电话';
