/*
 * DWD_CUST_MAN
 * 中文名称: 信贷管户关系表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_MAN (
    CUST_ID VARCHAR NOT NULL, -- 客户编号
    MNGR_POST_ID VARCHAR NOT NULL, -- 客户经理编号
    ORG_ID VARCHAR NOT NULL, -- 机构编号
    MNG_TYP VARCHAR NOT NULL, -- 管理类型(1-理财管户，2-信贷管户)
    MODF_TIME VARCHAR NOT NULL, -- 变更时间
    MODF_TYP VARCHAR NULL, -- 变更类型
    DATA_SRC VARCHAR NULL, -- 数据来源
    VALID_DATE VARCHAR NULL, -- 有效日期
    PERSN_LEGAL_BK_CODE VARCHAR NULL -- 法人行号
);

COMMENT ON TABLE DWD_CUST_MAN IS '信贷管户关系表';
COMMENT ON COLUMN DWD_CUST_MAN.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_MAN.MNGR_POST_ID IS '客户经理编号';
COMMENT ON COLUMN DWD_CUST_MAN.ORG_ID IS '机构编号';
COMMENT ON COLUMN DWD_CUST_MAN.MNG_TYP IS '管理类型(1-理财管户，2-信贷管户)';
COMMENT ON COLUMN DWD_CUST_MAN.MODF_TIME IS '变更时间';
COMMENT ON COLUMN DWD_CUST_MAN.MODF_TYP IS '变更类型';
COMMENT ON COLUMN DWD_CUST_MAN.DATA_SRC IS '数据来源';
COMMENT ON COLUMN DWD_CUST_MAN.VALID_DATE IS '有效日期';
COMMENT ON COLUMN DWD_CUST_MAN.PERSN_LEGAL_BK_CODE IS '法人行号';
