/*
 * DWD_CUST_CTRAKT_INFO
 * 中文名称: 客户合同信息
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_CTRAKT_INFO (
    CUST_ID VARCHAR(21) NOT NULL, -- 客户编号
    CTRAKT_ID VARCHAR(60) NULL, -- 合同编号
    LOAN_ACCT VARCHAR(80) NULL, -- 贷款账号
    CRDT_LMT NUMBER(24,4) NULL, -- 授信额度
    LOAN_BAL NUMBER(24,4) NULL, -- 贷款余额
    GUARANT_MODE VARCHAR(80) NULL, -- 担保方式
    CATE_5LVL VARCHAR(30) NULL, -- 五级分类
    CCY_CD VARCHAR(10) NULL, -- 币种
    RATE_INTRI NUMBER(18,4) NULL, -- 利率
    CONTR_AMT NUMBER(18,4) NULL, -- 合同金额
    BGN_DATE VARCHAR(10) NULL, -- 开始日期
    END_DATE VARCHAR(10) NULL, -- 结束日期
    OPRTR VARCHAR(30) NULL, -- 经办人
    OPRT_ORG VARCHAR(7) NULL, -- 经办机构
    PERSN_LEGAL_BK_CODE VARCHAR(7) NULL, -- 法人行号
    CYCL_TYP VARCHAR(1) NULL, -- 是否可循环
    CMS_CUST_ID VARCHAR(40) NULL, -- 客户编号
    PRDKT_ID VARCHAR(40) NULL, -- 产品编号
    PRDKT_NAME VARCHAR(100) NULL -- 产品名称
);

COMMENT ON TABLE DWD_CUST_CTRAKT_INFO IS '客户合同信息';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.CTRAKT_ID IS '合同编号';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.LOAN_ACCT IS '贷款账号';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.CRDT_LMT IS '授信额度';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.LOAN_BAL IS '贷款余额';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.GUARANT_MODE IS '担保方式';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.CATE_5LVL IS '五级分类';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.CCY_CD IS '币种';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.RATE_INTRI IS '利率';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.CONTR_AMT IS '合同金额';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.BGN_DATE IS '开始日期';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.END_DATE IS '结束日期';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.OPRTR IS '经办人';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.OPRT_ORG IS '经办机构';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.CYCL_TYP IS '是否可循环';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.CMS_CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.PRDKT_ID IS '产品编号';
COMMENT ON COLUMN DWD_CUST_CTRAKT_INFO.PRDKT_NAME IS '产品名称';
