/*
 * DWD_PRDKT_INFO
 * 中文名称: 产品信息表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_PRDKT_INFO (
    PRDKT_ID VARCHAR(40) NOT NULL,
    PRDKT_NAME VARCHAR(100) NULL,
    PRDKT_CATE_BIG VARCHAR(10) NULL,
    BGN_DATE VARCHAR(10) NULL,
    END_DATE VARCHAR(10) NULL,
    PRDKT_LINE VARCHAR(10) NULL,
    SUP_PRDKT_ID VARCHAR(30) NULL,
    MDL_BIZ_RATE_FEE NUMBER(18,
    4) NULL,
    PRDKT_RATE NUMBER(18,
    4) NULL,
    SYS_SRC VARCHAR(6) NULL,
    PRDKT_STATE VARCHAR(10) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(30) NULL
);

COMMENT ON TABLE DWD_PRDKT_INFO IS '产品信息表';
COMMENT ON COLUMN DWD_PRDKT_INFO.PRDKT_ID IS '产品编号';
COMMENT ON COLUMN DWD_PRDKT_INFO.PRDKT_NAME IS '产品名称';
COMMENT ON COLUMN DWD_PRDKT_INFO.PRDKT_CATE_BIG IS '产品大类';
COMMENT ON COLUMN DWD_PRDKT_INFO.BGN_DATE IS '开始日期';
COMMENT ON COLUMN DWD_PRDKT_INFO.END_DATE IS '结束日期';
COMMENT ON COLUMN DWD_PRDKT_INFO.PRDKT_LINE IS '产品条线';
COMMENT ON COLUMN DWD_PRDKT_INFO.SUP_PRDKT_ID IS '上级产品编号';
COMMENT ON COLUMN DWD_PRDKT_INFO.MDL_BIZ_RATE_FEE IS '中间业务费率';
COMMENT ON COLUMN DWD_PRDKT_INFO.PRDKT_RATE IS '产品利率';
COMMENT ON COLUMN DWD_PRDKT_INFO.SYS_SRC IS '系统来源';
COMMENT ON COLUMN DWD_PRDKT_INFO.PRDKT_STATE IS '产品状态(在售/停售)';
COMMENT ON COLUMN DWD_PRDKT_INFO.PERSN_LEGAL_BK_CODE IS '法人行号';