/*
 * DWD_ACCT_DEPO
 * 中文名称: 存款账户信息表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWD_ACCT_DEPO (
    CUST_ID VARCHAR(20) NOT NULL,
    CUST_TYP VARCHAR(2) NULL,
    ACCT_ID VARCHAR(40) NULL,
    CARD_NO VARCHAR(40) NULL,
    PRDKT_ID VARCHAR(30) NULL,
    PRDKT_NAME VARCHAR(200) NULL,
    PRDKT_CATE_BIG VARCHAR(64) NULL,
    ACCT_TYP VARCHAR(10) NULL,
    CCY_CD VARCHAR(4) NULL,
    BAL NUMBER(20,
    2) NULL,
    RMB_BAL NUMBER(20,
    2) NULL,
    OPEN_ACCT_ORG VARCHAR(7) NULL,
    OPEN_DATE VARCHAR(10) NULL,
    RATE_INTRI NUMBER(20,
    2) NULL,
    INTRI_BGN_DATE VARCHAR(10) NULL,
    EXPR_DATE VARCHAR(10) NULL,
    ACCT_CLOZ_DATE VARCHAR(10) NULL,
    ACCT_STATE VARCHAR(10) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL,
    VCHR_TYP VARCHAR(10) NULL,
    CUNQ VARCHAR(10) NULL,
    FIX_CURNT_FLG VARCHAR(1) NULL
);

COMMENT ON TABLE DWD_ACCT_DEPO IS '存款账户信息表';
COMMENT ON COLUMN DWD_ACCT_DEPO.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_ACCT_DEPO.CUST_TYP IS '客户类型';
COMMENT ON COLUMN DWD_ACCT_DEPO.ACCT_ID IS '账户';
COMMENT ON COLUMN DWD_ACCT_DEPO.CARD_NO IS '卡/折号';
COMMENT ON COLUMN DWD_ACCT_DEPO.PRDKT_ID IS '产品编号';
COMMENT ON COLUMN DWD_ACCT_DEPO.PRDKT_NAME IS '产品名称';
COMMENT ON COLUMN DWD_ACCT_DEPO.PRDKT_CATE_BIG IS '产品大类';
COMMENT ON COLUMN DWD_ACCT_DEPO.ACCT_TYP IS '账户类型';
COMMENT ON COLUMN DWD_ACCT_DEPO.CCY_CD IS '币种';
COMMENT ON COLUMN DWD_ACCT_DEPO.BAL IS '余额';
COMMENT ON COLUMN DWD_ACCT_DEPO.RMB_BAL IS '折人民币余额';
COMMENT ON COLUMN DWD_ACCT_DEPO.OPEN_ACCT_ORG IS '归属机构';
COMMENT ON COLUMN DWD_ACCT_DEPO.OPEN_DATE IS '开户日期';
COMMENT ON COLUMN DWD_ACCT_DEPO.RATE_INTRI IS '利率';
COMMENT ON COLUMN DWD_ACCT_DEPO.INTRI_BGN_DATE IS '起息日期';
COMMENT ON COLUMN DWD_ACCT_DEPO.EXPR_DATE IS '到期日期';
COMMENT ON COLUMN DWD_ACCT_DEPO.ACCT_CLOZ_DATE IS '销户日期';
COMMENT ON COLUMN DWD_ACCT_DEPO.ACCT_STATE IS '账户状态';
COMMENT ON COLUMN DWD_ACCT_DEPO.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_ACCT_DEPO.VCHR_TYP IS '凭证类型';
COMMENT ON COLUMN DWD_ACCT_DEPO.CUNQ IS '存期';
COMMENT ON COLUMN DWD_ACCT_DEPO.FIX_CURNT_FLG IS '定活标志';