/*
 * DWD_CUST_INDV_KYC
 * 中文名称: 客户KYC信息表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_INDV_KYC (
    PERSN_LEGAL_BK_CODE VARCHAR NULL, -- 法人行号
    CUST_ID VARCHAR NOT NULL, -- 客户编号
    CUST_NAME VARCHAR NULL, -- 客户名称
    ESTT_INF VARCHAR NULL, -- 住宅信息
    SHOP_INF VARCHAR NULL, -- 商铺信息
    VIKL_INF VARCHAR NULL, -- 车辆信息
    BK_OUTER_DEPO NUMBER NULL, -- 行外存款
    BK_OUTER_FIN NUMBER NULL, -- 行外理财
    BK_OUTER_FUND NUMBER NULL, -- 行外基金
    BK_OUTER_INSUR NUMBER NULL, -- 行外保险
    BK_OUTER_GOLD NUMBER NULL, -- 行外贵金属
    STK_INVEST VARCHAR NULL, -- 股票投资
    MTH_INCOM NUMBER NULL, -- 月收入
    YR_INCOM NUMBER NULL, -- 年收入
    BK_OUTER_LOAN_BAL NUMBER NULL, -- 行外贷款余额
    BK_OUTER_CRDT_LMT NUMBER NULL, -- 行外授信额度
    AVAIL_LMT NUMBER NULL, -- 可用额度
    CREATR VARCHAR NULL, -- 创建人
    CREAT_ORG VARCHAR NULL, -- 创建机构
    CREAT_TIME VARCHAR NULL -- 创建时间
);

COMMENT ON TABLE DWD_CUST_INDV_KYC IS '客户KYC信息表';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.CUST_NAME IS '客户名称';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.ESTT_INF IS '住宅信息';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.SHOP_INF IS '商铺信息';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.VIKL_INF IS '车辆信息';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_DEPO IS '行外存款';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_FIN IS '行外理财';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_FUND IS '行外基金';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_INSUR IS '行外保险';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_GOLD IS '行外贵金属';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.STK_INVEST IS '股票投资';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.MTH_INCOM IS '月收入';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.YR_INCOM IS '年收入';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_LOAN_BAL IS '行外贷款余额';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.BK_OUTER_CRDT_LMT IS '行外授信额度';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.AVAIL_LMT IS '可用额度';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.CREATR IS '创建人';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.CREAT_ORG IS '创建机构';
COMMENT ON COLUMN DWD_CUST_INDV_KYC.CREAT_TIME IS '创建时间';
