/*
 * DWD_CUST_INDIV_RISK_INVST
 * 中文名称: 客户风险评估
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_CUST_INDIV_RISK_INVST (
    CUST_ID VARCHAR(21) NOT NULL, -- 客户编号
    INVEST_TYP VARCHAR(6) NULL, -- 投资类型
    ESTIM_RSLT VARCHAR(6) NULL, -- 评估结果
    SCORE NUMBER(22) NULL, -- 分数
    RISK_LVL VARCHAR(6) NULL, -- 风险级别
    ESTIM_DATE VARCHAR(10) NULL, -- 评估日期
    EXPR_DATE VARCHAR(10) NULL, -- 到期日期
    PERSN_LEGAL_BK_CODE VARCHAR(7) NULL -- 法人行号
);

COMMENT ON TABLE DWD_CUST_INDIV_RISK_INVST IS '客户风险评估';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.INVEST_TYP IS '投资类型';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.ESTIM_RSLT IS '评估结果';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.SCORE IS '分数';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.RISK_LVL IS '风险级别';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.ESTIM_DATE IS '评估日期';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.EXPR_DATE IS '到期日期';
COMMENT ON COLUMN DWD_CUST_INDIV_RISK_INVST.PERSN_LEGAL_BK_CODE IS '法人行号';
