/*
 * DWD_ACCT_DEPO
 * 中文名称: 存款账户信息表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWD_ACCT_DEPO (
    CUST_ID VARCHAR(20) NOT NULL, -- 客户编号
    CUST_TYP VARCHAR(2) NULL, -- 客户类型
    ACCT_ID VARCHAR(40) NULL, -- 账户
    CARD_NO VARCHAR(40) NULL, -- 卡/折号
    PRDKT_ID VARCHAR(30) NULL, -- 产品编号
    PRDKT_NAME VARCHAR(200) NULL, -- 产品名称
    PRDKT_CATE_BIG VARCHAR(64) NULL, -- 产品大类
    ACCT_TYP VARCHAR(10) NULL, -- 账户类型
    CCY_CD VARCHAR(4) NULL, -- 币种
    BAL NUMBER(20,2) NULL, -- 余额
    RMB_BAL NUMBER(20,2) NULL, -- 折人民币余额
    OPEN_ACCT_ORG VARCHAR(6) NULL, -- 归属机构
    OPEN_DATE VARCHAR(10) NULL, -- 开户日期
    RATE_INTRI NUMBER(20,2) NULL, -- 利率
    INTRI_BGN_DATE VARCHAR(10) NULL, -- 起息日期
    EXPR_DATE VARCHAR(10) NULL, -- 到期日期
    ACCT_CLOZ_DATE VARCHAR(10) NULL, -- 销户日期
    ACCT_STATE VARCHAR(10) NULL, -- 账户状态
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL, -- 法人行号
    VCHR_TYP VARCHAR(10) NULL, -- 凭证类型
    CUNQ VARCHAR(10) NULL, -- 存期
    FIX_CURNT_FLG VARCHAR(1) NULL -- 定活标志
);

COMMENT ON TABLE DWD_ACCT_DEPO IS '存款账户信息表';
COMMENT ON COLUMN DWD_ACCT_DEPO.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWD_ACCT_DEPO.CUST_TYP IS '客户类型';
COMMENT ON COLUMN DWD_ACCT_DEPO.ACCT_ID IS '账户';
COMMENT ON COLUMN DWD_ACCT_DEPO.CARD_NO IS '卡/折号';
COMMENT ON COLUMN DWD_ACCT_DEPO.PRDKT_ID IS '产品编号';
COMMENT ON COLUMN DWD_ACCT_DEPO.PRDKT_NAME IS '产品名称';
COMMENT ON COLUMN DWD_ACCT_DEPO.PRDKT_CATE_BIG IS '产品大类';
COMMENT ON COLUMN DWD_ACCT_DEPO.ACCT_TYP IS '账户类型';
COMMENT ON COLUMN DWD_ACCT_DEPO.CCY_CD IS '币种';
COMMENT ON COLUMN DWD_ACCT_DEPO.BAL IS '余额';
COMMENT ON COLUMN DWD_ACCT_DEPO.RMB_BAL IS '折人民币余额';
COMMENT ON COLUMN DWD_ACCT_DEPO.OPEN_ACCT_ORG IS '归属机构';
COMMENT ON COLUMN DWD_ACCT_DEPO.OPEN_DATE IS '开户日期';
COMMENT ON COLUMN DWD_ACCT_DEPO.RATE_INTRI IS '利率';
COMMENT ON COLUMN DWD_ACCT_DEPO.INTRI_BGN_DATE IS '起息日期';
COMMENT ON COLUMN DWD_ACCT_DEPO.EXPR_DATE IS '到期日期';
COMMENT ON COLUMN DWD_ACCT_DEPO.ACCT_CLOZ_DATE IS '销户日期';
COMMENT ON COLUMN DWD_ACCT_DEPO.ACCT_STATE IS '账户状态';
COMMENT ON COLUMN DWD_ACCT_DEPO.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWD_ACCT_DEPO.VCHR_TYP IS '凭证类型';
COMMENT ON COLUMN DWD_ACCT_DEPO.CUNQ IS '存期';
COMMENT ON COLUMN DWD_ACCT_DEPO.FIX_CURNT_FLG IS '定活标志';
