-- ============================================================
-- 客户资产负债基数表属性维度结构升级脚本
-- 适用对象: CRMDM.DWS_CUST_ASSE_LIAB_CUMU、CRMDM.DWS_CUST_ASSE_LIAB_CUMU_HIS
-- 变更内容: 新增办理渠道、办理日期、投保单号或者借据号
-- 执行说明: 本脚本为一次性数据库结构升级脚本；执行前应确认三列尚未存在。
--           严禁使用DROP TABLE重建正式当前表或历史表，避免丢失累计历史数据。
-- ============================================================

-- 01. 客户资产负债基数当前表
ALTER TABLE CRMDM.DWS_CUST_ASSE_LIAB_CUMU
    ADD COLUMN CHNL_NO VARCHAR(10) NULL;

ALTER TABLE CRMDM.DWS_CUST_ASSE_LIAB_CUMU
    ADD COLUMN ISSU_DATE VARCHAR(10) NULL;

ALTER TABLE CRMDM.DWS_CUST_ASSE_LIAB_CUMU
    ADD COLUMN IOU_NO VARCHAR(100) NULL;

COMMENT ON COLUMN CRMDM.DWS_CUST_ASSE_LIAB_CUMU.CHNL_NO IS '办理渠道';
COMMENT ON COLUMN CRMDM.DWS_CUST_ASSE_LIAB_CUMU.ISSU_DATE IS '办理日期';
COMMENT ON COLUMN CRMDM.DWS_CUST_ASSE_LIAB_CUMU.IOU_NO IS '投保单号或者借据号';

-- 02. 客户资产负债基数历史表
ALTER TABLE CRMDM.DWS_CUST_ASSE_LIAB_CUMU_HIS
    ADD COLUMN CHNL_NO VARCHAR(10) NULL;

ALTER TABLE CRMDM.DWS_CUST_ASSE_LIAB_CUMU_HIS
    ADD COLUMN ISSU_DATE VARCHAR(10) NULL;

ALTER TABLE CRMDM.DWS_CUST_ASSE_LIAB_CUMU_HIS
    ADD COLUMN IOU_NO VARCHAR(100) NULL;

COMMENT ON COLUMN CRMDM.DWS_CUST_ASSE_LIAB_CUMU_HIS.CHNL_NO IS '办理渠道';
COMMENT ON COLUMN CRMDM.DWS_CUST_ASSE_LIAB_CUMU_HIS.ISSU_DATE IS '办理日期';
COMMENT ON COLUMN CRMDM.DWS_CUST_ASSE_LIAB_CUMU_HIS.IOU_NO IS '投保单号或者借据号';
