/*
 * DWS_CUST_REFERRAL_RMND
 * 中文名称: 转介绍提醒表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_REFERRAL_RMND (
    PK_ID VARCHAR(40) NOT NULL,
    MNGR_POST_ID VARCHAR(20) NULL,
    REFERRER_CUST_ID VARCHAR(20) NULL,
    REFERRER_NAME VARCHAR(120) NULL,
    REFEREE_CUST_ID VARCHAR(20) NULL,
    REFEREE_NAME VARCHAR(120) NULL,
    RMND_TIME VARCHAR(20) NULL,
    RMND_INF VARCHAR(600) NULL,
    HDLE_STATE VARCHAR(2) NULL,
    HDLE_TIME VARCHAR(20) NULL
);

COMMENT ON TABLE DWS_CUST_REFERRAL_RMND IS '转介绍提醒表';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.PK_ID IS '主键';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.MNGR_POST_ID IS '客户经理编号';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.REFERRER_CUST_ID IS '转介人客户号';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.REFERRER_NAME IS '转介人名称';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.REFEREE_CUST_ID IS '被转介人客户号';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.REFEREE_NAME IS '被转介人名称';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.RMND_TIME IS '提醒时间';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.RMND_INF IS '提醒内容';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.HDLE_STATE IS '处理状态 0-未读 1-已读';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.HDLE_TIME IS '处理时间';