/*
 * DWS_CUST_CAPITAL_RMND
 * 中文名称: 客户资金异动提醒表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_CAPITAL_RMND (
    RMND_ID VARCHAR(40) NOT NULL, -- 提醒ID
    MNGR_POST_ID VARCHAR(20) NULL, -- 客户经理编号
    MNGR_NAME VARCHAR(120) NULL, -- 客户经理名称
    CUST_ID VARCHAR(20) NULL, -- 客户编号
    CUST_TYP VARCHAR(4) NULL, -- 客户类型
    CUST_NAME VARCHAR(100) NULL, -- 客户名称
    ACCT_NO VARCHAR(40) NULL, -- 账号
    HAPN_BAL NUMBER(20,2) NULL, -- 发生金额
    ORG_ID VARCHAR(7) NULL, -- 机构ID
    PHONE_NO VARCHAR(32) NULL, -- 手机号
    HDLE_STATE VARCHAR(2) NULL, -- 处理状态(0为浏览,1已浏览)
    DC_FLAG VARCHAR(2) NULL, -- 借贷标志
    RMND_TIME VARCHAR(20) NULL, -- 发生时间
    TX_CHNL VARCHAR(20) NULL, -- 交易渠道
    OPNT_BK_KEEP VARCHAR(200) NULL, -- 对手行
    OPNT_NAME VARCHAR(200) NULL, -- 对手姓名
    PERSN_LEGAL_BK_CODE VARCHAR(7) NULL, -- 法人行号
    HDLE_TIME VARCHAR(20) NULL, -- 处理时间
    REMARK VARCHAR(200) NULL, -- 备注
    CUST_LVL VARCHAR(2) NULL, -- 客户层级
    RMND_INF VARCHAR(600) NULL -- 提醒内容
);

COMMENT ON TABLE DWS_CUST_CAPITAL_RMND IS '客户资金异动提醒表';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.RMND_ID IS '提醒ID';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.MNGR_POST_ID IS '客户经理编号';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.MNGR_NAME IS '客户经理名称';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.CUST_TYP IS '客户类型';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.CUST_NAME IS '客户名称';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.ACCT_NO IS '账号';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.HAPN_BAL IS '发生金额';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.ORG_ID IS '机构ID';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.PHONE_NO IS '手机号';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.HDLE_STATE IS '处理状态(0为浏览,1已浏览)';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.DC_FLAG IS '借贷标志';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.RMND_TIME IS '发生时间';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.TX_CHNL IS '交易渠道';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.OPNT_BK_KEEP IS '对手行';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.OPNT_NAME IS '对手姓名';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.HDLE_TIME IS '处理时间';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.REMARK IS '备注';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.CUST_LVL IS '客户层级';
COMMENT ON COLUMN DWS_CUST_CAPITAL_RMND.RMND_INF IS '提醒内容';
