/*
 * DWS_CUST_CAPITAL_RMND
 * 中文名称: 客户资金异动提醒表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_CAPITAL_RMND (
    RMND_ID VARCHAR(40) NOT NULL COMMENT '提醒ID',
    MNGR_POST_ID VARCHAR(20) NULL COMMENT '客户经理编号',
    MNGR_NAME VARCHAR(120) NULL COMMENT '客户经理名称',
    CUST_ID VARCHAR(20) NULL COMMENT '客户编号',
    CUST_TYP VARCHAR(4) NULL COMMENT '客户类型',
    CUST_NAME VARCHAR(100) NULL COMMENT '客户名称',
    ACCT_NO VARCHAR(40) NULL COMMENT '账号',
    HAPN_BAL NUMBER(20,2) NULL COMMENT '发生金额',
    ORG_ID VARCHAR(6) NULL COMMENT '机构ID',
    PHONE_NO VARCHAR(32) NULL COMMENT '手机号',
    HDLE_STATE VARCHAR(2) NULL COMMENT '处理状态(0为浏览,1已浏览)',
    DC_FLAG VARCHAR(2) NULL COMMENT '借贷标志',
    RMND_TIME VARCHAR(20) NULL COMMENT '发生时间',
    TX_CHNL VARCHAR(20) NULL COMMENT '交易渠道',
    OPNT_BK_KEEP VARCHAR(200) NULL COMMENT '对手行',
    OPNT_NAME VARCHAR(200) NULL COMMENT '对手姓名',
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL COMMENT '法人行号',
    HDLE_TIME VARCHAR(20) NULL COMMENT '处理时间',
    REMARK VARCHAR(200) NULL COMMENT '备注',
    CUST_LVL VARCHAR(2) NULL COMMENT '客户层级',
    RMND_INF VARCHAR(600) NULL COMMENT '提醒内容'
);

COMMENT ON TABLE DWS_CUST_CAPITAL_RMND IS '客户资金异动提醒表';
