/*
 * DWS_CUST_ASSE_LIAB_CUMU
 * 中文名称: 客户资产负债基数表
 * 版本: v1.1
 * 创建时间: 2026-07-21
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_ASSE_LIAB_CUMU (
    DATA_DATE VARCHAR(8) NOT NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(7) NULL,
    OPRT_ORG VARCHAR(7) NULL,
    CUST_ID VARCHAR(20) NULL,
    ACCT_ID VARCHAR(40) NULL,
    PRDKT_ID VARCHAR(40) NULL,
    PRDKT_CATE_BIG VARCHAR(40) NULL,
    PRDKT_TYP VARCHAR(1) NULL,
    BAL NUMBER(20,
    2) NULL,
    MTH_BAL NUMBER(20,
    2) NULL,
    QRT_BAL NUMBER(20,
    2) NULL,
    YAR_BAL NUMBER(20,
    2) NULL,
    MTH_DAYS NUMBER(20,
    2) NULL,
    QRT_DAYS NUMBER(20,
    2) NULL,
    YAR_DAYS NUMBER(20,
    2) NULL
);

COMMENT ON TABLE DWS_CUST_ASSE_LIAB_CUMU IS '客户资产负债基数表';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU.DATA_DATE IS '数据日期';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU.OPRT_ORG IS '归属机构';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU.CUST_ID IS '客户号';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU.ACCT_ID IS '账号';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU.PRDKT_ID IS '产品编号';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU.PRDKT_CATE_BIG IS '产品大类';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU.PRDKT_TYP IS '产品类型';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU.BAL IS '日余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU.MTH_BAL IS '月余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU.QRT_BAL IS '季余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU.YAR_BAL IS '年余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU.MTH_DAYS IS '月天数';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU.QRT_DAYS IS '季天数';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU.YAR_DAYS IS '年天数';