/*
 * DWS_CUST_CARE_RMND
 * 中文名称: 客户关怀提醒表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_CARE_RMND (
    CARE_ID VARCHAR(40) NOT NULL,
    CARE_TYP VARCHAR(2) NULL,
    MNGR_POST_ID VARCHAR(20) NULL,
    MNGR_NAME VARCHAR(120) NULL,
    CUST_ID VARCHAR(20) NULL,
    CUST_NAME VARCHAR(120) NULL,
    PHONE_NO VARCHAR(32) NULL,
    CUST_TYP VARCHAR(2) NULL,
    ORG_ID VARCHAR(7) NULL,
    HDLE_STATE VARCHAR(2) NULL,
    CATE_TIME VARCHAR(20) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL,
    HDLE_TIME VARCHAR(20) NULL,
    CTKTR_NAME VARCHAR(64) NULL,
    CTKTR_REL VARCHAR(6) NULL,
    DATA_DATE VARCHAR(8) NULL,
    MSG_CONTENT VARCHAR(200) NULL
);

COMMENT ON TABLE DWS_CUST_CARE_RMND IS '客户关怀提醒表';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.CARE_ID IS '关怀ID';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.CARE_TYP IS '关怀类型(01生日关怀,02节假日关怀)';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.MNGR_POST_ID IS '客户经理编号';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.MNGR_NAME IS '客户经理名称';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.CUST_ID IS '客户ID';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.CUST_NAME IS '客户名称';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.PHONE_NO IS '手机号';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.CUST_TYP IS '客户类型';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.ORG_ID IS '所属机构(客户经理所在机构)';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.HDLE_STATE IS '处理状态(0 未处理，1 已处理，2已到期)';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.CATE_TIME IS '关怀时间';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.HDLE_TIME IS '处理时间';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.CTKTR_NAME IS '联系人姓名';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.CTKTR_REL IS '联系人关系';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.DATA_DATE IS '数据日期';
COMMENT ON COLUMN DWS_CUST_CARE_RMND.MSG_CONTENT IS '消息内容';