/*
 * DWS_CUST_DEADLINE_RMND
 * 中文名称: 客户到期提醒
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_DEADLINE_RMND (
    RMND_ID VARCHAR(40) NOT NULL COMMENT '到期提醒ID',
    RMND_TYP VARCHAR(6) NULL COMMENT '提醒类型',
    RMND_NAME VARCHAR(100) NULL COMMENT '提醒名称',
    MNGR_POST_ID VARCHAR(20) NULL COMMENT '客户经理编号',
    MNGR_NAME VARCHAR(120) NULL COMMENT '客户经理名称',
    CUST_ID VARCHAR(20) NULL COMMENT '客户ID',
    CUST_TYP VARCHAR(6) NULL COMMENT '客户类型',
    CUST_NAME VARCHAR(100) NULL COMMENT '客户名称',
    PRDKT_NAME VARCHAR(100) NULL COMMENT '产品名称',
    EXPR_AMT NUMBER(20,2) NULL COMMENT '到期金额',
    EXPR_DATE VARCHAR(10) NULL COMMENT '到期日期',
    ORG_ID VARCHAR(6) NULL COMMENT '机构(客户经理所在机构)',
    HDLE_STATE VARCHAR(2) NULL COMMENT '处理状态(0为未读,1已读)',
    RMND_DATE VARCHAR(10) NULL COMMENT '提醒日期',
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL COMMENT '法人行号',
    HDLE_TIME VARCHAR(20) NULL COMMENT '处理时间',
    DEL_FLG CHAR(1) NULL COMMENT '删除标志 1 是 0 否',
    PHONE_NO VARCHAR(20) NULL COMMENT '手机号',
    RMND_INF VARCHAR(200) NULL COMMENT '提醒内容',
    CUST_LVL VARCHAR(2) NULL COMMENT '客户层级'
);

COMMENT ON TABLE DWS_CUST_DEADLINE_RMND IS '客户到期提醒';
