/*
 * DWS_CUST_CARE_RMND
 * 中文名称: 客户关怀提醒表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_CARE_RMND (
    CARE_ID VARCHAR(40) NOT NULL COMMENT '关怀ID',
    CARE_TYP VARCHAR(2) NULL COMMENT '关怀类型(01生日关怀,02节假日关怀)',
    MNGR_POST_ID VARCHAR(20) NULL COMMENT '客户经理编号',
    MNGR_NAME VARCHAR(120) NULL COMMENT '客户经理名称',
    CUST_ID VARCHAR(20) NULL COMMENT '客户ID',
    CUST_NAME VARCHAR(120) NULL COMMENT '客户名称',
    PHONE_NO VARCHAR(32) NULL COMMENT '手机号',
    CUST_TYP VARCHAR(2) NULL COMMENT '客户类型',
    ORG_ID VARCHAR(6) NULL COMMENT '所属机构(客户经理所在机构)',
    HDLE_STATE VARCHAR(2) NULL COMMENT '处理状态(0 未处理，1 已处理，2已到期)',
    CATE_TIME VARCHAR(20) NULL COMMENT '关怀时间',
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL COMMENT '法人行号',
    HDLE_TIME VARCHAR(20) NULL COMMENT '处理时间',
    CTKTR_NAME VARCHAR(64) NULL COMMENT '联系人姓名',
    CTKTR_REL VARCHAR(6) NULL COMMENT '联系人关系',
    DATA_DATE VARCHAR(8) NULL COMMENT '数据日期',
    MSG_CONTENT VARCHAR(200) NULL COMMENT '消息内容'
);

COMMENT ON TABLE DWS_CUST_CARE_RMND IS '客户关怀提醒表';
