/*
 * DWS_CUST_INDIV_REFERRAL
 * 中文名称: 客户转介绍
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_INDIV_REFERRAL (
    PK_ID VARCHAR(40) NOT NULL,
    CUST_ID VARCHAR(20) NULL,
    CUST_NAME VARCHAR(120) NULL,
    CUST_TYP VARCHAR(2) NULL,
    TEL_NO VARCHAR(20) NULL,
    CERT_ID VARCHAR(32) NULL,
    INTENT_PRDKT VARCHAR(200) NULL,
    REFERRER VARCHAR(20) NULL,
    REFERRAL_DATE VARCHAR(8) NULL,
    RSV_DATE VARCHAR(8) NULL,
    STATE VARCHAR(2) NULL,
    DSC VARCHAR(400) NULL,
    ELEVT_AUM NUMBER(20,
    2) NULL,
    AUM NUMBER(20,
    2) NULL
);

COMMENT ON TABLE DWS_CUST_INDIV_REFERRAL IS '客户转介绍';
COMMENT ON COLUMN DWS_CUST_INDIV_REFERRAL.PK_ID IS '主键';
COMMENT ON COLUMN DWS_CUST_INDIV_REFERRAL.CUST_ID IS '被转介客户号';
COMMENT ON COLUMN DWS_CUST_INDIV_REFERRAL.CUST_NAME IS '被转介客户姓名';
COMMENT ON COLUMN DWS_CUST_INDIV_REFERRAL.CUST_TYP IS '被转介客户类型';
COMMENT ON COLUMN DWS_CUST_INDIV_REFERRAL.TEL_NO IS '被转介客户联系电话';
COMMENT ON COLUMN DWS_CUST_INDIV_REFERRAL.CERT_ID IS '被转介客户证件号码';
COMMENT ON COLUMN DWS_CUST_INDIV_REFERRAL.INTENT_PRDKT IS '被转介客户意向产品';
COMMENT ON COLUMN DWS_CUST_INDIV_REFERRAL.REFERRER IS '转介人编号';
COMMENT ON COLUMN DWS_CUST_INDIV_REFERRAL.REFERRAL_DATE IS '转介日期';
COMMENT ON COLUMN DWS_CUST_INDIV_REFERRAL.RSV_DATE IS '接收日期';
COMMENT ON COLUMN DWS_CUST_INDIV_REFERRAL.STATE IS '状态';
COMMENT ON COLUMN DWS_CUST_INDIV_REFERRAL.DSC IS '说明';
COMMENT ON COLUMN DWS_CUST_INDIV_REFERRAL.ELEVT_AUM IS 'AUM提升金额';
COMMENT ON COLUMN DWS_CUST_INDIV_REFERRAL.AUM IS '接收时被转介客户AUM余额';