/*
 * DWS_CUST_LVL_INFO
 * 中文名称: 客户等级信息表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_LVL_INFO (
    PERSN_LEGAL_BK_CODE VARCHAR(7) NULL, -- 法人行号
    DATA_DATE VARCHAR(8) NOT NULL, -- 数据日期
    CUST_ID VARCHAR(20) NOT NULL, -- 客户编号
    CUST_LVL VARCHAR(2) NOT NULL, -- 客户等级
    ORG_ID VARCHAR(8) NULL, -- 归属机构
    CUST_HRAKY VARCHAR(2) NULL -- 客户权益等级
);

COMMENT ON TABLE DWS_CUST_LVL_INFO IS '客户等级信息表';
COMMENT ON COLUMN DWS_CUST_LVL_INFO.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWS_CUST_LVL_INFO.DATA_DATE IS '数据日期';
COMMENT ON COLUMN DWS_CUST_LVL_INFO.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWS_CUST_LVL_INFO.CUST_LVL IS '客户等级';
COMMENT ON COLUMN DWS_CUST_LVL_INFO.ORG_ID IS '归属机构';
COMMENT ON COLUMN DWS_CUST_LVL_INFO.CUST_HRAKY IS '客户权益等级';
