/*
 * DWS_CUST_REFERRAL_RMND
 * 中文名称: 转介绍提醒表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_REFERRAL_RMND (
    PK_ID VARCHAR(40) NOT NULL, -- 主键
    MNGR_POST_ID VARCHAR(20) NULL, -- 客户经理编号
    REFERRER_CUST_ID VARCHAR(20) NULL, -- 转介人客户号
    REFERRER_NAME VARCHAR(120) NULL, -- 转介人名称
    REFEREE_CUST_ID VARCHAR(20) NULL, -- 被转介人客户号
    REFEREE_NAME VARCHAR(120) NULL, -- 被转介人名称
    RMND_TIME VARCHAR(20) NULL, -- 提醒时间
    RMND_INF VARCHAR(600) NULL, -- 提醒内容
    HDLE_STATE VARCHAR(2) NULL, -- 处理状态 0-未读 1-已读
    HDLE_TIME VARCHAR(20) NULL -- 处理时间
);

COMMENT ON TABLE DWS_CUST_REFERRAL_RMND IS '转介绍提醒表';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.PK_ID IS '主键';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.MNGR_POST_ID IS '客户经理编号';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.REFERRER_CUST_ID IS '转介人客户号';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.REFERRER_NAME IS '转介人名称';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.REFEREE_CUST_ID IS '被转介人客户号';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.REFEREE_NAME IS '被转介人名称';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.RMND_TIME IS '提醒时间';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.RMND_INF IS '提醒内容';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.HDLE_STATE IS '处理状态 0-未读 1-已读';
COMMENT ON COLUMN DWS_CUST_REFERRAL_RMND.HDLE_TIME IS '处理时间';
