/*
 * DWS_CUST_DEADLINE_RMND
 * 中文名称: 客户到期提醒
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_DEADLINE_RMND (
    RMND_ID VARCHAR(40) NOT NULL,
    RMND_TYP VARCHAR(6) NULL,
    RMND_NAME VARCHAR(100) NULL,
    MNGR_POST_ID VARCHAR(20) NULL,
    MNGR_NAME VARCHAR(120) NULL,
    CUST_ID VARCHAR(20) NULL,
    CUST_TYP VARCHAR(6) NULL,
    CUST_NAME VARCHAR(100) NULL,
    PRDKT_NAME VARCHAR(100) NULL,
    EXPR_AMT NUMBER(20,
    2) NULL,
    EXPR_DATE VARCHAR(10) NULL,
    ORG_ID VARCHAR(7) NULL,
    HDLE_STATE VARCHAR(2) NULL,
    RMND_DATE VARCHAR(10) NULL,
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL,
    HDLE_TIME VARCHAR(20) NULL,
    DEL_FLG CHAR(1) NULL,
    PHONE_NO VARCHAR(20) NULL,
    RMND_INF VARCHAR(200) NULL,
    CUST_LVL VARCHAR(2) NULL
);

COMMENT ON TABLE DWS_CUST_DEADLINE_RMND IS '客户到期提醒';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.RMND_ID IS '到期提醒ID';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.RMND_TYP IS '提醒类型';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.RMND_NAME IS '提醒名称';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.MNGR_POST_ID IS '客户经理编号';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.MNGR_NAME IS '客户经理名称';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.CUST_ID IS '客户ID';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.CUST_TYP IS '客户类型';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.CUST_NAME IS '客户名称';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.PRDKT_NAME IS '产品名称';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.EXPR_AMT IS '到期金额';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.EXPR_DATE IS '到期日期';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.ORG_ID IS '机构(客户经理所在机构)';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.HDLE_STATE IS '处理状态(0为未读,1已读)';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.RMND_DATE IS '提醒日期';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.HDLE_TIME IS '处理时间';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.DEL_FLG IS '删除标志 1 是 0 否';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.PHONE_NO IS '手机号';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.RMND_INF IS '提醒内容';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.CUST_LVL IS '客户层级';