/*
 * DWS_CUST_REFERRAL_RMND
 * 中文名称: 转介绍提醒表
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_REFERRAL_RMND (
    PK_ID VARCHAR(40) NOT NULL COMMENT '主键',
    MNGR_POST_ID VARCHAR(20) NULL COMMENT '客户经理编号',
    REFERRER_CUST_ID VARCHAR(20) NULL COMMENT '转介人客户号',
    REFERRER_NAME VARCHAR(120) NULL COMMENT '转介人名称',
    REFEREE_CUST_ID VARCHAR(20) NULL COMMENT '被转介人客户号',
    REFEREE_NAME VARCHAR(120) NULL COMMENT '被转介人名称',
    RMND_TIME VARCHAR(20) NULL COMMENT '提醒时间',
    RMND_INF VARCHAR(600) NULL COMMENT '提醒内容',
    HDLE_STATE VARCHAR(2) NULL COMMENT '处理状态 0-未读 1-已读',
    HDLE_TIME VARCHAR(20) NULL COMMENT '处理时间'
);

COMMENT ON TABLE DWS_CUST_REFERRAL_RMND IS '转介绍提醒表';
