/*
 * DWS_CUST_DEADLINE_RMND
 * 中文名称: 客户到期提醒
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_DEADLINE_RMND (
    RMND_ID VARCHAR(40) NOT NULL, -- 到期提醒ID
    RMND_TYP VARCHAR(6) NULL, -- 提醒类型
    RMND_NAME VARCHAR(100) NULL, -- 提醒名称
    MNGR_POST_ID VARCHAR(20) NULL, -- 客户经理编号
    MNGR_NAME VARCHAR(120) NULL, -- 客户经理名称
    CUST_ID VARCHAR(20) NULL, -- 客户ID
    CUST_TYP VARCHAR(6) NULL, -- 客户类型
    CUST_NAME VARCHAR(100) NULL, -- 客户名称
    PRDKT_NAME VARCHAR(100) NULL, -- 产品名称
    EXPR_AMT NUMBER(20,2) NULL, -- 到期金额
    EXPR_DATE VARCHAR(10) NULL, -- 到期日期
    ORG_ID VARCHAR(7) NULL, -- 机构(客户经理所在机构)
    HDLE_STATE VARCHAR(2) NULL, -- 处理状态(0为未读,1已读)
    RMND_DATE VARCHAR(10) NULL, -- 提醒日期
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL, -- 法人行号
    HDLE_TIME VARCHAR(20) NULL, -- 处理时间
    DEL_FLG CHAR(1) NULL, -- 删除标志 1 是 0 否
    PHONE_NO VARCHAR(20) NULL, -- 手机号
    RMND_INF VARCHAR(200) NULL, -- 提醒内容
    CUST_LVL VARCHAR(2) NULL -- 客户层级
);

COMMENT ON TABLE DWS_CUST_DEADLINE_RMND IS '客户到期提醒';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.RMND_ID IS '到期提醒ID';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.RMND_TYP IS '提醒类型';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.RMND_NAME IS '提醒名称';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.MNGR_POST_ID IS '客户经理编号';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.MNGR_NAME IS '客户经理名称';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.CUST_ID IS '客户ID';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.CUST_TYP IS '客户类型';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.CUST_NAME IS '客户名称';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.PRDKT_NAME IS '产品名称';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.EXPR_AMT IS '到期金额';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.EXPR_DATE IS '到期日期';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.ORG_ID IS '机构(客户经理所在机构)';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.HDLE_STATE IS '处理状态(0为未读,1已读)';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.RMND_DATE IS '提醒日期';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.HDLE_TIME IS '处理时间';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.DEL_FLG IS '删除标志 1 是 0 否';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.PHONE_NO IS '手机号';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.RMND_INF IS '提醒内容';
COMMENT ON COLUMN DWS_CUST_DEADLINE_RMND.CUST_LVL IS '客户层级';
