/*
 * DWS_CUST_INDV_POTEN
 * 中文名称: 零售潜在客户信息表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_INDV_POTEN (
    PERSN_LEGAL_BK_CODE VARCHAR(4) NULL, -- 法人行号
    POTEN_CUST_ID VARCHAR(40) NOT NULL, -- 潜在客户号(自增键)
    POTEN_CUST_NAME VARCHAR(40) NULL, -- 潜在客户名称
    POTEN_TYP VARCHAR(100) NULL, -- 潜客类型
    GENDER VARCHAR(6) NULL, -- 性别
    CERT_TYP VARCHAR(6) NULL, -- 证件类型
    CERT_ID VARCHAR(32) NULL, -- 证件号码
    TEL_NO VARCHAR(32) NULL, -- 联系电话
    INTENT_DSC VARCHAR(400) NULL, -- 备注说明
    DTL_ADDRS VARCHAR(400) NULL, -- 居住地址
    CREATR VARCHAR(20) NULL, -- 创建人
    CREAT_TIME VARCHAR(20) NULL, -- 创建时间
    POTEN_CUST_STATE VARCHAR(6) NULL, -- 潜在客户状态
    SRC_TYP VARCHAR(20) NULL, -- 来源类型
    MKT_PERSN VARCHAR(6) NULL, -- 客户经理
    MKT_ORG VARCHAR(200) NULL, -- 归属机构
    SERV_ENTER VARCHAR(6) NULL, -- 工作单位
    POST NUMBER NULL, -- 职位
    MTH_INCOM NUMBER NULL, -- 月收入
    YR_INCOM VARCHAR(400) NULL, -- 年收入
    RMARK VARCHAR(10) NULL, -- 备注
    INF_KLKT_DATE VARCHAR(200) NULL, -- 潜客转化日期
    UNIT_ADDRS VARCHAR(60) NULL, -- 工作单位地址
    INTN_PRDKT VARCHAR(40) NULL, -- 意向产品
    NO_BAT VARCHAR(21) NULL, -- 批次号
    CUST_ID VARCHAR(60) NULL, -- 转化后核心客户号
    POT_CNVRT_PRDKT VARCHAR(6) NULL, -- 潜客转化产品
    POT_CNVRT_ORG VARCHAR(8) NULL, -- 潜客转化机构
    ALLO_DATE VARCHAR(8) NULL, -- 分配日期
    REC_DATE VARCHAR(8) NULL, -- 回收日期
    AGE NUMBER NULL -- 客户年龄
);

COMMENT ON TABLE DWS_CUST_INDV_POTEN IS '零售潜在客户信息表';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.POTEN_CUST_ID IS '潜在客户号(自增键)';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.POTEN_CUST_NAME IS '潜在客户名称';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.POTEN_TYP IS '潜客类型';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.GENDER IS '性别';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.CERT_TYP IS '证件类型';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.CERT_ID IS '证件号码';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.TEL_NO IS '联系电话';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.INTENT_DSC IS '备注说明';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.DTL_ADDRS IS '居住地址';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.CREATR IS '创建人';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.CREAT_TIME IS '创建时间';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.POTEN_CUST_STATE IS '潜在客户状态';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.SRC_TYP IS '来源类型';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.MKT_PERSN IS '客户经理';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.MKT_ORG IS '归属机构';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.SERV_ENTER IS '工作单位';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.POST IS '职位';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.MTH_INCOM IS '月收入';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.YR_INCOM IS '年收入';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.RMARK IS '备注';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.INF_KLKT_DATE IS '潜客转化日期';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.UNIT_ADDRS IS '工作单位地址';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.INTN_PRDKT IS '意向产品';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.NO_BAT IS '批次号';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.CUST_ID IS '转化后核心客户号';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.POT_CNVRT_PRDKT IS '潜客转化产品';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.POT_CNVRT_ORG IS '潜客转化机构';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.ALLO_DATE IS '分配日期';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.REC_DATE IS '回收日期';
COMMENT ON COLUMN DWS_CUST_INDV_POTEN.AGE IS '客户年龄';
