/*
 * DWS_CUST_INDIV_REFERRAL
 * 中文名称: 客户转介绍
 * 版本: v1.0
 * 创建时间: 2026-07-17
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_INDIV_REFERRAL (
    PK_ID VARCHAR(40) NOT NULL COMMENT '主键',
    CUST_ID VARCHAR(20) NULL COMMENT '被转介客户号',
    CUST_NAME VARCHAR(120) NULL COMMENT '被转介客户姓名',
    CUST_TYP VARCHAR(2) NULL COMMENT '被转介客户类型',
    TEL_NO VARCHAR(20) NULL COMMENT '被转介客户联系电话',
    CERT_ID VARCHAR(32) NULL COMMENT '被转介客户证件号码',
    INTENT_PRDKT VARCHAR(200) NULL COMMENT '被转介客户意向产品',
    REFERRER VARCHAR(20) NULL COMMENT '转介人编号',
    REFERRAL_DATE VARCHAR(8) NULL COMMENT '转介日期',
    RSV_DATE VARCHAR(8) NULL COMMENT '接收日期',
    STATE VARCHAR(2) NULL COMMENT '状态',
    DSC VARCHAR(400) NULL COMMENT '说明',
    ELEVT_AUM NUMBER(20,2) NULL COMMENT 'AUM提升金额',
    AUM NUMBER(20,2) NULL COMMENT '接收时被转介客户AUM余额'
);

COMMENT ON TABLE DWS_CUST_INDIV_REFERRAL IS '客户转介绍';
