/*
 * DWS_CUST_ASSE_LIAB
 * 中文名称: 客户资产负债表
 * 来源: Mapping Excel 同步
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_ASSE_LIAB (
    DATA_DATE VARCHAR(8) NOT NULL, -- 数据日期
    CUST_ID VARCHAR(20) NOT NULL, -- 客户号
    ORG_ID VARCHAR(7) NOT NULL, -- 归属机构
    ORG_ID_LOAN VARCHAR(6) NULL, -- 信贷归属机构
    BAL_TYPE CHAR(1) NOT NULL, -- 类型1-余额2-月日均3-季日均4-年日均
    AUM_BAL NUMBER(20,2) NULL, -- AUM余额
    DEPO_BAL NUMBER(20,2) NULL, -- 定期余额
    DEPO_CURNT_DEPO_BAL NUMBER(20,2) NULL, -- 活期余额
    FIXD_DEPO_BAL NUMBER(20,2) NULL, -- 普通定期余额
    LEHUI_BAL NUMBER(20,2) NULL, -- 乐惠存产品余额
    LARGEDP_BAL NUMBER(20,2) NULL, -- 大额存单余额
    FIN_BAL NUMBER(20,2) NULL, -- 理财余额
    CLOSE_AGEN_FIN_BAL NUMBER(20,2) NULL, -- 代销封闭式理财余额
    OPEN_AGEN_FIN_BAL NUMBER(20,2) NULL, -- 代销开放式理财余额
    CLOSE_SELF_FIN_BAL NUMBER(20,2) NULL, -- 自营封闭式理财余额
    OPEN_SELF_FIN_BAL NUMBER(20,2) NULL, -- 自营开放式理财余额
    INSUR_BAL NUMBER(20,2) NULL, -- 保险余额
    LOAN_BAL NUMBER(20,2) NULL, -- 贷款余额
    PERSN_LEGAL_BK_CODE VARCHAR(7) NULL -- 法人行号
);

COMMENT ON TABLE DWS_CUST_ASSE_LIAB IS '客户资产负债表';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.DATA_DATE IS '数据日期';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.CUST_ID IS '客户号';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.ORG_ID IS '归属机构';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.ORG_ID_LOAN IS '信贷归属机构';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.BAL_TYPE IS '类型1-余额2-月日均3-季日均4-年日均';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.AUM_BAL IS 'AUM余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.DEPO_BAL IS '定期余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.DEPO_CURNT_DEPO_BAL IS '活期余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.FIXD_DEPO_BAL IS '普通定期余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.LEHUI_BAL IS '乐惠存产品余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.LARGEDP_BAL IS '大额存单余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.FIN_BAL IS '理财余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.CLOSE_AGEN_FIN_BAL IS '代销封闭式理财余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.OPEN_AGEN_FIN_BAL IS '代销开放式理财余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.CLOSE_SELF_FIN_BAL IS '自营封闭式理财余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.OPEN_SELF_FIN_BAL IS '自营开放式理财余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.INSUR_BAL IS '保险余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.LOAN_BAL IS '贷款余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB.PERSN_LEGAL_BK_CODE IS '法人行号';
