/*
 * DWS层表
 * 表名: crmdm.dws_cust_asse_liab_cumu_his
 * 来源: TB.ddl
 */

-- crmdm.dws_cust_asse_liab_cumu_his 定义

-- Drop table

-- DROP TABLE crmdm.dws_cust_asse_liab_cumu_his;

CREATE TABLE crmdm.dws_cust_asse_liab_cumu_his (
    data_date varchar(8) NOT NULL,
    persn_legal_bk_code varchar(7) NULL,
    oprt_org varchar(7) NULL,
    cust_id varchar(20) NOT NULL,
    acct_id varchar(40) NOT NULL,
    prdkt_id varchar(40) NOT NULL,
    prdkt_cate_big varchar(40) NULL,
    chnl_no varchar(10) NULL,
    issu_date varchar(10) NULL,
    iou_no varchar(100) NULL,
    prdkt_typ varchar(1) NULL,
    bal numeric(20,
    2) NULL,
    mth_bal numeric(20,
    2) NULL,
    qrt_bal numeric(20,
    2) NULL,
    yar_bal numeric(20,
    2) NULL,
    mth_days numeric(20,
    2) NULL,
    qrt_days numeric(20,
    2) NULL,
    yar_days numeric(20,
    2) NULL
);



COMMENT ON TABLE DWS_CUST_ASSE_LIAB_CUMU_HIS IS '客户资产负债基数历史表';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.DATA_DATE IS '数据日期';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.OPRT_ORG IS '归属机构';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.CUST_ID IS '客户号';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.ACCT_ID IS '账号';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.PRDKT_ID IS '产品编号';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.PRDKT_CATE_BIG IS '产品大类';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.CHNL_NO IS '办理渠道';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.ISSU_DATE IS '办理日期';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.IOU_NO IS '投保单号或者借据号';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.PRDKT_TYP IS '产品类型';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.BAL IS '日余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.MTH_BAL IS '月累计余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.QRT_BAL IS '季累计余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.YAR_BAL IS '年累计余额';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.MTH_DAYS IS '月已过天数';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.QRT_DAYS IS '季已过天数';
COMMENT ON COLUMN DWS_CUST_ASSE_LIAB_CUMU_HIS.YAR_DAYS IS '年已过天数';



-- 02. 客户资产负债基数历史表
ALTER TABLE CRMDM.DWS_CUST_ASSE_LIAB_CUMU_HIS
    ADD COLUMN CHNL_NO VARCHAR(10) NULL;

ALTER TABLE CRMDM.DWS_CUST_ASSE_LIAB_CUMU_HIS
    ADD COLUMN ISSU_DATE VARCHAR(10) NULL;

ALTER TABLE CRMDM.DWS_CUST_ASSE_LIAB_CUMU_HIS
    ADD COLUMN IOU_NO VARCHAR(100) NULL;

COMMENT ON COLUMN CRMDM.DWS_CUST_ASSE_LIAB_CUMU_HIS.CHNL_NO IS '办理渠道';
COMMENT ON COLUMN CRMDM.DWS_CUST_ASSE_LIAB_CUMU_HIS.ISSU_DATE IS '办理日期';
COMMENT ON COLUMN CRMDM.DWS_CUST_ASSE_LIAB_CUMU_HIS.IOU_NO IS '投保单号或者借据号';