/*
 * DWS_CUST_LVL_INFO_HIS
 * 中文名称: 客户等级信息表（历史快照）
 * 来源: 用户确认（2026-09-02，指标基数口径拆分 v2.4）；与主表 DWS_CUST_LVL_INFO 同构
 * 用途: 存非当日跑批的历史客户等级快照；指标基准回溯取数（基准日<跑批日时读本表，主表仅存当日跑批数据）
 */

CREATE TABLE IF NOT EXISTS DWS_CUST_LVL_INFO_HIS (
    PERSN_LEGAL_BK_CODE VARCHAR(7) NULL, -- 法人行号
    DATA_DATE VARCHAR(8) NOT NULL, -- 数据日期
    CUST_ID VARCHAR(20) NOT NULL, -- 客户编号
    CUST_LVL VARCHAR(2) NOT NULL, -- 客户等级
    ORG_ID VARCHAR(8) NULL, -- 归属机构
    CUST_HRAKY VARCHAR(2) NULL -- 客户权益等级
);

COMMENT ON TABLE DWS_CUST_LVL_INFO_HIS IS '客户等级信息表（历史快照）';
COMMENT ON COLUMN DWS_CUST_LVL_INFO_HIS.PERSN_LEGAL_BK_CODE IS '法人行号';
COMMENT ON COLUMN DWS_CUST_LVL_INFO_HIS.DATA_DATE IS '数据日期';
COMMENT ON COLUMN DWS_CUST_LVL_INFO_HIS.CUST_ID IS '客户编号';
COMMENT ON COLUMN DWS_CUST_LVL_INFO_HIS.CUST_LVL IS '客户等级';
COMMENT ON COLUMN DWS_CUST_LVL_INFO_HIS.ORG_ID IS '归属机构';
COMMENT ON COLUMN DWS_CUST_LVL_INFO_HIS.CUST_HRAKY IS '客户权益等级';
