-- crmdm.cms_user_info 定义

-- Drop table

-- DROP TABLE crmdm.cms_user_info;

CREATE TABLE crmdm.cms_user_info (
	userid varchar(32) NOT NULL,
	loginid varchar(32) NULL,
	username varchar(32) NULL,
	"password" varchar(32) NULL,
	belongorg varchar(32) NULL,
	attribute1 varchar(80) NULL,
	attribute2 varchar(80) NULL,
	attribute3 varchar(80) NULL,
	attribute4 varchar(80) NULL,
	attribute5 varchar(80) NULL,
	attribute6 varchar(80) NULL,
	attribute7 varchar(80) NULL,
	attribute8 varchar(80) NULL,
	"attribute" varchar(80) NULL,
	describe1 varchar(250) NULL,
	describe2 varchar(250) NULL,
	describe3 varchar(250) NULL,
	describe4 varchar(250) NULL,
	status varchar(80) NULL,
	certtype varchar(18) NULL,
	certid varchar(32) NULL,
	companytel varchar(32) NULL,
	mobiletel varchar(32) NULL,
	email varchar(80) NULL,
	accountid varchar(32) NULL,
	id1 varchar(32) NULL,
	id2 varchar(32) NULL,
	sum1 numeric(24, 6) NULL,
	sum2 numeric(24, 6) NULL,
	inputorg varchar(32) NULL,
	inputuser varchar(32) NULL,
	inputdate varchar(20) NULL,
	updatedate varchar(20) NULL,
	inputtime varchar(20) NULL,
	updateuser varchar(32) NULL,
	updatetime varchar(20) NULL,
	remark varchar(250) NULL,
	birthday varchar(10) NULL,
	gender varchar(18) NULL,
	familyadd varchar(250) NULL,
	educationalbg varchar(18) NULL,
	amlevel varchar(18) NULL,
	title varchar(18) NULL,
	educationexp bpchar(800) NULL,
	vocationexp bpchar(800) NULL,
	"position" varchar(250) NULL,
	qualification varchar(250) NULL,
	ntid varchar(32) NULL,
	belongteam varchar(32) NULL,
	lob varchar(32) NULL,
	skinpath varchar(200) NULL,
	"language" varchar(32) NULL,
	mfuserid varchar(32) NULL,
	oauserid varchar(32) NULL,
	ryzd varchar(1) NULL
);
CREATE INDEX index_crmdm_cms_user_info_index_1 ON crmdm.cms_user_info USING btree (userid);
