/*
 * 上游信贷系统
 * 表名: crmdm.cms_ent_info
 * 来源: TB.ddl
 */

-- crmdm.cms_ent_info 定义

-- Drop table

-- DROP TABLE crmdm.cms_ent_info;

CREATE TABLE crmdm.cms_ent_info (
	customerid varchar(40) NOT NULL,
	corpid varchar(32) NULL,
	enterprisename varchar(80) NULL,
	englishname varchar(80) NULL,
	fictitiousperson varchar(80) NULL,
	orgnature varchar(18) NULL,
	financetype varchar(18) NULL,
	enterprisebelong varchar(18) NULL,
	industrytype varchar(18) NULL,
	industrytype1 varchar(18) NULL,
	industrytype2 varchar(18) NULL,
	private varchar(18) NULL,
	economytype varchar(18) NULL,
	orgtype varchar(18) NULL,
	mostbusiness varchar(1600) NULL,
	budgettype varchar(18) NULL,
	rccurrency varchar(18) NULL,
	registercapital numeric(24, 6) NULL,
	pccurrency varchar(18) NULL,
	paiclupcapital numeric(24, 6) NULL,
	fundsource varchar(200) NULL,
	totalassets numeric(24, 6) NULL,
	netassets numeric(24, 6) NULL,
	annualincome numeric(24, 6) NULL,
	"scope" varchar(18) NULL,
	creditdate varchar(10) NULL,
	licenseno varchar(32) NULL,
	licensedate varchar(10) NULL,
	licensematurity varchar(10) NULL,
	setupdate varchar(10) NULL,
	inspectionyear varchar(10) NULL,
	locksituation varchar(200) NULL,
	taxno varchar(32) NULL,
	banklicense varchar(32) NULL,
	managearea varchar(200) NULL,
	banchamount numeric NULL,
	exchangeid varchar(32) NULL,
	registeradd varchar(160) NULL,
	chargedepartment varchar(80) NULL,
	officeadd varchar(160) NULL,
	officezip varchar(32) NULL,
	countrycode varchar(18) NULL,
	regioncode varchar(18) NULL,
	villagecode varchar(18) NULL,
	villagename varchar(80) NULL,
	relativetype varchar(200) NULL,
	officetel varchar(32) NULL,
	officefax varchar(32) NULL,
	webadd varchar(80) NULL,
	emailadd varchar(80) NULL,
	employeenumber numeric NULL,
	mainproduction varchar(800) NULL,
	newtechcorpornot varchar(18) NULL,
	listingcorpornot varchar(18) NULL,
	hasieright varchar(18) NULL,
	hasdirectorate varchar(18) NULL,
	basicbank varchar(80) NULL,
	basicaccount varchar(32) NULL,
	manageinfo varchar(800) NULL,
	customerhistory varchar(800) NULL,
	projectflag varchar(18) NULL,
	realtyflag varchar(18) NULL,
	workfieldarea numeric NULL,
	workfieldfee varchar(18) NULL,
	accountdate varchar(10) NULL,
	loancardno varchar(32) NULL,
	loancardpassword varchar(32) NULL,
	loancardinsyear varchar(10) NULL,
	loancardinsresult varchar(200) NULL,
	loanflag varchar(18) NULL,
	financeornot varchar(18) NULL,
	financebelong varchar(18) NULL,
	creditbelong varchar(18) NULL,
	creditlevel varchar(80) NULL,
	evaluatedate varchar(10) NULL,
	othercreditlevel varchar(80) NULL,
	otherevaluatedate varchar(10) NULL,
	otherorgname varchar(80) NULL,
	inputorgid varchar(32) NULL,
	inputuserid varchar(32) NULL,
	inputdate varchar(10) NULL,
	updateorgid varchar(32) NULL,
	updateuserid varchar(32) NULL,
	updatedate varchar(10) NULL,
	remark varchar(200) NULL,
	taxno1 varchar(32) NULL,
	fictitiouspersonid varchar(32) NULL,
	groupflag varchar(18) NULL,
	evaluatelevel varchar(18) NULL,
	mybank varchar(80) NULL,
	mybankaccount varchar(32) NULL,
	otherbank varchar(80) NULL,
	otherbankaccount varchar(32) NULL,
	tempsaveflag varchar(18) NULL,
	financedepttel varchar(32) NULL,
	ecgroupflag varchar(18) NULL,
	supercorpname varchar(80) NULL,
	superloancardno varchar(32) NULL,
	supercerttype varchar(18) NULL,
	smeindustrytype varchar(10) NULL,
	sellsum numeric(24, 6) NULL,
	supercertid varchar(32) NULL,
	officecountrycode varchar(18) NULL,
	officeregioncode varchar(18) NULL,
	registerzip varchar(32) NULL,
	limitck numeric(24, 6) NULL,
	sillerent varchar(2) NULL,
	industrialadjust varchar(10) NULL,
	industrialupgrading varchar(10) NULL,
	newindustry varchar(10) NULL,
	czcountryent varchar(10) NULL,
	isfarming varchar(10) NULL,
	czareaname varchar(50) NULL,
	registeraddecifid varchar(20) NULL,
	officeaddecifid varchar(20) NULL,
	officetelecifid varchar(20) NULL,
	officefaxecifid varchar(20) NULL,
	relativetypeecifid varchar(20) NULL,
	emailaddecifid varchar(20) NULL,
	webaddecifid varchar(20) NULL,
	unitycreditcode varchar(32) NULL,
	entnature varchar(32) NULL,
	otherreceivables numeric(24, 6) NULL,
	czarea varchar(18) NULL,
	listingtype varchar(10) NULL,
	listingcountry varchar(10) NULL,
	listingcorpnumber varchar(10) NULL,
	financedate varchar(18) NULL,
	totaldebt numeric(24, 6) NULL,
	officeaddcode varchar(10) NULL,
	jxscope varchar(18) NULL,
	openaccontlicense varchar(32) NULL,
	regulatoryrating varchar(10) NULL,
	ratingfirmriting varchar(10) NULL,
	bankshareholder varchar(10) NULL,
	listingplace varchar(50) NULL,
	interbankquota numeric(24, 6) NULL,
	taxpayerid varchar(50) NULL,
	standardevlaresult varchar(10) NULL,
	moodyevlaresult varchar(10) NULL,
	otherevlaresult varchar(10) NULL,
	bankid varchar(32) NULL,
	regdate varchar(10) NULL,
	fitchratresult varchar(10) NULL,
	hightechent varchar(10) NULL,
	accountbussdate varchar(10) NULL,
	otherreceive numeric(24, 6) NULL,
	department varchar(80) NULL,
	interregion varchar(18) NULL,
	countryrisk varchar(18) NULL,
	certificatenum varchar(32) NULL,
	isfirstloanuser varchar(2) NULL,
	firstloandate varchar(10) NULL,
	lastyearemployees numeric(24, 6) NULL,
	lastyearbusinessincome numeric(24, 6) NULL,
	lastyeartotalassets numeric(24, 6) NULL,
	systemscope varchar(10) NULL,
	isspecialandnew varchar(2) NULL,
	belonggroupname varchar(80) NULL,
	isnewagriculture varchar(2) NULL,
	tjaddrcode varchar(20) NULL,
	isfarmer varchar(8) NULL,
	ryzd varchar(1) NULL,
	CONSTRAINT pk_cms_ent_info PRIMARY KEY (customerid)
);

