/*
 * 上游信贷系统
 * 表名: crmdm.cms_business_approve
 * 来源: TB.ddl
 */

-- crmdm.cms_business_approve 定义

-- Drop table

-- DROP TABLE crmdm.cms_business_approve;

CREATE TABLE crmdm.cms_business_approve (
    serialno varchar(32) NOT NULL,
    relativeserialno varchar(40) NULL,
    occurdate varchar(10) NULL,
    customerid varchar(32) NULL,
    customername varchar(120) NULL,
    businesstype varchar(18) NULL,
    businesssubtype varchar(18) NULL,
    occurtype varchar(18) NULL,
    currenylist varchar(18) NULL,
    currencymode varchar(18) NULL,
    businesstypelist varchar(18) NULL,
    calculatemode varchar(18) NULL,
    useorglist varchar(18) NULL,
    flowreduceflag varchar(18) NULL,
    contractflag varchar(18) NULL,
    subcontractflag varchar(18) NULL,
    selfuseflag varchar(18) NULL,
    creditaggreement varchar(32) NULL,
    relativeagreement varchar(32) NULL,
    loanflag varchar(18) NULL,
    totalsum numeric(24,
    6) NULL,
    ourrole varchar(18) NULL,
    reversibility varchar(18) NULL,
    billnum int4 NULL,
    housetype varchar(18) NULL,
    lctermtype varchar(18) NULL,
    riskattribute varchar(18) NULL,
    suretype varchar(18) NULL,
    safeguardtype varchar(18) NULL,
    creditbusiness varchar(18) NULL,
    businesscurrency varchar(18) NULL,
    businesssum numeric(24,
    6) NULL,
    businessprop numeric(10,
    6) NULL,
    termyear int4 NULL,
    termmonth int4 NULL,
    termday int4 NULL,
    lgterm int4 NULL,
    baseratetype varchar(18) NULL,
    baserate numeric(10,
    6) NULL,
    ratefloattype varchar(18) NULL,
    ratefloat numeric(10,
    6) NULL,
    businessrate numeric(10,
    6) NULL,
    ictype varchar(18) NULL,
    iccyc varchar(18) NULL,
    pdgratio numeric(10,
    6) NULL,
    pdgsum numeric(24,
    6) NULL,
    pdgpaymethod varchar(18) NULL,
    pdgpayperiod varchar(18) NULL,
    promisesfeeratio numeric(10,
    6) NULL,
    promisesfeesum numeric(24,
    6) NULL,
    promisesfeeperiod int4 NULL,
    promisesfeebegin varchar(10) NULL,
    mfeeratio numeric(10,
    6) NULL,
    mfeesum numeric(24,
    6) NULL,
    mfeepaymethod varchar(18) NULL,
    agentfee numeric(24,
    6) NULL,
    dealfee numeric(24,
    6) NULL,
    totalcast numeric(24,
    6) NULL,
    discountinterest numeric(24,
    6) NULL,
    purchaserinterest numeric(24,
    6) NULL,
    bargainorinterest numeric(24,
    6) NULL,
    discountsum numeric(24,
    6) NULL,
    bailratio numeric(10,
    6) NULL,
    bailcurrency varchar(18) NULL,
    bailsum numeric(24,
    6) NULL,
    bailaccount varchar(80) NULL,
    fineratetype varchar(18) NULL,
    finerate numeric(10,
    6) NULL,
    drawingtype varchar(18) NULL,
    firstdrawingdate varchar(10) NULL,
    drawingperiod int4 NULL,
    paytimes int4 NULL,
    paycyc varchar(18) NULL,
    graceperiod int4 NULL,
    overdraftperiod int4 NULL,
    oldlcno varchar(32) NULL,
    oldlctermtype varchar(18) NULL,
    remitmode varchar(18) NULL,
    oldlcsum numeric(24,
    6) NULL,
    oldlcloadingdate varchar(10) NULL,
    oldlcvaliddate varchar(10) NULL,
    direction varchar(18) NULL,
    purpose varchar(2000) NULL,
    planallocation varchar(300) NULL,
    immediacypaysource varchar(300) NULL,
    paysource varchar(300) NULL,
    corpuspaymethod varchar(18) NULL,
    interestpaymethod varchar(18) NULL,
    thirdparty1 varchar(300) NULL,
    thirdpartyid1 varchar(60) NULL,
    thirdparty2 varchar(300) NULL,
    thirdpartyid2 varchar(60) NULL,
    thirdparty3 varchar(300) NULL,
    thirdpartyid3 varchar(32) NULL,
    thirdpartyregion varchar(18) NULL,
    thirdpartyaccounts varchar(32) NULL,
    cargoinfo varchar(80) NULL,
    projectname varchar(120) NULL,
    operationinfo varchar(600) NULL,
    contextinfo varchar(300) NULL,
    securitiestype varchar(18) NULL,
    securitiesregion varchar(18) NULL,
    constructionarea numeric(24,
    6) NULL,
    usearea numeric(24,
    6) NULL,
    flag1 varchar(18) NULL,
    flag2 varchar(18) NULL,
    flag3 varchar(18) NULL,
    tradecontractno varchar(60) NULL,
    invoiceno varchar(32) NULL,
    tradecurrency varchar(18) NULL,
    tradesum numeric(24,
    6) NULL,
    paymentdate varchar(10) NULL,
    operationmode varchar(18) NULL,
    vouchclass varchar(18) NULL,
    vouchtype varchar(18) NULL,
    vouchtype1 varchar(18) NULL,
    vouchtype2 varchar(18) NULL,
    vouchflag varchar(18) NULL,
    warrantor varchar(80) NULL,
    warrantorid varchar(32) NULL,
    othercondition varchar(600) NULL,
    guarantyvalue numeric(24,
    6) NULL,
    guarantyrate numeric(10,
    6) NULL,
    baseevaluateresult varchar(18) NULL,
    riskrate numeric(24,
    6) NULL,
    lowrisk varchar(18) NULL,
    otherarealoan varchar(18) NULL,
    lowriskbailsum numeric(24,
    6) NULL,
    originalputoutdate varchar(10) NULL,
    extendtimes int4 NULL,
    lngotimes int4 NULL,
    golntimes int4 NULL,
    drtimes int4 NULL,
    baseclassifyresult varchar(18) NULL,
    applytype varchar(18) NULL,
    bailrate numeric(24,
    6) NULL,
    finishorg varchar(18) NULL,
    describe1 varchar(300) NULL,
    operateorgid varchar(32) NULL,
    operateuserid varchar(32) NULL,
    operatedate varchar(10) NULL,
    inputorgid varchar(32) NULL,
    inputuserid varchar(32) NULL,
    inputdate varchar(20) NULL,
    updatedate varchar(10) NULL,
    pigeonholedate varchar(10) NULL,
    remark varchar(600) NULL,
    paycurrency varchar(18) NULL,
    paydate varchar(10) NULL,
    flag4 varchar(18) NULL,
    fundsource varchar(18) NULL,
    operatetype varchar(18) NULL,
    approvetype varchar(20) NULL,
    cycleflag varchar(20) NULL,
    classifyresult varchar(80) NULL,
    classifydate varchar(10) NULL,
    classifyfrequency int4 NULL,
    vouchnewflag varchar(20) NULL,
    adjustratetype varchar(18) NULL,
    adjustrateterm varchar(18) NULL,
    rateadjustcyc varchar(18) NULL,
    fzanbalance numeric(24,
    6) NULL,
    acceptinttype varchar(18) NULL,
    ratio numeric(24,
    6) NULL,
    thirdpartyadd1 varchar(160) NULL,
    thirdpartyzip1 varchar(32) NULL,
    thirdpartyadd2 varchar(80) NULL,
    thirdpartyzip2 varchar(32) NULL,
    thirdpartyadd3 varchar(80) NULL,
    thirdpartyzip3 varchar(50) NULL,
    effectarea varchar(18) NULL,
    termdate1 varchar(10) NULL,
    termdate2 varchar(10) NULL,
    termdate3 varchar(10) NULL,
    fixcyc int4 NULL,
    describe2 varchar(300) NULL,
    approveopinion varchar(300) NULL,
    tempsaveflag varchar(18) NULL,
    approvedate varchar(10) NULL,
    flag5 varchar(18) NULL,
    creditcycle varchar(18) NULL,
    guarantyflag varchar(18) NULL,
    executeyearrate numeric(10,
    6) NULL,
    paysourcen varchar(18) NULL,
    returnfrequency varchar(18) NULL,
    backfrequency varchar(18) NULL,
    ishostbank varchar(18) NULL,
    havepayplan varchar(2) NULL,
    ipcode varchar(4) NULL,
    frcode varchar(4) NULL,
    paysourcedetail varchar(300) NULL,
    businesssource varchar(6) NULL,
    barcode varchar(64) NULL,
    creditmethod varchar(18) NULL,
    titularsum1 numeric(24,
    6) NULL,
    titularsum2 numeric(24,
    6) NULL,
    titularsum3 numeric(24,
    6) NULL,
    titularsum4 numeric(24,
    6) NULL,
    titularsum5 numeric(24,
    6) NULL,
    exposuresum1 numeric(24,
    6) NULL,
    exposuresum2 numeric(24,
    6) NULL,
    exposuresum3 numeric(24,
    6) NULL,
    exposuresum4 numeric(24,
    6) NULL,
    exposuresum5 numeric(24,
    6) NULL,
    overagesum1 numeric(24,
    6) NULL,
    overagesum2 numeric(24,
    6) NULL,
    overagesum3 numeric(24,
    6) NULL,
    operateuserid1 varchar(32) NULL,
    reapply varchar(18) NULL,
    usedepositpile varchar(4) NULL,
    depositpilesum numeric(24,
    6) NULL,
    preappno varchar(32) NULL,
    direction1 varchar(18) NULL,
    billtype varchar(4) NULL,
    basebusinesstype varchar(18) NULL,
    investedcapital numeric(24,
    6) NULL,
    promisesfeetype varchar(18) NULL,
    issuetype varchar(20) NULL,
    issuebankname varchar(90) NULL,
    isinsurance varchar(4) NULL,
    extend numeric(24,
    6) NULL,
    extend1 varchar(80) NULL,
    businessloantype varchar(20) NULL,
    extend3 varchar(20) NULL,
    extend4 numeric(24,
    6) NULL,
    approveartificialno varchar(60) NULL,
    isfarming varchar(10) NULL,
    xwbz varchar(80) NULL,
    farmorg varchar(50) NULL,
    industrialadjust varchar(10) NULL,
    industrialupgrading varchar(10) NULL,
    newindustry varchar(10) NULL,
    firstdrawingterm int4 NULL,
    enddrawingterm int4 NULL,
    enddrawingdate varchar(10) NULL,
    reauditterm int4 NULL,
    reauditdate varchar(10) NULL,
    yz varchar(2) NULL,
    redeclare varchar(10) NULL,
    businesssum1 numeric(24,
    6) NULL,
    businesssum2 numeric(24,
    6) NULL,
    relaserialno varchar(32) NULL,
    bridlemark varchar(4000) NULL,
    linetype varchar(32) NULL,
    ispolicyloan varchar(10) NULL,
    bankvouchtype varchar(18) NULL,
    productid varchar(32) NULL,
    isdiscount varchar(10) NULL,
    vouchcompanybailaccount varchar(40) NULL,
    oldputoutdate varchar(20) NULL,
    approveuser varchar(18) NULL,
    imagebatchno varchar(90) NULL,
    oldoccurtype varchar(18) NULL,
    oldapplytype varchar(18) NULL,
    finishuser varchar(32) NULL,
    channel varchar(20) NULL,
    oldmaturity varchar(20) NULL,
    loanpersontype varchar(10) NULL,
    graduatetype varchar(10) NULL,
    disabletype varchar(10) NULL,
    femaleflag varchar(10) NULL,
    greencredit varchar(15) NULL,
    exposuresum numeric(24,
    6) NULL
);