/*
 * 上游信贷系统
 * 表名: crmdm.cms_business_duebill
 * 来源: TB.ddl
 */

-- crmdm.cms_business_duebill 定义

-- Drop table

-- DROP TABLE crmdm.cms_business_duebill;

CREATE TABLE crmdm.cms_business_duebill (
    serialno varchar(40) NOT NULL,
    relativeserialno1 varchar(40) NULL,
    relativeserialno2 varchar(40) NULL,
    subjectno varchar(20) NULL,
    mfcustomerid varchar(40) NULL,
    customerid varchar(40) NULL,
    customername varchar(80) NULL,
    businesstype varchar(18) NULL,
    businesssubtype varchar(20) NULL,
    businessstatus varchar(20) NULL,
    businesscurrency varchar(20) NULL,
    businesssum numeric(24,
    6) NULL,
    putoutdate varchar(10) NULL,
    maturity varchar(10) NULL,
    actualmaturity varchar(10) NULL,
    businessrate numeric(24,
    10) NULL,
    actualbusinessrate numeric(10,
    6) NULL,
    ictype varchar(20) NULL,
    iccyc varchar(20) NULL,
    paytimes numeric NULL,
    paycyc varchar(20) NULL,
    corpuspaymethod varchar(20) NULL,
    extendtimes numeric NULL,
    reorgtimes numeric NULL,
    renewtimes numeric NULL,
    golntimes numeric NULL,
    balance numeric(24,
    6) NULL,
    normalbalance numeric(24,
    6) NULL,
    overduebalance numeric(24,
    6) NULL,
    dullbalance numeric(24,
    6) NULL,
    badbalance numeric(24,
    6) NULL,
    interestbalance1 numeric(24,
    6) NULL,
    interestbalance2 numeric(24,
    6) NULL,
    finebalance1 numeric(24,
    6) NULL,
    finebalance2 numeric(24,
    6) NULL,
    receivebalance numeric(24,
    6) NULL,
    payedbalance numeric(24,
    6) NULL,
    overduedays numeric NULL,
    payaccount varchar(40) NULL,
    putoutaccount varchar(40) NULL,
    paybackaccount varchar(40) NULL,
    payinterestaccount varchar(40) NULL,
    oweinterestdays numeric NULL,
    tabalance numeric(24,
    6) NULL,
    tainterestbalance numeric(24,
    6) NULL,
    tatimes numeric(24,
    6) NULL,
    lcatimes numeric(24,
    6) NULL,
    saledate varchar(10) NULL,
    finishtype varchar(20) NULL,
    finishdate varchar(10) NULL,
    mfareaid varchar(20) NULL,
    mforgid varchar(20) NULL,
    mfuserid varchar(20) NULL,
    operateorgid varchar(20) NULL,
    operateuserid varchar(20) NULL,
    inputorgid varchar(20) NULL,
    inputuserid varchar(20) NULL,
    inputdate varchar(10) NULL,
    updatedate varchar(10) NULL,
    inoutflag varchar(40) NULL,
    dealflag varchar(1) NULL,
    occurdate varchar(10) NULL,
    businessprop numeric(10,
    6) NULL,
    benefitcorp varchar(40) NULL,
    actualtermmonth numeric NULL,
    actualtermday numeric NULL,
    baseratetype varchar(20) NULL,
    baserate numeric(24,
    6) NULL,
    ratefloattype varchar(20) NULL,
    ratefloat numeric(24,
    6) NULL,
    timsflag varchar(40) NULL,
    bailratio numeric(10,
    6) NULL,
    logoutdate varchar(10) NULL,
    cancellogoutdate varchar(10) NULL,
    bailsum numeric(24,
    6) NULL,
    bailaccount varchar(40) NULL,
    purpose varchar(200) NULL,
    advanceflag varchar(20) NULL,
    relativeduebillno varchar(40) NULL,
    actualartificialno varchar(40) NULL,
    accountno varchar(40) NULL,
    loanaccountno varchar(40) NULL,
    secondpayaccount varchar(40) NULL,
    adjustratetype varchar(20) NULL,
    adjustrateterm varchar(20) NULL,
    overinttype varchar(20) NULL,
    rateadjustcyc varchar(20) NULL,
    pdgaccountno varchar(40) NULL,
    deductdate varchar(10) NULL,
    fzanbalance numeric(24,
    6) NULL,
    acceptinttype varchar(20) NULL,
    ratio numeric(24,
    6) NULL,
    thirdpartyadd1 varchar(80) NULL,
    thirdpartyzip1 varchar(40) NULL,
    thirdpartyadd2 varchar(80) NULL,
    thirdpartyzip2 varchar(40) NULL,
    termdate1 varchar(10) NULL,
    termdate2 varchar(10) NULL,
    termdate3 varchar(10) NULL,
    describe2 varchar(200) NULL,
    fixcyc numeric NULL,
    thirdparty1 varchar(200) NULL,
    thirdpartyid1 varchar(40) NULL,
    thirdparty2 varchar(200) NULL,
    thirdparty3 varchar(200) NULL,
    type1 varchar(20) NULL,
    type2 varchar(20) NULL,
    type3 varchar(20) NULL,
    billno varchar(64) NULL,
    flag1 varchar(20) NULL,
    flag2 varchar(20) NULL,
    flag3 varchar(20) NULL,
    thirdpartyregion varchar(20) NULL,
    thirdpartyaccounts varchar(40) NULL,
    cargoinfo varchar(80) NULL,
    securitiestype varchar(20) NULL,
    securitiesregion varchar(20) NULL,
    aboutbankid2 varchar(40) NULL,
    aboutbankname2 varchar(80) NULL,
    aboutbankid3 varchar(40) NULL,
    aboutbankname varchar(80) NULL,
    aboutbankid varchar(40) NULL,
    oldlctermtype varchar(20) NULL,
    negotiateno varchar(40) NULL,
    creditkind varchar(20) NULL,
    gatheringname varchar(80) NULL,
    preinttype varchar(20) NULL,
    resumeinttype varchar(20) NULL,
    guarantyno varchar(40) NULL,
    pztype varchar(20) NULL,
    graceperiod numeric NULL,
    oldlcvaliddate varchar(10) NULL,
    mfeepaymethod varchar(20) NULL,
    describe1 varchar(200) NULL,
    tradecontractno varchar(40) NULL,
    loantype varchar(20) NULL,
    fixterm numeric(24,
    6) NULL,
    cancelsum numeric(24,
    6) NULL,
    cancelinterest numeric(24,
    6) NULL,
    bailacount varchar(40) NULL,
    classify4 varchar(18) NULL,
    classifyresult varchar(18) NULL,
    returntype varchar(18) NULL,
    bailpercent numeric(10,
    6) NULL,
    paymenttype varchar(18) NULL,
    termsfreq varchar(18) NULL,
    overduedate varchar(10) NULL,
    oweinterestdate varchar(10) NULL,
    lcstatus varchar(18) NULL,
    ichangedate varchar(10) NULL,
    vouchtype varchar(10) NULL,
    executeyearrate numeric(10,
    6) NULL,
    offsheetflag varchar(6) NULL,
    basebusinesstype varchar(18) NULL,
    interestoverduedate varchar(18) NULL,
    currentrpttermid varchar(32) NULL,
    lctermtype varchar(18) NULL,
    paytype varchar(12) NULL,
    lastclassifyresult varchar(18) NULL,
    sysclassifyresult varchar(10) NULL,
    putoutorgid varchar(100) NULL,
    balanceoverduedate varchar(18) NULL,
    guaranteeway varchar(18) NULL,
    gjflag varchar(18) NULL,
    lcno varchar(32) NULL,
    cancleinterestsum2 numeric(24,
    6) NULL,
    canclefinesum1 numeric(24,
    6) NULL,
    canclefinesum2 numeric(24,
    6) NULL,
    canclebalance numeric(24,
    6) NULL,
    cancleinterestbalance2 numeric(24,
    6) NULL,
    canclefinebalance1 numeric(24,
    6) NULL,
    canclefinebalance2 numeric(24,
    6) NULL,
    unacceptbalance numeric(24,
    2) NULL,
    dongjbho varchar(40) NULL,
    taskflag varchar(2) NULL,
    yzflag varchar(5) NULL,
    ratetermid varchar(20) NULL,
    bpratetermid varchar(20) NULL,
    bprateadjustcyc varchar(20) NULL,
    bpadjustratetype varchar(20) NULL,
    bpratefloat numeric(10,
    6) NULL,
    bpratefloattype varchar(20) NULL,
    bpbaserate numeric(10,
    6) NULL,
    bpbaseratetype varchar(20) NULL,
    financebailoutdelay varchar(20) NULL,
    financebailoutdelaymonths numeric NULL,
    iswriteoffaccrualflag varchar(2) NULL,
    loanwriteofftype varchar(10) NULL,
    observedate varchar(10) NULL,
    ryzd varchar(1) NULL,
    CONSTRAINT pk_cms_business_duebill PRIMARY KEY (serialno)
);