/*
 * 上游信贷系统
 * 表名: crmdm.cms_guaranty_info
 * 来源: TB.ddl
 */

-- crmdm.cms_guaranty_info 定义

-- Drop table

-- DROP TABLE crmdm.cms_guaranty_info;

CREATE TABLE crmdm.cms_guaranty_info (
	guarantyid varchar(40) NOT NULL,
	guarantytype varchar(20) NULL,
	guarantystatus varchar(20) NULL,
	ownerid varchar(40) NULL,
	ownername varchar(80) NULL,
	ownertype varchar(20) NULL,
	rate numeric(24, 6) NULL,
	custguarantytype varchar(20) NULL,
	subjectno varchar(40) NULL,
	relativeaccount varchar(40) NULL,
	guarantyrightid varchar(2000) NULL,
	otherguarantyright varchar(300) NULL,
	guarantyname varchar(120) NULL,
	guarantysubtype varchar(20) NULL,
	guarantyownway varchar(20) NULL,
	guarantyusing varchar(200) NULL,
	guarantylocation varchar(300) NULL,
	guarantyamount numeric(24, 6) NULL,
	guarantyamount1 numeric(24, 6) NULL,
	guarantyamount2 numeric(24, 6) NULL,
	guarantyresouce varchar(80) NULL,
	guarantydate varchar(80) NULL,
	begindate varchar(10) NULL,
	ownertime varchar(80) NULL,
	guarantydescript varchar(300) NULL,
	aboutotherid1 varchar(500) NULL,
	aboutotherid2 varchar(40) NULL,
	aboutotherid3 varchar(40) NULL,
	aboutotherid4 varchar(40) NULL,
	purpose varchar(300) NULL,
	aboutsum1 numeric(24, 6) NULL,
	aboutsum2 numeric(24, 6) NULL,
	aboutrate numeric(24, 6) NULL,
	guarantyana varchar(200) NULL,
	guarantyprice numeric(24, 6) NULL,
	evalmethod varchar(20) NULL,
	evalorgid varchar(40) NULL,
	evalorgname varchar(120) NULL,
	evaldate varchar(10) NULL,
	evalnetvalue numeric(24, 6) NULL,
	confirmvalue numeric(24, 6) NULL,
	guarantyrate numeric(24, 6) NULL,
	thirdparty1 varchar(200) NULL,
	thirdparty2 varchar(2000) NULL,
	thirdparty3 varchar(200) NULL,
	guarantydescribe1 varchar(200) NULL,
	guarantydescribe2 varchar(300) NULL,
	guarantydescribe3 varchar(200) NULL,
	flag1 varchar(20) NULL,
	flag2 varchar(20) NULL,
	flag3 varchar(20) NULL,
	flag4 varchar(20) NULL,
	guarantyregno varchar(40) NULL,
	guarantyregorg varchar(80) NULL,
	guarantyregdate varchar(10) NULL,
	guarantywodate varchar(10) NULL,
	insurecertno varchar(40) NULL,
	otherassumpsit varchar(300) NULL,
	inputorgid varchar(40) NULL,
	inputuserid varchar(40) NULL,
	inputdate varchar(10) NULL,
	updateuserid varchar(40) NULL,
	updatedate varchar(10) NULL,
	remark varchar(300) NULL,
	sapvouchtype varchar(20) NULL,
	certtype varchar(18) NULL,
	certid varchar(50) NULL,
	loancardno varchar(32) NULL,
	guarantycurrency varchar(18) NULL,
	evalcurrency varchar(18) NULL,
	guarantydescribe4 numeric(24, 6) NULL,
	evaldate1 varchar(10) NULL,
	evaldate2 varchar(10) NULL,
	guarantyvalue numeric(24, 6) NULL,
	useyear numeric(10) NULL,
	enddate varchar(10) NULL,
	isreverse varchar(2) NULL,
	yz varchar(2) NULL,
	outbounddate varchar(20) NULL,
	instoragedate varchar(20) NULL,
	ispwancredit varchar(4) NULL,
	pwancreditno varchar(32) NULL,
	pwancreditdivno varchar(32) NULL,
	guarantyaddress varchar(200) NULL,
	keepaccountingorgid varchar(32) NULL
);

