/*
 * 上游网联系统
 * 表名: crmdm.uepp_pay_mct_info
 * 来源: TB.ddl
 */

-- crmdm.uepp_pay_mct_info 定义

-- Drop table

-- DROP TABLE crmdm.uepp_pay_mct_info;

CREATE TABLE crmdm.uepp_pay_mct_info (
    mct_id varchar(40) NOT NULL,
    "name" varchar(300) NOT NULL,
    short_name varchar(100) NOT NULL,
    category_id varchar(40) NULL,
    mct_type varchar(20) NULL,
    phone varchar(20) NULL,
    email varchar(200) NULL,
    website varchar(300) NULL,
    contacts varchar(40) NULL,
    contacts_cert_type varchar(2) NULL,
    contacts_cert_no varchar(50) NULL,
    contacts_cert_back_url varchar(300) NULL,
    contacts_cert_face_url varchar(300) NULL,
    contacts_phone varchar(20) NULL,
    customer_phone varchar(20) NULL,
    chain_id varchar(40) NULL,
    mct_dept_id varchar(40) NULL,
    is_own_data varchar(1) NULL,
    is_settle_acc varchar(1) NULL,
    agree_url varchar(300) NULL,
    shop_url varchar(300) NULL,
    settle_type varchar(2) NULL,
    province varchar(10) NULL,
    city varchar(10) NULL,
    area varchar(10) NULL,
    address varchar(300) NULL,
    dit_id varchar(40) NULL,
    org_id varchar(40) NULL,
    job_id varchar(40) NULL,
    remark varchar(300) NULL,
    check_status varchar(2) NULL,
    status varchar(2) NULL,
    create_user varchar(40) NULL,
    create_time varchar(20) NULL,
    update_user varchar(40) NULL,
    update_time varchar(20) NULL,
    lng varchar(30) NULL,
    lat varchar(30) NULL,
    sign_date varchar(10) NULL,
    is_become_t0_flag varchar(1) NULL,
    mct_logo_url varchar(100) NULL,
    check_task_id varchar(40) NULL,
    banker_id varchar(40) NULL,
    banker_name varchar(100) NULL,
    category_parent_id varchar(40) NULL,
    risk_level varchar(2) NULL,
    rade_area_id varchar(10) NULL,
    from_way varchar(10) NULL,
    cancel_date varchar(8) NULL,
    last_org_trf_id varchar(40) NULL,
    last_cmg_trf_id varchar(40) NULL,
    month_deposit numeric(16,
    2) NULL,
    season_deposit numeric(16,
    2) NULL,
    shop_back_url varchar(300) NULL,
    yunhorn varchar(20) NULL,
    expire_check_type varchar(2) NULL,
    company_size varchar(2) NULL,
    order_remark_flag varchar(1) NULL,
    mct_power varchar(10) NULL,
    push_start varchar(10) NULL,
    assist_remark varchar(1000) NULL,
    assist_data1 varchar(60) NULL,
    assist_data2 varchar(60) NULL,
    assist_data3 varchar(60) NULL,
    assist_data4 varchar(60) NULL,
    assist_data5 varchar(60) NULL,
    collect_flag varchar(10) NULL,
    wx_category_code varchar(20) NULL,
    ali_category_code varchar(20) NULL,
    ali_mcc varchar(20) NULL,
    union_mcc varchar(20) NULL,
    xcx_push_start varchar(20) NULL,
    xcx_push_cashier varchar(2) NULL,
    ryzd varchar(1) NULL,
    CONSTRAINT pk_uepp_pay_mct_info PRIMARY KEY (mct_id)
);