/*
 * 上游网联系统
 * 表名: crmdm.uepp_pay_aml_order_info
 * 来源: TB.ddl
 */

-- crmdm.uepp_pay_aml_order_info 定义

-- Drop table

-- DROP TABLE crmdm.uepp_pay_aml_order_info;

CREATE TABLE crmdm.uepp_pay_aml_order_info (
    tr_id varchar(256) NOT NULL,
    tr_dt varchar(48) NULL,
    tr_tm varchar(48) NULL,
    tr_no varchar(50) NULL,
    rcv_pay_type varchar(2) NULL,
    rcv_pay_no varchar(200) NULL,
    tr_org_id varchar(16) NULL,
    cust_id varchar(32) NULL,
    cust_name varchar(512) NULL,
    cust_type varchar(1) NULL,
    acct_id varchar(64) NULL,
    card_no varchar(64) NULL,
    card_style varchar(2) NULL,
    oth_card_style varchar(128) NULL,
    subject_id varchar(20) NULL,
    prd_id varchar(20) NULL,
    tr_chnl varchar(32) NULL,
    s_tr_chnl varchar(10) NULL,
    tr_cd varchar(4) NULL,
    s_tr_cd varchar(10) NULL,
    biz_type varchar(2) NULL,
    is_cash varchar(2) NULL,
    pay_type varchar(4) NULL,
    debit_credit varchar(1) NULL,
    rcv_pay varchar(2) NULL,
    curr_cd varchar(3) NULL,
    is_local_curr varchar(1) NULL,
    tr_amt numeric(30,
    4) NULL,
    tr_cny_amt numeric(30,
    4) NULL,
    tr_usd_amt numeric(30,
    4) NULL,
    tr_bal_amt numeric(30,
    4) NULL,
    tr_country varchar(3) NULL,
    tr_area varchar(6) NULL,
    fund_use varchar(256) NULL,
    agent_name varchar(128) NULL,
    agent_nat varchar(3) NULL,
    agent_cert_type varchar(6) NULL,
    oth_agent_cert_type varchar(128) NULL,
    agent_cert_no varchar(128) NULL,
    opp_name varchar(128) NULL,
    opp_acct_id varchar(64) NULL,
    opp_acct_type varchar(6) NULL,
    opp_is_cust varchar(1) NULL,
    opp_cust_id varchar(64) NULL,
    opp_cust_type varchar(1) NULL,
    opp_off_shore varchar(1) NULL,
    opp_card_no varchar(64) NULL,
    opp_card_style varchar(2) NULL,
    oth_opp_card_style varchar(128) NULL,
    opp_cert_type varchar(6) NULL,
    oth_opp_cert_type varchar(128) NULL,
    opp_cert_no varchar(128) NULL,
    opp_org_id varchar(16) NULL,
    opp_org_name varchar(128) NULL,
    opp_org_type varchar(2) NULL,
    opp_org_country varchar(3) NULL,
    opp_org_area varchar(6) NULL,
    tr_go_country varchar(3) NULL,
    tr_go_area varchar(6) NULL,
    is_cross varchar(1) NULL,
    opr_id varchar(32) NULL,
    re_opr_id varchar(32) NULL,
    rev_cd varchar(1) NULL,
    pbc_rltp varchar(15) NULL,
    pbc_tsct varchar(16) NULL,
    sys_id varchar(32) NULL,
    ip varchar(15) NULL,
    tr_ipv6 varchar(32) NULL,
    tr_mac varchar(32) NULL,
    tr_note1 varchar(256) NULL,
    tr_note2 varchar(256) NULL,
    bank_pay_cd varchar(128) NULL,
    eqpt_cd varchar(500) NULL,
    merch_id varchar(20) NULL,
    merch_type varchar(4) NULL,
    is_3rd_pay varchar(1) NULL,
    tr_crt_type varchar(1) NULL,
    bh_exec varchar(1) NULL,
    bs_exec varchar(1) NULL,
    clct_sts varchar(1) NULL,
    bh_valid varchar(1) NULL,
    bs_valid varchar(1) NULL,
    due_dt DATE NULL,
    rsrv_01 varchar(48) NULL,
    rsrv_02 varchar(48) NULL,
    rsrv_03 varchar(48) NULL,
    rsrv_04 varchar(48) NULL,
    pbc_chnl varchar(50) NULL,
    non_dept_type varchar(2) NULL,
    oth_non_dept_type varchar(64) NULL,
    pbc_orgkey varchar(16) NULL,
    main_acct_id varchar(64) NULL,
    agent_tel varchar(60) NULL,
    opp_acct_type1 varchar(6) NULL,
    pos_owner varchar(40) NULL,
    is_cadr_trans varchar(2) NULL,
    cert_no varchar(128) NULL,
    cert_type varchar(6) NULL,
    oth_cert_type varchar(128) NULL,
    atm_bank_code varchar(20) NULL,
    ryzd varchar(1) NULL,
    CONSTRAINT pk_uepp_pay_aml_order_info PRIMARY KEY (tr_id)
);