/*
 * 上游网联系统
 * 表名: crmdm.uepp_pay_order_info
 * 来源: TB.ddl
 */

-- crmdm.uepp_pay_order_info 定义

-- Drop table

-- DROP TABLE crmdm.uepp_pay_order_info;

CREATE TABLE crmdm.uepp_pay_order_info (
	order_id varchar(40) NOT NULL,
	order_type varchar(10) NULL,
	channel varchar(40) NULL,
	pay_type varchar(40) NULL,
	mct_id varchar(40) NOT NULL,
	dit_id varchar(40) NOT NULL,
	order_amt numeric(16, 2) NOT NULL,
	pay_amt numeric(16, 2) NULL,
	dis_amt numeric(16, 2) NULL,
	dis_auth_id varchar(40) NULL,
	pay_time varchar(20) NULL,
	jungle_type varchar(2) NULL,
	jungle_amt numeric(16, 2) NULL,
	server_id varchar(40) NULL,
	mct_fee numeric(16, 2) NULL,
	dit_fee numeric(16, 2) NULL,
	buyer_pay_amt numeric(16, 2) NULL,
	buyer_user_id varchar(200) NULL,
	third_mch_id varchar(40) NULL,
	third_sub_mch_id varchar(40) NULL,
	third_pay_fee numeric(16, 2) NULL,
	third_trade_no varchar(40) NULL,
	third_end_time varchar(20) NULL,
	settle_date varchar(8) NULL,
	timeout_express varchar(20) NULL,
	limit_pay varchar(20) NULL,
	out_trade_no varchar(40) NULL,
	or_order_id varchar(40) NULL,
	web_notify_url varchar(256) NULL,
	notify_url varchar(500) NULL,
	order_body varchar(200) NULL,
	order_detail varchar(1000) NULL,
	term_id varchar(100) NULL,
	dev_info varchar(500) NULL,
	auth_code varchar(200) NULL,
	qr_code varchar(300) NULL,
	"attach" varchar(500) NULL,
	remark varchar(300) NULL,
	status varchar(2) NULL,
	create_user varchar(40) NULL,
	create_time varchar(20) NULL,
	update_user varchar(40) NULL,
	update_time varchar(20) NULL,
	buyer_user_name varchar(200) NULL,
	pay_card_type varchar(2) NULL,
	client_id varchar(40) NULL,
	client_info varchar(300) NULL,
	cost_rate numeric(16, 4) NULL,
	dit_fee_rate numeric(16, 4) NULL,
	mct_fee_rate numeric(16, 4) NULL,
	settle_flag varchar(2) NULL,
	bala_flag varchar(1) NULL,
	settle_serial_no varchar(40) NULL,
	settle_update_date varchar(8) NULL,
	bala_update_date varchar(8) NULL,
	settle_type varchar(2) NULL,
	activity_rate numeric(16, 4) NULL,
	activity_fee numeric(16, 2) NULL,
	mct_real_fee numeric(16, 2) NULL,
	activity_id varchar(32) NULL,
	isscode varchar(11) NULL,
	ip varchar(16) NULL,
	tr_mac varchar(32) NULL,
	core_id varchar(40) NULL,
	mct_related_id varchar(32) NULL,
	consumer_id varchar(40) NULL,
	idc_flag varchar(10) NULL,
	device_ip varchar(64) NULL,
	device_location varchar(32) NULL,
	user_id varchar(128) NULL,
	is_next_refund varchar(10) NULL,
	store_id varchar(40) NULL,
	wal_acct_amt numeric(16, 2) NULL,
	wal_acct_status varchar(2) NULL,
	wal_acct_no varchar(40) NULL,
	refund_mode varchar(2) NULL,
	pay_zh varchar(2) NULL,
	wal_trade_no varchar(40) NULL,
	wal_end_time varchar(20) NULL,
	wal_bala_flag varchar(1) NULL,
	calc_fee_flag varchar(2) NULL,
	mct_real_fee_type varchar(2) NULL,
	app_refundable_flag varchar(1) NULL,
	ryzd varchar(1) NULL,
	CONSTRAINT pk_uepp_pay_order_info PRIMARY KEY (order_id)
);

